src/travel-details-screens/TripDetailsScreenComponent.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/7276

fix: Remove "Buy ticket" button from bike journeys

---

src/translations/dictionary.ts
src/translations/screens/subscreens/TripDetails.ts
src/utils/transportation-names.ts

Fixes comment in https://github.com/AtB-AS/kundevendt/issues/7280

fix: Accessibility on non transit trips

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/HarborSelection.tsx
src/translations/screens/subscreens/PurchaseOverview.ts

Fixes screenreader issues for boat dock selection
https://github.com/AtB-AS/kundevendt/issues/4137#issuecomment-1659906255

fix: fix screenreader for boat dock selection

---

src/assets/information-data/ticketInspectionInformation.json
src/translations/components/CityBoxMessage.ts
src/translations/components/Pagination.ts
src/translations/screens/Departures.ts
src/translations/screens/FareContract.ts
src/translations/screens/Nearby.ts
src/translations/screens/Profile.ts
src/translations/screens/TripSearch.ts
src/translations/screens/subscreens/ActiveTokenRequired.ts
src/translations/screens/subscreens/AddEditFavorite.ts
src/translations/screens/subscreens/DepartureDetails.ts
src/translations/screens/subscreens/HarborSearch.ts
src/translations/screens/subscreens/JourneyDatePicker.ts
src/translations/screens/subscreens/MobilityTexts.ts
src/translations/screens/subscreens/PurchaseOverview.ts
src/translations/screens/subscreens/RecentFareContractsTexts.ts
src/translations/screens/subscreens/TariffZones.ts
src/translations/screens/subscreens/TravelToken.ts

Fix some bokmål and nynorsk issues

fix: Fix bokmål and nynorsk

---

src/remote-config.ts
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-show-valid-time-info-enabled.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
src/storage/StorageModel.tsx

Closes: https://github.com/AtB-AS/kundevendt/issues/7389

feat: Add a flag to hide or show the valid ticket info

---

src/components/map/hooks/use-update-bottom-sheet-when-selected-entity-changes.tsx
src/components/map/index.ts
src/components/map/types.ts
src/components/map/utils.ts
src/mobility/components/ParkAndRideBottomSheet.tsx
src/mobility/index.ts
src/place-screen/components/StopPlaceView.tsx
src/translations/screens/subscreens/MobilityTexts.ts

Closes https://github.com/AtB-AS/kundevendt/issues/4093
Screen shots can be seen here: https://github.com/AtB-AS/kundevendt/issues/4093#issuecomment-1669156106

feat: Park'n Ride in map

---

src/translations/screens/subscreens/TravelToken.ts

Replacing text for refunds at FRAM

replace FRAM refund question answer

---

src/mobility/components/ParkAndRideBottomSheet.tsx

Found during testing of https://github.com/AtB-AS/kundevendt/issues/4093
The fix just sets `maxHeightValue={0.5}` on the bottom sheet and wraps the content in a `<ScrollView>`.

fix: Make park'n ride work for large zoom

---

src/mobile-token/tokenService.ts

Closes https://github.com/AtB-AS/kundevendt/issues/4313

fix: Remove bugsnag logging of RemoteTokenStateError (412 responses)

---

src/fare-contracts/FareContractInfo.tsx
src/fare-contracts/ValidityLine.tsx
src/fare-contracts/use-validity-line-colors.ts
src/ticketing/types.ts
src/utils/use-transportation-color.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/7361

fix: Remove app logic based in fare product type

---

src/fare-contracts/carnet/UsedAccessValidityHeader.tsx

Fix icon size for tickets on active tickets page to match other ticket types
Close https://github.com/AtB-AS/kundevendt/issues/7796

fix: Fix carnet icon size

---

android/app/build.gradle

Trying to remove new prop style as I found some reference to if it was present it voided the old way. Crossing all my fingers and toes.

fix: removing new react gradle props

---

src/mobility/components/filter/FormFactorFilter.tsx
src/mobility/components/filter/MobilityFilters.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/7800

fix: Heading spacing in map filter

---

src/configuration/converters.ts

Closes https://github.com/AtB-AS/kundevendt/issues/7497

chore: Remove bugsnag log for expected config Zod parse errors

---

android/app/build.gradle
fastlane/Fastfile

https://github.com/facebook/react-native/issues/35398

chore: Change bundle path

---

src/mobility/components/filter/MobilityFilters.tsx

Found during testing of https://github.com/AtB-AS/kundevendt/issues/7800

fix: Spacing above header in filter

---

src/mobility/components/BikeStationBottomSheet.tsx

Found during testing: https://github.com/AtB-AS/kundevendt/issues/3869#issuecomment-1693228242

fix: Make BikeStationBottomSheet use max 50% height

---

src/translations/screens/subscreens/AppearanceSettings.ts

fix: language fix

---

src/api/vipps-login/api.ts
src/auth/AuthContext.tsx
src/auth/auth-utils.ts
src/auth/index.ts
src/auth/types.ts
src/auth/use-check-if-account-creation-finished.ts
src/auth/use-fetch-customer-data-after-user-changed.ts
src/auth/use-subscribe-to-auth-user-change.ts
src/auth/use-update-auth-language-on-change.ts
src/auth/utils.ts
src/mobile-token/MobileTokenContext.tsx
src/stacks-hierarchy/Root_LoginConfirmCodeScreen.tsx
src/stacks-hierarchy/Root_LoginOptionsScreen.tsx
src/stacks-hierarchy/Root_LoginPhoneInputScreen.tsx

Not really changed much in the auth flow, just refactored so the
details are more optional to read into. Previously looking into
the AuthContext could feel a little overwhelming.
The main change of this refactor is that the AuthContext has an
AuthStatus which may be 'loading', 'creating-account, 'finished',
or 'error'.

refactor: Auth flow

---

src/remote-config.ts

refactor: Remove enable_creditcard RemoteConfig flag

---

.github/workflows/build-store-ios.yml

fix: apple pass presentation suppression build command

---

package.json
yarn.lock

This fixes an error where FareProductGroup was undefined after import:

fix: update config-specs to version 3.5.3

---

src/components/sections/Section.tsx
src/fare-contracts/CompactFareContractInfo.tsx
src/favorites/FavoriteChips.tsx
src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx
src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/CompactFareContracts.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/SectionHeading.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/8088

refactor: Tidy up use of margins

---

src/translations/screens/subscreens/PurchaseConfirmation.ts

Closing https://github.com/AtB-AS/kundevendt/issues/7804, this time for real

fix: remove tram reference in FRAM harbour view

---

src/loading-screen/LoadingErrorScreen.tsx
src/loading-screen/LoadingScreen.tsx
src/loading-screen/LoadingScreenBoundary.tsx
src/loading-screen/index.ts
src/loading-screen/use-loading-screen-enabled.ts
src/remote-config.ts
src/stacks-hierarchy/RootStack.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
src/storage/StorageModel.tsx
src/translations/dictionary.ts
src/translations/index.ts
src/translations/screens/LoadingScreen.ts

Shows a loading screen while the auth connection is established and
the account is created. If this takes more than 10 seconds, the user
will be shown an error screen with some extra information, and the
possibility to try again.

feat: Loading screen on startup and while logging in

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/HarborSelection.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/8113

fix: Add borders to harbor selection

---

src/loading-screen/LoadingErrorScreen.tsx
src/loading-screen/LoadingScreen.tsx

Added some test-ids for loading screen to be able to check for its existence, and possible retries, in the e2e-tests.

test: add test-ids for loading screen

---

src/favorites/FavoriteChips.tsx
src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx
src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx

Fixes an issue found during testing of https://github.com/AtB-AS/kundevendt/issues/8088
See https://github.com/AtB-AS/kundevendt/issues/8088#issuecomment-1710018616

fix: Favorite chips margins

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContractComponent.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/types.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/use-recent-fare-contracts.ts
src/ticketing/types.ts

This is a cherry pick from release/1.41 branch to master as the changes made are breaking and therefore needed for local development.
Ref. task: https://github.com/AtB-AS/team-platform/issues/419

feat: swap order id with direction in recent fare contract (#3835)

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx
src/translations/screens/Dashboard.ts

Fixes bugs found during testing of https://github.com/AtB-AS/kundevendt/issues/7907
See https://github.com/AtB-AS/kundevendt/issues/7907#issuecomment-1717246455

fix: Accessibility and language fixes for Announcements

---

src/auth/AuthContext.tsx
src/auth/use-set-error-status-if-loading-too-long.ts
src/loading-screen/LoadingErrorScreen.tsx
src/translations/screens/LoadingScreen.ts

Show error screen to user if no user changed callback happened for
10 seconds. Most likely this will be because of missing inet
connection.

feat: Add loading boundary timeout 

---

.github/workflows/build-store-android.yml

Hopefully it this fixes the build error:
https://github.com/AtB-AS/mittatb-app/actions/runs/6186469796/job/16803423932#step:10:54

chore: Update get-release dep

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx

Fixes bug found during testing of https://github.com/AtB-AS/kundevendt/issues/8088

fix: Remove margin above travel search input

---

src/components/info-tag/InfoTag.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTile.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/Root_TicketAssistantStack.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_CategoryPickerScreen.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_FrequencyScreen.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketAssistant_SummaryScreen.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketSummary/TicketSummary.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_WelcomeScreen.tsx
src/translations/components/InfoTag.ts
src/translations/index.ts
src/translations/screens/TicketAssistant.ts
src/translations/screens/Ticketing.ts

[Figma for the assistant](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=16086-67186&mode=design&t=FQJHhx9OhcQOBN4l-4)
Changes:
Moved the text, and changed it according to figma:
Added a custom text to the child ticket:
Changed spacings between between texts(right is the updated):
Small changes to the summary, and made short ticket period info to a message box.

fix: Adjustments to ticket assistant

---

src/fare-contracts/use-validity-line-colors.ts

Possibly closing https://github.com/AtB-AS/kundevendt/issues/8648
Based on context from [Slack](https://mittatb.slack.com/archives/CSFC6PG23/p1695211994092889?thread_ts=1692000467.135619&cid=CSFC6PG23).

fix: change line colour for validity line

---

src/place-screen/components/EstimatedCallItem.tsx
src/travel-details-screens/DepartureDetailsScreenComponent.tsx

Adding test-ids to departure details.

test: add test-ids to departure details

---

src/beacons/index.ts
src/beacons/use-is-beacons-enabled.tsx
src/remote-config.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
src/storage/StorageModel.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/8617

feat: Beacons feature flag

---

src/beacons/use-is-beacons-enabled.tsx

Fix based on comment in https://github.com/AtB-AS/mittatb-app/pull/3880

fix: Retun debugOverrideReady from useIsBeaconsEnabled

---

src/components/sections/items/TextInputSectionItem.tsx

Happened to forget removing background color that was not supposed to be there.

refactor: remove background color

---

src/tariff-zones-selector/TariffZonesSelectorMap.tsx

- Calculating starting coordinates only at mount, so they aren't
affected by geolocation change.
- Added UserLocation pin on the map
- Pressing the "My location" button no longer auto-selects the zone
your position is in.

fix: TariffZone map recenters on location change

---

package.json
yarn.lock

Related to: https://github.com/AtB-AS/kundevendt/issues/8614

update: Upgrade Mapbox

---

src/fare-contracts/FareContractInfo.tsx

closes https://github.com/AtB-AS/kundevendt/issues/8975

feat: show inspection symbol for boat tickets

---

src/stacks-hierarchy/RootStack.tsx
src/stacks-hierarchy/Root_AddPaymentMethodScreen/Root_AddPaymentMethodScreen.tsx
src/stacks-hierarchy/Root_AddPaymentMethodScreen/use-add-payment-method.tsx
src/stacks-hierarchy/Root_PurchasePaymentWithCreditCardScreen/use-terminal-state.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentOptionsScreen.tsx
src/stacks-hierarchy/navigation-types.ts
src/ticketing/api.ts
src/ticketing/types.ts
src/ticketing/utils.ts
src/translations/screens/subscreens/AddPaymentMethodTexts.ts
src/translations/screens/subscreens/PaymentOptions.ts

Closes https://github.com/AtB-AS/kundevendt/issues/3533

feat: Save payment card outside of purchase process

---

.github/workflows/test-performance-android.yml
e2e/test/pageobjects/departure.overview.page.ts
e2e/test/specs/departure.e2e.ts
e2e/test/specs/frontpage.e2e.ts
e2e/test/utils/element.helper.ts

The E2E-test GH Action job runs a tsc check on the e2e folder. The errors are fixed here.

test: fix tsc error

---

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/translations/screens/subscreens/PurchaseConfirmation.ts

closes https://github.com/AtB-AS/kundevendt/issues/11850

feat: remove info message about ticket starting now

---

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/translations/screens/subscreens/PurchaseConfirmation.ts

closes https://github.com/AtB-AS/kundevendt/issues/11850
ref. https://github.com/AtB-AS/mittatb-app/pull/3936#discussion_r1356689240

feat: remove info message about ticket start time

---

src/translations/screens/FareContract.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/10491
Couldn't find any other references to passenger boat in either webshop, app or reference data.

fix: changes from passenger boat -> express boat in liue with KTF

---

src/components/screen-header/ScreenHeader.tsx

closes https://github.com/AtB-AS/kundevendt/issues/12601

fix: move padding below global messages in headers

---

src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketSummary/TicketSummary.tsx
src/translations/screens/TicketAssistant.ts

This PR is dependent on https://github.com/AtB-AS/atb-ticket/pull/196. 
If the recommended ticket is very close to the price of single tickets, we still recommend the periodic one as it allows for more flexibility. Was discussed with @Sebstorvik

fix: added case to ticket assistant

---

src/api/types/mobility.ts
src/stacks-hierarchy/Root_ParkingViolationsReporting/Root_ParkingViolationsConfirmation.tsx
src/stacks-hierarchy/Root_ParkingViolationsReporting/Root_ParkingViolationsPhoto.tsx
src/stacks-hierarchy/Root_ParkingViolationsReporting/Root_ParkingViolationsQr.tsx
src/stacks-hierarchy/Root_ParkingViolationsReporting/components/ProviderLogo.tsx
src/stacks-hierarchy/Root_ParkingViolationsReporting/components/ScreenContainer.tsx
src/translations/screens/ParkingViolations.ts

Fixes found during testing of https://github.com/AtB-AS/kundevendt/issues/7908
Corresponding BFF pr: https://github.com/AtB-AS/atb-bff/pull/307

fix: Misc parking violations reporting fixes

---

src/stacks-hierarchy/Root_ParkingViolationsReporting/Root_ParkingViolationsSelect.tsx
src/stacks-hierarchy/Root_ParkingViolationsReporting/components/ScreenContainer.tsx
src/translations/screens/ParkingViolations.ts

Fixes an error introduced in a previous pr and aligns texts to Figma sketches.
https://github.com/AtB-AS/kundevendt/issues/7908

fix: Parking violations titles

---

src/fare-contracts/details/Barcode.tsx
src/translations/screens/FareContract.ts

Should solve issue mentioned in https://github.com/AtB-AS/mittatb-app/pull/3952#issuecomment-1766362259

fix: accessability for barcode

---

src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx
src/stacks-hierarchy/Root_LocationSearchByTextScreen/utils.ts

- Not filtering out previous locations from results
- Deleted filter function
https://github.com/AtB-AS/mittatb-app/assets/70323886/fa035aae-c39c-4a78-a418-d83f4c3c384e

fix: show favorites in search results

---

src/tariff-zones-selector/TariffZonesSelectorMap.tsx
src/utils/__tests__/use-delay-gate.test.ts
src/utils/use-delay-gate.ts
src/utils/use-is-loading.ts

During our team talk today we mob-programmed a few eslint
exhaustive deps fixes.

refactor: Some eslint exhaustive deps fixes

---

src/analytics/AnalyticsContext.tsx
src/stacks-hierarchy/Root_TipsAndInformation/Root_TipsAndInformation.tsx
src/theme/ThemeContext.tsx
src/travel-details-screens/use-current-trip-pattern-with-updates.ts
src/travel-details-screens/use-get-service-journey-vehicles.ts
src/utils/use-focus-on-load.ts
src/utils/use-interval.ts

refactor: Some low hanging exhaustive deps fixes

---

src/AppContext.tsx
src/storage/StorageModel.tsx

Removes some remaining state for some old ticketing information, that's no longer in use.

chore: remove unused state for tickeing info

---

src/push-notifications/index.ts
src/push-notifications/use-push-notifications-enabled.tsx
src/remote-config.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
src/storage/StorageModel.tsx

🔔 Feature Toggle for Push Notifications
Added feature toggle, with debug override, for push notifications.
Stored as `enable_push_notifications` in remote config.
Adding this PR to https://github.com/AtB-AS/kundevendt/issues/5674, so they can be tested together. 
https://github.com/AtB-AS/mittatb-app/pull/3996 is dependent on this PR

feat: feature toggle for push notifications

---

src/api/mobility.ts

fixes https://github.com/AtB-AS/kundevendt/issues/15210

fix: prevent unnecessary station requests

---

.eslintrc.js
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistantContext.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_CategoryPickerScreen.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_DurationScreen/TicketAssistant_DurationScreen.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_FrequencyScreen.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_ZonePickerScreen.tsx

💥 Fixed exhaustive deps in the ticket assistant. 
☝🏻 Also found a minor quotation mark fix in `eslintrc.js`
✅ Acceptance criteria:
- Be able to select zones
- Be able to swipe between pages, and the data should be correct

refactor: ticket assistant eslint exhaustive deps

---

src/preferences/types.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx

❌ **Problem:**
> Info texts are not shown for users which had toggled of the "Show info" toggle which we previously had in the app.
✅ **Solution:** Removed the usage of the preference

fix: remove usage of hideTravellerDescription

---

src/api/client.ts
src/api/headers.ts

Discussed here: https://github.com/AtB-AS/mittatb-app/pull/4011#discussion_r1385068257
Closes https://github.com/AtB-AS/kundevendt/issues/15395

chore: Add Platform.Version as http header

---

src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx

ref https://mittatb.slack.com/archives/C02EEG7D8EL/p1699627568987689

fix: update invalid notifications import

---

android/app/src/beacons/AndroidManifest.xml
src/beacons/use-beacons.ts
src/translations/dictionary.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/8615
Rationale way of work:
https://reactnative.dev/docs/permissionsandroid#request

Fix: Bluetooth for Android permissions

---

package.json
yarn.lock

Related to https://github.com/AtB-AS/kundevendt/issues/15480
There are some issues happening when adding payment method in the Android version of the app, this dependency update hopefully fixes that and we should update the version anyway to help with stability.

chore: update react-native-webview to v13.6.2

---

src/notifications/use-push-notifications.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx

ref. https://mittatb.slack.com/archives/C0642RNB86L/p1700032726550399

feat: add notification register and token to debug menu

---

android/app/build.gradle
package.json
yarn.lock

Closes https://github.com/AtB-AS/kundevendt/issues/8615

fix: Update Kettle SDK

---

android/app/src/main/AndroidManifest.xml

Closes https://github.com/AtB-AS/kundevendt/issues/8615

fix: Remove broadcaster from Kogenta SDK

---

src/favorites/FavoritesContext.tsx

Ensure that `potentiallyMigrateFavoriteDepartures` is a stable reference.
Fixes potential future issue as mentioned [here](https://github.com/AtB-AS/mittatb-app/pull/4056#discussion_r1400312428).
Resolves https://github.com/AtB-AS/kundevendt/issues/2732

fix: wrap potentiallyMigrateFavoriteDepartures in useCallback

---

ios/departureWidget/APIService.swift

fix: Change invalid var name

---

src/translations/screens/LocationWhenInUsePermission.ts

From https://github.com/AtB-AS/kundevendt/issues/8622#issuecomment-1822262927

feat: Update location onboarding title

---

e2e/test/pageobjects/onboarding.page.ts
e2e/test/specs/onboarding.e2e.ts
src/onboarding-screen/OnboardingScreen.tsx
src/stacks-hierarchy/Root_LocationWhenInUsePermissionScreen.tsx
src/stacks-hierarchy/Root_NotificationPermissionScreen.tsx
src/stacks-hierarchy/Root_ShareTravelHabitsScreen.tsx

Added test-ids to the new "onboarding" screens, and adapted the e2e tests accordingly.

test: handle onboarding in e2e

---

src/api/delete_profile.ts

After creating a [new profile service on the BE](https://github.com/AtB-AS/team-platform/issues/446), we now have [new Url's ](https://github.com/AtB-AS/team-platform/issues/446#issuecomment-1823970984)for requests to this service. We therefore should update the url for the DELETE request in the app. 
We will add GET and PATCH as part of work in https://github.com/AtB-AS/kundevendt/issues/4275, but opening a separate PR for changing the existing one (delete) in the app.

feat: update url for delete profile

---

src/notifications/types.ts
src/notifications/use-on-push-notification-opened.ts

ref. https://github.com/AtB-AS/mittatb-app/pull/4065#discussion_r1405920785

refactor: change push notification payload type naming

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx

Fixes bug found during testing: https://github.com/AtB-AS/kundevendt/issues/15752#issuecomment-1831541094

bug: Hide announcements header when no active announcements.

---

src/mobility/use-is-eligible-for-benefit.tsx

Found during testing of https://github.com/AtB-AS/kundevendt/issues/15779

bug: Benefit isLoading is not working as expected when enabled is false

---

package.json
src/mobility/components/BicycleSheet.tsx
src/mobility/components/BikeStationBottomSheet.tsx
src/mobility/components/ScooterSheet.tsx
src/theme/ThemedAssets.tsx
yarn.lock

Found during testing of https://github.com/AtB-AS/kundevendt/issues/15241

fix: Update mobility images according to theme

---

src/notifications/api/index.ts

closes https://github.com/AtB-AS/kundevendt/issues/15875

refactor: remove duplicate header data from notification register body

---

src/index.tsx
src/mobile-token/MobileTokenContext.tsx
src/mobile-token/use-token-toggle-details.ts
src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TravelTokenScreen/ChangeTokenAction.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TravelTokenScreen/Profile_TravelTokenScreen.tsx
src/token-toggle-info/TokenToggleInfo.tsx

Follow up of https://github.com/AtB-AS/mittatb-app/pull/4064
Also fixes https://github.com/AtB-AS/kundevendt/issues/8653#issuecomment-1831493326

refactor: Use useQuery for useTokenToggleDetails hook.

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_EditProfileScreen.tsx

Allow empty email address when editing account details
Closes: https://github.com/AtB-AS/kundevendt/issues/15944

fix: allow empty email address when editing account details

---

src/announcements/AnnouncementsContext.tsx

Since we have introduced min/max version, to/from data and a rule
enginge, we need to update announcements versioning.
Note: Need to be added to Firestore as well. Remember the document rules.

feat: Announcements v2

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NotificationsScreen.tsx
src/translations/screens/Profile.ts

Added button to add e-mail to profile for e-mail notifications.
Closes: https://github.com/AtB-AS/kundevendt/issues/7225

feat: add register email button in notifications

---

src/on-behalf-of/index.ts
src/on-behalf-of/use-on-behalf-of.tsx
src/remote-config.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
src/storage/StorageModel.tsx

Added feature flag for onBehalfOf.
Flag in remote config: `enable_on_behalf_of `

feat: onBehalfOf feature flag

---

src/components/toggle/Toggle.tsx

fixes comment https://github.com/AtB-AS/kundevendt/issues/7225#issuecomment-1855916381

fix: show disabled toggle state on android

---

src/fare-contracts/FareContractAndReservationsList.tsx
src/stacks-hierarchy/Root_MobileTokenOnboarding/components/InspectableTokenInfo.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TravelTokenScreen/Profile_TravelTokenScreen.tsx
src/theme/ThemedAssets.tsx
src/theme/colors.ts
src/translations/components/TravelTokenBox.ts
src/translations/screens/subscreens/TravelToken.ts
src/travel-token-box/TravelTokenBox.tsx
src/travel-token-box/TravelTokenDeviceTitle.tsx
src/travel-token-box/index.ts

A part of https://github.com/AtB-AS/kundevendt/issues/8620
This updates the existing TravelTokenBox component with the new design.
NOTE: The Change button currently does nothing. This is intentional and will be updated in an upcoming PR.
Edit: after some font and text changes:

feat: update TravelTokenBox

---

src/components/text/index.ts
src/components/text/markdown-renderer.tsx
src/components/text/strip-markdown.tsx
src/configuration/types.ts
src/remote-config.ts
src/stacks-hierarchy/RootStack.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FareProductHeader.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-is-ticket-information-enabled.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
src/stacks-hierarchy/Root_TicketInformationScreen.tsx
src/stacks-hierarchy/navigation-types.ts
src/storage/StorageModel.tsx
src/translations/screens/subscreens/PurchaseOverview.ts

Closes https://github.com/AtB-AS/kundevendt/issues/15899
This pr contains the ticket information page with just the description section. Mobility benefits and generic tips and information are handled in separate PRs.
<details>
<summary>Screen shots</summary>
</details>
Related pr: https://github.com/AtB-AS/firestore-configuration/pull/397

feat: Ticket information screen

---

src/components/screen-view/FullScreenView.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/16103

fix: Show header in FullScreenView without parallax content

---

src/notifications/api/index.ts
src/notifications/use-push-notifications.tsx
src/translations/utils.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/16111

refactor: use LanguageAndTextLanguagesEnum for register notification

---

src/stacks-hierarchy/Root_TicketInformationScreen.tsx

Fixes issue found during testing of https://github.com/AtB-AS/kundevendt/issues/15899
https://github.com/AtB-AS/kundevendt/issues/15899#issuecomment-1864083084

fix: Ticket info heading padding

---

src/translations/screens/subscreens/EditProfileScreen.ts

Closing https://github.com/AtB-AS/kundevendt/issues/16096 
Addressing comment https://github.com/AtB-AS/mittatb-app/pull/4140#discussion_r1432716517

fix: typos in disabled email field texts

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NotificationsScreen.tsx

- If the user haven't given permission to receive notifications, the toggle value is always false.
- If the user doesn't have an email registered on their profile, the toggle value is always false.
might fix some of the issues in https://mittatb.slack.com/archives/C0642RNB86L/p1703160462775469

fix: use local status in notification toggle values

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx

Found during testing of https://github.com/AtB-AS/kundevendt/issues/8621

fix: Update privacy screen to match Figma

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx
src/translations/screens/subscreens/PurchaseOverview.ts

Closes https://github.com/AtB-AS/kundevendt/issues/15551
- Adds a new text when user is sending ticket to others
- Adds accessibility text when user is sending ticket to others

feat: add info text when sending ticket to others on traveller selection

---

package.json
src/GeolocationContext.tsx
src/components/map/hooks/use-decide-camera-focus-mode.tsx
src/favorites/types.ts
src/parking-violations-reporting/use-parking-violations.tsx
src/sdk.ts
src/situations/types.ts
src/situations/utils.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/SelectFavouritesBottomSheet.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/RailReplacementBusMessage.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/handle-recommended-ticket-response.ts
src/travel-details-screens/components/TripSection.tsx
src/utils/location.ts
src/utils/transportation-names.ts
src/utils/use-initial-coordinates.ts
yarn.lock

closes https://github.com/AtB-AS/kundevendt/issues/16187
This PR will : 
- Move some types/enums/interfaces to `sdk.ts` as temporary place before further refactoring
- Remove entur sdk dependency from `package.json`
- Remove some unused types from `sdk.ts`

chore: remove Entur SDK

---

src/mobility/components/OperatorActionButton.tsx
src/mobility/use-app-missing-alert.tsx
src/mobility/use-stations.tsx
src/mobility/use-vehicles.tsx

Fixes exhaustive deps errors in mobility. 
Partly closes https://github.com/AtB-AS/kundevendt/issues/15526

fix: Remove exhaustive deps errors in mobility

---

src/information-screen/InformationScreenComponent.tsx

Part of https://github.com/AtB-AS/kundevendt/issues/16180

fix: Use FullScreenView on InformationScreenComponent

---

src/analytics/AnalyticsContext.tsx
src/analytics/use-is-posthog-enabled.tsx
src/index.tsx
src/remote-config.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
src/storage/StorageModel.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/7801
Remote config is added in both Staging and Production

feat: Feature toggle for PostHog

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/16203

fix: Remove excessive padding in travel info

---

src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx

Same as https://github.com/AtB-AS/mittatb-app/pull/4108, except it now works with https://github.com/AtB-AS/mittatb-app/pull/4136

chore: re-add feature toggle for notification check on startup

---

src/chat/ContactSheet.tsx
src/chat/use-chat-icon.tsx
src/components/bottom-sheet/BottomSheetContainer.tsx
src/components/bottom-sheet/BottomSheetHeader.tsx
src/departure-list/section-items/FavoriteDialogSheet.tsx
src/service-disruptions/ServiceDisruptionSheet.tsx
src/service-disruptions/use-service-disruption-icon.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/StartTimeSelection.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravelDate/TravelDateSheet.tsx

Bottom sheet title were always focused, so when another ref was
added to the sheet content it was a race condition which ref was
focused by the screen reader.
Added a parameter to the BottomSheetContainer to specify whether
the title should be focused or not, and fixed up some of the bottom
sheets to use this parameter correctly.

fix: Bottom sheet title focus race condition

---

src/AppContext.tsx
src/translations/screens/subscreens/Login.ts

Fixes for https://github.com/AtB-AS/mittatb-app/pull/4106#discussion_r1433984534 and https://github.com/AtB-AS/mittatb-app/pull/4106#discussion_r1441573894

fix: use correct strings

---

src/beacons/BeaconsContext.tsx

This PR handles a case where the `KettleInfo` state changed due to a revoke, onboard but the `useEffect` was not aware of it, so it did not trigger start again the beacons, so `kettleInfo` had to be added in the deps list in order to know if it is running or not and depending on changes, and be able to start it again.

fix: Update Beacons context to handle better status updates

---

src/beacons/BeaconsContext.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx
src/translations/screens/subscreens/PrivacySettingsTexts.ts

closes https://github.com/AtB-AS/kundevendt/issues/16285

feat: redirect to Settings from PrivacyScreen for permissions

---

src/beacons/BeaconsContext.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/16142

fix: Check for permissions before start the beacons

---

src/api/types/generated/DeparturesQuery.ts
src/place-screen/components/EstimatedCallItem.tsx

closes https://github.com/AtB-AS/kundevendt/issues/16257
BFF part: https://github.com/AtB-AS/atb-bff/pull/322

fix: use service journey transport mode in departure

---

src/onboarding-screen/OnboardingScreenComponent.tsx

Fix for android, see [comment here](https://github.com/AtB-AS/mittatb-app/pull/4230/files/04c722a41280339fe713a4b85f69403ba2178c31#r1453319773)

fix: missing accessible for android

---

src/components/bordered-info-box/BorderedInfoBox.tsx
src/components/theme-icon/NotificationIndicator.tsx
src/components/theme-icon/ThemeIcon.tsx
src/components/theme-icon/types.ts
src/storybook/stories/BorderedInfoBox.stories.js

Needed since the component is going to be used on recent ticket
component which is styles based on interactive color.

refactor: Bordered box support interactive color

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx

Closing https://github.com/AtB-AS/kundevendt/issues/16587
Not able to test locally, so maybe the reviewer with a functional setup could verify this works as intended? 🙏

feat: hide new pill for privacy choice if beacons are disabled

---

src/mobility/api/api.ts

Follow up to https://github.com/AtB-AS/kundevendt/issues/15906, now that https://github.com/AtB-AS/team-platform/issues/487 is done 
resolves https://github.com/AtB-AS/kundevendt/issues/15906

chore: uncomment code to fetch benefits for fare products

---

.storybook/storybook.requires.js
src/components/tile/TileWithButton.tsx
src/components/tile/index.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContractComponent.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContracts.tsx
src/storybook/stories/TileWithButton.stories.tsx

closes https://github.com/AtB-AS/kundevendt/issues/16297
Adds a new "TileWithButton" component, that is used for recent face contracts, and soon for bundled benefits in ticket details.

feat: add TileWithButton component

---

src/anonymous-purchase-consequences-screen/AnonymousPurchaseConsequencesScreenComponent.tsx
src/components/bottom-sheet/BottomSheetHeader.tsx
src/onboarding-screen/OnboardingFullScreenView.tsx
src/onboarding-screen/OnboardingScreenComponent.tsx
src/stacks-hierarchy/Root_LoginOptionsScreen.tsx

Adding test-ids for the new onboarding. Will be used by an update to the e2e-tests.
Also a test-id for the bottom-sheet close button.

test: add test-ids for onboarding

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx
src/translations/screens/subscreens/PrivacySettingsTexts.ts

Closes https://github.com/AtB-AS/kundevendt/issues/16407

feature: Add button about how we use user data in privacy settings

---

package.json
src/components/icon-box/CounterIconBox.tsx
src/components/icon-box/TransportationIconBox.tsx
src/components/icon-box/TransportationIconBoxList.tsx
src/components/theme-icon/NotificationIndicator.tsx
src/components/tile/TileWithButton.tsx
src/departure-list/section-items/line.tsx
src/fare-contracts/ValidityHeader.tsx
src/fare-contracts/carnet/UsedAccessValidityHeader.tsx
src/place-screen/components/EstimatedCallItem.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductGroup.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContractComponent.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketSummary/TicketSummary.tsx
src/stacks-hierarchy/Root_TicketInformationScreen.tsx
src/travel-details-screens/DepartureDetailsScreenComponent.tsx
src/travel-details-screens/components/TripSection.tsx
yarn.lock

- Changes small icon size to 16
- Adds a new icon size, xSmall = 12
closes https://github.com/AtB-AS/kundevendt/issues/3834

feat: update icon sizes

---

fastlane/Fastfile

Closes: https://github.com/AtB-AS/kundevendt/issues/16030

fix: Fix avoid Apple complains about missing keys in infoPlist

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTileIllustration.tsx

Show TicketMultiple as illustration for carnet tickets
Closes: https://github.com/AtB-AS/kundevendt/issues/12600

style: change illustration for carnet tickets

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByProducts.tsx
src/translations/screens/subscreens/RecentFareContractsTexts.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/12515

feat: show radio group for multiple selectable fareProducts and only header section when only one selectable

---

src/fare-contracts/FareContractAndReservationsList.tsx
src/fare-contracts/FareContractInfo.tsx
src/fare-contracts/FareContractOrReservation.tsx
src/fare-contracts/PreActivatedFareContractInfo.tsx
src/fare-contracts/SimpleFareContract.tsx
src/fare-contracts/ValidityHeader.tsx
src/fare-contracts/components/FareContractStatusSymbol.tsx
src/fare-contracts/components/InspectionSymbol.tsx
src/fare-contracts/details/DetailsContent.tsx
src/fare-contracts/utils.ts
src/stacks-hierarchy/Root_FareContractDetailsScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_ActiveFareProductsTabScreen.tsx
src/stacks-hierarchy/navigation-types.ts
src/ticket-history/TicketHistoryScreenComponent.tsx
src/ticketing/TicketingContext.tsx
src/translations/screens/FareContract.ts
src/translations/screens/Ticketing.ts

closes
https://github.com/AtB-AS/kundevendt/issues/15879
https://github.com/AtB-AS/kundevendt/issues/16304
Both issues practically uses the same layout.
[Figma link for reference](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=20920-15395&mode=design&t=6mTCaFpOu6j9Cw2q-4)
This PR will make the necessary adjustments for sent tickets, some of them are:
- Adding routes and params to pass the sent ticket status.
- Add handling for validity status `sent`.
- Add text for sent tickets.
- Mark `sent` tickets as invalid for inspection.
<details>
<summary>Videos</summary>
https://github.com/AtB-AS/mittatb-app/assets/1777333/cb08a9c0-63b5-44d4-abbf-16b4366f5962
https://github.com/AtB-AS/mittatb-app/assets/1777333/890f2912-e812-4335-aab6-c277bc32ac07
</details>

feat: implement handling of tickets sent to others

---

src/components/sections/items/HeaderSectionItem.tsx

Ref. comment in: https://github.com/AtB-AS/kundevendt/issues/12515#issuecomment-1933575059

fix: add top padding to sectionHeader subtext

---

src/fare-contracts/FareContractView.tsx
src/fare-contracts/components/ConsumeCarnetBottomSheet.tsx
src/fare-contracts/components/ConsumeCarnetButton.tsx
src/fare-contracts/details/DetailsContent.tsx
src/ticketing/api.ts
src/ticketing/utils.ts
src/translations/screens/FareContract.ts

https://github.com/AtB-AS/mittatb-app/assets/1774972/a99ccbc3-49a6-462d-9434-065eb68ae85e
closes https://github.com/AtB-AS/kundevendt/issues/12562

feat: add consumption of carnet tickets

---

src/place-screen/components/EstimatedCallItem.tsx
src/travel-details-screens/DepartureDetailsScreenComponent.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/16259
This PR will :

feat: add warning icon and add warning info below title on departure

---

.github/actions/ios-build-setup/action.yml
.github/workflows/build-staging-ios.yml
.github/workflows/build-store-ios.yml
.github/workflows/inspect-variable.yml
.github/workflows/ios-certificates.yml

Closes: https://github.com/AtB-AS/kundevendt/issues/16925
Version of Xcode updated:

update: Set Xcode version to 15.2.0 (15C500b) and gha: macos-13

---

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx

Fixes https://github.com/AtB-AS/kundevendt/issues/17036

fix: fix VAT amount calculation

---

e2e/package.json
e2e/test/flashlight/performanceMeasures.e2e.ts
e2e/test/utils/app.helper.ts
src/components/popover/PopOver.tsx

The performance test script needs to handle the on-behalf-of popover. Added a step to close a popover if it exists.
NB! Added test-id to the popover component.

test: handle popovers in e2e test

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_ActiveFareProductsTabScreen.tsx
src/utils/__tests__/is-element-fully-inside-screen.test.ts
src/utils/is-element-fully-inside-screen.ts

followup of https://github.com/AtB-AS/mittatb-app/pull/4334#discussion_r1504260089
just naming change, functionality does not change at all.

refactor: rename function isViewVisibleOnScreen to isElementFullyInsideScreen

---

.github/workflows/build-staging-ios.yml
.github/workflows/build-store-ios.yml

another attempt to fix build issue, similar to https://github.com/AtB-AS/mittatb-app/pull/4366

build: remove symlink to `/usr/local/bin/2to3` on buildscript

---

.github/workflows/build-staging-ios.yml
.github/workflows/build-store-ios.yml

Include the build fix for the builds on master 
This is a combination of the following commits
- 7b17cdd8ae7542df093bad40b7020e97b4d0ba62
- d2888af80324e8233380182bb1a60950b9a38dac
- 704f175ff216d85231a2d3ac18ec79444e59e427

build: fix imagemagick installation

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx

Fixes issue on purchase overview screen, introduced by this PR https://github.com/AtB-AS/mittatb-app/pull/4364, sorry! 😅

fix: wrong popover ref causing popover not showing

---

src/fare-contracts/details/OrderDetails.tsx

This PR fixes this issue : https://mittatb.slack.com/archives/CS3JNRXEV/p1709718708466419
Wrong placement of parentheses.
Will cherry-pick to `release/1.48` after merging

fix: show valid from and valid to on ticket details

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx

Nice to have while working on https://github.com/AtB-AS/kundevendt/issues/16314

feat: add debug links to send bugsnag reports

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx

Fixes issue encountered in https://github.com/AtB-AS/mittatb-app/pull/4364
Only adding a parentheses so the grouping works properly. We should count the issues with parentheses that I have this week. 🙃

fix: traveller selection accessibility

---

src/fare-contracts/details/Barcode.tsx
src/mobile-token/MobileTokenContext.tsx
src/mobile-token/hooks/useGetSignedTokenQuery.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx

Using react-query and letting that handle the refetch interval instead.

refactor: Make getSignedToken use react-query

---

src/fare-contracts/FareContractView.tsx
src/fare-contracts/carnet/UsedAccessValidityHeader.tsx
src/fare-contracts/details/DetailsContent.tsx
src/fare-contracts/utils.ts

ref. https://mittatb.slack.com/archives/C0116FMPX4Y/p1710495503900459
<div>
</div>

fix: don't show carnets as inspectable when sent to others

---

e2e/test/pageobjects/onboarding.page.ts
e2e/test/pageobjects/purchase.overview.page.ts
e2e/test/pageobjects/purchase.payment.page.ts
e2e/test/pageobjects/purchase.summary.page.ts
e2e/test/pageobjects/ticket.page.ts
e2e/test/pageobjects/travelsearch.overview.page.ts
e2e/test/specs/ticket.e2e.ts
src/anonymous-purchase-consequences-screen/AnonymousPurchaseConsequencesScreenComponent.tsx
src/components/checkbox/Checkbox.tsx
src/components/message-info-box/MessageInfoBox.tsx
src/onboarding/OnboardingFullScreenView.tsx
src/stacks-hierarchy/Root_LoginRequiredForFareProductScreen.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelectionSheet.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ZonesSelection.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/AnonymousPurchaseWarning.tsx

Added some e2e-scenarios for ticketing (the actual purchase is not included in the tests):
- should be able to buy on behalf of others
- should have restrictions for anonymous users
- should have a correct purchase flow
NOTE! I've added some test-ids to be able to have these e2e-tests.

test: e2e-ticketing tests

---

src/onboarding/OnboardingContext.tsx

ref. https://mittatb.slack.com/archives/C0116FMPX4Y/p1711033383333879 / https://github.com/AtB-AS/mittatb-app/pull/4404

fix: check for user being undefined on auth state change

---

src/fare-contracts/FareContractInfo.tsx
src/fare-contracts/components/InspectionSymbol.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FareContractsScreen.tsx
src/ticketing/types.ts
src/ticketing/utils.ts

* Showing fare contract for Youth ticket
* Added youth ticket to `Profile_FareContractsScreen` to show the variation through the design system
Closing: https://github.com/AtB-AS/kundevendt/issues/17075

feat: show fare contract for youth-ticket

---

ios/Podfile.lock

Related to: https://github.com/AtB-AS/kundevendt/issues/16261

fix: Update podfile to upgrade hermes engine

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ZonesSelection.tsx
src/translations/screens/subscreens/PurchaseOverview.ts

fixes issue https://github.com/AtB-AS/kundevendt/issues/17191#issuecomment-2039697224
Figma reference: https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=24257-23049&mode=design&t=pUHna6cMye5jWctn-4

fix: use correct zone label & a11y

---

src/fare-contracts/FareContractView.tsx
src/fare-contracts/details/DetailsContent.tsx
src/ticketing/utils.ts

closes https://github.com/AtB-AS/kundevendt/issues/17263
add check for sent tickets when showing the activation button.

fix: remove activation button on sent carnet tickets

---

src/ticketing/utils.ts

closes : https://github.com/AtB-AS/kundevendt/issues/17595
old PR and discussion : https://github.com/AtB-AS/mittatb-app/pull/4430
Use existing function for checking ticket status.

fix: use correct check for disabling carnet consumption

---

src/api/types/generated/journey_planner_v3_types.ts

This updates journey_planner_v3_types to the new version after https://github.com/AtB-AS/atb-bff/pull/330.

chore: update journey_planner_v3_types.ts

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/17026

fix: Remove screen with restriction about do not allow user to buy ticket on fallback state

---

docs/TicketingQA.md

ref. https://mittatb.slack.com/archives/C02EEG7D8EL/p1713340972289909

docs: update TicketingQA.md

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx

closes https://github.com/AtB-AS/kundevendt/issues/17105
Pretty straightforward PR, I changed some naming for consistency, mainly the `styles = useStyles()` part.

feat: update travel assistant header button style

---

package.json
src/configuration/FirestoreConfigurationContext.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
src/translations/screens/Profile.ts
yarn.lock

Added a link to the accessibility statement in profile screen under "info and prices"
Part of: https://github.com/AtB-AS/kundevendt/issues/17480

feat: add link to a11y statement for the app

---

src/popover/PopOverContext.tsx

closes https://github.com/AtB-AS/kundevendt/issues/17628
comment out the code that shows the popover, the rest of the code will be removed if popover is no longer used, which will be decided in the future.
Example issue with popover: https://github.com/AtB-AS/kundevendt/issues/17475

feat: disable popover

---

android/app/build.gradle
ios/Podfile.lock
package.json
yarn.lock

Closes https://github.com/AtB-AS/kundevendt/issues/17604
- Includes bug fixes and privacy files as described in https://developer.kogenta.com/docs/changelog/ios#version-130
- New privacy policy required from Apple (required for https://github.com/AtB-AS/mittatb-app/pull/4438)

fix: Update kettle SDK to the newest version

---

ios/Podfile.lock
ios/PrivacyInfo.xcprivacy
ios/atb.xcodeproj/project.pbxproj
package.json
yarn.lock

Closes https://github.com/AtB-AS/kundevendt/issues/17379
Taking as base input:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc
NOTE: Some of the definitions are needed from our vendors before merge this. There is a current PR for this on https://github.com/AtB-AS/mittatb-app/pull/4453

fix: 🍎 Privacy info declarations

---

src/global-messages/GlobalMessage.tsx

closes https://github.com/AtB-AS/kundevendt/issues/17781
Adds capability to set rules for `authenticationType`, the usage is similar to the existing rule system.

feat: add global rule for checking authentication type

---

src/stacks-hierarchy/Root_LoginOptionsScreen.tsx

ref. https://github.com/AtB-AS/kundevendt/issues/17792

feat: highlight Vipps login on LoginOptionsScreen

---

src/translations/components/ScreenHeader.ts
src/translations/components/ServiceDisruptions.ts
src/translations/screens/ExtendedOnboarding.ts
src/translations/screens/Profile.ts
src/translations/screens/subscreens/ContactSheet.ts
src/translations/screens/subscreens/DeleteProfile.ts
src/translations/screens/subscreens/MobileTokenOnboarding.ts
src/translations/screens/subscreens/OnBehalfOf.ts
src/translations/screens/subscreens/PurchaseConfirmation.ts
src/translations/screens/subscreens/PurchaseOverview.ts
src/translations/screens/subscreens/TravelToken.ts

The hard-coded in-app texts are ready for testing

feat: Basic translations related to Troms/Svipper app

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx

Pro tip: Disable display of whitespaces when reviewing this PR 🤓
fixes https://github.com/AtB-AS/kundevendt/issues/17386

fix: make ActivityIndicatorOverlay non-scrollable

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
src/translations/screens/Profile.ts

ref. https://github.com/AtB-AS/mittatb-app/pull/4479#discussion_r1591961582 and https://github.com/AtB-AS/mittatb-app/pull/4479#pullrequestreview-2042411247

chore: update claims error

---

src/auth/use-fetch-id-token-with-custom-claims.ts
src/loading-screen/__tests__/use-notify-bugsnag-on-timeout-status.test.ts
src/loading-screen/use-notify-bugsnag-on-timeout-status.ts
src/mobile-token/MobileTokenContext.tsx
src/mobile-token/hooks/useGetSignedTokenQuery.tsx
src/stacks-hierarchy/Root_PurchasePaymentScreen/WebViewTerminal.tsx
src/ticketing/TicketingContext.tsx
src/utils/bugsnag-utils.ts

Fixes issue in master branch after merging the release 1.50 branch.

chore: fix `notifyBugsnag` function by making `errorGroupHash` optional 

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx

This PR fixes the green dot issue addressed in
https://github.com/AtB-AS/kundevendt/issues/17913#issuecomment-2110323180

fix: display green dot when filters other than the default filters are selected

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx

removing "new" label from the on-behalf-of feature as requested by @Sebstorvik

feat: remove new label from on-behalf-of feature

---

src/translations/screens/subscreens/TravelToken.ts

Add the translations for the Frequently Asked Questions for Troms, including the translations for when travel card is disabled, which are the most important ones currently.
Closes https://github.com/AtB-AS/kundevendt/issues/18118

fix: add FAQ translations for Troms

---

package.json
yarn.lock

Some minor changes to the design-system for Troms (favicon, empty illustrations, and a color change).
Partially closes https://github.com/AtB-AS/kundevendt/issues/8280

chore: upgrade atb design-system packages

---

src/mobile-token/hooks/use-toggle-token-mutation.tsx

fixes https://github.com/AtB-AS/kundevendt/issues/18134

fix: use correct query key for list tokens when toggling

---

package.json
yarn.lock

This new version contains a new NoFavoriteDeparture.svg for Troms.

chore: upgrade generate assets package

---

src/api/types/generated/TripsQuery.ts
src/api/types/generated/fragments/authority.ts
src/api/types/generated/fragments/trips.ts
src/translations/screens/subscreens/TripDetails.ts
src/travel-details-screens/components/TripSection.tsx

closes https://github.com/AtB-AS/kundevendt/issues/3238
<div>
</div>

feat: add link to authority in trip search

---

src/stacks-hierarchy/Root_LoginOptionsScreen.tsx

This reverts commit 283be7a66988188305170734ec96b8e69dd79b8b (#4462)
closes https://github.com/AtB-AS/kundevendt/issues/18052

revert: highlight Vipps login on LoginOptionsScreen

---

src/translations/screens/subscreens/TripDetails.ts
src/travel-details-screens/components/TripSection.tsx

closes https://github.com/AtB-AS/kundevendt/issues/3238
- Fixes a Talkback issue https://github.com/AtB-AS/kundevendt/issues/3238#issuecomment-2126589724
- And text in the header https://github.com/AtB-AS/kundevendt/issues/3238#issuecomment-2126857109

fix: fix authority link a11y and wording

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Summary.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts
src/translations/screens/subscreens/PurchaseOverview.ts

part of https://github.com/AtB-AS/kundevendt/issues/18132
In this PR : 
1. Defaults the flexible discount dropdown to closed state.
2. Show original price when a discount is applied.
3. Hide the flex discount layout when there is no flex discounts available, but show them if there are flex discount available. (the new flex discount allows purchasing other types of user and the flex discount will apply to eligible passengers, f.eks: 1 voksen & 1 honnør, only the voksen gets flex discounted price, total price is discounted price for voksen + normal price for honnør) - not testable yet, the backend isn't ready.
4. ~~Shows multiple rows of passengers that gets a discount on discount information (f.eks 5 voksen = 5 rows of passengers on discount information)~~ **UPDATE**: based on latest …

feat: update flexible ticket discount dropdown layout

---

src/remote-config.ts

I suggest sorting the remote-config file alphabetically to make it easier to read and get an overview when adding new parameters.
It's a suggestions so approve if you agree this could be a good idea! 🌟

refactor: sort remote-config file alphabetically to improve legibility

---

src/storage/StorageModel.tsx

similar to https://github.com/AtB-AS/mittatb-app/pull/4546
Since we will add some remote config values for auth, I'm guessing this will also improve legibility. (?)
Let me know what do you think!

refactor: sort storage model keys enum alphabetically

---

package.json
src/components/label-info/LabelInfo.tsx
src/components/message-info-box/MessageInfoBox.tsx
src/components/sections/items/MessageSectionItem.tsx
src/components/text/ThemeText.tsx
src/components/theme-icon/NotificationIndicator.tsx
src/components/theme-icon/ThemeIcon.tsx
src/components/theme-icon/types.ts
src/fare-contracts/components/InspectionSymbol.tsx
src/fare-contracts/use-validity-line-colors.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
src/storybook/ThemedStoryDecorator.tsx
src/storybook/stories/ThemeIcon.stories.tsx
src/storybook/stories/ThemeText.stories.tsx
src/theme/colors.ts
yarn.lock

related to
- https://github.com/AtB-AS/kundevendt/issues/15379
- https://github.com/AtB-AS/kundevendt/issues/18138
- https://github.com/AtB-AS/kundevendt/issues/18136
related PR on https://github.com/AtB-AS/design-system/ :
- https://github.com/AtB-AS/design-system/pull/171
- https://github.com/AtB-AS/design-system/pull/172
This PR will update the usage of all `StatusColor` to match the new system.
Color update (when it is ready) will also affect the "New"/"Ny" badge color in https://github.com/AtB-AS/kundevendt/issues/18132
Most color usage right now is mapped to `primary` and some to `secondary`, currently there are no differences between `primary` and `secondary`, but this will change when the design for OMS is ready, and the usage should be checked across components.
<details> …

feat: update status color usage

---

src/components/snackbar/Snackbar.tsx
src/components/snackbar/__tests__/use-stable-value.test.ts
src/components/snackbar/index.ts
src/components/snackbar/use-snackbar-is-visible.ts
src/components/snackbar/use-snackbar-screen-reader-focus.ts
src/components/snackbar/use-snackbar-vertical-position-animation.ts
src/components/snackbar/use-stable-value.ts

This PR adds https://github.com/AtB-AS/mittatb-app/pull/4561 to the release branch.
---
* Support Snackbar position toggling
* Rename to isDisabled
* Optimize with SnackbarInstanceAtPosition
* Reduce Snackbar complexity
* Set opacity 0 when Snackbar is hidden
* Set Snackbar pointerEvents none while hidden
* nfk tsc fix
* Pair progamming refactor
* oops
* Revert "oops"
This reverts commit 06e82f92f65498e925753f17380a0d38425e6417.
* Revert "Pair progamming refactor"
This reverts commit a8cc6310a211d24b1f633b0f057b439cef5d4ac0.
* Revert "nfk tsc fix"
This reverts commit fa30a5329f7cda6b966d9d16d03c3c977c21bf67.
* Revert "Set Snackbar pointerEvents none while hidden"
This reverts commit 78402f80ff048b735482ceab2b9fbf4d4a1ceee5.
* Revert "Set opacity 0 when Snackbar is hidden"
This reverts …

feat: support Snackbar position toggling (#4561)

---

package.json
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/translations/screens/subscreens/PurchaseConfirmation.ts
yarn.lock

Implementation of config from https://github.com/AtB-AS/fare-product-type-configs/pull/50

feat: use direction config to show boat validity texts

---

src/api/vipps-login/api.ts

Vipps login using the identity service should now be ready for use in staging

Use identity service for vipps login

---

src/api/identity.ts
src/auth/AuthContext.tsx
src/auth/auth-utils.ts
src/auth/types.ts
src/auth/use-is-backend-sms-auth-enabled.tsx
src/translations/screens/subscreens/Login.ts

closes https://github.com/AtB-AS/kundevendt/issues/18127

feat: add identity service SMS login

---

src/auth/auth-utils.ts
src/auth/types.ts
src/translations/components/PhoneInput.ts

closes https://github.com/AtB-AS/kundevendt/issues/18127
ref. https://mittatb.slack.com/archives/C06U8EM72TF/p1718710006130689

feat: support 429 errors on phone sign in

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx

closes https://github.com/AtB-AS/kundevendt/issues/18458
remove label as requested

feat: remove "new" label for profile and notifications

---

src/fare-contracts/__tests__/sort-fc-reservation-by-validity-creation.test.ts
src/fare-contracts/details/OrderDetails.tsx
src/ticketing/types.ts
src/translations/screens/FareContract.ts

closes https://github.com/AtB-AS/kundevendt/issues/17139
Should be a pretty straightforward PR, just adding the price from fareContract firestore to show on the app.

feat: add ticket price to ticket detail screen

---

src/stacks-hierarchy/Root_PurchasePaymentScreen/Root_PurchasePaymentScreen.tsx
src/stacks-hierarchy/Root_PurchasePaymentScreen/use-purchase-callback-listener.ts

Closes https://github.com/AtB-AS/kundevendt/issues/18133
I wrote a comment in the issue about the conclusions of why this.

refactor: Redirect user to my tickets if wrong payment state

---

android/app/src/debug/AndroidManifest.xml
android/app/src/staging/AndroidManifest.xml
android/app/src/staging/res/network_security_config.xml

For testing purposes we need to use proxyman in staging to intercept network calls. In order for it to work for android in staging we need som additional configuration. This should not affect prod or store. 
From proxyman documentation: https://docs.proxyman.io/debug-devices/android-device#:~:text=Open%20your%20app,files

chore: update network security config

---

android/app/src/debug/res/xml/network_security_config.xml
android/app/src/staging/AndroidManifest.xml
android/app/src/staging/res/xml/network_security_config.xml

Added clearTextTrafficPermitted parameter to config for showing network requests in proxyman.

chore: add clearTextTrafficPermitted

---

src/fare-contracts/FareContractView.tsx
src/fare-contracts/components/ActivateNowSectionItem.tsx
src/translations/screens/FareContract.ts

closes https://github.com/AtB-AS/kundevendt/issues/18387

feat: update activate now button

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentOptionsScreen.tsx
src/translations/screens/Profile.ts
src/translations/screens/subscreens/PaymentOptions.ts

closes https://github.com/AtB-AS/kundevendt/issues/18562

feat: change "payment options" to "payment cards"

---

src/translations/screens/subscreens/AddPaymentMethodTexts.ts
src/translations/screens/subscreens/PaymentOptions.ts

https://github.com/AtB-AS/mittatb-app/pull/4617#discussion_r1664198050 and https://github.com/AtB-AS/kundevendt/issues/18562#issuecomment-2206120344

chore: update remaining payment method texts

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx
src/translations/screens/subscreens/PurchaseOverview.ts

feat: update translations for flexible ticket

---

src/translations/screens/subscreens/AnonymousPurchases.ts

closes https://github.com/AtB-AS/kundevendt/issues/18590

feat: add text about accumulated price on anonymous info screen

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx
src/translations/screens/subscreens/AnonymousPurchases.ts
src/translations/screens/subscreens/PurchaseOverview.ts

This reverts commit 5e360c5df13a5f4ceb1bb029357646b824528fc4. (https://github.com/AtB-AS/mittatb-app/pull/4625)
Also updates text on anonymous purchase consequences to "You lose access to previously purchased tickets, history and discounts if you lose or get a new phone."
closes https://github.com/AtB-AS/kundevendt/issues/18590

revert: revert most of the recent flexible ticket changes

---

src/stacks-hierarchy/Root_LoginConfirmCodeScreen.tsx
src/stacks-hierarchy/Root_LoginPhoneInputScreen.tsx
src/utils/use-rate-limit-when.ts

implements https://github.com/AtB-AS/mittatb-app/pull/4621#issuecomment-2206196503
closes https://github.com/AtB-AS/kundevendt/issues/18555

refactor: add useRateLimitWhen hook for login timeouts

---

package.json
src/components/message-info-box/MessageInfoBox.tsx
src/components/message-info-text/MessageInfoText.tsx
src/components/sections/items/MessageSectionItem.tsx
src/components/sections/items/PhoneInputSectionItem.tsx
src/components/sections/items/TextInputSectionItem.tsx
src/departure-list/section-items/line.tsx
src/mobility/components/BenefitImage.tsx
src/place-screen/components/EstimatedCallItem.tsx
src/situations/SituationOrNoticeIcon.tsx
src/situations/utils.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/RailReplacementBusMessage.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
src/token-toggle-info/TokenToggleInfo.tsx
src/travel-details-screens/DepartureDetailsScreenComponent.tsx
src/travel-details-screens/components/BookingInfoBox.tsx
src/travel-details-screens/components/FlexibleTransportBookingDetailsSheet.tsx
src/travel-details-screens/components/TripSection.tsx
src/travel-details-screens/components/WaitSection.tsx
src/utils/message-type-to-icon.ts
yarn.lock

<div>
</div>
closes https://github.com/AtB-AS/kundevendt/issues/15379
closes https://github.com/AtB-AS/kundevendt/issues/18138

feat: update message box colors and icons

---

package.json
yarn.lock

closes https://github.com/AtB-AS/kundevendt/issues/18463

chore: upgrade theme to include new atb colors

---

ios/atb.xcodeproj/project.pbxproj
ios/departureWidget/DepartureWidget.swift
ios/departureWidget/Structs.swift

Enables live-ish editing of departureWidget
Follow up to https://github.com/AtB-AS/mittatb-app/pull/4636

feat: add Xcode Preview of DepartureWidget

---

src/stacks-hierarchy/RootStack.tsx
src/stacks-hierarchy/Root_ChooseTicketReceiverScreen/index.ts
src/stacks-hierarchy/Root_ChooseTicketReceiverScreen/navigation-types.ts
src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/Root_ChooseTicketRecipientScreen.tsx
src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/index.ts
src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/navigation-types.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/navigation-types.ts

Aligning the naming in the app with what is used in Figma. No code
changes done, just file/directory renaming.

refactor: TicketReceiver -> TicketRecipient

---

src/global-messages/types.ts
src/rule-engine/rules.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/18591

feat: Global message to inform about flexible tickets for anonymous

---

android/app/build.gradle
android/app/src/beacons/AndroidManifest.xml

Closes https://github.com/AtB-AS/kundevendt/issues/18747

fix: Crashes for android when collection of travel data is turned on

---

src/components/sections/RadioGroupSection.tsx
src/components/sections/items/RadioSectionItem.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx

Necessary for the delete recipient flow.
Screenshot from design-system in app:

feat: Add support for right side action on radio sections

---

src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/SubmitButton.tsx

Background: https://github.com/AtB-AS/kundevendt/issues/17226#issuecomment-2291270901

fix: Not always send in recipient name

---

src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/ExistingRecipientsList.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentOptionsScreen.tsx
src/translations/dictionary.ts
src/translations/screens/subscreens/OnBehalfOf.ts

Background: 
https://www.figma.com/design/zdZwvobgpEWSagKt0tderx/App?node-id=26201-72898&t=RMkoLnHR96X3FIhu-4
In-app screenshot:

feat: Add delete recipient modal

---

src/fare-contracts/FareContractInfo.tsx
src/fare-contracts/details/DetailsContent.tsx
src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/ExistingRecipientsList.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_EditProfileScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
src/translations/screens/subscreens/EditProfileScreen.ts
src/utils/phone-number-utils.ts

Background:
https://github.com/AtB-AS/kundevendt/issues/17226#issuecomment-2291048304
App screenhots:
<div>
</div>

feat: Format recipient phone number

---

src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/PhoneAndNameInputSection.tsx
src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/SubmitButton.tsx
src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/types.ts
src/translations/screens/subscreens/OnBehalfOf.ts

Background:
https://github.com/AtB-AS/kundevendt/issues/17226#issuecomment-2293450504

feat: Recipient name length validation

---

src/configuration/types.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts
src/ticketing/types.ts

There were some minor errors in our typings for Offer and PreassignedFareProduct. 
- Offer updated to match https://github.com/AtB-AS/ticket-legacy/blob/696b458d9dc2042fa9d4c9cb8dee31b3512bfa54/src/tickets/search_ticket.rs#L117
- PreassignedFareProduct updated to match ReferenceData.
Noticed while working on https://github.com/AtB-AS/kundevendt/issues/18693

refactor: update Offer and PreassignedFareProduct types

---

src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/Root_ChooseTicketRecipientScreen.tsx
src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/ExistingRecipientsList.tsx
src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/TitleAndDescription.tsx

Background:
https://github.com/AtB-AS/kundevendt/issues/17226#issuecomment-2296310993

fix: ScreenReader focus after deleting recipient

---

docs/Release.md

So that people don't make the same mistake that I did....

chore: Update Release.md with version number checking

---

src/stacks-hierarchy/Root_LoginOptionsScreen.tsx

@Sebstorvik wanted us to move the Vipps button to the top again :)

chore: move vipps login button to top

---

src/components/sections/items/time-input/TimeInputSectionItem.android.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/DayLabel.tsx
src/utils/date.ts

Fixes some from feedback in https://github.com/AtB-AS/kundevendt/issues/9610
- Fixes issue with selecting time on Android devices in other timezones
- Fixes issue with date labels in search list
This does not fix all issues. But fixing continuously, and reduces most prominent bugs.

fix: issue with timezone and android time picker

---

package.json
src/place-screen/components/DateSelection.tsx
src/utils/__tests__/date.test.ts
src/utils/date.ts
yarn.lock

Fixes issues reported from https://github.com/AtB-AS/kundevendt/issues/9610#issuecomment-2301284181
- Adds tests to update time function to make sure it works
- Fixes date shown in departure view
- fixes navigate next/prev for departure view.

fix: time zone issues after enforcing CET

---

src/fare-contracts/components/InspectionSymbol.tsx

ref. https://github.com/AtB-AS/mittatb-app/pull/4693#issuecomment-2311806637

refactor: use getTransportModeSvg for inspection svg

---

src/api/vipps-login/api.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentOptionsScreen.tsx

A bit nicer opening of the in-app-browser for vipps and adding payment card
https://github.com/user-attachments/assets/92611a1e-33ae-4e16-b7bc-9bd08ebc802e
related to https://github.com/AtB-AS/kundevendt/issues/18885

feat: animate to InAppBrowser

---

patches/@entur-private+abt-token-state-react-native-lib+2.1.6.patch

Closes: https://github.com/AtB-AS/kundevendt/issues/18559
More details about why this, in the issue messages.

chore: Patch Mobile Token SDK iOS to improve error messages

---

src/api/vipps-login/api.ts
src/in-app-browser/in-app-browser.tsx
src/in-app-browser/index.ts
src/stacks-hierarchy/Root_LoginOptionsScreen.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentMethodsScreen.tsx

follow up to https://github.com/AtB-AS/mittatb-app/pull/4711#discussion_r1756891669

refactor: add in app browser util functions

---

src/components/map/Map.tsx
src/components/map/components/mobility/ShmoTesting.tsx

Fixes https://github.com/AtB-AS/kundevendt/issues/18891#issuecomment-2363415039
Only 2 changes:
- Moves `ShmoTesting` outside of `MapView`
- Uses `safeAreaTop` rather than hard coded padding
Closes https://github.com/AtB-AS/kundevendt/issues/18891

fix: Move ShmoTesting out of MapView

---

src/mobility/components/BicycleSheet.tsx
src/mobility/components/BikeStationBottomSheet.tsx
src/mobility/components/CarSharingStationBottomSheet.tsx
src/mobility/components/ScooterSheet.tsx

Fixes a padding issue.
| <img width="200" src="https://github.com/user-attachments/assets/4ad9fb22-7648-45eb-b672-e5f9dbef72aa" /> | <img width="200" src="https://github.com/user-attachments/assets/8e6f68b2-0839-4cdf-8918-e0a408b9870d" /> |

fix: Map Item Error Message Padding

---

src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/SubmitButton.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PreassignedFareProductSummary.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/navigation-types.ts
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/use-reserve-offer-mutation.ts
src/stacks-hierarchy/types.ts
src/ticketing/api.ts
src/ticketing/types.ts

closes https://github.com/AtB-AS/kundevendt/issues/19056

feat: use store_alias params on reserve offer

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/AccountWrongMessage.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/ErrorWithAccountMessage.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx
src/translations/screens/Ticketing.ts

This is in addition to the error message in the profile screen, since
we have a theory that isn't always found.

feat: Error msg on ticketing screen if something wrong with account

---

package.json
src/configuration/types.ts
yarn.lock

To some degree part of https://github.com/AtB-AS/kundevendt/issues/17087

refactor: upgrade config-specs and replace reference data types

---

ios/Podfile
ios/Podfile.lock
ios/atb.xcodeproj/project.pbxproj
package.json
yarn.lock

Compiling the app using the XCode 16 fails, these changes are intented to fix that + some upgrades needed for Mapbox.

chore: Fix compilation issues for Xcode 16 & mapbox

---

src/api/types/generated/DeparturesQuery.ts
src/place-screen/components/EstimatedCallItem.tsx
src/preferences/types.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx

closes https://github.com/AtB-AS/kundevendt/issues/19294

feat: add debug PredictionInaccurate display in departures

---

src/components/sections/items/ToggleSectionItem.tsx

Complement for: https://github.com/AtB-AS/mittatb-app/pull/4760

feat: Support markdown in the toggle component subtext

---

src/place-screen/components/EstimatedCallItem.tsx

A small testId-fix after https://github.com/AtB-AS/mittatb-app/pull/4765.

test: a small testId fix for estimated calls for departures

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_LanguageScreen.tsx

feat: Enable nynorsk for all orgs

---

src/travel-details-screens/DepartureDetailsScreenComponent.tsx

closes https://github.com/AtB-AS/kundevendt/issues/19125

feat: show travel aid only if enabled

---

src/feature-toggles/toggle-specifications.ts
src/remote-config.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_LanguageScreen.tsx

feat: Add nynorsk feature toggle

---

src/components/sections/items/ToggleSectionItem.tsx
src/components/text/ThemeText.tsx
src/components/text/markdown-renderer.tsx

Related to: https://github.com/AtB-AS/kundevendt/issues/17887
|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 - 2024-11-05 at 10 47 12](https://github.com/user-attachments/assets/452fee68-12b7-47ba-9b09-34912c1aab39)|![Simulator Screenshot - iPhone 15 - 2024-11-05 at 10 47 18](https://github.com/user-attachments/assets/819fb021-b2aa-497a-a7f5-e077de45296d)|

fix: Markdown with new lines

---

package.json
src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/StartTimeSelection.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravelDate/TravelDateSheet.tsx
src/translations/screens/subscreens/TravelDate.ts
yarn.lock

Not in use anymore:
https://mittatb.slack.com/archives/C025NUF4WA0/p1730809563733599

refactor: Remove unused latestActivationDate

---

.github/actions/python-setup/action.yml
.github/workflows/test-e2e-android.yml
.github/workflows/test-performance-android.yml
e2e/performance/createPerformanceSummary.ts
e2e/performance/removeMeasures.py
e2e/scripts/handle-flashlight-results.sh
e2e/scripts/run-flashlight-tests.sh
e2e/test/flashlight/performanceMeasures_map.e2e.ts
e2e/test/flashlight/performanceMeasures_travelsearch.e2e.ts
e2e/test/pageobjects/map.page.ts
e2e/test/specs/travelsearch.filter.e2e.ts

Per now, the tests measuring performance for Android ([action](https://github.com/AtB-AS/mittatb-app/actions/workflows/test-performance-android.yml)), run all "features" in one run. This makes it a bit harder to distinguish differences in trend for a specific feature.
This PR measures performance per feature, i.e. run a test per feature.
The map tests are created with some pinch to zoom and drag gestures to generate some actions. The travel search tests are mainly a functional test, so this (and other features) will be improved in later PRs.

test: run perf tests per feature

---

src/travel-aid/TravelAidScreenComponent.tsx

Related to: https://github.com/AtB-AS/kundevendt/issues/19126
This change fixes duplications and get information of notices from: https://github.com/AtB-AS/mittatb-app/blob/cf7423f955ea07cc8b2ac542ddd128ae3b17fc87/src/travel-details-screens/utils.ts#L71

fix: Remove duplicated messages on Journey Aid screen

---

src/travel-aid/TravelAidScreenComponent.tsx

Close https://github.com/AtB-AS/kundevendt/issues/19126
This PR allows notices/situations to be selected/focused to be used in accessibility mode, and improve the announcements.

fix: Announce situations and notices

---

src/travel-aid/TravelAidScreenComponent.tsx

Close https://github.com/AtB-AS/kundevendt/issues/19126
Fix for https://github.com/AtB-AS/mittatb-app/pull/4802

fix: Wrong semicolon breaks text in accessibility for situation messages

---

src/analytics/types.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TravelAidScreen.tsx
src/travel-details-screens/DepartureDetailsScreenComponent.tsx

closes https://github.com/AtB-AS/kundevendt/issues/19521

feat: add journey aid posthog events

---

src/translations/screens/subscreens/TravelAid.ts
src/travel-aid/TravelAidScreenComponent.tsx

ref. https://mittatb.slack.com/archives/C07TD4U69L4/p1731507606731019

fix: show "Scheduled at" text in journey aid for no realtime

---

src/travel-aid/TravelAidScreenComponent.tsx
src/travel-aid/__tests__/sent-stop-signals-cache.test.ts
src/travel-aid/sent-stop-signals-cache.ts
src/travel-aid/use-stop-signal-mutation.ts

A simple in-memory cache that is cleared at app restart.

feat: Add sent stop signals cache

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TravelAidScreen.tsx

Issue found by @tormoseng in the release candidate

fix: enable travel aid toggle regardless of stop button config

---

src/translations/screens/subscreens/TravelAid.ts
src/travel-aid/TravelAidScreenComponent.tsx
src/travel-aid/components/StopSignalButton.tsx

Changed according to latest Figma sketches.
Figma / App:
<div>
</div>

feat: Success message box instead of active button state

---

.github/workflows/tsc.yml
package.json
src/stacks-hierarchy/RootStack.tsx

This is just a suggestion. If you feel it is too strict to check prettier during build don't be afraid to say so!

build: Add check-all script for tsc, lint, test, prettier

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx

closes https://github.com/AtB-AS/kundevendt/issues/19515

chore: remove 'new' tag for my price

---

src/translations/screens/subscreens/TravelAid.ts
src/travel-aid/TravelAidScreenComponent.tsx
src/travel-aid/get-focused-estimated-call.ts
src/travel-details-screens/DepartureDetailsScreenComponent.tsx

closes https://github.com/AtB-AS/kundevendt/issues/19512

fix: make journey aid skip cancelled calls

---

src/components/sections/items/ButtonSectionItem.tsx
src/stacks-hierarchy/Root_AddEditFavoritePlaceScreen/Root_AddEditFavoritePlaceScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx

fixes https://github.com/AtB-AS/kundevendt/issues/16840#issuecomment-2507326745

fix: fix bottom sheet close focus for emoji and filters

---

src/components/bottom-sheet/BottomSheetContext.tsx

Looking for feedback in case I'm missing something, but I don't think the useMemo had much of an effect here. After replacing the `const bottomSheet = useMemo()` with a `BottomSheetOnBackDrop` component, it still seems performant, and without excessive re-renders.
closes https://github.com/AtB-AS/kundevendt/issues/16267

refactor: replace bottomSheet useMemo to fix exhaustive deps

---

src/api/vehicles.ts
src/travel-details-screens/DepartureDetailsScreenComponent.tsx
src/travel-details-screens/components/Trip.tsx
src/travel-details-screens/use-get-service-journey-vehicles.ts

This also fixes an exhaustive deps issue :)
closes https://github.com/AtB-AS/kundevendt/issues/16267

refactor: use useQuery for fetching live bus status

---

README.md
docs/WindowsSetup.md

https://github.com/AtB-AS/mittatb-app/blob/rosvik/readme/README.md

docs: update README

---

src/fare-contracts/FareContractInfo.tsx
src/fare-contracts/components/FareContractHarborStopPlaces.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContractComponent.tsx
src/translations/screens/FareContract.ts

Closes AtB-AS/kundevendt#18923

fix: Added directionality for screenreader with two-way tickets

---

src/fare-contracts/components/InspectionSymbol.tsx

Closes AtB-AS/kundevendt#19517

fix: Reduced borderWidth for InspectionSymbol, and removed to-from zone names

---

src/fare-contracts/details/DetailsContent.tsx
src/mobility/components/MobilityBenefitsInfoSectionItem.tsx

Or else this code 'arr.length && …' will try to render the text "0"
if the array length is zero, which will blow up since the text
isn't rendered inside a Text component.

fix: Length checks need to be converted to booleans

---

src/api/types/generated/DeparturesQuery.ts
src/api/types/generated/NearestStopPlacesQuery.ts
src/api/types/generated/StopsDetailsQuery.ts
src/api/types/generated/fragments/estimated-calls.ts
src/api/types/generated/fragments/journey-patterns.ts
src/api/types/generated/fragments/quays.ts
src/api/types/generated/fragments/service-journeys.ts
src/api/types/generated/fragments/situations.ts
src/api/types/generated/fragments/trips.ts

refactor: Use generated bff types with inline fragments

---

package.json
src/fare-contracts/details/OrderDetails.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PaymentBrand.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentMethodsScreen.tsx
src/stacks-hierarchy/types.ts
src/stacks-hierarchy/utils.ts
src/ticketing/types.ts
src/ticketing/utils.ts
src/translations/screens/subscreens/PurchaseConfirmation.ts
svgo.config.js
yarn.lock

closes https://github.com/AtB-AS/kundevendt/issues/18725

feat: add amex as payment method 

---

src/fare-contracts/FareContractView.tsx
src/fare-contracts/components/FareContractFromTo.tsx
src/translations/screens/FareContract.ts

Fixes an error found during testing AtB-AS/mittatb-app#4869

fix: Fixed text wrapping and accessibility label

---

README.md

Doing this stays clear of some issues..

docs: ruby/cocoapods readme fix

---

src/feature-toggles/toggle-specifications.ts
src/remote-config.ts

closes https://github.com/AtB-AS/kundevendt/issues/19780

feat: adds isBonusProgramEnabled feature flag

---

src/notifications/use-has-fare-contract-with-activated-notification.tsx
src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx
src/stacks-hierarchy/Root_LoginAvailableFareContractWarningScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/CompactFareContracts.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DeleteProfileScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_AvailableFareContractsTabScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/Ticketing_TicketTabNavStack.tsx
src/ticket-history/TicketHistoryScreenComponent.tsx
src/ticketing/TicketingContext.tsx
src/ticketing/api.ts
src/ticketing/use-fare-contracts.ts
src/ticketing/use-has-reservation-or-available-fare-contract.ts
src/utils/__tests__/date.test.ts
src/utils/date.ts

Can evaluate commits one-by-one to get a better overview.

feat: Pull to refresh to fetch fare contracts from backend

---

src/api/types/mobility.ts
src/components/map/components/mobility/ShmoTesting.tsx

closes https://github.com/AtB-AS/kundevendt/issues/19796

fix start and stop functionallity in shmo testing component

---

src/components/map/Map.tsx
src/components/map/components/ScanButton.tsx
src/components/map/hooks/use-control-styles.ts
src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/19789
Fixes crash and [button position](https://github.com/AtB-AS/mittatb-app/pull/4921#issuecomment-2589595364)

fix: controlPositions style fix

---

src/api/types/mobility.ts
src/stacks-hierarchy/Root_ParkingViolationsReporting/Root_ParkingViolationsSelectScreen.tsx
src/translations/screens/ParkingViolations.ts

Closes https://github.com/AtB-AS/kundevendt/issues/19810
Pair programmed with @Dahly96 and @jorunnl
Removed subtitle, changed title.
Removed icons.
Acceptance criteria:

feat: Update text and remove icon from screen

---

package.json
src/api/client.ts
src/api/profile.ts
src/queries/ReactQueryProvider.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/use-reserve-offer-mutation.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts
src/ticketing/api.ts
src/travel-details-screens/use-get-service-journey-vehicles.ts

Closes AtB-AS/kundevendt#19693

fix: Disable retries on response code 429

---

package.json
yarn.lock

Adds changes from https://github.com/AtB-AS/design-system/pull/278
ref. https://github.com/AtB-AS/kundevendt/issues/18103

chore: upgrade theme to 13.1.3

---

package.json
src/components/icon-box/utils.ts
src/mobility/components/BicycleSheet.tsx
src/mobility/components/ParkAndRideBottomSheet.tsx
src/mobility/components/PricingPlan.tsx
src/mobility/components/ScooterSheet.tsx
src/mobility/components/VehicleCard.tsx
src/mobility/components/VehicleCardStat.tsx
src/mobility/utils.ts
src/storybook/stories/ThemeIcon.stories.tsx
src/translations/screens/subscreens/MobilityTexts.ts
yarn.lock

closes: https://github.com/AtB-AS/kundevendt/issues/19914
| <img width="200" src="https://github.com/user-attachments/assets/f277adc1-6ddd-45f1-820d-7f4038a13c44" /> | <img width="200" src="https://github.com/user-attachments/assets/ac584425-1a99-441d-9778-601076ad957d" /> |
updated vehiclecard and added new icons to the design system which made some changes to the path of some already in use icons.

feat: updated vehiclecard

---

src/mobility/components/CarPreviews.tsx

fixes https://mittatb.slack.com/archives/C0116FMPX4Y/p1738312695843649?thread_ts=1738311346.651029&cid=C0116FMPX4Y

fix: update MoreCarsIndicator color

---

docs/Release.md

Make the release version warning more prominent.

chore: update release.md with warning about release

---

src/mobile-token/MobileTokenContext.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx

Add a debug menu to create token, this can be useful in simulating conditions where there are multiple mobile tokens in the same device.
The target branch for this PR is my own branch, but still creating a PR that can serve as a notification and so people can look into what I'm working on.

feat: debug menu create token

---

src/in-app-browser/in-app-browser.tsx
src/in-app-browser/index.ts
src/stacks-hierarchy/Root_LoginOptionsScreen.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentMethodsScreen.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/19403

chore: Remove created field from recurring payments & add documentation for close in app browser

---

src/mobile-token/hooks/use-load-native-token-query.tsx
src/mobile-token/utils.ts
src/utils/bugsnag-utils.ts

closes https://github.com/AtB-AS/kundevendt/issues/19972
ℹ️ This PR is targeted to the mobile-token-v3 branch
- Adds error name to breadcrumb metadata
- Adds logging to create new mobile token flow
- Improve existing mobile token logging by adding the error metadata (error name & error message) if any.

feat: add logging to mobile token create flow

---

src/components/sections/RadioGroupSection.tsx
src/components/sections/items/RadioSectionItem.tsx
src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/ExistingRecipientsList.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByProducts.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DefaultUserProfileScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
src/translations/screens/subscreens/UserProfileSettingsTexts.ts

Closes https://github.com/AtB-AS/kundevendt/issues/18735

fix: Consolidate radio button group

---

src/components/tile/TileWithButton.tsx
src/recent-fare-contracts/RecentFareContract.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/19666

fix: Update zone/quay view for RecentFareContract

---

src/date-picker/DatePickerSheet.tsx

Background:
https://github.com/AtB-AS/kundevendt/issues/16749#issuecomment-2636185047

fix: Set theme on date picker

---

src/components/feedback/GoodOrBadButton.tsx
src/components/radio/RadioBox.tsx
src/components/radio/RadioSegments.tsx
src/components/radio/index.ts
src/components/radio/utils.ts
src/components/sections/RadioGroupSection.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductAliasChip.tsx
src/translations/screens/Feedback.ts

Background:
https://github.com/AtB-AS/kundevendt/issues/16749#issuecomment-2642419798
https://github.com/facebook/react-native/issues/43266

fix: Improve a11y for radio boxes on iOS

---

src/utils/__tests__/use-persisted-bool-state.test.ts

https://github.com/AtB-AS/mittatb-app/pull/5003#issuecomment-2650736672

chore: Fix a persisted bool test warning

---

ios/Podfile.lock
ios/atb.xcodeproj/project.pbxproj
package.json
src/analytics/types.ts
src/feature-toggles/toggle-specifications.ts
src/remote-config.ts
src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx
src/travel-details-screens/DepartureDetailsScreenComponent.tsx
src/travel-details-screens/components/Trip.tsx
src/utils/use-in-app-review.ts
yarn.lock

Close https://github.com/AtB-AS/kundevendt/issues/3644

feat: In app review

---

src/fare-contracts/components/InspectionSymbol.tsx

feat: Inspection symbol filled for HomeWorkHome

---

src/utils/use-in-app-review.ts

Part of: https://github.com/AtB-AS/kundevendt/issues/3644

fix: Wrong if statement on in app review

---

package.json
yarn.lock

https://github.com/AtB-AS/utils/pull/8

fix: upgrade utils to make `purchasedBy` optional

---

package.json
yarn.lock

Changed interactive 0 for Troms light mode to better suit the newly introduced light background.
Does not affect other orgs

chore: Bumped @atb-as/theme and @atb-as/generate-assets

---

src/modules/fare-contracts/sections/FareContractHeaderSectionItem.tsx

See: https://mittatb.slack.com/archives/C0116FMPX4Y/p1740555384060609

fix: Fixed wrong checking of phonenumber for all fare contracts

---

src/modules/fare-contracts/sections/OrderDetailsSectionItem.tsx

ref. https://mittatb.slack.com/archives/C0116FMPX4Y/p1740654201899839

fix: use correct value for travelright endDateTime

---

src/mobility/components/BikeStationBottomSheet.tsx
src/mobility/components/PayWithBonusPointsCheckbox.tsx

fix: disabled accessibility pay with bonus check box

fix: disabled accessibility pay with bonus check box

---

src/translations/screens/FareContract.ts

Ref Slack discussion: https://mittatb.slack.com/archives/C0116FMPX4Y/p1741338962137569

Unswaps NN and EN, as they were swapped

---

src/utils/bugsnag-utils.ts

This is cherry pick of https://github.com/AtB-AS/mittatb-app/pull/5065 to Master branch

fix: add an object check on errorToMetadata function (#5065)

---

README.md

Let me know if the command is missing something ✌️

docs: add rebuild tip to README

---

src/api/client.ts
src/api/headers.ts

closes https://github.com/AtB-AS/kundevendt/issues/19715

feat: add Atb-Distribution-Channel header for all requests

---

src/components/map/components/SelectedFeatureIcon.tsx

Fixes Map Test [Observation 1](https://github.com/AtB-AS/kundevendt/issues/20260#issuecomment-2729770969)
Resolves https://github.com/AtB-AS/kundevendt/issues/10821

fix: Always show SelectedFeatureIcon

---

Gemfile
Gemfile.lock

A missing extension was found while building the app, the extension is the one that removes the widget if is not needed.

chore: Add configure extensions

---

README.md

Hi :), this issue came as a suggestion from @Oleninkaa about a wrong or missing ruby dependency, in order to make it more clear we took her suggestion to include more details in the README.

chore: Update README.md to describe how to fix a ruby gem issue

---

src/api/types/mobility.ts

updated booking type since entur is introducing breaking changes
https://github.com/AtB-AS/kundevendt/issues/20230

feat:updated booking type

---

src/modules/fare-contracts/components/RefundBottomSheet.tsx
src/modules/fare-contracts/components/RefundSectionItem.tsx
src/modules/fare-contracts/details/DetailsContent.tsx
src/modules/feature-toggles/toggle-specifications.ts
src/remote-config.ts
src/ticketing/api.ts
src/ticketing/types.ts
src/ticketing/use-refund-mutation.tsx
src/ticketing/use-refund-options-query.tsx
src/translations/screens/FareContract.ts
src/translations/screens/Profile.ts

https://github.com/user-attachments/assets/761c3f76-fa63-41cd-a0f3-5903c6c015a0
closes https://github.com/AtB-AS/kundevendt/issues/20058

feat: add self service refund of fare contracts

---

src/modules/fare-contracts/CompactFareContractInfo.tsx
src/translations/screens/FareContract.ts

fixes comments https://github.com/AtB-AS/kundevendt/issues/20063#issuecomment-2750398641 and https://github.com/AtB-AS/kundevendt/issues/20063#issuecomment-2750686063

fix: show travelerName on compact fare contact

---

ios/Podfile
ios/Podfile.lock

Missing step for https://github.com/AtB-AS/mittatb-app/pull/5102

fix: Update mapbox version for iOS

---

src/mobile-token/hooks/use-toggle-token-mutation.tsx

addresses https://github.com/AtB-AS/kundevendt/issues/20216#issuecomment-2747955834
Only added `nativeToken` to the query dependency so it can update the data properly.

fix: add missing query dependency to token toggle mutation

---

android/build.gradle
package.json
src/mobile-token/hooks/use-validate-token.tsx
yarn.lock

part of https://github.com/AtB-AS/kundevendt/issues/20216
follow up to issues found during testing of https://github.com/AtB-AS/mittatb-app/pull/5103
Reference :  https://github.com/react-native-device-info/react-native-device-info?tab=readme-ov-file#syncuniqueid

fix: fix issue with iOS mobile token sometimes renewing endlessly due to wrong device info

---

src/api/mobility.ts
src/api/types/mobility.ts
src/components/map/components/mobility/ShmoTesting.tsx
src/components/map/hooks/use-active-shmo-booking.tsx
src/mobility/components/sheets/ActiveScooterSheet.tsx
src/mobility/queries/use-get-ids-from-qr-code-mutation.tsx
src/stacks-hierarchy/Root_ScanQrCodeScreen.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/20230
Breaking changes from entur in updating the Asset and booking type. Also now uses Asset as QR response object

feat:updated asset type for breaking changes from entur

---

android/build.gradle
ios/Podfile
ios/Podfile.lock
package.json
yarn.lock

Context: https://mittatb.slack.com/archives/C07A7TH7ATH/p1743578359152499
Follow up after https://github.com/AtB-AS/mittatb-app/pull/5102

fix: Upgrade mapbox version

---

package.json
src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx
src/storybook/stories/ThemeIcon.stories.tsx
yarn.lock

- Adds filled variants of icons
- Limits font scale in the tab bar to 1.2
closes https://github.com/AtB-AS/kundevendt/issues/20389

feat: update tab bar icons

---

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PaymentSelectionSectionItem.tsx

ref https://github.com/AtB-AS/kundevendt/issues/18186#issuecomment-2796653690

fix: give correct screen reader focus after payment selection

---

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PriceSummary.tsx

fixes https://github.com/AtB-AS/kundevendt/issues/18186#issuecomment-2820680290

refactor: clean up PurchaseConfirmationScreen styling

---

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PaymentSelectionSectionItem.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx
src/stacks-hierarchy/saved-payment-utils.ts
src/translations/screens/subscreens/PaymentMethods.ts
src/translations/screens/subscreens/SelectPaymentMethodTexts.ts

Fixes bugs that were noticed during testing of https://github.com/AtB-AS/kundevendt/issues/18186
Observations:
- https://github.com/AtB-AS/kundevendt/issues/18186#issuecomment-2792946597
- https://github.com/AtB-AS/kundevendt/issues/18186#issuecomment-2793118866
- https://github.com/AtB-AS/kundevendt/issues/18186#issuecomment-2793217469
- https://github.com/AtB-AS/kundevendt/issues/18186#issuecomment-2793322865
- https://github.com/AtB-AS/kundevendt/issues/18186#issuecomment-2796246118

fix: purchase confirmation bug fixes (testing)

---

package.json
src/error-boundary/FullScreenErrorView.tsx
src/mobility/components/BenefitImage.tsx
src/mobility/components/BicycleSheet.tsx
src/mobility/components/BikeStationBottomSheet.tsx
src/mobility/components/BrandingImage.tsx
src/mobility/components/onboarding/LocationScreenComponent.tsx
src/mobility/components/onboarding/PaymentScreenComponent.tsx
src/modules/fare-contracts/components/FareContractStatusSymbol.tsx
src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx
src/stacks-hierarchy/Root_ConsiderTravelTokenChangeScreen/components/NoTravelTokenInfo.tsx
src/stacks-hierarchy/Root_LocationWhenInUsePermissionScreen.tsx
src/stacks-hierarchy/Root_LoginRequiredForFareProductScreen.tsx
src/stacks-hierarchy/Root_NotificationPermissionScreen.tsx
src/stacks-hierarchy/Root_ShareTravelHabitsScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/CityZoneMessage.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_AvailableFareContractsTabScreen.tsx
src/theme/ThemedAssets.tsx
src/ticket-history/TicketHistoryScreenComponent.tsx
src/travel-details-screens/components/FlexibleTransportBookingDetailsSheet.tsx
src/travel-token-box/TravelTokenBox.tsx
yarn.lock

closes https://github.com/AtB-AS/kundevendt/issues/20046
Pretty straightforward PR, major version bump to the design system, added light & dark variant for many assets, and maintained compatibility with the OMS apps (should use old assets

feat: update illustration

---

src/modules/bonus/components/PayWithBonusPointsCheckbox.tsx
src/modules/bonus/components/UserBonusBalance.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_BonusScreen.tsx

closes https://github.com/AtB-AS/kundevendt/issues/19986
fixes to the bonus balance component:
- null now shows as --
- Color for large is now primary, while small is secondary

fix: color and null value bonus balance

---

package.json
src/components/empty-state/EmptyState.tsx
src/error-boundary/FullScreenErrorView.tsx
src/mobility/components/BenefitImage.tsx
src/mobility/components/BikeStationBottomSheet.tsx
src/mobility/components/OperatorBenefit.tsx
src/modules/native-bridges/pass-presentation.ts
src/onboarding/OnboardingScreenComponent.tsx
src/stacks-hierarchy/Root_LoginRequiredForFareProductScreen.tsx
src/stacks-hierarchy/Root_NotificationPermissionScreen.tsx
src/stacks-hierarchy/Root_ShareTravelHabitsScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/CityZoneMessage.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/Results.tsx
src/theme/ThemedAssets.tsx
src/translations/screens/subscreens/Login.ts
src/travel-details-screens/components/FlexibleTransportBookingDetailsSheet.tsx
yarn.lock

follow up of https://github.com/AtB-AS/kundevendt/issues/20046
Done together with @hannahATB

fix: illustration issues

---

package.json
yarn.lock

Fixes issue in https://github.com/AtB-AS/kundevendt/issues/19173#issuecomment-2841778656

fix: use correct image for nfk crash screen

---

src/mobility/components/BikeStationBottomSheet.tsx
src/mobility/components/OperatorActionButton.tsx
src/modules/bonus/api/api.ts
src/modules/bonus/index.tsx
src/modules/bonus/queries/get-bonus-balance-query.tsx
src/modules/bonus/queries/use-buy-value-code-with-bonus-points-query.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/20042
Makes a call to bonus service to buy a voucher code for bonus points when checkbox is checked.
App switches to Trondheim bysykkel when code is returned from bonus service.
If an error occurs (for example no voucher codes left), the following message shows:

feat: pay with bonus points to by trd bysykkel trip

---

src/recent-fare-contracts/use-recent-fare-contracts.ts
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PaymentSelectionSectionItem.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PriceSummary.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/use-cancel-payment-mutation.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentMethodsScreen.tsx
src/stacks-hierarchy/saved-payment-utils.ts
src/ticketing/api.ts
src/ticketing/types.ts

This pull request focuses on transitioning from use ticket-legacy to using the new sales service for endpoints related to ticketing.
We've discovered some discrepancies along the way while transitioning the endpoints, related pull requests in the sales repository are listed in the end of this description.
In addition to transitioning to using the new endpoints we focused on making the switch to using camelCase for all of the responses from the backend, so some of the backend PRs are related to that as well. 
closes https://github.com/AtB-AS/kundevendt/issues/20453
---
related backend PRs: 
- https://github.com/AtB-AS/sales/pull/43
- https://github.com/AtB-AS/sales/pull/40
- https://github.com/AtB-AS/sales/pull/39
- https://github.com/AtB-AS/sales/pull/34
- …

refactor: use sales service

---

src/components/map/MapV2.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/20585

feat:fixed locationarrow onclick

---

src/mobility/components/ShmoActionButton.tsx
src/mobility/components/sheets/ActiveScooterSheet.tsx
src/mobility/utils.ts

Closes https://github.com/AtB-AS/kundevendt/issues/20287
Added attribute to the errormessages thats friendly so the client can know if the message should be shown

feat: new attribute from server for friendly errormessages

---

src/modules/fare-contracts/components/ConsumeCarnetBottomSheet.tsx

🙈 
(ref. https://github.com/AtB-AS/mittatb-app/pull/5158)

fix: disable school ticket error message by default

---

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx

There was a bug related to the onSuccess callback on the reserveMutation in PurchaseConfirmationScreen that broke saving of recurring payment.
It seems the root of the issue was a "stale closure" problem, and works as follows:
1. A closure was provided as useReserveOfferMutation's onSuccess, that had a callback to onPaymentCompleted.
2. onPaymentCompleted is a useCallback, with a dependency array updating the function every time recurringPaymentId changes.
3. The assumption was that once recurringPaymentId changes, the onSuccess closure would update as well. But this is not the case, since onSuccess itself doesn't have a dependency array, and becomes stale if any state other that the argument (reserveOfferResponse) changes.
I believe this is why the onSuccess, onError and onSettled …

fix: save recurring payments as previous payment method

---

package.json
src/mobility/components/onboarding/PaymentScreenComponent.tsx
src/theme/ThemedAssets.tsx
yarn.lock

Closes https://github.com/AtB-AS/kundevendt/issues/20075

feat: added new illustration for shmo paymentonboarding

---

src/modules/mobile-token/hooks/use-load-native-token-query.tsx
src/modules/mobile-token/hooks/use-validate-token.tsx
src/modules/mobile-token/tokenService.ts

closes https://github.com/AtB-AS/kundevendt/issues/20600

chore: remove validate function from tokenService

---

src/modules/mobility/queries/use-shmo-booking-query.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/20230

added featureflag on bookingQuery

---

patches/@react-native-async-storage+async-storage+1.19.8.patch

There was some extra information that had to be changed as well, like the index IDs and more. This version reverts my previous change and makes a fix.

fix: Revert "Update @react-native-async-storage+async-storage+1.19.8" and apply patch properly

---

package.json
src/api/types/sales.ts
src/modules/ticketing/api.ts
src/modules/ticketing/types.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts
yarn.lock

Removed local Offer-type, and used the common TicketOffer from utils

feat: Bump utils and use TicketOffer from utils

---

src/api/types/mobility.ts
src/api/utils.ts

https://zod.dev/api?id=nullish

refactor: make optional zod fields nullish

---

src/modules/mobility/components/CarSharingStationBottomSheet.tsx

closes https://github.com/AtB-AS/kundevendt/issues/20668
adds bonus checkbox to car sharing bottom sheet
only visible if car sharing bonus product exists in firestore

Feat: add car sharing bonus checkbox

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchFiltersBottomSheet.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-travel-search-filters-state.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/20180 for the **App**:
- a different component is being used for the transportation icons

fix: changed component for transportation icons

---

ios/Podfile.lock
package.json
src/modules/mobility/components/sheets/ActiveScooterSheet.tsx
yarn.lock

Closes https://github.com/AtB-AS/kundevendt/issues/20800

feat: added keep alive for the active trip bottomsheet

---

src/modules/mobility/components/CarSharingStationBottomSheet.tsx

closes https://github.com/AtB-AS/kundevendt/issues/20668

fix: remove duplicate line from car sharing bonus checkbox

---

src/modules/mobile-token/utils.ts

part of https://github.com/AtB-AS/kundevendt/issues/20605#issuecomment-2943596404
Proper clock skew error handling based on server update.

fix: improve token clock skew handling

---

src/components/sections/items/ToggleSectionItem.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchFiltersBottomSheet.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-travel-search-filters-state.tsx
src/translations/screens/TripSearch.ts
src/utils/use-transport-color.ts

Some changes regarding comments for https://github.com/AtB-AS/kundevendt/issues/20180 in testing:
- https://github.com/AtB-AS/kundevendt/issues/20180#issuecomment-2943720432
- https://github.com/AtB-AS/kundevendt/issues/20180#issuecomment-2948448973
- https://github.com/AtB-AS/kundevendt/issues/20180#issuecomment-2948456030
- https://github.com/AtB-AS/kundevendt/issues/20180#issuecomment-2948583909

fix:  removed some TripSearch text and changed colors for the airportLinkBus

---

src/modules/mobile-token/hooks/use-load-native-token-query.tsx

docs: update some comments for better clarity

---

src/stacks-hierarchy/Root_TripSelectionScreen/use-booking-trips.ts

Implements the required change from  AtB-AS/atb-bff#396 and AtB-AS/kundevendt#20849

feat: Added count to passenger in call to BFF

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchFiltersBottomSheet.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchPreference.tsx
src/translations/screens/TripSearch.ts

ref: https://github.com/AtB-AS/kundevendt/issues/20180#issuecomment-2958867563
The heading text will be added in https://github.com/AtB-AS/firestore-configuration/pull/834

fix: fix texts for transport filter

---

src/api/types/sales.ts
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PreassignedFareProductSummary.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TripSelection.tsx
src/translations/screens/subscreens/PurchaseConfirmation.ts

Fix for: https://github.com/AtB-AS/kundevendt/issues/20767#issuecomment-2970081703

fix: Add line name

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultRow.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultRowFooter.tsx

Closes:
https://github.com/AtB-AS/kundevendt/issues/21010
|Before|After|
|-|-|
|![Screenshot_1750158893](https://github.com/user-attachments/assets/b5a8f4cd-e3c8-4aa3-81e5-3a5f074c53a6)|![Screenshot_1750161164](https://github.com/user-attachments/assets/c7b61216-99f7-4691-aabf-c7ba4d9b5425)|

bug: Wrong background color when search back in time - Travel search

---

src/components/sections/items/ExpandableSectionItem.tsx
src/components/sections/items/LinkSectionItem.tsx
src/components/sections/items/ToggleSectionItem.tsx
src/components/tag/Tag.tsx
src/modules/bonus/components/EarnedBonusPointsSectionItem.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PreassignedFareProductSummary.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/PriceTravellerSummary.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TripSelection.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultRow.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
src/stacks-hierarchy/Root_TripSelectionScreen/Root_TripSelectionScreen.tsx
src/stacks-hierarchy/Root_TripSelectionScreen/types.ts
src/stacks-hierarchy/Root_TripSelectionScreen/use-booking-trips.ts
src/translations/screens/Ticketing.ts

Closes AtB-AS/kundevendt#20850
[Figma](https://www.figma.com/design/4ogkwxdLNstDHQUKKGgARW/Booking-for-b%C3%A5t?node-id=8920-34337&t=M7UleNHcAbhg582s-0)
Implements the required changes to the TripSelectionScreen. Also contains a small refactor where I renamed `label` to `labels` in the `Tag`-component, since it takes an array of strings. 
Now looks like this: 
<details>
</details>

feat: Added changes for booking to TripSelectionScreen

---

src/modules/mobile-token/hooks/use-validate-token.tsx

fix issue with token keeps renewing that @tormoseng found

fix: fix the token renewal check version

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultRow.tsx

Part of:
https://github.com/AtB-AS/kundevendt/issues/21010
Before
After

fix: Wrong spacing when presenting information in asssitant

---

src/components/tag/Tag.tsx
src/stacks-hierarchy/Root_TripSelectionScreen/components/TripSelection.tsx

Related to AtB-AS/kundevendt#20454 and AtB-AS/kundevendt#20850 
Does three things: 
- Moves Tag component into its correct position, according to sketches
- Refactors Tag component into a less coupled format
- Adds a border / stroke to all Tags except from Primary
[Figma](https://www.figma.com/design/4ogkwxdLNstDHQUKKGgARW/Booking-for-b%C3%A5t?node-id=10167-99434&t=ctTvJ2prIILRuFdQ-0)
<details>
</details>

fix: Booking tag fixes

---

src/components/tag/Tag.tsx

Small fix related to AtB-AS/kundevendt#20454
<details>
<b>Before:</b> <br>
<b>After:</b> <br>
</details>

fix: Remove black border for primary tag

---

src/modules/storybook/stories/Section.stories.tsx

Adds the new SelectionInlineSectionItem component to Storybook.

chore: add SelectionInlineSectionItem to Storybook

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_EnrollmentScreen.tsx
src/translations/screens/subscreens/Enrollment.ts

closes https://github.com/AtB-AS/kundevendt/issues/21088
Updates enrollment screen to look cuter

feat: update enrollment screen

---

src/modules/smart-park-and-ride/api/api.ts
src/modules/smart-park-and-ride/index.tsx
src/modules/smart-park-and-ride/queries/use-add-vehicle-registration-mutation.ts
src/modules/smart-park-and-ride/queries/use-get-vehicle-registrations-query.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SmartParkAndRideScreen.tsx

Refactor some changes based on feedback. The endpoints are changing to get an `s` on the end, and also following some conventions.

refactor: update spar endpoints and conventions

---

src/modules/fare-contracts/FareContractAndReservationsList.tsx
src/modules/fare-contracts/__tests__/sort-fc-or-reservation.test.ts
src/modules/fare-contracts/index.ts
src/modules/fare-contracts/sort-fc-or-reservation.ts
src/modules/fare-contracts/utils.ts

Closes https://github.com/AtB-AS/kundevendt/issues/20510

fix: Improve display of rejected payments

---

src/modules/mobility/components/ShmoActionButton.tsx
src/modules/mobility/components/sheets/ActiveScooterSheet.tsx
src/stacks-hierarchy/Root_ParkingPhotoScreen.tsx

Closes https://github.com/AtB-AS/team-platform/issues/818
added posthog logs for start, start finishing and finish shmo booking

feat: added logging for start/stop shmo booking in posthog

---

package.json
src/api/types/generated/fragments/mobility-shared.ts
src/modules/map/hooks/use-opening-hours.tsx
src/modules/map/hooks/use-shmo-warnings.tsx
src/modules/map/utils.ts
src/translations/screens/subscreens/MobilityTexts.ts
yarn.lock

Closes https://github.com/AtB-AS/kundevendt/issues/20826
Added warning message in the scooter sheet if outside of opening hours, displaying the opening time.

feat: added opening hours to scooters

---

src/modules/bonus/components/PayWithBonusPointsCheckbox.tsx
src/modules/mobility/components/BikeStationBottomSheet.tsx
src/modules/mobility/components/CarSharingStationBottomSheet.tsx
src/modules/mobility/components/OperatorActionButton.tsx

closes https://github.com/AtB-AS/kundevendt/issues/21134
Unchecks the bonus checkbox automatically after purchase.

fix: uncheck bonus checkbox after purchase

---

src/theme/ThemedAssets.tsx

Refactor of the ThemedAssets file to avoid duplication, and make it easier to add new illustrations in the future ✨

refactor: add getThemedAsset util to ThemedAssets

---

src/stacks-hierarchy/Root_LoginConfirmCodeScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SettingsScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/components/UserInfo.tsx
src/translations/screens/Profile.ts
src/translations/screens/subscreens/EditProfileScreen.ts
src/utils/__tests__/phone-number-utils.test.ts
src/utils/phone-number-utils.ts

Updates the section at the top of the Profile page ✨ 
https://github.com/user-attachments/assets/5cfc9eca-79b9-4589-8fb6-84a90327f194
closes https://github.com/AtB-AS/kundevendt/issues/20064

feat: update user info design on the Profile screen

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/CityZoneMessage.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_HelpAndContactScreen.tsx
src/translations/ExternalLinks.ts
src/translations/components/CityBoxMessage.ts
src/translations/dictionary.ts

Closes https://github.com/AtB-AS/kundevendt/issues/20065

fix: Add A11y hint for contact screen

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/components/UserInfo.tsx

fixes https://github.com/AtB-AS/kundevendt/issues/20064#issuecomment-3061248151

fix: add a11y button role to UserInfo

---

src/modules/booking/use-booking-trips.ts
src/modules/booking/utils.ts
src/modules/fare-contracts/index.ts
src/modules/fare-contracts/utils.ts
src/modules/feature-toggles/toggle-specifications.ts
src/modules/remote-config/remote-config.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_TripSelectionScreen/components/TripSelection.tsx

Related to https://github.com/AtB-AS/kundevendt/issues/20769
Just the feature-toggle removal (and a couple small fixes, see commit messages) from https://github.com/AtB-AS/mittatb-app/pull/5337.

refactor: remove booking featureToggle

---

src/components/tag/Tag.tsx

Fix to error found while testing https://github.com/AtB-AS/mittatb-app/pull/5330#issuecomment-3132473449 See discussion there

fix: Removed accesibilityRole=button from Tag

---

tools/release/release-draft.sh

(n/Y) means that if you enter blank it will default to yes. But the next line in the script `if [[ ! $REPLY =~ ^[Yy]$ ]]` means that if you enter blank it will exit the script, i.e. default to no. This tripped me up, so I fix it here

fix: Fixes yes/no prompt

---

src/components/trip-pattern-legs-summary/TripPatternLegsSummary.tsx
src/components/trip-pattern-legs-summary/index.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PreassignedFareProductSummary.tsx

A step towards https://github.com/AtB-AS/kundevendt/issues/20769

refactor: Refactored component into TripPatternLegsSummary

---

src/theme/ThemedAssets.tsx

Did an oopsie when I implemented this. Small fix :) 
Fix for https://github.com/AtB-AS/kundevendt/issues/20064

fix: Swapped light/dark themed assets for ProfileCard

---

src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx

https://github.com/AtB-AS/mittatb-app/pull/5343#discussion_r2281827811

refactor: clean up getProfileNotification logic

---

src/modules/fare-contracts/FareContractView.tsx
src/modules/fare-contracts/details/DetailsContent.tsx
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PreassignedFareProductSummary.tsx

Small issue after https://github.com/AtB-AS/kundevendt/issues/20769
Fixes the issue [discovered here](https://github.com/AtB-AS/mittatb-app/pull/5374#discussion_r2282014695)

fix: Removed empty legs-section item in PreassignedFareProductSummary

---

src/stacks-hierarchy/Root_SmartParkAndRide/Root_SmartParkAndRideAddScreen.tsx

Update the secondary button's background color to the correct accent color for better visual consistency.

fix(spar): use correct secondary button color

---

src/api/stop-signal.ts
src/screen-components/travel-aid/components/StopSignalButton.tsx

@Nisha1306 Notified me about some changes to the blue button endpoint:
- `serviceDate` -> `serviceJourneyDate`
- `/journey/v1/signal/stop` -> `/journey/v1/signal/pickup`

feat: update blue button stop signal endpoint

---

src/modules/bonus/api/api.ts
src/modules/bonus/index.ts
src/modules/bonus/queries/index.tsx
src/modules/bonus/queries/use-bonus-amount-earned-query.tsx
src/modules/event-stream/handle-stream-event.ts
src/modules/event-stream/types.ts
src/modules/event-stream/use-setup-event-stream.ts
src/modules/fare-contracts/FareContractView.tsx
src/modules/fare-contracts/details/DetailsContent.tsx

Updates StreamEventSchema to reflect backend
Invalidate Bonus amount query on FARE_CONTRACT event

feat: use stream service to invalidate bonus amount query

---

src/modules/bonus/components/PayWithBonusPointsCheckbox.tsx
src/modules/mobility/components/BikeStationBottomSheet.tsx
src/modules/mobility/components/CarSharingStationBottomSheet.tsx

newState logged in posthog for checkbox toggle is now actual newState value

fix: bonus checkbox posthog value logged is correct

---

src/modules/fare-contracts/FareContractView.tsx

|----------|----------|
| <img width="200" height="2868" alt="image" src="https://github.com/user-attachments/assets/813cc347-2ea4-4aec-90ca-4205ed6749d3" />    | <img width="200" height="2868" alt="image" src="https://github.com/user-attachments/assets/42dc7a45-4bee-42e6-82cb-21508957c624" />   |

fix: Earning 0 points is not visble on bought ticket

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/21182
Have not talked to @Sebstorvik if we should consider adding hasValidFareContract to globalRuleVariables in GlobalMessages or not. But I understood from discussion with @marius-at-atb and @rosvik that it's probably not necessary?

feat: Add hasValidFareContract variable for Announcements

---

src/modules/smart-park-and-ride/queries/use-get-vehicle-registrations-query.ts

Eliminate the need for user authentication in the vehicle registrations query, simplifying access for users.
fixes https://github.com/AtB-AS/kundevendt/issues/21022

fix(spar): remove authenticated requirement

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
src/translations/screens/Profile.ts

Moves the button to Smart Park & Ride to the "Discover" section and changed the title of it to "Park and ride" (and "Innfartsparkering").
<details><summary>Screenshot</summary>
<p>
</p>
</details>

fix(spar): move SP&R button

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx
src/translations/dictionary.ts
src/translations/screens/Dashboard.ts
src/translations/screens/Departures.ts
src/translations/screens/Profile.ts
src/translations/screens/TripSearch.ts

- **fix: Shorten login button text**
- **fix: Shorten no favorite departures widget text and illustration**
- **fix: Fix travel bottom tab text + header**
Closes https://github.com/AtB-AS/kundevendt/issues/21287
Fix app side of things for: https://github.com/AtB-AS/kundevendt/issues/21472

fix: Adjust texts and illustration

---

README.md

Sometimes need this to fix failing builds. Explanation: https://stackoverflow.com/a/45081972

docs: add `--repo-update` to rebuild command

---

src/translations/screens/FareContract.ts

https://mittatb.slack.com/archives/CSFC6PG23/p1757928424180429

feat: change wording from "start ticket" to "use ticket"

---

.github/workflows/build-staging-android.yml
.github/workflows/build-staging-ios.yml

Closes: https://github.com/AtB-AS/kundevendt/issues/21656

feat: Add workflow option to apply new arch to staging builds

---

src/components/camera/use-permissions.tsx

This was broken by the dependencies upgrade, but the old way of resolving native modules like that with unstable APIs should either way not be done.

fix: Refactor to more stable react-native-permissions library for camera permission requests

---

src/screen-components/smart-park-and-ride/Root_SmartParkAndRideAddScreenComponent.tsx

fixes https://github.com/AtB-AS/kundevendt/issues/21078

fix(spar): reword posthog event

---

e2e/test/flashlight/performanceMeasures_tickets.e2e.ts
e2e/test/pageobjects/purchase.overview.page.ts
e2e/test/pageobjects/travelsearch.overview.page.ts
e2e/test/specs/auth.0.cleanup.e2e.ts
e2e/test/specs/auth.1.token.e2e.ts
e2e/test/specs/auth.2.ticket.buy.e2e.ts
e2e/test/specs/auth.3.ticket.e2e.ts
e2e/test/specs/frontpage.e2e.ts
e2e/test/specs/onboarding.e2e.ts
e2e/test/specs/ticket.e2e.ts
e2e/test/specs/travelsearch.e2e.ts
e2e/test/specs/travelsearch.filter.e2e.ts
e2e/test/utils/alert.helper.ts

Three updates:
- Seems like alert title id in Android alerts has changed to `alert_title`
- System settings prompt appears more now than before
- Heading `Travel search` > `Find journey`

test: e2e updates

---

src/components/sections/items/RadioSectionItem.tsx

Manually reads out radio section item changes on android.
closes https://github.com/AtB-AS/kundevendt/issues/19430

fix: announce radio button selection changes on android

---

src/components/bottom-sheet-map/MapBottomSheet.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/18903
Set a maxheight for when dynamic content gets to heigh, and also fixed scrolling in dynamic content when there is more content then what can be shown on screen

fix: fixed maxheight and scrolling when dynamic content gets to large

---

src/components/bottom-sheet-map/MapBottomSheet.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/18903

fix: added handling for dynamic content vs static content

---

src/modules/map/MapContext.tsx
src/modules/mobility/use-shmo-requirements.tsx
src/stacks-hierarchy/Root_ShmoOnboardingScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/18903
After doing onboarding for accepting shmo consent the state didnt update for the bottomsheet, making it stuck in onboarding. This PR moved consentlogic to context for shared state across the app

fix: fixed stale consentstate in bottomsheet
