AtB-AS/mittatb-app

src/api/departures/stops-nearest.ts, src/api/departures/types.ts, src/favorites/FavoritesContext.tsx, src/favorites/utils.ts, src/place-screen/hooks/use-departures-data.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/use-favorite-departure-data.ts
Migrate favorites using data received from the `/bff/v2/departures/departures` call
Depends on https://github.com/AtB-AS/atb-bff/pull/313
Resolves https://github.com/AtB-AS/kundevendt/issues/2732
(mentioned in this [comment](https://github.com/AtB-AS/kundevendt/issues/2732#issuecomment-1792286534))
=> feat: support favorite migration also on departures response

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-non-transit-trips-query.tsx
The non-transit results wasn't reset when invalid search
parameters, like equal from and to place. This ment the non-transit
search results from the last successful search was still visisble.
=> fix: Outdated non-transit-search

src/translations/screens/subscreens/DeleteProfile.ts
AtB wants to add a description that says all your data is deleted.
The text is from @Sebstorvik: `Når du sletter Min Profil vil alle dine lagrede data slettes. Du mister også tilgang på billett- og kjøpshistorikk, kvitteringer og dine innstillinger.`
=> feat: Update delete user text

src/notifications/index.ts, src/notifications/types.ts, src/notifications/use-on-push-notification-opened.ts, src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx
Added a new hook "useOnPushNotificationOpened" that is called when the TabNavigator is rendered. This adds two listeners that reacts to app open events, one from background state and one from closed state. 
If `data.type` is "FARE_CONTRACT_EXPIRY", navigate to ActiveFareProductsTabScreen.
closes https://github.com/AtB-AS/kundevendt/issues/7229
=> feat: handle click actions on push notifications

src/notifications/use-push-notifications.tsx, src/stacks-hierarchy/Root_NotificationPermissionScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NotificationsScreen.tsx
closes https://github.com/AtB-AS/kundevendt/issues/7230
Renamed the `register` function to `requestPermissions`, and pulled the register endpoint -part into it's own function. This is useful when we want to register the app language without prompting the user, which now happends on app start and on language change.
=> feat: register notifications on startup and language change

src/place-screen/components/StopPlaceView.tsx
This will add analytics when user presses the `Travel From` and `Travel To` button on the stop place view, with stop place ID as property.
context : https://github.com/AtB-AS/kundevendt/issues/15241#issuecomment-1831750663
=> feat: add analytics for stop place travelFrom and travelTo button

package.json, src/mobility/components/OperatorActionButton.tsx, yarn.lock
Closes https://github.com/AtB-AS/team-platform/issues/473
A new version of config-specs is required to get the correct benefit type when parsing data from Firestore. Correspondig PRs: 
- https://github.com/AtB-AS/fare-product-type-configs/pull/33
- https://github.com/AtB-AS/firestore-configuration/pull/380
=> fix: Make Hyre ticket bundling work

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DeleteProfileScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_EditProfileScreen.tsx, src/translations/screens/subscreens/EditProfileScreen.ts
* using refs in header to set screen reader focus in Edit profile screen and delete profile screen
* added punctuation
* reset error state for email when changing email
Ref. comments in: https://github.com/AtB-AS/kundevendt/issues/4275
=> fix: screen reader and error on email in profile screen

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
Views without style are removed from the Android native hierarchy
as an optimisation. Since we have attached a ref to it, we set
collapsable to false so it is still there when rendered natively.
=> fix: Popover working on Android

src/notifications/api/index.ts
Since https://github.com/AtB-AS/team-platform/issues/481 is now fixed, we can use the PATCH endpoint for updating notification config.
=> refactor: use PATCH for notification config updates

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_EditProfileScreen.tsx
~Noticed in the demo today that it looks like email input was with capital letter 🤔 Wonder if it is due to keyboard type being set instead of input mode? Is there a specific reason as to why it was set without input type? I think maybe also input type will improve autocomplete features~
~I see `autoCapitalize` is set so that fixes the letter, but will it work with autocomplete?~
OK, doing some research and seeing that keyboardType should work as expected. Just found it odd that it didn't handle capitalized automatically 🤔 But also, maybe it makes sense to add autocomplete property?
=> fix: add autocomplete=email to email input

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentOptionsScreen.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/15521
The response returned by netaxept nets when cancelling to add payment was
`atb-dev://profile?response_code=Cancel&recurring_payment_id=12210`
we can see that the `response_code` is `Cancel`, but in the code we are handling it using `CANCEL`, by fixing the capitalization, the code can now proceed and handle it properly.
<details>
<summary>Video proof</summary>
https://github.com/AtB-AS/mittatb-app/assets/1777333/1e1c6f06-1165-4eb4-a13f-9ca69a8342e0
</details>
=> fix: Stop infinite loading of cancelled add payment card view

android/app/build.gradle, android/app/src/main/java/no/mittatb/MainApplication.java, android/build.gradle
closes https://github.com/AtB-AS/kundevendt/issues/15989
- Updated some libraries that can be updated without any issues (soLoader, NDK, desugar, splashscreen).
- Updated Android bugsnag integration based on https://docs.bugsnag.com/platforms/android/#installation
- Updated Android bugsnag initialization (as shown in the issue)
=> chore: update android dependencies

package.json, src/departure-list/section-items/line.tsx, src/place-screen/components/EstimatedCallItem.tsx, yarn.lock
- Removed realtime icon
- Changed to Primary--strike with secondary color ([also added to design system](https://github.com/AtB-AS/design-system/commit/ded2c4d1f94632f7ed8e2c3326c02e365e40c2d0))
- Added Primary--strike with secondary color on line name
| Before    | After |
| -------- | ------- |
| <img width=300 src="https://github.com/AtB-AS/mittatb-app/assets/70323886/62fa713b-e790-45e3-8dd0-ecbcfc208746"/> | <img width=300 src="https://github.com/AtB-AS/mittatb-app/assets/70323886/d48a61e2-b681-4b9f-b1b1-91416f712cb4"/>    |
| <img width=300 src="https://github.com/AtB-AS/mittatb-app/assets/70323886/93fdb485-1ded-4c83-b1b2-03f442969f76"/> | <img width=300 src="https://github.com/AtB-AS/mittatb-app/assets/70323886/a6c854c0-70a5-4b81-a1e1-6aae879d9bfd"/>  |
=> fix: Improve visuals on cancelled departures

package.json, src/components/sections/items/ToggleSectionItem.tsx, src/mobility/components/filter/FormFactorFilter.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelectionSheet.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchFiltersBottomSheet.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx, src/translations/screens/subscreens/PurchaseOverview.ts, yarn.lock
closes https://github.com/AtB-AS/kundevendt/issues/15546
also closes https://github.com/AtB-AS/kundevendt/issues/15547
- Added [image from design system for the bottom sheet](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=20920-13075&mode=design&t=8EbbMsjGLKbyaeJ0-4), updated design system package version.
- Use "on behalf of" feature flag to show/hide components (can test via debug developer menu in profile)
- Refactored the `leftIcon` on `ToggleSectionItem` component to allow better flexibility of use, it is now called `leftImage` and can use SVGs for image. Also updated the styling to closely match existing components (only 1 part is different, see screenshots below)
- toggle value of the `on behalf of` toggle is prepared on `Root_PurchaseOverviewScreen`. …
=> feat: add on behalf of option in bottom sheet

ios/BridgeModules/KettleSDKExtension.m, src/beacons/BeaconsContext.tsx, src/stacks-hierarchy/Root_ShareTravelHabitsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcement.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/8621
This issue fix a non-covered case when requesting kettle info but without having initialized the SDK, so it might close the app is the state is not right.
=> fix: Error while beacons is activated

src/departure-list/section-items/line.tsx, src/place-screen/components/EstimatedCallList.tsx, src/place-screen/components/QuaySection.tsx, src/travel-details-screens/DepartureDetailsScreenComponent.tsx
Now removes the realtime icon and the text with position if the route is cancelled. Also shows the warning seen below now.
=> fix: remove realtime position in details on cancelled departures

src/components/sections/items/ToggleSectionItem.tsx, src/translations/components/Section.ts
ref. QA feedback https://github.com/AtB-AS/kundevendt/issues/15351#issuecomment-1857972212
- Adds a hint to ToggleSectionItem when toggle is disabled. (`accessibilityState` with disabled=true wasn't picked up on iOS)
- Prevents toggles from being toggleable with screan reader when they are disabled.
closes https://github.com/AtB-AS/kundevendt/issues/15351
=> feat: add screen reader support for disabled ToggleSectionItems

src/beacons/BeaconsContext.tsx
While testing, the beacons were not properly started, so after refactoring this class a small piece was missing to keep it on after close the app.
Closes: https://github.com/AtB-AS/kundevendt/issues/8621
=> fix: Update Beacons starting useEffect

src/components/phone-input/PhoneInput.tsx, src/components/phone-input/index.ts, src/stacks-hierarchy/RootStack.tsx, src/stacks-hierarchy/Root_ChooseTicketReceiverScreen/Root_ChooseTicketReceiverScreen.tsx, src/stacks-hierarchy/Root_ChooseTicketReceiverScreen/index.ts, src/stacks-hierarchy/Root_ChooseTicketReceiverScreen/navigation-types.ts, src/stacks-hierarchy/Root_LoginPhoneInputScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/stacks-hierarchy/navigation-types.ts, src/translations/screens/subscreens/OnBehalfOf.ts, src/translations/screens/subscreens/PurchaseConfirmation.ts
closes https://github.com/AtB-AS/kundevendt/issues/15548
- Made the layout for ticket receiver screen based on [figma design](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=20920-13014)
- The screen flow will be `Root_PurchaseOverviewScreen {params} => Root_ChooseTicketReceiverScreen {params} => Root_PurchaseConfirmationScreen`. Params sent to `Root_ChooseTicketReceiverScreen` is similar to the one sent to `Root_PurchaseConfirmationScreen` because the confirmation screen needs the info from `Root_PurchaseOverviewScreen`.
- All translations are just placeholder until [this page](https://www.figma.com/file/AJZIYrzbvkySeJcRQYS1gX/P%C3%A5-vegne-av%3A-Tekst-og-oversettelser?type=whiteboard&node-id=0-1&t=tmQIkwwbj5KPSvnv-0) is updated from Marked.
- Added dummy …
=> feat: on behalf of ticket receiver input screen

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx
Fix for this comment : https://github.com/AtB-AS/kundevendt/issues/15546#issuecomment-1860559898
Add a label text for the screen reader.
Pretty straightforward fix.
=> fix: add correct accessibility text for label in traveller selection

src/announcements/converters.ts, src/announcements/types.ts, src/components/sections/Section.tsx, src/components/sections/items/GenericSectionItem.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcement.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx, src/translations/screens/Dashboard.ts
Closes https://github.com/AtB-AS/kundevendt/issues/15746
Announcements are stretched vertically to be come as tall as the tallest visible announcement.
In addition to the horizontal scroll, this pr also ensures that legacy announcement  are opened in bottom sheet.
The announcement close icon is moved inside the header. This leaves more room for the content, which is more important now, since the announcements will be narrower.
<details>
<summary>Screen shots</summary>
</details>
=> feat: Make announcement scroll horizontally when more than one 

ios/Podfile.lock, package.json, src/components/map/Map.tsx, src/components/map/MapConfig.ts, src/components/map/components/mobility/Bicycles.tsx, src/components/map/components/mobility/BikeStations.tsx, src/components/map/components/mobility/CarStations.tsx, src/components/map/components/mobility/Scooters.tsx, src/components/map/components/mobility/Stations.tsx, src/components/map/components/mobility/Vehicles.tsx, src/tariff-zones-selector/TariffZonesSelectorMap.tsx, src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx, yarn.lock
Replaces PR : https://github.com/AtB-AS/mittatb-app/pull/4141
Closes : https://github.com/AtB-AS/kundevendt/issues/16093
This PR updates the RNMapBox dependency to fix the issue with using `UserLocation` with `onMapIdle` on Android.
Also replaces the deprecated `UserLocation` with the new `LocationPuck` as suggested by RNMapBox (`NativeUserLocation` is also deprecated).
~~iOS users might have to run `pod update MapboxMaps` before `pod install` for it to be able to run. Please let me know if I need to update something regarding this issue.~~ just pod install should work now, I have updated the podfile.lock.
Screenshots: 
Android: 
iOS:
=> feat: update RNMapBox dependency and update usage of UserLocation

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx
Found during testing of https://github.com/AtB-AS/kundevendt/issues/15746
Screen reader on iOS reads horisontal content horizontally, which means all the titles will be read as one "row", then all the descriptions as the next row, etc.
The easies solution to fix this is to align announcements vertically for screen readers since they have to scroll through them anyways.
=> fix: Show announcements vertically on screen reader

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx
Fixes margin at the top of the page both when beacons are enabled and not
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> fix: Top margin in PrivacyScreen

src/components/label-info/LabelInfo.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/7415
Note that the images in the linked issue to not agree 100% with the [Figma sketches](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=16551-85510&mode=design&t=pCpX2mgFwu33Q2u4-0). The labels in the issue are aligned to the left with the text, while in Figma they are aligned to the right, next to the arrow. This PR keeps them right aligned in accordance with Figma.
=> fix: Update new/beta label design

src/components/content-heading/ContentHeading.tsx, src/mobility/components/filter/FormFactorFilter.tsx, src/mobility/components/filter/MobilityFilters.tsx, src/mobility/components/filter/use-filter-style.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/CompactFareContracts.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/16120
Uses the ContentHeader component on Dashboard and MapFilters to ensure a more unified look through the app
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> fix: Use <ContentHeader> on Dashboard and MapFilters

src/mobile-token/MobileTokenContext.tsx, src/mobile-token/mobileTokenClient.ts
Every 6 hours, check if token needs to be renewed.
Checks by using the native token validity end. Won't catch changes
to the validity done online. To catch that a validation (on app
start) is necessary.
The original plan was to validate with a given interval, but as first 
measure we try this instead, which is less intruding and doesn't
need network requests.
=> feat: Check if token should be renewed

src/components/screen-header/HeaderButton.tsx, src/components/screen-header/ScreenHeader.tsx, src/components/screen-header/index.ts
They were used in bottom sheets, but are no longer in use when the
bottom sheets have gotten a new header.
=> refactor: Remove unused header without navigation

android/app/build.gradle, android/app/proguard-rules.pro
closes https://github.com/AtB-AS/kundevendt/issues/3744
This PR will enable obfuscation and resource shrinking in Android builds for store variant. 
In order to test the build, you can go to the GitHub Actions, then click on the "Build staging android project", select "run workflow", select branch `ridwan/obfuscation-android`, set force new build to true, and then run the workflow. 
The build will be for "Store" variant even though its "Build staging android project" (just for testing the build). Will only build for AtB, and will publish the result to AppCenter.
=> feat: enable obfuscation and resource shrinking for Android

src/configuration/types.ts, src/tariff-zones-selector/TariffZoneResults.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/9642
This will add description to the zone selector. Descriptions are added to another PR in firestore-configuration repo.  https://github.com/AtB-AS/firestore-configuration/pull/418. 
Please see the screenshot below to see how it looks with/without description.
<details>
</details>
=> feat: add description to zones

src/fare-contracts/CompactFareContractInfo.tsx, src/fare-contracts/FareContractInfo.tsx, src/fare-contracts/details/DetailsContent.tsx, src/fare-contracts/utils.ts
Closing https://github.com/AtB-AS/kundevendt/issues/16242.
TariffZoneSummary is no longer shown for FareContracts where the ticket is sold on the authority endpoint and valid for all zones.
The same logic was being applied both for the normal FareContracts and the compact ones, so extracted it into a custom hook.
This might be cherry-picked into a FRAM 1.45 release branch
=> feat: hide tariffzoneSummary for authority tickets

.eslintrc.js, src/RemoteConfigContext.tsx, src/fare-contracts/details/Barcode.tsx, src/mobile-token/MobileTokenContext.tsx, src/place-screen/hooks/use-departures-data.ts, src/stacks-hierarchy/Root_CarnetDetailsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/use-favorite-departure-data.ts, src/time/TimeContext.tsx, src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx, src/utils/__tests__/use-interval.test.ts, src/utils/use-interval.ts, src/utils/use-now.ts, src/utils/use-pollable-resource.ts
You get the power of the exhaustive deps eslint rule on your
custom hooks by adding them in the 'additionalHooks' argument
in the rule options.
To make this work the first argument of the custom hook needs to
be the function, while the second argument needs to be the deps.
Added this to the 'useInterval' hook and fixed the errors that
showed up.
=> refactor: Add exhaustive deps rule to useInterval

ios/atb/Info.plist, ios/en.lproj/InfoPlist.strings, ios/nb.lproj/InfoPlist.strings, ios/nn.lproj/InfoPlist.strings, src/translations/screens/ShareTravelHabits.ts
- Updated the texts to be according to [Figma](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=18256-2778&mode=dev) and will resolve the comments in [Figma](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=18256-2778&mode=dev) when this is merged. 
- Added translations for the text for iOS.
- The announcements have been updated in firebase to match [Figma](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=18256-2778&mode=dev). These were only in staging, and I did not add them to prod.
The "new-norwegian" texts should probably be double checked by @marius-at-atb or @rosvik. (Nynorsk wasn't my strongest side in high school)
=> fix: updating beacons text and adding translations

src/components/bottom-sheet/BottomSheetHeader.tsx
@ckbilstad discovered that we used the wrong interactive color on the[ button on the bottom-sheet.](https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/Components?type=design&node-id=4573-10756&mode=dev)
| ------ | ----- |
| <img src="https://github.com/AtB-AS/mittatb-app/assets/70323886/35938a7a-91a3-4256-ac69-e49af3e1d5bd" width="300"> | <img src="https://github.com/AtB-AS/mittatb-app/assets/70323886/66b1dc5f-3737-4d5f-8d01-53ff6ccda567" width="300"> |
=> fix: bottom sheet close button color

src/notifications/utils.ts, src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx, src/ticketing/types.ts
This PR updates the logic for displaying the notification onboarding. With these changes:
- The onboarding will only be shown to users who have a ticket with notifications set to default enabled.
- If the user has already enabled notifications through their settings, the onboarding will not be displayed.
=> fix: notification onboarding logic

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentOptionsScreen.tsx
Remove margins from message boxes as there is a gap set on the
container level.
Before/After (constructed example with all message boxes set to visible):
<div>
</div>
=> refactor: Fix gap on payment options screen

src/configuration/types.ts, src/fare-contracts/utils.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-defaults.ts
Added a boolean `isDefault` to the 30 day ticket in [referenceData in Firestore.](https://github.com/AtB-AS/firestore-configuration/pull/421), and made the logic similar as for the defaultTariffZone.
=> feat: default period ticket

src/fare-contracts/details/Barcode.tsx, src/fare-contracts/details/DetailsContent.tsx
Closing https://github.com/AtB-AS/kundevendt/issues/15554
Introducing a full width white padding for static QR codes (which means this should only affect FRAM), even in dark mode. Should improve readability for validation at FLV+ in FRAM buses.
<details>
After:
Before:
</details>
=> feat: add custom view styling for static qr barcode view

src/components/button/Button.tsx, src/travel-details-screens/components/FlexibleTransportBookingOptions.tsx
> "... has reported a UI error on the button in the travel search when AtB Bestill comes up. We should fix this so that the text is closer to the symbol and make the buttons more similar. The point is the space between the icon and the text on the phone."
| Android Before                                      | Android After                                       |
|-----------------------------------------------------|-----------------------------------------------------|
| <img src="https://github.com/AtB-AS/mittatb-app/assets/70323886/c3031871-f826-4ebc-a6c7-2b77c6ba0f1e" width="300"> | <img src="https://github.com/AtB-AS/mittatb-app/assets/70323886/25dc6968-91aa-4a53-a2dc-d9f99f20e1dd" width="300"> |
| iOS Before                                          | iOS After …
=> fix: Atb bestill button text placement with larger text

src/notifications/use-config.tsx
This fixes a bug where stale notification config data would stay after the auth user had changed. By providing userId as part of the useQuery key, this is automagically refetched when the userId changes.
1. While logged in, go to My profile -> Notifications
2. Enable notifications from some tickets other that the defaults
3. Log out
4. Open the Notifications page again,
- Before this fix, the settings would show as the same as for the logged in user, even though this is a new anonymous user with default configs. Once you toggle something, the default configs will be loaded.
- After this fix, the default configs should be shown.
=> fix: refetch notification config on auth user change

src/travel-token-box/TravelTokenBox.tsx
The edit button will only fully work after https://github.com/AtB-AS/mittatb-app/pull/4106 has been merged.
Removing the button for 1.46.
The removed button:
Resolves https://github.com/AtB-AS/kundevendt/issues/8620
=> Fix: remove edit button in TravelTokenBox

src/stacks-hierarchy/Root_ParkingViolationsReporting/components/ScreenContainer.tsx
The screen reader was stuck on iOS since it focused the title-less
header. Now instead focus the larger title in the body instead of
the heading.
=> fix: Parking violations screen reader focus

src/notifications/use-has-fare-contract-with-activated-notification.tsx, src/notifications/utils.ts, src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx, src/ticketing/use-valid-right-now-fare-contracts.tsx
@HanneLH discovered a bug in the onboarding after this PR https://github.com/AtB-AS/mittatb-app/pull/4183. ([Slack thread](https://mittatb.slack.com/archives/C0116FMPX4Y/p1704354186562479))
The issue was that the introduced dependencies to the use effect caused it to trigger too often. This was solved by creating a hook as seen in [this commit](https://github.com/AtB-AS/mittatb-app/pull/4106/commits/afd3a40fec40eecea3542bd84a0970eb45ce08d5#diff-ffacdee1fc9ed442bbfd49dd4360b8b26d85b4cca286da3cbf3c4e87e1b3428c) on [this PR](https://github.com/AtB-AS/mittatb-app/pull/4106/files#diff-bef323399bd92561797b93b8692d74f9e2c53ffa1b23fb5c3963137fad1ea782) by @marius-at-atb.
I belive the onboarding PR from @marius-at-atb will fix it on the master branch, and this is enough to fix it on the release …
=> fix: onboarding appearing twice 

src/components/button/Button.tsx
@reidzeibel noticed that the text was not centered on block buttons.([Slack thread](https://mittatb.slack.com/archives/C02EEG7D8EL/p1704357853109059))
It was caused by https://github.com/AtB-AS/mittatb-app/pull/4178
Fixed by making the `width: 100%` dependent on whether or not the button is inline.
=> fix: button text placement

android/app/build.gradle, android/app/src/main/AndroidManifest.xml
This PR tries to fix issue mentioned in this comment : https://github.com/AtB-AS/kundevendt/issues/3744#issuecomment-1875211143
I updated the bugsnag Android gradle implementation based on the link https://docs.bugsnag.com/build-integrations/gradle/, this should automatically uploads the source files to bugsnag for translation of obfuscated errors.
=> fix: upload source maps Android using bugsnag plugin

.storybook/storybook.requires.js, src/storybook/stories/Button.stories.js, src/storybook/stories/MessageInfoBox.stories.js, src/storybook/stories/MessageInfoText.stories.js, src/storybook/stories/ThemeText.stories.js
- Added the button component with block, pill and inline  
- Changed theme selection to radio buttons on existing stories for faster switching 🏎️ 
Another possibility would also to have the switch between button modes(pill, inline, block) to be a selection in the addons instead of separate pages, however I belive it is more structured this way and also the addons page already had a lot of options.
<details>
<summary> 📷  Images </summary>
</details>
<details>
<summary> 📹 Video </summary>
https://github.com/AtB-AS/mittatb-app/assets/70323886/3f8e0961-4d27-4b5f-85a0-074ad6060d78
</details>
=> chore: adding button to storybook

src/travel-details-screens/DepartureDetailsScreenComponent.tsx, src/travel-details-screens/__tests__/get_should_show_live_vehicle.test.ts, src/travel-details-screens/utils.ts, src/utils/date.ts
We checked on whether the estimated call had realtime data to
determine whether to show live bus position or not, but it turns
out a vehicle may have live position even if it doesn't have
realtime data.
Changed the logic to be based on departure time instead. If there
is less than 10 minutes until the service journey starts, or it has
started, then we will start to fetch vehicle live position.
=> feat: Live position in map not reliant on vehicle position

ios/Podfile.lock
When building release candidate there was a broken url in the
Podfile.lock for the boost dependency. To fix this we needed to
update the pods, which also updated other pods within their
version range in the respective Podfiles were they are specified.
https://github.com/AtB-AS/mittatb-app/actions/runs/7448178232/job/20261959451
=> chore: Update podfile.lock

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/Ticketing_TicketTabNavStack.tsx, src/translations/screens/Ticketing.ts
| English | Bokmål | Nynorsk |
|---------|--------|---------|
| <img src="https://github.com/AtB-AS/mittatb-app/assets/70323886/4ee17af3-0408-4433-bfc1-524ac8942d70" width="250" alt="Simulator Screenshot - iPhone 15 Pro - 2024-01-08 at 14 36 52"> | <img src="https://github.com/AtB-AS/mittatb-app/assets/70323886/50c48fe2-2bd4-4e70-ac5a-544e15f20f45" width="250" alt="Simulator Screenshot - iPhone 15 Pro - 2024-01-08 at 14 36 33"> | <img src="https://github.com/AtB-AS/mittatb-app/assets/70323886/8fb9f959-67de-4d54-892a-ec29de420055" width="250" alt="Simulator Screenshot - iPhone 15 Pro - 2024-01-08 at 14 36 57"> |
=> fix: rename "active" tab title

src/beacons/BeaconsContext.tsx, src/beacons/permissions.ts, src/beacons/use-should-show-share-travel-habits-screen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx, src/translations/screens/subscreens/PrivacySettingsTexts.ts
Before I start https://github.com/AtB-AS/kundevendt/issues/16285, this PR is a refactor to hopefully make beacons less confusing to get started with :)
- Removes all references to Kettle from outside of the BeaconsContext
- Adds some docstrings for the fields in BeaconsInfo
- Fixes some formatting/whitespace
There should be no functional changes.
=> refactor: update naming, docs and formatting in BeaconsContext

src/travel-details-screens/components/Trip.tsx, src/travel-details-screens/utils.ts
The live button was missing in the trip details screen:
https://github.com/AtB-AS/kundevendt/issues/15618#issuecomment-1878666180
Fixed by using same utility function as in:
https://github.com/AtB-AS/mittatb-app/pull/4203
=> feat: Show live button in trip screen not reliant on realtime

src/analytics/types.ts, src/beacons/permissions.ts, src/stacks-hierarchy/Root_ShareTravelHabitsScreen.tsx
closes https://github.com/AtB-AS/kundevendt/issues/16115
Pretty straightforward PR, sends a posthog event everytime the screen is shown, and send another posthog event when the permissions are given by the user.
=> feat: add analytics to share travel habits screen

src/components/map/hooks/use-update-bottom-sheet-when-selected-entity-changes.tsx
The fix in https://github.com/AtB-AS/mittatb-app/pull/4221 was happening because of some cached version locally. Did not work so reverting
=> revert: remove redundant close function for bottom sheet in map

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
On some screens, both android and iOS, the trip results which had _AtB bestill_ as its first leg did not show but were clickable. This was caused by the width of the content being larger than the parent. The following code therefore made it so that the **opacity was always 0**:
```
const fadeInValueRef = useRef(new Animated.Value(0));
// Dynamically collapse legs to fit horizontally
useEffect(() => {
if (legIconsParentWidth && legIconsContentWidth) {
if (legIconsContentWidth >= legIconsParentWidth) {
setNumberOfExpandedLegs((val) => Math.max(val - 1, 1));
} else {
Animated.timing(fadeInValueRef.current, {
toValue: 1,
duration: 250,
useNativeDriver: true,
}).start();
}
}
}, [legIconsParentWidth, legIconsContentWidth]);
```
<details>
<summary>The results were invisible but …
=> fix: results with AtB bestill as first leg not showing with larger text

src/components/bottom-sheet/BottomSheetContext.tsx, src/components/map/hooks/use-update-bottom-sheet-when-selected-entity-changes.tsx, src/components/sections/items/TextInputSectionItem.tsx, src/stacks-hierarchy/Root_PurchaseHarborSearchScreen/Root_PurchaseHarborSearchScreen.tsx, src/utils/use-focus-on-load.ts, src/utils/use-focus-refs.ts
Issue link: https://github.com/AtB-AS/kundevendt/issues/16389
The problem was the node trying to call `AccessibilityInfo.setAccessibilityFocus(reactTag)` when the node was unmounted. 
As @marius-at-atb said in [a comment](https://github.com/AtB-AS/mittatb-app/pull/4221#issuecomment-1887463960):
> When giveFocus receives a ref, then its current value will later be modified, and this change will be reflected inside giveFocus.
> 
> When giveFocus receives a ref.current directly, that value will later be reassigned, and the change won't be reflected inside giveFocus.
> 
> Therefore when using async logic inside giveFocus and accepting a ref.current directly, the value can be outdated by the time it is used, causing a crash.
This fix addresses the bottom-sheet crashing when pressing the close …
=> fix: giveFocus to unmounted node

src/stacks-hierarchy/Root_ConsiderTravelTokenChangeScreen/Root_ConsiderTravelTokenChangeScreen.tsx, src/utils/use-onboarding-navigation-flow.ts
The travel token needs some time before it is ready after a login.
The new onboarding flow showed the `Root_ConsiderTravelTokenChangeScreen` screen immediately, but this caused an error state to be visible. Now the flag for whether that screen should show or not is false until the travel token is ready.
One change this causes, is that it will no longer show as the first screen after login (but atm it has highest priority, so as soon as it is ready, it will be shown.) In most cases it will now be shown right after the location onboarding screen.
Closes https://github.com/AtB-AS/kundevendt/issues/8620#issuecomment-1891961937
=> fix: travel token consider change screen onboarding flag

src/components/map/Map.tsx, src/mobility/use-stations.tsx, src/mobility/use-vehicles.tsx, src/mobility/utils.ts
There was two error that together caused this:
- The onMapIdle listener fires way too often, which make it seems
like the viewport has changed when it really hasn't.
- Bug in the code comparing the previously loaded area with the new
area, which caused refetching data when it was not necessary.
Since onMapIdle fired too many times (with the same map region
visible) and there was a bug when comparing two map regions, we
ended up fetching data more than we should.
This is now fixed by:
- The onMapIdle listener updates a state storing the map region, but
only if it has really changed. So now, even though the onMapIdle
listener fires more than it should, it shouldn't update the state.
- Fixed the logic comparing two areas, where we now transform
both previous area and new area to features of …
=> fix: Stations and vehicles fetched too often

src/components/screen-header/HeaderButton.tsx, src/components/screen-header/ScreenHeader.tsx, src/components/screen-header/index.ts, src/components/screen-header/use-ticket-info.tsx, src/stacks-hierarchy/Root_CarnetDetailsScreen.tsx, src/stacks-hierarchy/Root_FareContractDetailsScreen.tsx, src/translations/components/ScreenHeader.ts, src/translations/screens/FareContract.ts
closes https://github.com/AtB-AS/kundevendt/issues/16298
This PR will add new ticket info header button on ticket detail screen (both regular tickets and carnet tickets), and the navigation to the ticket information screen. Also added accessibility information, tested on 200% font size, both iOS and Android. Language is not ready until this issue is done https://github.com/AtB-AS/kundevendt/issues/15863
Sjekk ut skjermbilde for detaljer 
(Check out screenshots for details, hopefully this is correct, trying to not use google translate)
<details>
<summary>Vis skjermbilde</summary>
https://github.com/AtB-AS/mittatb-app/assets/1777333/801ba88e-7188-454b-baa2-80c0c78faadd
https://github.com/AtB-AS/mittatb-app/assets/1777333/ef114f3f-6afe-4161-95bf-fceddf3c7fe2
</details>
=> feat: ticket info button on ticket detail screen

src/beacons/BeaconsContext.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NotificationsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx, src/translations/screens/Profile.ts
closes https://github.com/AtB-AS/kundevendt/issues/16425
This PR attempts to separate "consents" and "permissions" more clearly by adding message boxes that warns about missing permissions when consent is given. This applies to push notifications, email and beacons. (ref. https://github.com/AtB-AS/kundevendt/issues/15656#issuecomment-1886818199)
In the BeaconsContext, this is reflected by always setting local storage `beaconsConsent = true`, even if the user doesn't give permissions. 
Also changes some variable names and adds some comments :) 
<div>
</div>
=> feat: add new permission prompts for notifications and beacons

src/onboarding-screen/OnboardingScreenComponent.tsx
When using screenreader, set the focus on the title for OnboardingScreenComponent.
Prevents issues like https://github.com/AtB-AS/kundevendt/issues/8620#issuecomment-1878544889 where the screenreader can get stuck in the title.
=> fix: set screenreader focus on title for OnboardingScreenComponent

src/beacons/BeaconsContext.tsx, src/stacks-hierarchy/Root_ShareTravelHabitsScreen.tsx
Sets `shareTravelHabitsOnboarded` to true when `onboardForBeacons` is run. That way, we won't show onboarding after the user have manually given consent.
alternative solution to https://github.com/AtB-AS/mittatb-app/pull/4231
fixes https://github.com/AtB-AS/kundevendt/issues/16288
=> fix: complete travel habits onboarding in onboardForBeacons

src/tips-and-information/TipsAndInformation.tsx, src/tips-and-information/converters.ts, src/tips-and-information/types.ts
Removing the usage of emojis in tips and information
Closes: https://github.com/AtB-AS/kundevendt/issues/16299
=> feat: remove emojis from tips and information

src/beacons/BeaconsContext.tsx, src/stacks-hierarchy/Root_ShareTravelHabitsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx
ref. https://github.com/AtB-AS/kundevendt/issues/16425#issuecomment-1893576632
Fixes a few issues from QA:
- Dismissing the permissions prompt during onboarding no longer sets consent to true.
- The prompt to open phone settings on the privacy page is now based on if we have _any_ beacons permission, not just bluetooth
- The prompt to open phone settings on the privacy page is now removed when permissions are allowed
=> fix: fix qa issues on permissions flow

.storybook/storybook.requires.js, src/components/bordered-info-box/BorderedInfoBox.tsx, src/components/bordered-info-box/index.ts, src/storybook/stories/BorderedInfoBox.stories.js, src/utils/add-opacity.ts
Adds a new component to the src and storybook. This is the bordered
info box introduced in the on behalf of product initiative. Pretty
basic component, where the main cavaet is that the border is based
on the text color with 0.1 opacity. This was since we didn't have
an appropriate color to use in the design-system, and we didn't
want to introduced a new one just for this use case.
<details>
<summary>Screenshots from Storybook:</summary>
</details>
=> feat: Add BorderedInfoBox component

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FareContractsScreen.tsx
Since fare contracts that are for different abtCustomerIds are filtered out (because we don't want to show reservations for subaccounts) the customerAccountId needs to be correct for it to show up in the design system.
=> fix: show reservations under fare contracts in design system

src/fare-contracts/CompactFareContractInfo.tsx, src/fare-contracts/FareContractInfo.tsx, src/fare-contracts/carnet/CarnetDetails.tsx, src/fare-contracts/details/DetailsContent.tsx, src/fare-contracts/utils.ts
Figma sketches now contain the traveller count on ticket details
screen, where we previously omitted the count if it was 1.
Before/After:
<div>
</div>
Image from Figma:
=> feat: Show traveller count on details screen

src/components/sections/items/ExpandableSectionItem.tsx
The screen reader can now access and read out the content of the expanded section in ExpandableSectionItem, both on android and iOS 👾 
Fixed as part of: https://github.com/AtB-AS/kundevendt/issues/16299
Also closing the reported bug: https://github.com/AtB-AS/kundevendt/issues/10098
=> fix: make expanded part of expandable section item accessible

src/components/screen-view/FullScreenView.tsx
Fixes a bug where setFocusOnLoad was true regardless of the headerProps input.
This caused several focus calls resulting in race conditions.
Closes https://github.com/AtB-AS/kundevendt/issues/8619#issuecomment-1898076894
Replaces https://github.com/AtB-AS/mittatb-app/pull/4250 for now
=> fix: setFocusOnLoad in FullScreenView

src/stacks-hierarchy/Root_LoginConfirmCodeScreen.tsx, src/stacks-hierarchy/Root_LoginOptionsScreen.tsx
Two main changes in this PR:
- We complete onboarding before the last step of the authentication
process, like sending in the confirmation code. This is so we don't
end up in a race condition between Firebase Auth switching user and
setting the onboarded flag to true.
- We do not navigate anywhere after login, as changing user is
basically a reload of the app, and we end up back at the starting
screen no matter what.
=> feat: Not navigate after login

src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx, src/utils/use-onboarding-flow.ts
No longer showing the travel token onboarding screen when the travel token is already on your device.
Note: this opened up a new path where a user doesn't have to see the travel token onboarding screen to finish the onboarding. So when changing the token to another device, it would show the onboarding then instead. To ensure this doesn't happen, an extra useEffect was added in the `SelectTravelTokenScreenComponent`.
Resolves https://github.com/AtB-AS/kundevendt/issues/8619#issuecomment-1903824259
=> fix: only show travel token onboarding if not on your device

src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SelectTravelTokenScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/TabNav_ProfileStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/navigation-types.ts
Since the screen transitions in popping up, it should have a close button instead of back button.
Also deletes a now unused profile screen.
Resolves https://github.com/AtB-AS/kundevendt/issues/8619#issuecomment-1903824259
=> fix: change token screen back button

src/AppContext.tsx, src/beacons/use-should-show-share-travel-habits-screen.tsx, src/stacks-hierarchy/Root_LoginConfirmCodeScreen.tsx, src/stacks-hierarchy/Root_LoginOptionsScreen.tsx, src/stacks-hierarchy/Root_PurchaseAsAnonymousConsequencesScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/utils/use-complete-user-creation-onboarding-and-enter-app.ts, src/utils/use-onboarding-flow.ts
This PR is all about renaming `onboarded` to `userCreationOnboarded`. Related names have also been renamed the same way.
After the renaming, its current purpose finally becomes obvious, and this allowed a simplification of `useOnboardingFlow`.
Related discussion: https://github.com/AtB-AS/mittatb-app/pull/4257#issuecomment-1903654902
=> chore: rename onboarded

.github/workflows/build-store-ios.yml
Add the same [build step](https://github.com/AtB-AS/mittatb-app/pull/4273/files) for store-ios as in stage-ios.
Resolves https://github.com/AtB-AS/kundevendt/issues/16030
=> chore: build store ios - remove unused beacons

src/AppContext.tsx, src/stacks-hierarchy/Root_OnboardingStack/Onboarding_AlsoGoodToKnowScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/utils/use-onboarding-flow.ts
The extended onboarding wasn't properly supported by the new onboarding flow.
One issue with it was that if you restarted the app after completing it, you had to go through it again.
Now the implementation is in line with the new way to deal with the onboarding flow.
- Added `extendedOnboardingOnboarded` flag in AppContext (not a great name, but refactoring `AppContext` will have to wait)
- Using `extendedOnboardingOnboarded` in the new `useShouldShowExtendedOnboarding` in `useOnboardingFlow`
=> chore: use correct nav flow logic for extended onboarding

src/stacks-hierarchy/RootStack.tsx, src/utils/use-onboarding-flow.ts
This PR is just to simplify the `getInitialNavigationContainerState` function.
Note: The `shouldGoDirectlyToOnboardingScreen` parameter was unnecessary and is removed.
=> chore: simplify getInitialNavigationContainerState

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TicketHistoryScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TicketHistorySelectionScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/TabNav_ProfileStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/navigation-types.ts
closes https://github.com/AtB-AS/kundevendt/issues/16303
also closes https://github.com/AtB-AS/kundevendt/issues/16305
- Adds a new screen `Profile_TicketHistorySelectionScreen` with it's corresponding navigation requirements.
- Replaces the content in `Profile_TicketHistoryScreen` with the new `TicketHistoryScreenComponent`.
=> feat: add ticket selector to profile - ticket history screen

src/popover/types.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/translations/components/OneTimePopOver.ts
closes https://github.com/AtB-AS/kundevendt/issues/16033
Pretty straightforward PR, things added:
- ref to the new label.
- useFocusEffect to trigger popover when view is rendered and screen is shown.
- text for popover.
Preview below
=> feat: add popover for on-behalf–of

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FareContractsScreen.tsx, src/ticketing/types.ts
Adding `purchasedBy` and `customerAccountId` to `FareContract`, these are already in Firestore, just unused until now. 
On-behalf-or / På-vegne-av feature requires these props.
=> feat: add purchasedBy and customerAccountId to FareContract type

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TicketHistorySelectionScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/navigation-types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_ActiveFareProductsTabScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/navigation-types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/navigation-types.ts, src/ticket-history/TicketHistoryScreenComponent.tsx, src/ticket-history/index.tsx, src/ticket-history/types.ts, src/translations/screens/Ticketing.ts, src/translations/screens/subscreens/TicketHistory.ts
Part of https://github.com/AtB-AS/kundevendt/issues/16305
This PR will : 
- Improve the usage of `TicketHistoryMode = 'expired' | 'sent'` by using it everywhere else on the code (Profile ticket history screen, Ticket tab history screen, and Ticket history component).
- Allow the use of dynamic text translation on screens based on the mode `expired` or `sent` in `TicketHistoryScreenComponent`, moving the logic from the view to translation file.
- Remove unused file.
=> refactor: rework ticket history typing and text translations

android/app/proguard-rules.pro, android/build.gradle
slack discussion : https://mittatb.slack.com/archives/C0116FMPX4Y/p1706874281773619
This PR will: 
- add proguard rules to fix the crash that occurs on Vipps login. 
- update AndroidX Browser version to 1.5.0 (latest version allowed on apps targeting Android SDK 33)
=> Fix Vipps Login crash on 1.46 rc7

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_ActiveFareProductsTabScreen.tsx
Makes sure that the scrollbar and overflow show up correctly after https://github.com/AtB-AS/mittatb-app/pull/4284
Before/After 
<div>
</div>
=> fix: update scrollview padding on active tickets

src/notifications/api/index.ts, src/notifications/use-notification-config.tsx, src/notifications/use-push-notifications.tsx
Just a small refactor to make it more intuitive: 
useConfig ➡️ useNotificationConfig
use-config.tsx ➡️ use-notification-config.tsx
getConfig ➡️ getNotificationConfig
updateConfig ➡️ updateNotificationConfig
=> refactor: rename some notification-related file and functions

src/stacks-hierarchy/Root_PurchasePaymentWithVippsScreen/Root_PurchasePaymentWithVippsScreen.tsx
The current vipps payment redirection screen has no margin on the sides, this PR will add the necessary margins.
See screenshots below
**Without margin**
**With margin**
=> fix: add margin to vipps payment screen

src/fare-contracts/FareContractInfo.tsx, src/fare-contracts/PreActivatedFareContractInfo.tsx, src/fare-contracts/SimpleFareContract.tsx, src/fare-contracts/ValidityLine.tsx, src/fare-contracts/carnet/CarnetDetails.tsx, src/fare-contracts/details/DetailsContent.tsx, src/fare-contracts/utils.ts
Part of 
https://github.com/AtB-AS/kundevendt/issues/15879
https://github.com/AtB-AS/kundevendt/issues/16304
We need to be able to identify that a `FareContract` is `sent` to other recipient, this PR will:
- add new validity status `sent`.
- refactor `getValidityStatus` to accept `FareContract`.
=> refactor: update `getValidityStatus` to accept `FareContract`, added `sent` validity status

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
Adds missing "new" label to the notifications link in my profile: https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=16551-60217&mode=design&t=ttgHFyL8TcJ9VLpp-0
=> feat: add "new" label to notifications in my profile

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
fixes issue from slack : https://mittatb.slack.com/archives/CSFC6PG23/p1707392965566429
When sending to someone else, we should not show any token warning message.
This PR will hide the warning if `on-behalf-of` toggle is activated.
=> fix: hide token warning message if buying ticket for someone else

src/components/map/hooks/use-trigger-camera-move-effect.tsx
The problem was similar to the one in @gorandalum's PR https://github.com/AtB-AS/mittatb-app/pull/4040. I found the issue to be that we were taking font scale into the calculation of the padding. On the note 10, where the issue was, the scale was 0.8 making the padding bigger which means less space for the walking path. This led to it zooming all the way out since the path never fit inside the remaining space.
The scaling is also kind of counter intuitive, as when the font is smaller and things take less space, the padding was getting bigger. And vice versa with larger font. This made the path not centered when the font was scaled.
So this fixes both the very specific bug, and the map for larger fonts.
Below is before and after with larger font:
<details>
</details>
=> fix: map zooming all the way out on bicycle station in map

package.json, src/chat/ContactSheet.tsx, src/chat/use-chat-icon.tsx, yarn.lock
* update generate-assets for new icons on Chat and ServiceDisruptions
* added border around notification indicator when used with chat icon
Closes: https://github.com/AtB-AS/kundevendt/issues/15573
=> style: new icons and added border around notification indicator

src/components/tile/TileWithButton.tsx, src/fare-contracts/details/DetailsContent.tsx, src/mobility/components/BenefitTiles.tsx, src/translations/screens/subscreens/MobilityTexts.ts
Fix of QA feedback on bundling actions in ticket details
- Adds a11y role "button" to TileWithButton.
- Adds a11y hint to benefit tiles.
- Only shows benefits when the ticket is active.
fixes https://github.com/AtB-AS/kundevendt/issues/16297
=> fix: qa feedback for benefit tiles

src/components/icon-box/TransportationIconBox.tsx
Fixes feedback from https://github.com/AtB-AS/kundevendt/issues/3834#issuecomment-1934011715. Based on the sketches, TransportationIconBox should always have xSmall padding. 
<div>
</div>
fixes https://github.com/AtB-AS/kundevendt/issues/3834
=> fix: update TransportationIconBox padding to match sketches

src/index.tsx, src/remote-config.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/storage/StorageModel.tsx, src/time/TimeContext.tsx, src/time/index.ts, src/time/use-server-time-enabled.ts
- Add a feature flag to be able to turn of server time if
necessary. The feature flag has the default value true, and can be
set to false in RemoteConfig.
- Also fixed a bug where if the server clock didn't start as it
should, then the interval wasn't fired. This ment that if
something went wrong with the time-lib, we would never get an
updated time. Now the interval always runs every 2500 ms, but
fallbacks to Date.now() if server time not enabled or the time-lib
isn't started.
=> feat: Add feature flag for server time

src/api/departures/types.ts, src/api/types/departures.ts, src/api/types/generated/DeparturesQuery.ts, src/api/types/generated/fragments/estimated-calls.ts, src/api/types/generated/fragments/service-journeys.ts, src/departure-list/section-items/line.tsx, src/place-screen/components/EstimatedCallItem.tsx, src/situations/utils.ts, src/travel-details-screens/DepartureDetailsScreenComponent.tsx, src/travel-details-screens/utils.ts, src/utils/__tests__/status-comparator.test.ts, src/utils/status-comparator.ts
Show booking info on:
- As info-box on The departure details screen, with booking action
buttons if currently bookable.
- As icon in the upper left corner (same as situations) in the
departures list v2.
- As right icon on the departure chip in departures list v1.
=> feat: Add booking info to departures

src/components/icon-box/TransportationIconBox.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
This adds some more padding around transport icons in travel search ResultItems.
I was unsure about what kind of prop I should use here, so I'm open to feedback 😊 
1. I could use ContainerSizingType (`'compact' | 'standard' | 'spacious'`), but it didn't quite fit since all I needed was two modes, and default would be compact. 
2. A new prop `type='normal' | 'spacious'`. The `mode` name is taken for Transport Mode.
3. I felt like `spacious=boolean` was the simplest solution, but it doesn't really fit what we've done elsewhere
fixes https://github.com/AtB-AS/kundevendt/issues/3834#issuecomment-1943696655
=> fix: use small padding around icons in travel search results

src/travel-details-screens/DepartureDetailsScreenComponent.tsx
The trip row shouldn't be focusable, instead the booking info box
and booking buttons inside them should be.
https://github.com/AtB-AS/kundevendt/issues/4199#issuecomment-1945651874
=> refactor: Screen reader fix for departures booking info 

src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx
An empty object was used to represent that there was no filters,
but the object was recreated every render, which made several
useEffect's run way to often.
https://mittatb.slack.com/archives/C0116FMPX4Y/p1707984786631569
=> fix: Travel map useEffect loop

src/fare-contracts/carnet/CarnetFooter.tsx, src/fare-contracts/carnet/__tests__/calculate-carnet-data.test.ts, src/fare-contracts/carnet/calculate-carnet-data.ts, src/translations/screens/FareContract.ts
fixes https://github.com/AtB-AS/kundevendt/issues/16655
- Refactors how the display data for CarnetFooter is calculated
- Fixes several issues with CarnetFooter state for >10 accesses (see code comments for details)
- Adds unit tests to be sure it stays like that!
```
Carnet footer: 10 tickets
✓ 10 tickets, 0 used, not active. (2 ms)
✓ 10 tickets, 1 used, not active.
✓ 10 tickets, 2 used, not active.
✓ 10 tickets, 3 used, not active. (1 ms)
✓ 10 tickets, 4 used, not active.
✓ 10 tickets, 5 used, not active.
✓ 10 tickets, 6 used, not active.
✓ 10 tickets, 7 used, not active. (1 ms)
✓ 10 tickets, 8 used, not active.
✓ 10 tickets, 9 used, not active.
✓ 10 tickets, 10 used, not active.
✓ 10 tickets, 1 used, active. (1 ms)
✓ 10 tickets, 2 used, active.
✓ 10 tickets, 3 used, active.
✓ 10 …
```
=> fix: show the correct number of consumed carnets in CarnetFooter

src/fare-contracts/FareContractView.tsx, src/fare-contracts/components/ConsumeCarnetSectionItem.tsx, src/fare-contracts/details/DetailsContent.tsx, src/ticketing/utils.ts
- The main change here is to split `hasActiveOrUsableCarnetTravelRight()` into two smaller util functions that when used together, can achieve more granular functionality.
- Since fare contract state doesn't give the wanted data for showing ConsumeCarnetSectionItemProps, we now check active state based on `usedAccesses` trough `isCanBeConsumedNowFareContract`.
- Fixes some naming issues (https://github.com/AtB-AS/mittatb-app/pull/4339#discussion_r1497688948)
fixes https://github.com/AtB-AS/kundevendt/issues/12562
=> refactor: update ticketing util function to be more reusable

ios/Shared/BeaconsPermissions.swift, src/beacons/BeaconsContext.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/17005
NOTE: This solution makes sure for some cases where the initialization of the SDK is called but not started because lack of permissions on the simulator, so then make sure that only run Kettle of SDK was initialized.
=> fix: Simulator crashes during onboarding for beacons 

src/mobile-token/mobileTokenClient.ts
The refresh percentage should be 10 instead of 90. With the value
we had the 30 day token was renewed after 3 days, and not after 27
days as intended.
Note that changing the validity periods in BackOffice won't help, as it is the validity period on the local token that is evaluated. If we want to test this in a quicker manner than waiting many days we could modify the token-server in staging to create tokens with shorter validity days than 30.
=> fix: Correct value for token refresh percentage

src/stacks-hierarchy/Root_ChooseTicketReceiverScreen/Root_ChooseTicketReceiverScreen.tsx, src/translations/index.ts, src/translations/screens/subscreens/OnBehalfOf.ts, src/translations/screens/subscreens/PurchaseOverview.ts
There are two references to the AtB-app in the app for the OMS partners. Adding `orgSpecificTranslations` fixes this. 
Closes https://github.com/AtB-AS/kundevendt/issues/17056
=> fix: OMS translations for the on-behalf-of feature

src/translations/screens/ShareTravelHabits.ts
After the rejected Google submission, they asked us to change the location always on prompt. We have to include either `background`, `when the app is closed`, `always in use` or `when the app is not in use`.
The text has been changed by Marked.
See more in the Slack [thread](https://mittatb.slack.com/archives/C02EEG7D8EL/p1708787438664609).
=> fix: Update the position always on prompt text

src/translations/GeoLocation.ts
=> fix: typo in geolocation prompt

src/components/popover/PopOver.tsx, src/components/sections/items/LinkSectionItem.tsx, src/popover/PopOverContext.tsx, src/popover/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_ActiveFareProductsTabScreen.tsx, src/translations/components/OneTimePopOver.ts, src/utils/__tests__/is-view-visible-on-screen.test.ts, src/utils/is-view-visible-on-screen.ts
closes https://github.com/AtB-AS/kundevendt/issues/16927
This will show a popover to let the user knows where to find their sent tickets.
Added some comments to explain what the code means.
```
isViewVisibleOnScreen: view size <= window size, view located on top left (0,0)
✓ window size 10 x 10, view size 0 x 0 located top left (0,0) (4 ms)
✓ window size 10 x 10, view size 1 x 1 located top left (0,0)
✓ window size 10 x 10, view size 2 x 2 located top left (0,0)
✓ window size 10 x 10, view size 3 x 3 located top left (0,0)
✓ window size 10 x 10, view size 4 x 4 located top left (0,0) (1 ms)
✓ window size 10 x 10, view size 5 x 5 located top left (0,0)
✓ window size 10 x 10, view size 6 x 6 located top left (0,0)
✓ window size 10 x 10, view size 7 x 7 located top left (0,0)
✓ window size …
```
=> feat: popover for tickets sent to others button on my ticket screen.

src/chat/ContactSheet.tsx, src/components/feedback/SubmittedComponent.tsx, src/components/sections/items/LinkSectionItem.tsx, src/components/sections/items/MessageSectionItem.tsx, src/fare-contracts/PurchaseReservation.tsx, src/fare-contracts/details/DetailsContent.tsx, src/information-screen/InformationScreenComponent.tsx, src/loading-screen/LoadingErrorScreen.tsx, src/mobility/components/OperatorActionButton.tsx, src/service-disruptions/ServiceDisruptionSheet.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx, src/stacks-hierarchy/Root_PurchasePaymentWithVippsScreen/Root_PurchasePaymentWithVippsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcement.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_CategoryPickerScreen.tsx
Changes the default accessibilityRole of LinkSectionItem to "button" instead of "link"
follow up to https://github.com/AtB-AS/mittatb-app/pull/4345 and https://mittatb.slack.com/archives/CSCD9JWGP/p1708607084680919
=> refactor: change LinkSectionItem a11y role to button

src/fare-contracts/details/DetailsContent.tsx, src/ticketing/utils.ts
closes https://github.com/AtB-AS/kundevendt/issues/17062
Have also added a global message in staging with id `FareContractDetailsMultipleCarnets`, that shows for carnet tickets when `numberOfTravelRights > 1`.
=> feat: disable consumption of carnets with several travel rights

src/assets/information-data/termsInformation.json, src/stacks-hierarchy/Root_LoginOptionsScreen.tsx
In this pull request, I have addressed the issue of hardcoded terms of use information on the login screen by introducing the use of an external link for FRAM and NFK. This adjustment ensures that the terms of use information remains correct across different environments, including AtB, NFK and FRAM. 
When AtB has moved their terms of use information to their website, we can update this so that we have the same solution for everyone. 
<details>
</details>
Closes https://github.com/AtB-AS/kundevendt/issues/17084
=> feat: external link to terms of use on the login page

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx
closes https://github.com/AtB-AS/kundevendt/issues/17066
This PR will show the on-behalf-of toggle when the `travellerSelection=none`, also fixes an issue where the on-behalf-of popover was triggered even though the layout isn't there.
Tested on Fram youth ticket.
https://github.com/AtB-AS/mittatb-app/assets/1777333/81591b62-53ce-48ad-b54c-b10335578fb2
=> feat: show on-behalf-of menu on tickets without traveller selection

package.json, src/components/message-info-text/MessageInfoText.tsx, src/global-messages/GlobalMessage.tsx, src/global-messages/types.ts, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, yarn.lock
closes https://github.com/AtB-AS/kundevendt/issues/12547
This PR will : 
- Introduce global message on Purchase Confirmation screen.
- Adds a new global message context: `app-purchase-confirmation`.
- Add `TextColor` to `MessageInfoBox`, there was no way to give `secondary` color to the text component otherwise, none of the colors in `StaticColor` works.
- Add styling to necessary parts of `Root_PurchaseConfirmationScreen.tsx`, the flex part is necessary to make the text rendered correctly, especially line wrap on long text.
- Since we cannot get the carnet validity through the offer (only shows the validity of single ticket), we use global message to display the validity time.
- utilize the new `isCollectionOfAccesses` field for fareProductTypeConfig, to determine whether a ticket is a …
=> feat: add global message for carnet tickets summary

src/components/sections/items/GenericClickableSectionItem.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/translations/screens/subscreens/PurchaseOverview.ts
closes https://github.com/AtB-AS/kundevendt/issues/17099
This PR added some checks needed to disable the traveller selection when there's only 1 selectable profile, and updates the logic for accessibility.
https://github.com/AtB-AS/mittatb-app/assets/1777333/9ffa0bea-63cf-442b-8423-a7e10e9cef32
=> feat: add logic for selectable travellers and update accessibility

.github/workflows/build-store-ios.yml
An attempt at fixing
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
rm '/usr/local/bin/2to3'
To force the link and overwrite all conflicting files:
brew link --overwrite python@3.12
To list all files that would be deleted:
brew link --overwrite python@3.12 --dry-run
```
in this build: https://github.com/AtB-AS/mittatb-app/actions/runs/8137564197/job/22236213199
=> build: make brew overwrite while linking imagemagick

.github/workflows/build-staging-ios.yml, .github/workflows/build-store-ios.yml
On the latest store build (https://github.com/AtB-AS/mittatb-app/actions/runs/8153031698/job/22283620836), we have an issue as follows: 
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.11
Target /usr/local/bin/2to3-3.11
already exists. You may want to remove it:
rm '/usr/local/bin/2to3-3.11'
To force the link and overwrite all conflicting files:
brew link --overwrite python@3.11
To list all files that would be deleted:
brew link --overwrite python@3.11 --dry-run
Possible conflicting files are:
/usr/local/bin/2to3-3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3-3.11
/usr/local/bin/idle3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3.11 …
```
=> build: fix azure cli dependency

src/components/sections/items/GenericClickableSectionItem.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx
context: https://github.com/AtB-AS/mittatb-app/pull/4362#discussion_r1508915274
This PR attempts to refactor and remove the disabled part of the `GenericClickableSectionItem`, and instead use a `GenericSectionItem` if it is not clickable. 
The `<Section>` component is needed to be put around on both `GenericClickableSectionItem` and `GenericSectionItem` to ensure that the corner rounding works properly. 
Open to suggestion on how to implement this in a better way 😊 
- [ ] Traveller selection, when it is clickable, should behave normally, and visually the corners are rounded
=> refactor: rework TravellerSelection to add non-clickable section

scripts/ios/override-config-files.sh, scripts/register-local-app-version.sh
When trying to run register-local-app-version.sh, me and @hanne-at-atb spent some time looking at what "gxargs" is, where to install it, and how it differs from "xargs". While doing so, we found a alternative solution that uses xargs instead ([source](https://superuser.com/questions/467176/replacement-for-xargs-d-in-osx#comment581887_467192)). Since it comes pre-installed on macOS, this means we don't have to install it for CI, or when running register-local-app-version.sh locally!
An alternative solution would be to add docs for running `brew install findutils` while setting up the project, but I think this is nicer. :)
=> build: replace gxargs with xargs

src/components/heading/ContentHeading.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductGroup.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx
To more clearly indicate that the FareProductGroup heading belongs to the content below it and not above it, the marginTop is increased. As discussed with @ckbilstad, this was the original intention of the design.
UPDATE: The same done to the ticketAssistantTile heading after a good catch by @rosvik.
| <img width="200" src="https://github.com/AtB-AS/mittatb-app/assets/134292729/62675079-e9fb-44c9-9114-07219043824a" /> | <img width="200" src="https://github.com/AtB-AS/mittatb-app/assets/134292729/89900410-6640-4d8b-ab54-ba69bb921ed7" /> |
=> chore: increase FareProductGroup heading marginTop

src/mobile-token/MobileTokenContext.tsx, src/mobile-token/__tests__/tokenReducer.test.ts, src/mobile-token/hooks/useListRemoteTokensQuery.tsx, src/mobile-token/tokenReducer.ts
This is to enable more fine-grained error handling in mobile
token flow when updating the sdk. When we have decoupled the
different requests they can have their own error handling.
Without this change we would need a stored state specifying where
in the flow the error happened, so the correct step was retried.
=> refactor: Use react-query for listing tokens

src/mobile-token/MobileTokenContext.tsx, src/mobile-token/hooks/usePreemptiveRenewTokenMutation.tsx, src/mobile-token/tokenReducer.ts
Now using mutation from react-query for the renewal check which
happens every 6 hours. In line with earlier changes.
=> refactor: Mutation for renewal check

src/onboarding/onboarding-config.ts
This was not ment to happen, and we are not really sure if it can
happen or not without messing with onboarding flags in the debug
menu. But the safeguard is added just in case.
=> fix: Only show login onboarding if not logged in

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/utils.ts
Found a popover issue when opening the youth ticket, this PR will fix that issue, by not showing the popover when the on-behalf-of toggle is visible on the screen.
I have tested this fix on: 
- AtB (Night ticket, carnet ticket, periodic ticket, both boat tickets, single ticket, youth ticket)
- Fram (single ticket, periodic ticket, fram county periodic tickets)
- NFK (single ticket, night ticket, carnet ticket, Reis Youth, Travel Pass Nordland)
=> fix: don't show popover when the on-behalf-of toggle is visible

package.json, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelectionSheet.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/types.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/use-user-count-state.ts, yarn.lock
closes https://github.com/AtB-AS/kundevendt/issues/17193
This PR will handle the new `onBehalfOfEnabled` flag in `fareProductTypeConfig`.
Should be a pretty straightforward PR.
=> feat: handle fareProductTypeConfig onBehalfOfEnabled in app

e2e/test/pageobjects/myProfile.page.ts, e2e/test/pageobjects/notifications.page.ts, e2e/test/pageobjects/onboarding.page.ts, e2e/test/pageobjects/privacy.page.ts, e2e/test/specs/myProfile.e2e.ts, e2e/test/specs/onboarding.e2e.ts, e2e/test/texts/index.ts, e2e/test/utils/alert.helper.ts, e2e/test/utils/element.helper.ts, e2e/test/utils/utils.ts, src/components/sections/items/MessageSectionItem.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NotificationsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx
Added e2e-tests for
- the data collection (i.e. beacons/privacy page)
- notifications (default values + missing login/email)
Also removed a deprecated function from webdriverio.
**Note!** Added some test-ids for the privacy and notifications pages.
<details>
<summary>Privacy test</summary>
https://github.com/AtB-AS/mittatb-app/assets/5812433/a9f195e0-5402-4054-b908-4fcf6742cce9
</details>
=> test: e2e-myprofile tests

src/stacks-hierarchy/Root_ActiveTokenOnPhoneRequiredForFareProductScreen.tsx
When you have toggled to t:card and want to purchase for instance boat or youth ticket you have to toggle to phone. In order to do so we prompt the user to do it by showing a screen. If a user has increased the font size on their device they might not be able to currently read the whole info text or select the confirm "bytt til mobil" button. 
_Acceptance criteria_
_Before_ <img src="https://github.com/AtB-AS/mittatb-app/assets/126664682/f1292290-539d-4c0b-bbd7-fdf481c9175d" width="200" /> 👉🏼 👉🏼 👉🏼   _After_ <img src="https://github.com/AtB-AS/mittatb-app/assets/126664682/399aa349-1433-479e-b95b-459abc0759e1" width="200" />
Note: This shows the entire screen possible to scroll to, meaning scrolled all the way down. So the bottom text is cut and the button is not visible and clickable in …
=> fix: fixed scroll of ActiveTokenOnPhoneRequiredForFareProductScreen

src/fare-contracts/FareContractView.tsx, src/fare-contracts/ValidityHeader.tsx, src/fare-contracts/details/DetailsContent.tsx
It was using the valid from date, which doesn't work when
purchasing a ticket with a future start date.
Using the created date as the sent date.
Before/After (Notice the difference between "Sendt" and "Kjøpt" dates in the before picture)
<div>
</div>
=> fix: Presented sent date should show the created date

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProducts.tsx
closes https://github.com/AtB-AS/kundevendt/issues/17365
This PR will filter out empty fare product groups introduced by https://github.com/AtB-AS/firestore-configuration/pull/497.
For users without the ability to purchase HjemJobbHjem tickets, they won't have any products in that group, resulting in an empty group and weird display.
After this PR is merged, the empty product group should not be shown.
=> feat: filter empty fare product groups on ticket selection screen

src/on-behalf-of/index.ts, src/on-behalf-of/use-on-behalf-of-enabled.tsx, src/stacks-hierarchy/Root_ChooseTicketReceiverScreen/Root_ChooseTicketReceiverScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TicketHistorySelectionScreen.tsx
This is just a small PR to keep naming consistency, renaming `useOnBehalfOf` to `useOnBehalfOfEnabled`.
Also exporting and importing the `GetAccountByPhoneErrorCode` type through the `index.ts` file instead.
Closes https://github.com/AtB-AS/kundevendt/issues/15552
=> chore: rename useOnBehalfOf to useOnBehalfOfEnabled

src/components/icon-box/CounterIconBox.tsx, src/components/icon-box/TransportationIconBoxList.tsx, src/components/transportation-modes/TransportModes.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
- Updates logic for limit in TransportationIconBoxList to match sketches
- Makes sure that CounterIconBox uses the exact same styling as TransportationIcons, with font scale taken into consideration, except that the box is allowed to grow horizontally if the number is wider than it is tall.
- `textType` is added as a required param since there isn't a "correct" text type for a given size
- `spacing` as an optional param, to make it work in ResultItems.
<div>
</div>
closes https://github.com/AtB-AS/kundevendt/issues/17076
=> feat: update CouterIconBox styling and behavior

src/global-messages/types.ts, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
context: https://github.com/AtB-AS/kundevendt/issues/17075#issuecomment-2014785178
Straightforward PR, tried to add rule, but @gorandalum mentioned that it should be a different context. Suggestions to context naming are appreciated. :)
=> feat: add new global message component on purchase confirmation screen

src/translations/screens/Profile.ts
I've added a couple of org specific translations to have the correct org name in the notification settings. 
Fixes https://github.com/AtB-AS/kundevendt/issues/17505
=> fix: notification translations for OMS partners

src/components/icon-box/CounterIconBox.tsx, src/components/icon-box/TransportationIconBoxList.tsx, src/components/transportation-modes/TransportModes.tsx, src/translations/screens/FareContract.ts
ref. https://github.com/AtB-AS/kundevendt/issues/17076#issuecomment-2031962208
This changes how transportation icons are handled for screen reader. Instead of handling the case where some transport modes are hidden, we instead always read out every mode.
Also changes the text "Several travel modes" to "more"
=> fix: update transportation icon a11y labels

package.json, src/configuration/types.ts, src/fare-contracts/utils.ts, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ZonesSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-defaults.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTileIllustration.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProducts.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx, src/stacks-hierarchy/utils.ts, src/ticketing/api.ts, src/ticketing/use-get-fare-products-query.tsx, yarn.lock
closes https://github.com/AtB-AS/kundevendt/issues/17191
Changes in this PR: 
- Now uses product endpoint with fallback of firestore configuration to fetch the product list, used Tanstack react-query to call the endpoint.
- Re-introduced `offerEndpoint` setting in firestore.
- Added `City` image for HjemJobbHjem tickets.
- Updated dependencies for assets.
=> feat: enable hjemjobbhjem ticket purchase in app

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx
closes https://github.com/AtB-AS/kundevendt/issues/17206
Adds auth state check for on-behalf-of features, if not logged in, then don't show on-behalf-of
=> feat: disable on-behalf-of when anonymous

src/ticketing/firestore.ts
As of now only doing a superficial fix. When removing the
TravelRight.type logic this will be slightly cleaner.
Should then probably talk to platform team and create correct
raw-types in the app to use for the data from Firestore before
mapping.
=> fix: Support no start / end date on travel right

src/ticketing/utils.ts
closes https://github.com/AtB-AS/kundevendt/issues/17595
Don't show carnet consumption button on refunded/cancelled tickets, so basically only show it on a non-activated carnet ticket.
=> feat: only allow consumption on non-activated ticket for carnets.

src/api/types/generated/fragments/mobility-shared.ts, src/api/types/generated/readme
Update the SystemFragment type after merging https://github.com/AtB-AS/atb-bff/pull/330 in the BFF.
Also included a change to the type readme as it was a bit confusing that these files "are generated" and should "not be edited by hand", while you actually have to copy paste it in..
Resolves https://github.com/AtB-AS/kundevendt/issues/17614
=> chore: update SystemFragment type

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
adds missing check on https://github.com/AtB-AS/kundevendt/issues/17206#issuecomment-2045145986
While we're at it, should we add `isLoggedInWithPhone` inside `AuthContext.State` as well? Then we can use `{isLoggedInWithPhone}` directly from `useAuthState()` directly, or is it too specific to add that?
The result should look like this: 
```
...
...
const authenticationType = mapAuthenticationType(state.user); // added
const isLoggedInWithPhone = authenticationType === 'phone';  // added
return (
<AuthContext.Provider
value={{
...
signOut: useCallback(async () => {
await auth().signInAnonymously();
}, []),
authenticationType: authenticationType, // modified from mapAuthenticationType(state.user);
isLoggedInWithPhone: isLoggedInWithPhone, // added
...
}}
>
{children}
</AuthContext.Provider> …
```
=> feat: remove on-behalf-of for night ticket anonymous purchase

src/components/sections/Section.tsx, src/fare-contracts/FareContractView.tsx, src/fare-contracts/UnknownFareContract.tsx, src/fare-contracts/details/DetailsContent.tsx, src/fare-contracts/details/UnknownFareContractDetails.tsx, src/journey-date-picker/JourneyDatePickerScreenComponent.tsx, src/place-screen/components/DepartureTimeSheet.tsx, src/stacks-hierarchy/Root_AddEditFavoritePlaceScreen/Root_AddEditFavoritePlaceScreen.tsx, src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/JourneyHistory.tsx, src/stacks-hierarchy/Root_ReceiptScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_AppearanceScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DeleteProfileScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_EditProfileScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SelectStartScreenScreen.tsx, src/storybook/stories/Section.stories.tsx
closes https://github.com/AtB-AS/kundevendt/issues/15884
Removes `withPadding`, `withTopPadding`, `withBottomPadding`, and `withFullPadding` from `<Section>`, and replaces them with style.
Also adds some `prettier` auto-formatting, and replaces some style hooks with `const style = useStyles()` for consistency.
=> chore: remove withpadding parameters from <Section>

ios/atb/Info.plist
This PR resolves a login issue on the iOS app for Troms caused by an incorrect app ID. The current app ID is for the debug app and this PR replaces it with the staging app ID.
=> fix: correct Firebase ios app id for Troms

src/stacks-hierarchy/Root_AddEditFavoritePlaceScreen/Root_AddEditFavoritePlaceScreen.tsx
closes https://github.com/AtB-AS/kundevendt/issues/17633
before and after comparison:
=> fix: add missing rowgap on edit favourite location

src/translations/screens/subscreens/DepartureDetails.ts, src/translations/screens/subscreens/TripDetails.ts, src/travel-details-screens/DepartureDetailsScreenComponent.tsx, src/travel-details-screens/components/TripSection.tsx
This PR modifies the 'Live in Map' button text to include the transport mode name. The changes also ensure consistency between the Assistant and Departure screens.
<details>
</details>
Fixes https://github.com/AtB-AS/kundevendt/issues/17501
=> fix: update button text for bus live in map

src/global-messages/GlobalMessagesContext.tsx, src/global-messages/types.ts, src/stacks-hierarchy/Root_LoginConfirmCodeScreen.tsx, src/stacks-hierarchy/Root_LoginOptionsScreen.tsx, src/stacks-hierarchy/Root_LoginPhoneInputScreen.tsx
closes https://github.com/AtB-AS/kundevendt/issues/17783
Related documentation changes: https://github.com/AtB-AS/docs-private/pull/41
<div>
</div>
=> feat: add app-login and app-login-phone global message contexts

src/components/message-info-box/MessageInfoBox.tsx, src/global-messages/GlobalMessage.tsx, src/global-messages/converters.ts, src/global-messages/types.ts, src/translations/components/MessageBox.ts
closes https://github.com/AtB-AS/kundevendt/issues/2459
This PR will allow the screenreader to "read" global message links, and allows the global message to be activated to follow the URL to the specified link. For example, [this message in firestore](https://console.firebase.google.com/u/1/project/atb-mobility-platform-staging/firestore/databases/-default-/data/~2FglobalMessagesV2~2FMessage%20with%20scheduled%20timer).
~~When the screenreader is on, the action text that shows at the bottom (like the one in anonymous ticket purchase message), is hidden. Instead, the message text is replaced with the parsed text from the link markdown. This ensures that the message is read correctly by the screen reader and there are no redundant information being read aloud. The `onPressAction` will only …
=> feat: add action to global messages when there are links and screenreader is enabled

android/app/src/store/java/no/mittatb/ReactNativeFlipperInitializer.java
The name of the file where `ReactNativeFlipperInitializer` must be placed was changed, but the class was still referencing a wrong name, therefore not findable during compilation time for the store profile.
=> fix: Wrong class name on Android `ReactNativeFlipperInitializer`

src/components/sections/RadioGroupSection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByAlias.tsx
fixes https://github.com/AtB-AS/kundevendt/issues/17810
I didn't really find the root cause of why this started happening in the previous release, but it is due to how we compared objects, which is a flaky way to do it. With this change, we use FareProduct ID and the `keyExtractor` in RadioGroupSection to find the selected item.
=> fix: compare keys instead of objects for ProductSelection

src/travel-details-screens/__tests__/has_short_wait_time_and_not_guaranteed_correspondance.test.ts, src/travel-details-screens/components/Trip.tsx, src/travel-details-screens/utils.ts
Closes https://github.com/AtB-AS/kundevendt/issues/17624
A user has asked us a question regarding ambiguous messages. The messages at the top of the app say that correspondence cannot be guaranteed, while the message a little further down says that there is correspondence between 340 and 341 (picture 1). This is confusing. 
Remove the last sentence "Kan ikke garantere korrespondanse.", if the message box "Korrespondanse mellom 340 og 341 på Volda sjukehus" appears.   
<details>
<Summary>screenshots/video</Summary>
</details>
=> fix: avoid ambiguous messages about whether correspondence can or cannot be guaranteed

src/error-boundary/FullScreenErrorView.tsx
part of https://github.com/AtB-AS/kundevendt/issues/17839
On the announcement crash issue, the app doesn't show the usual crash screen. If we run the debug version of the app and trigger the crash, the issue shown would be `useAuthState must be used within a AuthContextProvider`, which is not the actual issue. 
After some investigation, it is because the `FullScreenErrorView` was calling the `ScreenHeader` component, which contains a `GlobalMessage` component. This `GlobalMessage` component reads `AuthState`, after it got updated recently on this issue https://github.com/AtB-AS/mittatb-app/issues/4456. Since the `ErrorBoundary` is the parent of `AuthContextProvider`, the app crashes due to `useAuthState` being called while the current context is the `ErrorBoundary`.
Therefore the solution …
=> fix: remove unnecessary ScreenHeader from FullScreenErrorView

src/announcements/converters.ts, src/announcements/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcement.tsx
closes https://github.com/AtB-AS/kundevendt/issues/17839
The destructuring of `actionButton` from firestore causes the app to crash when the values are invalid (in this case, `actionType`). This PR adds type-checking during the conversion to add handling of invalid data. With this PR, issues related to `actionType` in the announcements (for example, mistyping), will result in the announcement to not be shown to users.
I added the enum to provide a centralized place for typing, and to help reducing typo during development. In the future if we need another type of action (maybe Snackbar?), then we can just add them to the enum, create another button type or just add it to existing button type, and add correct handling on the `Announcement.tsx`.
Documentation is also updated on …
=> feat: add converter to set default values and prevent unwanted crash

src/ticketing/TicketingContext.tsx
This is done because of the error Nisha experiences, where the tokens from previous account is shown in the app even after logging out.
Log to Bugsnag on the `onError` callback when setting up Firestore.
Also removed some unused reducer actions/state regarding errors.
I'm not really sure how many errors this will give in Bugsnag, but
for now I think it is better to log too much than too little, and
we'll rather reduce it some later if necessary.
Shouldn't be any functional changes to test. The issue is sent through testing so that testers are aware of the new logging.
=> refactor: Add more logging to ticketing Firestore subscriptions

e2e/test/pageobjects/onboarding.page.ts, e2e/test/pageobjects/travelsearch.details.page.ts, e2e/test/pageobjects/travelsearch.filter.page.ts, e2e/test/pageobjects/travelsearch.overview.page.ts, e2e/test/specs/ticket.e2e.ts, e2e/test/specs/travelsearch.e2e.ts, e2e/test/specs/travelsearch.filter.e2e.ts, e2e/test/utils/app.helper.ts, e2e/test/utils/time.helper.ts, e2e/test/utils/utils.ts, src/components/icon-box/TransportationIconBox.tsx, src/journey-date-picker/JourneyDatePickerScreenComponent.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/NonTransitResults.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/SelectedFiltersButtons.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchFiltersBottomSheet.tsx
Added some e2e tests for travel search (in the `e2e/test/specs` folder):
- Should see walk and bike non-transit results
- Should be able to filter on departure time
- Should be able to filter on transport modes
- Should save filter options
- Should not save filter options
Also, added a test scenario after changing that on-behalf-of is only for logged-in users:
- Should not see on-behalf-of as anonymous
NOTE: Added some test-ids related to filter and date/time-picker + on-behalf-of toggle
=> test: e2e tests for travel search

src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/translations/screens/Profile.ts
Made while investigating https://github.com/AtB-AS/kundevendt/issues/17733
- Added message section item if there is no customer number, with action to retry auth.
- Added a red notification dot if there the message box is there, to make it more discoverable. 
- Retries are logged to posthog
ref. https://mittatb.slack.com/archives/CSFC6PG23/p1714987182087399
Not sure how easy this is to test, but
=> feat: add auth retry when there is no customer number

src/auth/AuthContext.tsx, src/auth/use-clear-queries-on-user-change.ts, src/index.tsx, src/mobile-token/hooks/useListRemoteTokensQuery.tsx, src/mobility/queries/use-fare-product-benefits-query.tsx, src/mobility/queries/use-user-benefits-query.tsx, src/mobility/queries/use-value-code-query.tsx, src/notifications/use-notification-config.tsx, src/queries/get-profile-query.ts, src/stacks-hierarchy/RootStack.tsx, src/ticketing/use-get-fare-products-query.tsx
Inspecting network requests we see that some requests are triggered more times than expected on user change, and some are also triggered before the user account is fully created, giving 401 responses.
The reason for this is that there are race conditions between the use-query hooks and the invalidate queries statement. Invalidating queries on user change was done in the RootStack, meaning that it happened after contexts had triggered based on user change, but before components had triggered based on user change.
This means that when the RootStack triggered invalidation of queries, existing queries was rerun for the old user, since the user isn't updated in the child-components yet. But it is injected with the new id-token in the axios client, which gives 401 since the request is for the …
=> refactor: Clear queries on user change

src/onboarding/OnboardingContext.tsx, src/stacks-hierarchy/RootStack.tsx
followup for issue in https://github.com/AtB-AS/kundevendt/issues/2269
If we use anonymous user, the `registerChatUser()` function doesn't get called, seems like the `userCreation` onboarding was not called for whatever reason :
```
loadedOnboardingSections.find(
(lOS) => lOS.onboardingSectionId === 'userCreation',
)?.isOnboarded
```
so the solution is just to create the chat user regardless of whether the onboarding is done or not, since we don't use any data from the user anyways. Here's the snippet of the `registerChatUser()` function: 
```
export async function register() {
await Intercom.loginUnidentifiedUser();
await Intercom.setBottomPadding(Platform.OS === 'ios' ? 40 : 80);
const installId = await storage.get('install_id');
const buildNumber = DeviceInfo.getBuildNumber();
const …
```
=> fix: init intercom user creation regardless of login status

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/NonTransitResults.tsx
Change testId for rental bike suggestions in the travel search. To distinguish between `rentalResult` and `bicycleResult`. In addition we have `footResult`. Easier to hit the correct testId.
=> test: test-id for rental bikes in travel search

ios/Podfile, ios/Podfile.lock
Fix the issue we got from Apple:
> ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/MapboxCommon.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.
=> fix: Apple privacy manifest error MapBox

src/loading-screen/__tests__/use-loading-state.test.ts, src/loading-screen/use-loading-state.ts
Found after investingating https://github.com/AtB-AS/mittatb-app/pull/4476#issuecomment-2100058427
The reason for the multiple calls to the lookup endpoint was that the user id was changed, while the loading boundary hadn't kicked in yet and the old tickets where still rendered. This means that every rendered ticket would be considered sent-to-others since customer id on ticket wasn't the same as the user id from Auth, which made the app try to look up the phone numbers.
The issue could be observed by logging user id and loading state in the `LoadingScreenBoundary`.
Added:
```ts
useEffect(() => {
console.log(userId, status);
}, [userId, status]);
```
Logs on user change:
```
LOG  x2ZdOrOXdgMg2OQv27bJ8K6xPmz1 success <-- Old user
LOG  gZoYiLYEBjccfHOHPny4s0ZBsJp1 success <-- User change, …
```
=> fix: Loading boundary based on derived state

src/stacks-hierarchy/Root_ParkingViolationsReporting/components/ProviderLogo.tsx
Fixes some bad contrast in light mode. ([Previously it looked like this](https://mittatb.slack.com/archives/C0116FMPX4Y/p1715598607170289?thread_ts=1715346138.109749&cid=C0116FMPX4Y))
=> fix: use correct text color on UnknownProvider icon

src/auth/AuthContext.tsx, src/auth/use-fetch-id-token-with-custom-claims.ts, src/auth/use-subscribe-to-auth-user-change.ts
closes https://github.com/AtB-AS/kundevendt/issues/17734
Adds some breadcrumbs for clearer logging of bugsnag errors. Right now we only have these logs on `Loading boundary timeout` issue, which aren't very helpful:
We are adding some more breadcrumbs to see when the actual fetching of id token happens, so we can check during which process the timeout occurs.
=> chore: add breadcrumbs to fetching firebase ID token process

src/translations/screens/Profile.ts
OMS would like to use "Tillet" instead of "Løyve" in the notification so that the bokmål and nynorsk translations are more similar. 
Currently, FRAM is the only OMS partner having nynorsk in the app so this change will only affect FRAM. 
Closes https://github.com/AtB-AS/kundevendt/issues/18048
=> fix: use tillet nn translation instead of loyve

src/loading-screen/__tests__/use-notify-bugsnag-on-timeout-status.test.ts, src/loading-screen/use-notify-bugsnag-on-timeout-status.ts, src/mobile-token/MobileTokenContext.tsx, src/mobile-token/hooks/useGetSignedTokenQuery.tsx, src/stacks-hierarchy/Root_PurchasePaymentScreen/WebViewTerminal.tsx, src/utils/bugsnag-utils.ts
closes https://github.com/AtB-AS/kundevendt/issues/5352
This PR will try to improve the error grouping in Bugsnag dashboard.
Currently, if we open an error in the Bugsnag dashboard, it will show the screen below (example):
We can see that while the error name is the same: `MainActivity`, the list of error shows that it can originate from different source, in this case we have both `network error` and `token loading timeout` in the same error category.
Check these links for more examples:
- https://app.bugsnag.com/atb-as/mittatb/errors/6615013360afa8000813aa21
- https://app.bugsnag.com/atb-as/mittatb/errors/6269b17a4d18f800088b523a
- https://app.bugsnag.com/atb-as/mittatb/errors/657bef1e901ded000850a86f 
We can also see that the list of error types in main `Inbox` page have lots of similar …
=> feat: add error grouping hash to bugsnag reporting

package.json, yarn.lock
This updates the @atb-as/theme package to 8.2.1 that includes the new Svipper-colors 🎉 
Part of closing https://github.com/AtB-AS/kundevendt/issues/8280
=> chore: upgrade atb-as/theme package

src/translations/screens/subscreens/TicketTraveller.ts
"Bike" was added as an extension when it should not have been. Removed it and set it to blank, similar to how it's done for both NFK and FRAM.
Closes https://github.com/AtB-AS/kundevendt/issues/18093
=> fix(troms): remove "Bike" from traveller extensions

src/fare-contracts/FareContractView.tsx, src/fare-contracts/components/ActivateNowBottomSheet.tsx, src/fare-contracts/components/ActivateNowSectionItem.tsx, src/fare-contracts/details/DetailsContent.tsx, src/fare-contracts/use-is-activate-now-enabled.tsx, src/remote-config.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/storage/StorageModel.tsx, src/ticketing/api.ts, src/ticketing/utils.ts, src/translations/screens/FareContract.ts
Mostly copied over code from carnet activation, but with different texts and making the API call to `ticket/v4/start-time`. 
I send no start time to the back end, so that we don't have to trust the client clock. Default seems to be that it starts immediately. (If that's an ok solution, @adriawh?)
https://github.com/AtB-AS/mittatb-app/assets/1774972/6295f59a-2eb8-4f56-95ab-1ab4b47465df
closes https://github.com/AtB-AS/kundevendt/issues/16878
=> feat: add activate now button to fare contracts

src/auth/AuthContext.tsx, src/auth/use-fetch-id-token-with-custom-claims.ts
Clearing queries on user change was introduced on master branch,
while using react-query for id token fetch was introduced on
release branch. When these two merged, the clearing of queries
happened after id token fetch, which led to errors.
=> fix: Clear queries before id token fetch

src/GeolocationContext.tsx, src/auth/use-subscribe-to-auth-user-change.ts, src/mobile-token/MobileTokenContext.tsx, src/mobile-token/hooks/use-load-native-token-query.tsx, src/stacks-hierarchy/RootStack.tsx
fixes the crash that happens on OMS-partners regarding Intercom.
closes https://github.com/AtB-AS/kundevendt/issues/2939 as well.
This PR wraps every Intercom-related call with a check to ensure that Intercom is enabled on remote config, to prevent it from getting called when the config is false.
=> fix: don't call intercom methods when remote config flag is false

src/index.tsx
related to https://github.com/AtB-AS/mittatb-app/pull/4515
fixes the crash issue reported on Slack https://mittatb.slack.com/archives/C025NUF4WA0/p1715858438465089?thread_ts=1715712822.965299&cid=C025NUF4WA0
During auth, we call remote config to check the ´enable_intercom´ flag, since we want to update the Intercom user during auth. Therefore we need to swap the context to allow calling remote config inside auth context.
=> fix: fix crash due to wrong context pyramid

src/loading-screen/__tests__/use-loading-state.test.ts, src/loading-screen/types.ts, src/loading-screen/use-loading-state.ts
This is done both on user change, and on status being set to
success. The error was that the timeout state wasn't reset on user
change, which made the loading for the new user go immediately to
timeout state.
=> fix: Reset is timeout state on loading status change

src/chat/user.ts
closes https://github.com/AtB-AS/kundevendt/issues/18085
Catches the failed registration issue and discards it so it doesn't get sent to bugsnag. The issue will still show in the log, but at least it is not sent to Bugsnag.
Old PR for reference : https://github.com/AtB-AS/mittatb-app/pull/4513
=> fix: catch intercom registration issue

src/remote-config.ts
Fixes the crash on OMS partners.
followup to https://github.com/AtB-AS/kundevendt/issues/2939 and PR https://github.com/AtB-AS/mittatb-app/pull/4515
The problem here is the Intercom code is called before the remote-config for intercom is fetched, because the default is `true`, the call will fail because Intercom is not initialized. 
In this PR, I changed the default to false, and then tested on both FRAM (without the intercom API keys), and AtB (with intercom API keys, and testing Intercom interface), everything works on debug, but will test in staging to confirm.
=> fix: defaults intercom remote-config to false

src/translations/screens/FareContract.ts
Refactor to use the word "QR code" instead of "Barcode" since the norwegian translation used is not a valid term. Additionally, "QR code" has become a well-known term widely used, and currently a QR code is shown in the app. Aztec codes might be used in the future, which is in fact a barcode, but the common user might not see the difference.
Fixes https://github.com/AtB-AS/kundevendt/issues/18061
=> fix: use "QR code" instead of "Barcode"

src/translations/screens/Profile.ts, src/translations/screens/subscreens/PurchaseConfirmation.ts, src/translations/screens/subscreens/PurchaseOverview.ts, src/translations/screens/subscreens/UserProfileSettingsTexts.ts
I am creating this PR on behalf of @tft-kaare (currently out of office) because Troms has requested these changes with the new RC that we are making today.
This PR only updates the texts for Troms. Ideally, we should standardize the texts for all OMS partners. However, because the release deadline is so close, we don't have time to find texts and verify that it works for everyone right now.
Part of closing https://github.com/AtB-AS/kundevendt/issues/8280
=> feat: custom translations for Troms

e2e/test/specs/travelsearch.e2e.ts, e2e/test/utils/time.helper.ts
When assessing travel times for bike and foot, there are sometimes small variations in minutes. Added a check that accepts small variations in minutes.
Note! Want to have a check that takes an expected value to not succeed on large variations to the expected one.
=> test: accept travel time variations

src/components/label-info/LabelInfo.tsx, src/components/sections/items/ExpandableSectionItem.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx
part of https://github.com/AtB-AS/kundevendt/issues/18132
Contents of this PR:
- Add the "label" property to `ExpandableSectionItem`.
- Add "new"/"ny" label to Flex discount section.
- ~~Update the color of both "new"/"ny" and "beta" badge. See below for comparison. [Figma component](https://www.figma.com/design/2QTjAdekdIPuLFovQhVrY3/Components?node-id=8344-45773&t=XZMNfCJIx11Rs0LM-4)~~
Color change is reverted and will be done on separate PR.
Added badge:
=> feat: update badge color and add badge to flex discount section

src/translations/components/TravelTokenBox.ts
Added translations for the error messages when there is an issue with the token tochange the reference from "t:card" to "travel card".
These errors should in theory not be shown when `disable_travelcard` is set to `true`, so for Troms it shouldn't be shown unless there's e.g. an issue with the token server.
https://github.com/AtB-AS/kundevendt/issues/18118
=> fix: add missing translation when no token for troms

src/ticketing/utils.ts
Since the back end now supports consume of carnets with more than one travel right, we can remove the check!
=> feat: remove check for several carnets to show consume button

src/fare-contracts/components/FareContractStatusSymbol.tsx
Noticed that none of the icons in FareContractStatusSymbol should have `size="large"`, according to [figma](https://www.figma.com/design/2QTjAdekdIPuLFovQhVrY3/Components?node-id=7415-26269) 🤓
=> fix: use correct icon size in FareContractStatusSymbol

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
part of https://github.com/AtB-AS/kundevendt/issues/18132
in this PR: 
- Update the original price display style.
- Update the ticket name display.
There are some style discrepancies between the design on the Figma link below and other ticket design. For example, passenger font style on the design for flexible ticket is `body--primary`, but the other text - and on the app - is still using `body--secondary`, based on what @hannahATB said, we should still follow the existing styles. 
[Figma link](https://www.figma.com/design/zdZwvobgpEWSagKt0tderx/App?node-id=26058-20433&t=Y2xIKRVKWdo4xIuD-4)
<details>
<summary>Reference screen</summary>
</details>
<details>
<summary>Old-New comparison</summary>
</details>
=> feat: update purchase confirmation screen

src/loading-screen/LoadingScreen.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/9189
From @Reis-Nordland :
The contrast colour of the spinner on the loading screen is to weak and not visible enough. This is the case especially on android. 
Not critical, but it would have been nice to have it fixed.
<details>
<summary>screenshots/light_mode</summary>
|   Light mode               |  Old  |  New |
|:---------:| :--------: | :-------: |
| FRAM    | ![Image](https://github.com/AtB-AS/kundevendt/assets/59939294/1f9b5a3d-ed96-4d40-a8b8-c1c891480c48) | ![fram_new_spinner_light](https://github.com/AtB-AS/mittatb-app/assets/59939294/48f873ab-0e21-4aa6-aaf7-47947fb65986)| 
| NFK       | ![Image](https://github.com/AtB-AS/kundevendt/assets/59939294/6168f7f0-dfa6-4717-86e5-1f1cb75c5945) | …
=> fix: update colour loading spinner

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
This allows the user to click reload and access the rest of the profile page, while ID token is loading
=> feat: use non-blocking ActivityIndicator when fetching id token

.storybook/storybook.requires.js, src/components/snackbar/Snackbar.tsx, src/components/snackbar/index.ts, src/components/snackbar/use-snackbar-vertical-position-animation.ts, src/storybook/stories/Snackbar.stories.tsx
Resolves https://github.com/AtB-AS/kundevendt/issues/17411
Two things in this PR:
- Add Snackbar to Storybook
- Fix a Snackbar padding issue https://github.com/AtB-AS/mittatb-app/pull/4549/commits/6998e87ebb94d645743e698b57eb5a83f9a633a9
What it looks like in Storybook:
<table>
<tr>
<td><img width="200" src="https://github.com/AtB-AS/mittatb-app/assets/134292729/9fcec1d5-1cb4-4edf-bbf7-fb1ee39f5ba5" /></td>
<td><img width="200" src="https://github.com/AtB-AS/mittatb-app/assets/134292729/167d23b3-fd0c-4ee7-b916-e40aaaf86d63" /></td>
<td><img width="200" src="https://github.com/AtB-AS/mittatb-app/assets/134292729/c7766006-a8c1-40ac-a967-1927c55e2769" /></td>
<td><img width="200" src="https://github.com/AtB-AS/mittatb-app/assets/134292729/70a9c8b9-68ab-4ca7-849e-b587b875a36c" /></td>
</tr> …
=> feat: Add snackbar to storybook

src/auth/use-is-backend-sms-auth-enabled.tsx, src/remote-config.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/storage/StorageModel.tsx
part of https://github.com/AtB-AS/kundevendt/issues/18127
Adds a feature flag for the new SMS auth through our backend (it uses Twilio - https://github.com/AtB-AS/team-platform/issues/599). Also added the debug menu to override remote config setting.
If the flag is:
- **true**: use the new SMS auth through our back-end.
- **false**: use the default SMS auth flow using Firebase.
=> feat: new feature flag for backend sms auth

src/mobile-token/MobileTokenContext.tsx
Even if the mobile token handling is never started because of the
user not getting auth status 'authenticated', the mobile token
timeout handler should still run. This means that the user will get
fallback after the timeout, even if there is something wrong with
the id token.
Also reset isTimeout value to false when mobile token no longer in
loading state.
=> feat: Token timeout even if not enabled

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Summary.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts, src/ticketing/api.ts, src/translations/screens/subscreens/PurchaseOverview.ts
closes https://github.com/AtB-AS/kundevendt/issues/18132
handles the latest change from back-end from https://github.com/AtB-AS/team-platform/issues/610.
In this PR : 
- Adds `is_on_behalf_of` parameter to "Offer search" endpoint.
- Fix discount layout not showing on combined ticket (e.g. Adult + Senior ticket purchase).
- Fix discount layout not showing 0% discount on first purchase.
=> feat: implement flex ticket

src/auth/AuthContext.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
The retry button now resubscribes to Firestore auth, no matter what
auth status it has.
=> feat: Retry button on profile page resets auth

src/components/activity-indicator-overlay/ActivityIndicatorOverlay.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/9189
After updating the colour of the spinner in the <LoadingScreen/> in the PR: https://github.com/AtB-AS/mittatb-app/pull/4545 , the colours in the spinners in the <LoadingScreen/> and the <ActivityIndicatorOverlay/> components became different. This PR fixes this, by updating the colour of the spinner in the <ActivityIndicatorOverlay/> component, ensuring that the same colour is being used in both spinners.  
AtB on android emulator.
<details>
<summary>screenshots/light_mode</summary>
|   Light mode               |  Old  |  New |
|:---------:| :--------: | :-------: |
| ATB | ![atb_spinner_lightmode1](https://github.com/AtB-AS/mittatb-app/assets/59939294/897ad944-996c-458b-9f25-1838a9bf92e2) | …
=> fix: update the colour of the spinner in the activity_indicator_overlay component

src/remote-config.ts
reference : https://github.com/AtB-AS/kundevendt/issues/18132#issuecomment-2147412737
slack thread: https://mittatb.slack.com/archives/C074CKTCFQW/p1717493402857439
Frontend doesn't use the remote config flag, since we distinguish the status of flexible ticket based on the response we get from the back-end. If we get `flex_discount_ladder` on the offer response, then the flexible ticket is active, otherwise, it is disabled. 
This flag is therefore useless, since Backend didn't use it either.
=> chore: remove unused `enable_flex_ticket` remote config flag

docs/Release.md
Added instruction for missing jq command, which will cause the following error when running the script:
=> chore: update release document about bump version

src/notifications/use-has-fare-contract-with-activated-notification.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/CompactFareContracts.tsx, src/ticketing/index.ts, src/ticketing/use-valid-right-now-fare-contracts.tsx
While working on https://github.com/AtB-AS/kundevendt/issues/15528, I noticed that `filterValidRightNowFareContracts` is called a lot (especially on startup) and since there is a lot of filtering/mapping on all fare contacts from ticketing state, I thought it was worth memoing it.
=> perf: use memo on useValidRightNowFareContract

src/mobility/api/api.ts
The error should be returned now that it is handled by the OperatorActionButtonWithValueCode component.
Fixes https://github.com/AtB-AS/mittatb-app/pull/4569#issuecomment-2158279620
=> fix: Return error onError in getValueCode

src/api/types/generated/fragments/stations.ts, src/api/types/generated/mobility-types_v2.ts
Update generated mobility types.
Includes the new `polylineEncodedMultiPolygon` on `GeofencingZoneProperties`.
Resolves https://github.com/AtB-AS/kundevendt/issues/17614
=> feat: Update mobility types

package.json, src/components/map/index.ts, src/components/map/types.ts, src/translations/screens/subscreens/MobilityTexts.ts, yarn.lock
As can be read in the [new docs](https://github.com/AtB-AS/docs-private/pull/53), there are 4 types of geofencingZone features: `Allowed`, `Slow`, `NoParking` and `NoEntry`.
This adds an explanation for each of them.
Also explanations are added for `Unspecified`, for the case when a user presses on a location without a feature.
`GeofencingZoneExtraExplanations` is an extra explanation that is added if `isStation` is set to `true` for that feature. (The rule for `isStation` is also described in the docs).
<table>
<tr>
<td><img width="200" src="https://github.com/AtB-AS/mittatb-app/assets/134292729/393fcef4-d70e-4364-b7f5-6b6ecbf42a60" /></td>
<td><img width="200" src="https://github.com/AtB-AS/mittatb-app/assets/134292729/e4566527-3272-47ae-a783-15f13f493926" /></td>
<td><img width="200" …
=> feat: geofencing zone explanations

src/api/mobility.ts, src/api/types/generated/GeofencingZonesQuery.ts, src/mobility/queries/use-geofencing-zones.tsx
Create hook `useGeofencingZonesQuery`, using `getGeofencingZones` and `GetGeofencingZonesQuery`.
This hook returns the geofencing zones data using the bff endpoint.
This is the first of a series of PRs on the way to support geofencing zones. You can take a look at https://github.com/AtB-AS/mittatb-app/pull/4572/files if you want to see how it is used.
Resolves https://github.com/AtB-AS/kundevendt/issues/17614
=> feat: get and use geofencing zones

src/components/map/components/mobility/Bicycles.tsx, src/components/map/components/mobility/BikeStations.tsx, src/components/map/components/mobility/CarStations.tsx, src/components/map/components/mobility/Scooters.tsx, src/components/map/index.ts, src/components/map/utils.ts, src/tariff-zones-selector/TariffZonesSelectorMap.tsx
Default hitbox is 44x44 pixels for `ShapeSource`. Sometimes this causes them to capture onPress events even when pressing on the side of the icon.
Using 1x1 still captures the event when the icon is pressed, but not when pressing on the side of it.
Resolves https://github.com/AtB-AS/kundevendt/issues/17614
=> feat: Set hitboxCoveringIconOnly on ShapeSources

src/translations/components/PhoneInput.ts, src/translations/screens/Profile.ts, src/translations/screens/subscreens/TravelToken.ts
Our marketing team insist on the use of 'telefon' in norwegian instead of 'mobil'.
=> feat: Use 'telefon' instead of 'mobil' in Svipper/Troms

src/fare-contracts/PurchaseReservation.tsx, src/ticket-history/TicketHistoryScreenComponent.tsx, src/ticketing/types.ts
closes https://github.com/AtB-AS/kundevendt/issues/17689
This PR will fix rejected reservations showing on both `Expired Tickets` and `Tickets sent to others`, by filtering the reservations based on the `customerAccountId`. Since we are removing the filtering of sent-to-other reservations, I also added filtering for subaccount purchases, so reservations for subaccount shouldn't be shown on the list.
=> fix: rejected reservations show on the correct screen

src/translations/screens/Profile.ts
I've added a new `orgSpecificTranslations` for a translation that made the app refer to AtB instead of Reis Nordland/FRAM/Svipper. Also changed "Reisnordland" to "Reis Nordland". 
Fixes https://github.com/AtB-AS/kundevendt/issues/18428
=> fix: oms profile translations referring to atb

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentOptionsScreen.tsx, src/stacks-hierarchy/saved-payment-utils.ts, src/ticketing/api.ts, src/ticketing/use-authorize-recurring-payment-mutation.tsx, src/ticketing/use-cancel-recurring-payment-mutation.tsx, src/ticketing/use-delete-recurring-payment-mutation.tsx, src/ticketing/use-list-recurring-payments-query.tsx
closes https://github.com/AtB-AS/kundevendt/issues/17817
old PR for reference : https://github.com/AtB-AS/mittatb-app/pull/4564
On this PR:
- Refactor calling payment cards API to `useQuery` and `useMutation`.
- Call API to check when getting saved card, to check if the saved card is still available on API or not.
=> feat: get saved card data from remote during payment confirmation

src/components/map/Map.tsx, src/components/map/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_RootScreen.tsx
https://mittatb.slack.com/archives/C02EEG7D8EL/p1718869819941549
Quick fix for when the `Snackbar` container is not at the top.
For the future, the `Snackbar` should probably be put inside a ContextProvider just like `BottomSheet` is in `BottomSheetProvider` instead.
=> fix: Add includeSnackbar prop to Map

src/components/map/Map.tsx
https://mittatb.slack.com/archives/C02EEG7D8EL/p1718886090430569?thread_ts=1718869819.941549&cid=C02EEG7D8EL
After the geofencing zones were added, the new on map click logic wasn't compatible with the map location selection mode.
Now the new logic is only applied when showing geofencingZones.
Two changes:
The fix: https://github.com/AtB-AS/mittatb-app/pull/4598/commits/50ac28f80f55cc231f2a06c6b9d8d31453aa739e
Wrapped `onFeatureClick` in a `useCallback`: https://github.com/AtB-AS/mittatb-app/pull/4598/commits/a9f1c9b100d26a08618c81bc67080c5c288437b5
=> fix: map location on press fix

src/fare-contracts/utils.ts, src/notifications/use-has-fare-contract-with-activated-notification.tsx, src/ticketing/TicketingContext.tsx, src/ticketing/__tests__/fixtures/skoleskyss-travelright.ts, src/ticketing/__tests__/travelrights.test.ts, src/ticketing/types.ts, src/ticketing/utils.ts
- Fixes a bug in `isNormalTravelRight` that doesn't catch `startDateTime: undefined`
- Filters out fare contracts that doesn't have any "normal" travel rights. This was needed to make some "firstTravelRight" logic work which assumes every fare contract has a travel right.
- Adds a test for a skoleskyss travelright.
fixes https://github.com/AtB-AS/kundevendt/issues/15528#issuecomment-2176504199
=> fix: make skoleskyss not resolve to NormalTravelRight

src/auth/use-fetch-id-token-with-custom-claims.ts, src/mobile-token/hooks/use-list-remote-tokens-query.tsx
Mainly some more logging in the fetch id token flow, and changed
the notify Bugsnag event to always be the same message, and the
actual error message is set in the description.
Also added Bugsnag breadcrumb when listing tokens for a user.
=> refactor: Add more logging to auth and mobile token requests

src/ticketing/TicketingContext.tsx
reference: https://mittatb.slack.com/archives/C0116FMPX4Y/p1718956797385489?thread_ts=1718794154.952519&cid=C0116FMPX4Y
This will fix a bug where successful sent-to-others reservation showing incorrectly on the "My Tickets" page. 
Repro steps on buggy version: 
1. successfully purchase a sent-to-others ticket
2. buy another sent-to-others ticket, but hold off the payment (easiest to test using vipps)
3. go back to the my ticket screen
4. the reservation of the pending payment (on step 2) and successful purchase (on step 1), is now shown on my ticket screen.
=> fix: filter out successful reservations for sent to other tickets.

src/ticket-history/TicketHistoryScreenComponent.tsx
closes https://github.com/AtB-AS/kundevendt/issues/18129
In this PR, Rejected reservation and Ongoing/pending reservation will be shown on sent-to-others ticket history screen.
Discussed with @Aliaaen and he said that both reservation (rejected & ongoing) status should show on both screens.
=> feat: show reservation buy-for-others

src/ticket-history/TicketHistoryScreenComponent.tsx
ref: https://github.com/AtB-AS/kundevendt/issues/18129#issuecomment-2185844922
only show `rejectedReservation` on `Utløpte billetter`
=> fix: only show rejected reservation on expired ticket

src/onboarding/onboarding-config.ts
closes: https://github.com/AtB-AS/kundevendt/issues/18445
Attempt fix the mobile token onboarding that appears after logout. I added the `authenticationType === 'phone` to `shouldShowPredicate` function, so that the onboarding will only show for authenticated users.
=> fix: mobile token onboarding will only show on authenticated users

src/mobile-token/abtClientLogger.ts, src/mobile-token/mobileTokenClient.ts, src/time/TimeContext.tsx
Related to: https://github.com/AtB-AS/kundevendt/issues/18509
TimeContextProvider requires AbtClient to be initialized, this fix import some configurations as well initializes the AbtClient.
=> fix: Wrong state for Abt Entur SDK when initializing timer

src/fare-contracts/details/OrderDetails.tsx
additional fix for https://github.com/AtB-AS/kundevendt/issues/17139
ref comment : https://github.com/AtB-AS/kundevendt/issues/17139#issuecomment-2188764253
- Removes the price text on refunded tickets.
- Removes the payment method text on refunded tickets.
- Switches the position of the price and payment method on the detail screen.
=> feat: hide payment method and price on refunded tickets

src/api/types/generated/TripsQuery.ts, src/translations/screens/subscreens/TripDetails.ts, src/travel-details-screens/components/TripSection.tsx
Fixes https://github.com/AtB-AS/kundevendt/issues/18410
Example of it is shown with interchange:
Related change in BFF: https://github.com/AtB-AS/atb-bff/pull/337
Release of BFF is required to show maximum wait time, but it is backwards compatible.
=> feat: show maximum interchange time in trip details if data is provided

docs/Release.md, scripts/update-app-version.sh
Adds a script to bump version numbers in .env and package.json files, so we don't have to do it manually for every release 🥳
=> build: add update-app-version script

src/api/geocoder.ts
closes https://github.com/AtB-AS/kundevendt/issues/16260
Shows the multimodal stop place properly when searching, instead of showing a separate stop place.
=> feat: show multimodal stop places in location search

src/stacks-hierarchy/Root_LoginConfirmCodeScreen.tsx, src/stacks-hierarchy/Root_LoginPhoneInputScreen.tsx, src/translations/components/PhoneInput.ts
When the app receives a 429 error (too_many_attempts) from the identity service, buttons to retry requests to /identity are disabled for 10 seconds. The error message "You have tried too many times. Please wait a bit before trying again." is shown as before.
This is just a suggestion for how to add some sort of limit on the amount of times the user can spam the submit buttons, so open for alternative solutions. But I think this is an ok solution because:
- It doesn't affect regular use (no 10s delay unless you're already rate limited by identity/Twilio)
- The logic in the app is simple, and easy to reason about. More complex logic should probably be on the backend.
closes https://github.com/AtB-AS/kundevendt/issues/18555
=> feat: prevent login retires for 10s after too many attempts

src/translations/screens/subscreens/PurchaseOverview.ts
After discussions with market, we want to keep some of the terminology from the reverted changes on flexible ticket.
closes https://github.com/AtB-AS/kundevendt/issues/18590
=> feat: update flexible ticket translations

src/situations/SituationBottomSheet.tsx, src/translations/components/SituationsTexts.ts
Adds a header to SituationBottomSheet based on the severity of the message. "Information", "Warning" or "Error".
<div>
</div>
=> feat: add header text to SituationBottomSheet

package.json, yarn.lock
Update the packages  `@atb-as/theme` and `@atb-as/generate-assets` to get the new colors for NFK (https://github.com/AtB-AS/design-system/pull/183) and the updated colors for FRAM (https://github.com/AtB-AS/design-system/pull/188).
https://github.com/AtB-AS/kundevendt/issues/18557
https://github.com/AtB-AS/kundevendt/issues/18558
=> chore: update to latest packages for new NFK colors and FRAM color update

ios/departureWidget/DepartureWidget.swift, ios/departureWidget/Views/DepartureTimesView.swift, ios/departureWidget/Views/NoFavoriteViewMedium.swift, ios/departureWidget/Views/NoFavoriteViewSmall.swift, ios/departureWidget/Views/WidgetInfoView.swift
This was caused by not using the containerBackground API (introduced in iOS 17.0), and instead relying on padding inside DepartureTimesView.
See https://developer.apple.com/documentation/widgetkit/preparing-widgets-for-additional-contexts-and-appearances
fixes https://github.com/AtB-AS/kundevendt/issues/18640
=> fix: remove unwanted widget padding for iOS 17 and above

src/travel-details-screens/TripDetailsScreenComponent.tsx
This PR extends the travel search to ticketing functionality by including single ticket boat for boat trips. Similar to bus ticket suggestions, the boat ticket option will be displayed only if the entire journey is composed exclusively of boat legs and there are no significant wait times between legs.
Closes https://github.com/AtB-AS/kundevendt/issues/18556
=> feat: extend travel search to ticketing functionality to include single ticket boat

src/components/message-info-box/MessageInfoBox.tsx, src/translations/components/MessageBox.ts
Adds simple prefix message to a11y hint. Will be present at all times even if icon is not visible, as all non visually impaired people will get this indication by colour.
Note for future: I see that there isn't any live region or automatic reading of messages here. These components typically have some assertive/polite reading to them to make sure people with screen readers notice them. Should test and investigate the consequences of introducing this now.
Note: I don't have phone connected and can't test actual screen reader now only debug inspection. So would be nice to have this actually tested on device.
Fixes https://github.com/AtB-AS/kundevendt/issues/18138
=> fix: adds a11y prefix hint for message box criticality

src/travel-details-screens/components/TripSection.tsx
@hanne-at-atb noticed that the decoration line for the interchange section is not correct. I've added a margin to the bottom to fix this. 
<details>
</details>
Fixes https://github.com/AtB-AS/kundevendt/issues/18410#issuecomment-2257857959
=> fix: decoration line for the interchange section

src/remote-config.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/storage/StorageModel.tsx, src/travel-details-screens/TripDetailsScreenComponent.tsx, src/travel-details-screens/use_from_travel_search_to_ticket_enabled.ts
Adds feature toggle `enable_from_trip_details_to_ticket_boat` that defaults to `false`. This will enable/disable the button to buy tickets in trip details for express boats.
Fixes issue after feedback in https://github.com/AtB-AS/kundevendt/issues/18556 by @hanne-at-atb
=> feat: adds feature toggle for boat ticket from trip details

src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/Root_ChooseTicketRecipientScreen.tsx, src/translations/components/PhoneInput.ts, src/translations/screens/subscreens/OnBehalfOf.ts
Figma sketch:  
Before / After in app (without the save recipient checkbox yet)
<div>
</div>
=> feat: Update buy-for-other screen according to Figma

src/components/sections/RadioGroupSection.tsx, src/components/sections/index.ts, src/components/sections/items/RadioSectionItem.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx, src/storybook/stories/Section.stories.tsx
The new sketches for saving recipient has a radio section group with the standard radio selection circle instead of using checkmarks as we did before. 
To not have two different radio groups in the app I took the liberty to just rewrite the existing one, making every radio button group use the new design.
Originally this was done as part of https://github.com/AtB-AS/kundevendt/issues/17226, but I added the PR to the board as an individual issue so it can be tested on its own.
<details>
<summary>Screenshots of the change</summary>
**Figma**:
<div>
</div>
**Some before/after examples from the app**:
<div>
</div>
<div>
</div>
<div>
</div>
<div>
</div>
</details>
The places in the app where we have used the `RadioGroupSection`. Should be enough to test just some of them.
- Single traveller …
=> feat: Consolidate radio button group

src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/Root_ChooseTicketRecipientScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/navigation-types.ts, src/stacks-hierarchy/Root_PurchasePaymentScreen/Root_PurchasePaymentScreen.tsx, src/stacks-hierarchy/Root_PurchasePaymentScreen/use-reserve-offer-mutation.ts, src/stacks-hierarchy/navigation-types.ts, src/ticketing/api.ts, src/ticketing/types.ts, src/translations/screens/subscreens/OnBehalfOf.ts
Added a checkbox and text input for saving recipient name in the on
behalf of purchase process. The recipient name is sent to the
backend when reserving the offer.
Figma sketches:
Screenshots from app:
<div>
</div>
=> feat: Save recipient name

android/app/src/main/AndroidManifest.xml
Closes: https://github.com/AtB-AS/kundevendt/issues/18747
During pushing the app to the play store, we got:
`Google Api Error: Invalid request - You must let us know whether your app uses any Foreground Service permissions.`
The solution is removed some permissions as Kogenta team pointed.
```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" tools:node="remove"/>
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" tools:node="remove"/>
```
=> fix: Update Android play console error

src/travel-details-screens/TripDetailsScreenComponent.tsx
Fixes issue reported in https://mittatb.slack.com/archives/C0116FMPX4Y/p1723289908783909
Can cherry-pick to `release/1.54` afterwards
Verified to be working for non-transit like walking, bike. Also routes without boat/bus (e.g. only train)
=> fix: issue with non-transit legs trying to show ticket info

__tests__/utils.test.ts, src/travel-details-screens/components/Time.tsx, src/travel-details-screens/use-realtime-text.ts, src/utils/date.ts
After [the upgrade of date-fns](https://github.com/AtB-AS/mittatb-app/pull/4638), a bug in roundToNearestMinutes was fixed, allowing us to use it instead of rolling our own.
The existing tests on formatToClock, that failed with the old version of date-fns, now passes!
=> refactor: replace custom rounding of minutes with date-fns

e2e/test/pageobjects/travelsearch.overview.page.ts, e2e/test/specs/travelsearch.filter.e2e.ts
With the new bus schedule, there are more bus departures between my origin and destination when testing travel search filters. Have to check more search results to find results with both buses and trains.
=> test: check more results when filtering travel searches

src/fare-contracts/FareContractInfo.tsx, src/on-behalf-of/queries/use-fetch-on-behalf-of-accounts-query.ts, src/on-behalf-of/types.ts, src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/Root_ChooseTicketRecipientScreen.tsx, src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/ExistingRecipientsList.tsx, src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/SaveRecipientToggle.tsx, src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/SubmitButton.tsx, src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/types.ts, src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/use-delete-recipient-mutation.ts, src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/use-recipient-selection-state.ts, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchasePaymentScreen/use-reserve-offer-mutation.ts
Show it on the confirmation screen and on the confirmation screen
and on sent-to-others tickets.
Needed a refactor where the fetch recipients query was moved to a
place it could be reused, so it was rebranded to an
on-behalf-of-accounts-query, which is more inline with the api
naming.
<div>
</div>
=> feat: Show recipient name

src/components/sections/RadioGroupSection.tsx, src/components/sections/items/RadioSectionItem.tsx, src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/SaveRecipientToggle.tsx, src/translations/dictionary.ts
Improves a11y for checkbox and radioboxes in select recipient flow.
Reason why this is now necessary:
https://github.com/facebook/react-native/issues/43266
=> feat: Improve a11y for radio and checkbox

src/mobility/use-stations.tsx
If city bikes was not enabled the useEffect getting and setting the stations is not run. The hook would also return undefined if city bikes was not enabled.
Updated the condition to check if either city bikes or car sharing is enabled.
Fixes https://github.com/AtB-AS/kundevendt/issues/18797
=> fix: update condition in useStations

src/api/types/generated/TripsQuery.ts, src/api/types/generated/fragments/trips.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx, src/translations/screens/subscreens/TripDetails.ts, src/travel-details-screens/components/TripSection.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/18758
In https://github.com/AtB-AS/kundevendt/issues/18588, travel planner web was updated with a feature to clarify when the travellers should stay seated during a bus line number change.  Currently, the app does not distinguish between how a bus line change and an actual bus interchange is displayed. This can be confusing for the users and might lead some to get of the bus when they are supposed to stay seated.
<details>
<summary>screenshots/video/reis-nordland</summary>
| Trip view  | Detailed view |
| -------- | ------- |
| ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-08-12 at 14 25 36](https://github.com/user-attachments/assets/737d1ad5-d215-4574-bfcf-21d3ac1e0922)  |  ![Simulator Screenshot - iPhone SE (3rd generation) …
=> feat: add condition to check whether passengers should stay seated between leg interchanges. 

src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/SubmitButton.tsx
This was caused by retrieving the recipients directly with the
getQueryData function, which doesn't apply the select function on
the returned data. Instead changed this to use the actual query.
https://github.com/AtB-AS/kundevendt/issues/17226#issuecomment-2290957485
=> fix: Wrong error message when no recipient name

.github/actions/update-devices/action.yml, .github/workflows/update-devices.yml
There was an issue while update devices ran at the same time to update provisioning profiles, it was separated in order to make it serialized, first development then adhoc.
Before:
Now:
=> build: Split update devices job to be run in serial

src/travel-details-screens/components/TripSection.tsx
The message notifying the travellers about the line change is incorrect. The message currently describes line change in reverse order. 
<details>
<Summary>screenshots/video</Summary>
</details>
=> fix: update the notice of line number change to display the correct order

src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_NearbyStopPlacesScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_NearbyStopPlacesScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NearbyStopPlacesScreen.tsx
closes https://github.com/AtB-AS/kundevendt/issues/17342
This PR will fix the issue where user couldn't navigate to the same favorite chip on the departure screen (and anywhere else). 
Other existing function should still function normally.
Also I added an offset for the refresh loading progress so it shows properly on the screen.
A question, can I use `useRef` to fix the issue on the other eslint issue in the same file?
https://github.com/user-attachments/assets/d0cbcf92-8ba2-408d-9dc1-7f856859babb
=> fix: allow navigation to same favorite chips in departure

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProducts.tsx
This fixes a react native warning for Troms where several groups has the same transport modes.
Noticed while working on https://github.com/AtB-AS/kundevendt/issues/18693
=> fix: prevent duplicate product group keys

src/translations/screens/subscreens/OnBehalfOf.ts
No wonder I couldn't replicate it on my device with Norwegian translations 😅 
=> fix: Typo in recipient name error msg

e2e/test/specs/travelsearch.e2e.ts, e2e/test/utils/time.helper.ts
Sometimes checking a start time or end time of a travel suggestion will differ by a minute when looking at the details. Most probably, this is due to the realtime where the single trip search is made after the trip search. In case this happens, the test need to cope with this.
E.g. from a test run ([ref](https://github.com/AtB-AS/mittatb-app/actions/runs/10466163914)):
```
Test:
expect(startTime).toEqual(startTimeInDetails);
Result:
1) Travel search should do a travel search and have correct travel times in the details
expect(received).toEqual(expected) // deep equality
Expected: "08:48"
Received: "08:49"
Error: expect(received).toEqual(expected) // deep equality
```
=> test: accept time difference

src/configuration/__tests__/utils.test.ts, src/configuration/index.ts, src/configuration/types.ts, src/configuration/utils.ts, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByAlias.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByProducts.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-defaults.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/use-recent-fare-contracts.ts
This adds support for a new field in reference data, `productAliasId`. When doing offer searches, ids for all PreassignedFareProducts with the same productAliasId will be provided (named `preassignedFareProductAlternatives` in the code).
This does in theory allow more than one offer to be returned from the offer search, but in practice tickets should be configured to not overlap (e.g. for Troms, the Saturday boat ticket should apply only to Saturday, and the regular ticket should apply outside of Saturday). If there for some reason is more than one result, we use the cheapest option as a fallback.
closes https://github.com/AtB-AS/kundevendt/issues/18693
=> feat: support multiple PreassignedFareProducts per offer search

android/app/src/beacons/res/values/styles.xml, android/app/src/main/AndroidManifest.xml, android/app/src/main/res/values/styles.xml
Closes https://github.com/AtB-AS/kundevendt/issues/16313
It fixes a wrong splash screen that makes the app to looks like the following.
This fix avoids that by looking at the configurations on:
- https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/AndroidManifest.xml
- https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/res/values/styles.xml
=> chore: Update Android theme references for BootTheme

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTileIllustration.tsx
This (in addition to changing fare-product-type-config) makes boat carnets show the boat illustration instead of bus.
=> fix: add boat-carnet ticket illustration type

ios/atb/Info.plist, ios/en.lproj/InfoPlist.strings, ios/nb.lproj/InfoPlist.strings, ios/nn.lproj/InfoPlist.strings
closes https://github.com/AtB-AS/kundevendt/issues/16202
Adds correct text for camera permission request, see screenshots below.
Also contains some change for the photo library permission request, but that's only a placeholder, since we don't use them for the app at the moment. The only usage for photo library in the app right now is for Intercom chat, and it is already handled by the Intercom SDK (App only have access to the selected photos that we send through Intercom, not the entire gallery).
English | Norsk Bokmål | Norsk Nynorsk
--------|---------------|---------------
=> Fix: use correct text for camera permission request

package.json, yarn.lock
The static QR codes, used by the OMS partners with TryggOvergang, do not appear in the app. This issue was introduced when we upgraded the qrcode package to 1.5.4, where TextEncoder was introduced. The absence of TextEncoder causes the SVG generation to fail, preventing QR codes from being displayed as intended. 
Instead of adding a polyfill for the TextEncoder property, I suggest that we go back to use version 1.5.3. I also think that we should use an explicit version for this package if we do so. 
Fixes https://github.com/AtB-AS/kundevendt/issues/18925
=> fix: resolve QR code display error by downgrading qrcode package

src/mobility/use-shmo-deep-integration-enabled.tsx, src/remote-config.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/storage/StorageModel.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/18946
During the development of shared mobility deep integration (starting with e-scooters only), that functionality should only be available behind this flag.
=> feat: Support enable_shmo_deep_integration remote config flag

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx, src/stacks-hierarchy/saved-payment-utils.ts
By passing `recurringPayments` as a prop to SelectPaymentMethodSheet, we don't have to do an extra API call to fetch the list of saved payments. This removes the loading state from the page, and means we can remove some state logic.
Also refactored the usePreviousPaymentMethods hook a bit.
related to https://github.com/AtB-AS/kundevendt/issues/18885
=> refactor: refactor usePreviousPaymentMethods

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx, src/translations/screens/subscreens/PurchaseOverview.ts, src/translations/screens/subscreens/SelectPaymentMethodTexts.ts
related to https://github.com/AtB-AS/kundevendt/issues/18885
The current flow, where selecting a payment method completes a purchase, can be counter intuitive at best, and can lead to wrong purchases at worst. It also breaks with how other bottom sheets work in the app, where making a selection doesn't also submit the parent screen. So after a talk with designers, it was decided to change the flow to have the bottom sheet apply changes, but not complete the purchase.
[Updated sketches](https://www.figma.com/design/zdZwvobgpEWSagKt0tderx/App?node-id=28048-99792&node-type=INSTANCE&t=EkVYakSquEsRJVYY-0)
https://github.com/user-attachments/assets/7e29c38c-5696-4fe0-a1a0-5815edeabb3b
=> feat: confirm payment method selection in purchase flow

src/in-app-browser/in-app-browser.tsx
Follow up to https://github.com/AtB-AS/mittatb-app/pull/4711
On iOS, the status bar content should always be light when using the auth browser. On android the setting is ignored.
=> fix: use light status bar content for auth browser

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/use-purchase-callback-listener.tsx, src/stacks-hierarchy/saved-payment-utils.ts
fixes https://github.com/AtB-AS/kundevendt/issues/18885#issuecomment-2357887414
This fixes an issue introduced after I started using the openAuth in-app-browser and forgot to call saving of payment methods. To make this harder to miss in the future, this PR gathers saving payment method and closing the in-app-browser into one `onPaymentCompleted` callback function. This also means payment method is saved when fare contracts appear in the background, and the regular payment flow isn't completed.
I also moved the saveLastUsedPaymentMethod into saved-payment-utils, and renamed it to `saveLastUsedRecurringPaymentOrType` as I thought that made more sense together with `savePreviousPaymentMethodByUser`.
=> fix: save payment method whenever payment is completed

src/api/mobility.ts, src/api/types/mobility.ts, src/api/use-accept-language.ts, src/components/map/Map.tsx, src/components/map/components/mobility/ShmoTesting.tsx, src/components/map/geofencing-zone-utils.ts, src/mobility/queries/use-active-shmo-booking-query.tsx, src/mobility/queries/use-get-ids-from-qr-code-mutation.tsx, src/mobility/queries/use-init-shmo-one-stop-booking-mutation.tsx, src/mobility/queries/use-send-shmo-booking-event-mutation.tsx, src/mobility/queries/use-shmo-booking-query.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/18891
The endpoints are as described in the issue.
One extra added for getting a booking based on id instead of just the active one: `/mobility/v1/bookings/${bookingId}`.
This is needed because the summary of a booking should be shown when it is no longer active.
A new test feature has been added behind the `shmoDeepIntegrationEnabled` flag, which can be turned on in the debug menu and restarting the app.
=> Create Shared Mobility endpoint hooks + test usage

src/components/map/components/mobility/ShmoTesting.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/18891
After the changes in https://github.com/AtB-AS/mittatb-app/pull/4717, `usePreviousPaymentMethods` should be used instead of `usePreviousPaymentMethod` in `ShmoTesting`.
=> fix: Update use of usePreviousPaymentMethods after merge

src/analytics/types.ts, src/api/geocoder.ts, src/components/checkbox/CheckboxWithLabel.tsx, src/components/checkbox/index.ts, src/geocoder/use-geocoder.ts, src/remote-config.ts, src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx, src/stacks-hierarchy/Root_LocationSearchByTextScreen/use-only-stop-places-checkbox-enabled.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/storage/StorageModel.tsx, src/translations/screens/subscreens/LocationSearch.ts
When looking at geocoder request logs, we see that only ~8% of
location searches end up in the user selecting an address. They
instead use my position or a stop place.
It was decided to do a proof of concept by swiftly adding a checkbox,
and get quick feedback on whether this is a feature that users will use
or not.
To make searching for stop places easier we add a checkbox the user
can check so only stop places are returned when searching for a
location. We will enable this to a subset of the users, and see if
it is a feature which will be used.
=> feat: Only stop places checkbox in location search

src/components/theme-icon/NotificationIndicator.tsx
The notification indicator icon was a little small, so the sizes are increased a little bit.
A part of https://github.com/AtB-AS/kundevendt/issues/18947
| <img width="200" src="https://github.com/user-attachments/assets/d16fa9ea-9bf0-45f2-ae7b-803faa8bb3bd" /> | <img width="200" src="https://github.com/user-attachments/assets/ae499231-1462-482e-891c-7b9a99ac8e4d" /> |
=> feat: Slightly increase notification icon size

src/mobile-token/MobileTokenContext.tsx
Fixes https://github.com/AtB-AS/kundevendt/issues/19181
This fixes the problem where the app does not check if devices are inspectable when TryggOvergang QR codes are enabled.
=> fix: mobile token status when trygg overgang is enabled

package.json, yarn.lock
This is to get the latest illustrations for Svipper.
https://github.com/AtB-AS/kundevendt/issues/18263
=> chore: update generate-assets dependency to latest

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Summary.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts
closes https://github.com/AtB-AS/kundevendt/issues/18978
- Sets originalPrice to 0 when CLEAR_OFFER is called, which fixes the issue from https://github.com/AtB-AS/kundevendt/issues/18978
- Hides the originalPrice text while loading offers. The normal price is hidden in that state, so it made sense to hide originalPrice as well.
=> fix: hide originalPrice when it's not relevant

e2e/test/pageobjects/frontpage.page.ts, e2e/test/pageobjects/purchase.overview.page.ts, e2e/test/specs/frontpage.e2e.ts, e2e/test/specs/ticket.e2e.ts, e2e/test/utils/alert.helper.ts, e2e/test/utils/app.helper.ts
The e2e-tests are currently failing (https://github.com/AtB-AS/mittatb-app/actions/runs/11119572718) since there are so many global messages on the ticket purchase screen in Staging (the purchase button is not visible). This PR:
- removes global messages before running the tests
- enables zone selection to the tests as I found the correct id to use in the location deny prompts
=> test: e2e ticket fix

src/remote-config.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/storage/StorageModel.tsx, src/travel-aid/use-is-travel-aid-enabled.tsx, src/travel-aid/use-is-travel-aid-stop-button-enabled.tsx
closes https://github.com/AtB-AS/kundevendt/issues/17891
- Adds `enable_travel_aid` and `enable_travel_aid_stop_button` to remote config staging.
- Adds related hook, default value, and debug override to app. (see screenshots below)
=> feat: add travel aid remote config flag

eslint-rules/translations-warning.js, src/LocaleProvider.tsx, src/translations/commons.ts
As @gorandalum discovered [here](https://github.com/AtB-AS/mittatb-app/pull/4727#discussion_r1790061992), the current `t` function can be problematic when you don't want it to re-trigger an action.
This PR introduces a new function `tGlobal`, which will give the correct translation when called, but not re-trigger anything on language changes.
`tGlobal ` is _not_ required as part of dependency arrays.
=> Support tGlobal

src/api/client.ts, src/auth/AuthContext.tsx, src/auth/types.ts, src/auth/use-fetch-id-token-with-custom-claims.ts
Use the Auth state values from the FirebaseAuthContext. They are
exported using the global variable pattern, to not make client
dependant on the React state.
=> feat: Axios client not use Firebase Auth directly

src/auth/AuthContext.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
This made the presentation of Firestore Auth data in the debug menu
be out of sync with what the user actually experienced.
Reused the pattern from MobileTokenContext where parameters only for
debugging in the debug screen is exported through a sub-field
'debug'.
=> refactor: Debug auth info not directly from Firebase Auth lib

scripts/android/replace-bundle.sh
Possible fix for build issue such as https://github.com/AtB-AS/mittatb-app/actions/runs/11272142291
The current build-tools version we use is 34.0.0, so we probably should also update the version on the script.
=> chore: update build tools version on script

src/auth/index.ts, src/auth/types.ts, src/auth/use-subscribe-to-auth-user-change.ts, src/onboarding/OnboardingContext.tsx
This is done to improve encapsulation of Firebase Auth in the
auth module.
=> refactor: Remove FirebaseAuth import in OnboardContext

src/utils/__tests__/use-do-once-when.test.ts, src/utils/use-do-once-when.ts
This allows a parameter to only run an action once, even if the condition keeps toggling between `true` and `false`.
More discussion can be found [here](https://github.com/AtB-AS/mittatb-app/pull/4727#discussion_r1793339837).
=> feat: Accept onlyOnce param for useDoOnceWhen and add tests

src/GeolocationContext.tsx, src/components/map/Map.tsx
Using a global variable is easier for clients since they don't need
to go through the context. Also they don't need to provide the ref
in the dependency array of hooks, which the linter demands even
though it doesn't make a difference.
=> refactor: Global var instead of ref for current coordinates

.github/workflows/test-e2e-android.yml, .github/workflows/test-performance-android.yml
The emulator action `reactivecircus/android-emulator-runner@v2` doesn't support ubuntu 24 yet. Will thus have to use ubuntu 22.04 since ubuntu-latest now has become ubuntu 24.
=> test: run app tests on previous ubuntu

src/api/types/mobility.ts, src/components/map/components/mobility/ShmoTesting.tsx, src/stacks-hierarchy/Root_ScanQrCodeScreen.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/19215
Completes https://github.com/AtB-AS/kundevendt/issues/19097
Now that Entur's endpoint supports `formFactor`, use that instead of the temporary solution to determine which type of bottom sheet to open after scanning a QR code in the map.
=> feat: use form factor to decide AutoSelectableBottomSheetType

src/RemoteConfigContext.tsx, src/auth/use-fetch-id-token-with-custom-claims.ts, src/remote-config.ts
Added as an option so we can increase the retry count and see if it
affects how many end up in the missing-id-token state.
=> feat: Remote Config flag for id token retry count

src/stacks-hierarchy/Root_ScanQrCodeScreen.tsx
This fixes a bug where the geofencingZones would still show even when no bottomSheet was active.
Fixes https://github.com/AtB-AS/kundevendt/issues/19097
=> fix: Always clear auto selected state when alerting error

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/navigation-types.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByProducts.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-defaults.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts, src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_CategoryPickerScreen.tsx, src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketAssistant_SummaryScreen.tsx, src/stacks-hierarchy/types.ts
The code in our purchase screens, especially `PurchaseOverviewScreen`, has just grown and grown and now feels a little out of control. There are multiple business rules applied in more or less random places, and they are more or less untestable as it is structured now.
Establish a domain model for the purchase selection, with encapsulation and testing.
This PR is the first step towards the goal, where it is introduced a `PurchaseSelectionType` which works as a domain model for a purchase selection state. I have tried to do the least amount of changes possible to introduce such a type, to not let the PR grow out of hand.
The next steps will be:
- Encapsulate creation and modification of the `PurchaseSelectionType` in a module
- Let the `PurchaseSelectionType` be the main object sent around …
=> feat: Add PurchaseSelectionType

.github/workflows/build-staging-android.yml, .github/workflows/build-store-android.yml
Image magick dependency was missing. At least is not included in the latest image update from last week.
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
=> chore: Add imagemagick installation to build workflows

src/components/text/ThemeText.tsx, src/components/text/markdown-renderer.tsx
Part of: 
https://github.com/AtB-AS/kundevendt/issues/17887
|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 16 Pro - 2024-10-16 at 09 11 21](https://github.com/user-attachments/assets/480e39b2-9e6d-4959-880b-b3af864e1e26)|![Simulator Screenshot - iPhone 16 Pro - 2024-10-16 at 08 58 01](https://github.com/user-attachments/assets/a755dcfa-5cf7-4fe7-ad04-1e5014705315)|
Bullets points are aligned to the left and text to the right, there is a space between elements.
=> feat: Support for better list views in markdown

src/components/estimated-call/DepartureTime.tsx, src/components/estimated-call/EstimatedCallInfo.tsx, src/components/estimated-call/LineChip.tsx, src/components/estimated-call/index.ts, src/place-screen/components/EstimatedCallItem.tsx
In https://github.com/AtB-AS/kundevendt/issues/19125, some estimated call -related components are outside of the place-screen context, so I thought it made sense to extract them into `src/components/estimated-call. 
Replaces the `mode` param with `ignoreSituationsAndCancellations`, since I don't think a general component should handle the differences between screen specific modes  (map/favorites/departures).
=> refactor: extract estimated call components

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/no/mittatb/LaunchActivity.kt
Reopening the app through the app icon on Android closes an open in-app-browser. This is not good when the user needs to do secure customer authentication (SCA) in another app. This only happens when using the app icon, if following a deeplink back to the app or using the app switcher, then this doesn't happen.
Description of the problem:
https://github.com/proyecto26/react-native-inappbrowser/issues/213#issuecomment-878915862
The solution with adding a `LaunchActivity` described here:
https://github.com/proyecto26/react-native-inappbrowser/issues/213#issuecomment-2165493514
**Before (with just `MainActivity`) / After (with `LaunchActivity`)**
<div>
</div>
It is hard to know if there are any unwanted side effects of adding this `LaunchActivity`. I have tried looking it up, but couldn't …
=> refactor: Use LaunchActivity on Android

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
The ProductSelectionType has one product, but the offer search may
return another product with the same product alias id. This is what
happens for carnet Trondheim-Vanvikan.
The double offer search was because of the ProductSelection was
updated after the offer search results came in. This shouldn't be
done, the selection should still be the same even if the product in
the offer response changes.
Also made som changes to ensure that texts shown in the app is the
texts for offer search result product.
=> fix: Fix double offer search

src/components/theme-icon/ThemeIcon.tsx
We got some reports in Bugsnag where the app has crashed because
of the svg prop sent to ThemeIcon was undefined. This should really
not happen, but it is a little extreme that the app crashes if it
does. This safeguard is added to prevent app crash, rather there
will be no rendered ThemeIcon.
Haven't been able to reproduce, we will rely on code review for this one.
=> refactor: ThemeIcon undefined svg safeguard

src/auth/AuthContext.tsx, src/auth/use-fetch-id-token-with-custom-claims.ts, src/auth/use-refresh-id-token-when-necessary.ts, src/auth/utils.ts, src/utils/bugsnag-utils.ts
There was no refresh logic for internal id token state in the
auth context. This wasn't really noticable before since the acios
client refetched the id tokens, so it didn't really matter that the
auth state was outdated. Now that we use id token from auth state
also for axios requests, then we need refresh logic in auth context.
=> fix: Add refresh logic for id token

src/api/serviceJourney.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_DepartureDetailsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TravelAidScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/TabNav_DashboardStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/navigation-types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_DepartureDetailsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_TravelAidScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/TabNav_DeparturesStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/navigation-types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_DepartureDetailsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_TravelAidScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/TabNav_MapStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/navigation-types.ts, src/translations/screens/subscreens/DepartureDetails.ts, src/translations/screens/subscreens/TravelAid.ts, src/travel-aid/TravelAidScreenComponent.tsx, src/travel-aid/use-travel-aid-data.tsx, src/travel-details-screens/DepartureDetailsScreenComponent.tsx, src/travel-details-screens/use-departure-data.ts, src/utils/date.ts
First iteration of https://github.com/AtB-AS/kundevendt/issues/19125
Most of the features are missing at this point, this is just to have a screen with journey info visible, then we'll iterate from that.
<div>
</div>
Note: There's some inconsistency between the use of "travel aid" and "journey aid" in the app now. I'll make a separate PR to fix this.
=> feat: add first iteration of journey aid screen

src/translations/screens/subscreens/TravelAid.ts, src/travel-aid/TravelAidScreenComponent.tsx, src/travel-aid/__tests__/get-focused-estimated-call.test.ts, src/travel-aid/get-focused-estimated-call.ts
part of https://github.com/AtB-AS/kundevendt/issues/19125
This adds logic for extracting the information that should be shown on the Journey Aid screen. At any time there the view has a "status" and a "focused" estimated call. 
- Status is documented in the `TravelAidStatus` enum
- Based on the status, `focusedEstimatedCall` can be the current stop, next stop or the stop the user selected start point.
We still need to decide what to show in the `NotGettingUpdates` state.
<div>
</div>
=> feat: make journey aid focus on current or upcoming stop

src/components/sections/Section.tsx, src/place-screen/components/EstimatedCallItem.tsx, src/translations/dictionary.ts, src/translations/screens/Departures.ts, src/translations/screens/subscreens/TravelAid.ts, src/travel-aid/TravelAidScreenComponent.tsx, src/travel-details-screens/utils.ts
part of https://github.com/AtB-AS/kundevendt/issues/19125
This adds a11y lables to the travel aid screen, with the focus areas described in [figma](https://www.figma.com/design/Ftpf9FC06MLGFVWI5vHLLu/Bl%C3%A5-knapp-(iterasjon)?node-id=1351-44780&node-type=frame&t=wNWuKJTY4tx0TtlG-0).
Still missing the "announcement" -parts, that will read out changes as they happen.
_Tip: Might be easier to review this PR one commit at a time_
=> feat: add screen reader labels to travel aid

src/travel-aid/TravelAidScreenComponent.tsx, src/utils/object.ts
closes https://github.com/AtB-AS/kundevendt/issues/19125
Adds a useEffect to the travel aid screen that reads out updates every time the a11y label changes.
Since hooks can't be run conditionally and I needed to check if `serviceJourney.estimatedCalls` was undefined before rendering TravelAidSection, I had to move the undefined check, and do some type-trickery to make things work. Added a type to utils to make it easier to discover this method in the future. ~Found one spot where it was used before.~
=> feat: add travel aid screen reader announcements

src/travel-aid/TravelAidScreenComponent.tsx
Sets focusRef on the loading indicator and error message on the travel aid screen, fixing point 4 from comment https://github.com/AtB-AS/kundevendt/issues/19125#issuecomment-2446398675
closes https://github.com/AtB-AS/kundevendt/issues/19125
=> fix: handle focus for travel aid error and loading states

src/components/map/Map.tsx, src/components/map/components/filter/MapFilter.tsx, src/components/map/components/filter/MapFilterSheet.tsx, src/mobility/components/filter/FormFactorFilter.tsx
In order to interact with the map (on a superficial kind of way), I need som extra test-ids for the map. I cannot interact with the map elements like el-scooter, but having e.g. `mapView` gives the possibility to drag and zoom. Along with toggling the filters, test scenarios testing the performance can be created.
=> test: add test-ids for the map

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/no/mittatb/LaunchActivity.kt, android/app/src/main/java/no/mittatb/MainActivity.kt
closes https://github.com/AtB-AS/kundevendt/issues/19454
related to https://github.com/AtB-AS/mittatb-app/pull/4763
This fix is a hotfix that should be already released on version 1.58.1-rc2.
It seems that the issue occurring on 1.58 was caused by the wrong splash screen placement. In 1.58, the `LaunchActivity` doesn't have any theme or splash screen on it, so when it launches the `MainActivity`, it will then show the splash screen stuffs. While this shouldn't block anything, on some Android devices, the splash screen blocks the user from interacting with the UI.
The fix here is to move all splash screen related functionality to the `LaunchActivity` instead, so when it launches `MainActivity`, it should directly shows the app, since the splash screen is shown on the `LaunchActivity`.
=> fix: sort out issues with splash screen

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts, src/translations/screens/subscreens/PurchaseOverview.ts
This error comes when the the travel date is outside of the
availability times configured for the product.
This is how the error looks:
With this change the empty offer response is just shown as a generic error:
=> feat: Handle 400 NotAvailable error from offer search

src/api/types/generated/TripsQuery.ts, src/api/types/generated/fragments/service-journeys.ts, src/api/types/generated/journey_planner_v3_types.ts, src/api/types/serviceJourney.ts
Changes to be in sync with the changes in BFF:
https://github.com/AtB-AS/atb-bff/pull/359
Also updated the `journey_planner_v3_types.ts` which hadn't been done in a while.
=> refactor: Add generated types including service journey authority

src/components/button/Button.tsx
Doesn't really make sense that you can click a button (even spam
it) while it is loading.
=> feat: Make buttons in loading state not pressable

src/translations/screens/subscreens/TravelAid.ts, src/travel-aid/TravelAidScreenComponent.tsx, src/travel-aid/use-travel-aid-data.tsx, src/travel-details-screens/DepartureDetailsScreenComponent.tsx
- Announces the time only if the focused stop hasn't changed since the last announcement
- Enables the travel aid button even when realtime is false
- Updates the no realtime message box wording and type
- Only shows scheduled time on `NotYetArrived`
- Refresh interval is 5 seconds
=> feat: various travel aid tweaks

.github/workflows/test-e2e-android.yml, .github/workflows/test-performance-android.yml, .github/workflows/test-visual-android.yml, e2e/scripts/restart-adb.sh, e2e/test/pageobjects/travelsearch.overview.page.ts, e2e/test/specs/travelsearch.e2e.ts
- Updated the emulator version to `12414864` (35.2.10)
- Added cache on AVD (system-image `default` since this is mostly used) for the regular e2e-tests
- Adde a possibility to run the e2e-tests for system images `google_apis` and `google_apis_playstore`
- Small fix on a test when there are no travel suggestions
Tests run OK: https://github.com/AtB-AS/mittatb-app/actions/runs/11855717155
=> test: emulator upgrade

src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts
Not available response from offer search is a normal flow and not
really an error situation that needs to be logged.
=> fix: Skip error logging for not available offer search

src/components/message-info-box/MessageInfoBox.tsx, src/components/screen-reader-announcement/LiveRegionWrapper.tsx, src/components/screen-reader-announcement/index.ts, src/components/screen-reader-announcement/use-live-region-announcement.ts, src/situations/SituationMessageBox.tsx, src/travel-aid/TravelAidScreenComponent.tsx
Refactors travel aid to use [live regions](https://reactnative.dev/docs/accessibility#accessibilityliveregion-android) to announce changes on the page. Since iOS doesn't support live regions, the `useLiveRegionAnnouncement` hook is added, that triggers screen reader announcements on iOS when a11yLabel changes. There's also a wrapper component `LiveRegionWrapper` that can be used for non-interactive components in JSX.
There are two main ways to implement live regions
```tsx
const a11yProps = useLiveRegionAnnouncement(a11yLabelThatChangesOverTime, true);
return (
<InteractiveComponentWithAnnoucements
accessibilityRole="button"
onPress={() => {}}
{...a11yProps}
/>
)
```
or
```tsx
return (
<LiveRegionWrapper accessibilityLabel={a11yLabelThatChangesOverTime}>
<NonInteractiveComponent /> …
```
=> feat: use live regions to announce travel aid updates

src/travel-aid/TravelAidScreenComponent.tsx, src/travel-details-screens/components/CancelledDepartureMessage.tsx
Observation from @tormoseng: Cancellation messages were not announced.
closes https://github.com/AtB-AS/kundevendt/issues/19525
=> fix: announce travel aid cancellation messages

src/purchase-selection/__tests__/purchase-selection-builder-for-type.test.ts, src/purchase-selection/__tests__/purchase-selection-builder-from-selection.test.ts, src/purchase-selection/__tests__/purchase-selection-builder-product.test.ts, src/purchase-selection/__tests__/purchase-selection-builder-stop-places.test.ts, src/purchase-selection/__tests__/purchase-selection-builder-zones.test.ts, src/purchase-selection/__tests__/test-utils.ts, src/purchase-selection/purchase-selection-builder.ts, src/purchase-selection/types.ts, src/purchase-selection/utils.ts, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PreassignedFareProductSummary.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FromToSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-defaults.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts, src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketAssistant_SummaryScreen.tsx, src/ticketing/api.ts
The type for selecting a place in the purchase selection was not
optimal. This was observed already when creating the
PurchaseSelectionType, but not done anything with to not embrace
too much.
The place selection was typed to either a zone or a StopPlace, and
was mandatory. That ment that every time a stop place was not
selected, then a zone was selected. So for example during a boat
ticket purchase process, if the selected from harbor was undefined,
then in the data structure the from place was actually a tariff
zone.
This was improved by creating two different fields for zones and
stop places, and they can both be undefined if there is no
zoneSelectionMode on the type config.
=> refactor: Better typing of places in purchase selection type

src/loading-screen/LoadingScreenBoundary.tsx, src/remote-config.ts
Requesting some feedback on a change I want to make, since it's been bugging me for a while 😄
The app currently has a 1s timeout on every cold start, _after_ the initial data is loaded (Firestore config, auth, etc.). This was done as an additional safety measure to prevent the "app freeze" a while back. At that point, the initial render of the app could be very demanding, since several contexts updated data globally, and caused several renders of the entire layout tree. It was probably due to some `setInterval` calls with a never ending update queue that caused the freeze to never stop, which was fixed by the addition of the `useInterval` hook.
But, as far as I know, we have no reason to believe that the 1s delay is necessary today, since no users with slow phones are complaining about …
=> feat: make delay in LoadingScreenBoundary configurable

ios/atb.xcodeproj/project.pbxproj, ios/atb/AtB.entitlements, ios/atb/Info.plist, ios/atb/atbDebug.entitlements, patches/@entur-private+abt-token-state-react-native-lib+2.1.6.patch
After the message we got from Apple rejecting the app because use of NFC, this PR removes the usage of it on the code and creates a patch towards Entur MobileTokenSDK.
=> feat: Remove use of NFC

src/translations/screens/subscreens/PurchaseOverview.ts
=> feat: Not available ticket text improvement

src/mobility/queries/use-active-shmo-booking-query.tsx
The call to get active shmo booking shouldn't be sent unless the feature flag is enabled.
=> fix: Only enable get active booking when feature flag true

.github/actions/update-devices/action.yml, .github/workflows/build-staging-ios.yml, fastlane/Fastfile, scripts/ios/replace-bundle.sh
It allows the certs always to be updated, this avoids always forcing a cache to update the certs, which means those are going to be up to date.
=> fix: Allow update certs to rebundle the app with cache on

src/travel-aid/TravelAidScreenComponent.tsx
Requested by PO that the scheduled time shouldn't be read aloud
because of changes in the relative real time.
=> feat: Not always announce scheduled time in travel aid

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
I don't think there's any point of having this button in the developer menu. The same can be done by everyone on the dashboard.
=> feat: remove favorite departures button from profile dev menu

src/purchase-selection/use-purchase-selection-builder.ts, src/ticketing/use-get-fare-products-query.tsx
The fare products in the PurchaseSelectionBuilderInput needs to
come from the products API for HjemJobbHjem to work.
Added staleTime to not make the app query products API everytime
it tries to open the purchase flow. Also set initialDataUpdateAt: 0
so the products directly from Firestore is considered stale at
query mount.
=> fix: Purchase builder products input from API

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/translations/screens/Profile.ts
Today I learned that talkback treats Views with `testID`s as accessible, and in the case of the Profile RootScreen, makes the whole ScrollView one focus area. This can be prevented by setting `importantForAccessibility="no"`.
This PR fixes this for My Profile, and some translation feedback from https://github.com/AtB-AS/mittatb-app/pull/4845#discussion_r1858732624
closes https://github.com/AtB-AS/kundevendt/issues/19593
=> fix: make talkback ignore parent View on Profile RootScreen

src/loading-screen/LoadingErrorScreen.tsx, src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/ExistingRecipientsList.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/components/ClickableCopy.tsx, src/translations/screens/Profile.ts, src/translations/screens/subscreens/DeleteProfile.ts, src/utils/accessibility.ts
Adds a `spellOut` util to be used with strings like phone numbers and IDs, and puts it to use wherever I found functionality in the app. 
Also improves accessibility of the `ClickableCopy` component.
closes https://github.com/AtB-AS/kundevendt/issues/19593
Numbers/IDs are read out one digit/letter at a time in
=> feat: add spellOut util function

src/travel-details-screens/DepartureDetailsScreenComponent.tsx, src/travel-details-screens/components/Trip.tsx
Identified as something that could be useful for VM, where global messages on submode `shuttleBus` could be used.
=> feat: add submode rule variable on trip and departure details

.github/workflows/build-store-ios.yml
Fix a building issue when the keychain name new parameter was missing for building for the App store.
=> fix: Update build-store-ios.yml to include KEYCHAIN_NAME

src/purchase-selection/index.ts, src/purchase-selection/use-selectable-user-profiles.ts, src/purchase-selection/utils.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-defaults.ts
closes https://github.com/AtB-AS/kundevendt/issues/19640
The `userProfileWithCount` is not used to determine whether the user can select travellers or not, therefore I added `selectableUserProfiles` to help determine the number of travellers that can be selected, this will then affect the display of the on-behalf-of layout on the purchase overview screen.
I'm guessing we could also just use the `userProfileRefs` count from the `limitation` field inside the `referenceData`, but then we need to have `UserProfile[]` for the `isSelectableUserProfile` function to work.
=> fix: use correct selectable traveller count

src/place-screen/components/QuaySection.tsx, src/place-screen/components/QuayView.tsx, src/place-screen/components/StopPlacesView.tsx, src/translations/screens/Departures.ts
Updated some logic related to departure favorites to have exhaustive deps. 
closes https://github.com/AtB-AS/kundevendt/issues/16267
=> refactor: fix some departure favorite exhaustive deps warnings

e2e/test/pageobjects/departure.details.page.ts, e2e/test/specs/departure.e2e.ts, src/travel-details-screens/DepartureDetailsScreenComponent.tsx
- Added a test-id to the departure details header for line name
- Changed the tests accordingly
=> test: e2e test change for departure details header

.eslintrc.js, package.json, src/components/screen-view/FullScreenView.tsx, src/mobility/components/MobilityStat.tsx, src/stacks-hierarchy/Root_ParkingViolationsReporting/components/ScreenContainer.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PreassignedFareProductSummary.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_EditProfileScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/travel-details-screens/components/TripSection.tsx, yarn.lock
In react-native the app crashes if trying to render text outside of
Text component. This has happened in our production app more than
once because of checks on length, and to be fair it will probably
happen more if we don't do anything about it.
This change adds an eslint rule that gives error when using in
combination with && inside jsx.
The eslint rule used is not that popular, but seems well created
and safe to use when reading through its code.
=> chore: Add eslint rules for not leaking values to jsx

src/fare-contracts/details/Barcode.tsx
Now that FRAM will be going from using static QR code to using Aztek, the testers have experienced that the Aztek is too large for FLV+, and that FLV+ sometimes has trouble reading. By reducing it to a maximum width of 200 (up for discussion), it will be easier for the FLV+ to read the code.
Co-authored-by: Morten Nordseth <morten@nordseth.net>
Co-authored-by: Mathias Oterhals Myklebust <mom@variant.no>
=> style: reduce size of Aztek

src/RemoteConfigContext.tsx, src/fare-contracts/__tests__/sort-fc-reservation-by-validity-creation.test.ts, src/feature-toggles/toggle-specifications.ts, src/loading-screen/__tests__/use-loading-state.test.ts, src/loading-screen/__tests__/use-notify-bugsnag-on-timeout-status.test.ts, src/loading-screen/types.ts, src/loading-screen/use-loading-state.ts, src/onboarding/OnboardingContext.tsx, src/onboarding/onboarding-config.ts, src/onboarding/types.ts, src/remote-config.ts
Disables the onboarding login if the `enable_onboarding_login` remote config flag is `false`.
Also adds remote config to the loading boundary, making the app wait for remote config to load before letting users into the app, since the `enable_onboarding_login` flag is needed before onboarding starts. If loading of remote config fails, the default value is true, meaning that the login will be shown after a loading boundary timeout.
Note: There's an issue with the extended onboarding (used by FRAM, and maybe other OMS partners), where if it's the only onboarding screen, it won't be able to navigate past the final extended onboarding page. (It ends up on `navigation.goBack()` in https://github.com/AtB-AS/mittatb-app/blob/master/src/onboarding/use-onboarding-navigation.ts#L42 )
closes …
=> feat: add feature flag for onboarding login

src/components/checkbox/CheckboxWithLabel.tsx, src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx
With the design system changes we need to send in contrast color
instead of the theme color name. The theme color name syntactic
sugar is no longer supported, so it ended up treated as a hex
color code.
Before / After:
<div>
</div>
=> fix: Only stop places checkbox label color

.github/CODEOWNERS
Since @strandlie is mostly focusing on app now in the start it is preferable he also is automatically added to reviews for learning.
=> chore: Add strandlie to codeowners

src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx, src/storage/StorageModel.tsx, src/utils/__tests__/use-persisted-bool-state.test.ts, src/utils/use-persisted-bool-state.ts
This is decided to be in place for next round of testing of the
only stop places checkbox. In last round of testing the usage of
the checkbox was quite high at the start, but then dropped of. The
theory is that users don't use the extra click to check off the
checkbox for every search.
=> feat: Store only stop places checkbox state on device

src/place-screen/components/StopPlacesView.tsx, src/travel-details-map-screen/components/CompactTravelDetailsMap.tsx, src/travel-details-screens/TripDetailsScreenComponent.tsx, src/travel-details-screens/components/Trip.tsx, src/travel-details-screens/components/TripSummary.tsx
closes https://github.com/AtB-AS/kundevendt/issues/19645
Since there was some padding after I removed the feedback component from trip details, I updated the styling to use rowGap instead. This should be better in line with how it's made in Figma, but no significant visual changes.
=> feat: remove feedback component from departures and trip details

src/travel-details-screens/use-get-service-journey-vehicles.ts
Retries are already handled by axios, so this is a quick fix to prevent retries from happening on two levels in this case. We should look into a more permanent and global solution as well.
ref. https://mittatb.slack.com/archives/C0116FMPX4Y/p1734353027280489
=> fix: prevent serviceJourneyVehicles retries from useQuery

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FromToSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/HarborSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByAlias.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByProducts.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/StartTimeSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Summary.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravelDate/TravelDateSheet.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ZonesSelection.tsx, src/ticketing/use-fare-contracts.ts
This is instead of passing multiple fields of the purchase selection
down individually, and gives a cleaner style overall. This is also
inline with the next step where the individual screen params of
the purchase overview screen will be replaced with the purchase
selection type.
=> refactor: Selection as field on purchase components

src/travel-details-screens/use-get-service-journey-vehicles.ts
We're still seeing a lot of requests towards vehicles in 1.60.1, and it seems it might be caused by requests that are active without focus. E.g. if the user navigates from trip details to departure details or switches tab, the trip query is still active and fetching updates every 20s. And if several screens with vehicles queries are open, several requests are sent every 20s.
follow up to https://github.com/AtB-AS/mittatb-app/pull/4885
=> fix: disable fetching of vehicles when out of focus

src/api/departures/index.ts, src/favorites/FavoritesContext.tsx, src/favorites/types.ts, src/favorites/use-on-mark-favourite-departures.tsx, src/place-screen/components/EstimatedCallList.tsx, src/place-screen/components/QuaySection.tsx, src/place-screen/components/QuayView.tsx, src/place-screen/components/StopPlacesView.tsx, src/storybook/stories/Section.stories.tsx
When thinking about it I think it is no reason to store the stop
place id on favorites, as the quay id is uniquely identifiable.
=> refactor: Not store stop place id on favorites

src/utils/__tests__/date.test.ts, src/utils/date.ts
The tests need to have current year provided programatically to not
need manual fixing every new year.
In addition when adding some more tests it came to light that the
formatting of the day and month differed based on whether it was
the current year or not. The full date formatting was changed to
give the same day/month format no matter if current year or not.
=> fix: Some date tests failing after new year

src/components/map/Map.tsx, src/components/map/utils.ts
Sometimes when clicking a geofencing zone, the snackbar didn't show.
This was because of incorrect input for `turfBooleanPointInPolygon`.
Acceptance Criteria:
=> fix: GeofencingZone onPress

src/travel-details-screens/DepartureDetailsScreenComponent.tsx
Since we don't want to merge https://github.com/AtB-AS/mittatb-app/pull/4907 to the release branch and spend time testing it right before the release, I'm making a temporary change to move the follow bus button back to beside the last passed stop text. Only for the release branch.
=> feat: move live bus button beside LastPassedStop text

src/components/estimated-call/LineChip.tsx, src/components/icon-box/TransportationIconBox.tsx, src/components/map/components/mobility/Bicycles.tsx, src/components/map/components/mobility/BikeStations.tsx, src/components/map/components/mobility/CarStations.tsx, src/components/map/components/mobility/Scooters.tsx, src/fare-contracts/components/InspectionSymbol.tsx, src/fare-contracts/use-validity-line-colors.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTile.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductTile.tsx, src/theme/colors.ts, src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx, src/travel-details-map-screen/components/MapRoute.tsx, src/travel-details-screens/DepartureDetailsScreenComponent.tsx, src/travel-details-screens/components/TripSection.tsx, src/travel-details-screens/components/WaitSection.tsx, src/utils/use-transport-color.ts, src/utils/use-transportation-color.ts
part of https://github.com/AtB-AS/kundevendt/issues/19401
In preparation for adding a VM specific transport colors, we need to use secondary transport colors for trip leg decorations in order to have enough contrast against the background in dark mode. See ad037ad90812c75553e4bb31459069632135983a for this change.
Since this made the secondary variant of transport colors more used in the app, I thought it made sense to return `TransportColor` (with both primary and secondary) from the useTransportColor hook instead of passing a `colorMode` parameter and returning ContrastColor. Because of this, the PR contains some refactorings related to usage of the hook as well.
=> feat: use secondary transport color for trip leg decorations

src/components/bordered-info-box/BorderedInfoBox.tsx
This was previously set using opacity, which obviously only works in light mode. 
**Before:** 
<div>
</div>
**After:**
<div>
</div>
=> fix: Set BorderedInfoBox border color in same way as SectionItem separator color

src/fare-contracts/FareContractAndReservationsList.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TicketHistorySelectionScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_AvailableFareContractsTabScreen.tsx, src/ticket-history/TicketHistoryScreenComponent.tsx, src/ticket-history/types.ts, src/ticketing/__tests__/get-availability-status.test.ts, src/ticketing/api.ts, src/ticketing/get-availability-status.ts, src/ticketing/types.ts, src/ticketing/use-fare-contracts.ts, src/translations/screens/Ticketing.ts
It is a more fitting term to use historical fare contracts than
historic fare contracts.
=> refactor: Rename historic to historical

.github/actions/update-devices/action.yml, scripts/ios/get_ios_certs.sh
It fixes issues while running update devices due to a missing parameter in the GA.
=> fix: Device update issue, missing keychain name

src/components/map/Map.tsx, src/components/map/hooks/use-control-styles.ts
In the map tab:
The bug is that users are not able to use area at the bottom of the screen between the buttons (area marked with red on the screenshot).
The user can not press buttons (for example bus stops) in the area or use the area to move the map.
This is now fixed.
=> bugfix: able to use map area between buttons

src/api/departures/types.ts, src/api/types/generated/DeparturesQuery.ts, src/api/types/generated/TripsQuery.ts, src/api/types/generated/fragments/estimated-calls.ts, src/api/types/generated/fragments/trips.ts, src/api/types/generated/journey_planner_v3_types.ts, src/components/map/components/DeparturesDialogSheet.tsx, src/components/map/types.ts, src/departure-list/section-items/line.tsx, src/place-screen/PlaceScreenComponent.tsx, src/place-screen/components/EstimatedCallList.tsx, src/place-screen/components/QuaySection.tsx, src/place-screen/components/QuayView.tsx, src/place-screen/components/StopPlacesView.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_RootScreen.tsx, src/travel-aid/TravelAidScreenComponent.tsx, src/travel-aid/__tests__/get-focused-estimated-call.test.ts, src/travel-aid/__tests__/sent-stop-signals-cache.test.ts, src/travel-aid/components/StopSignalButton.tsx, src/travel-aid/get-focused-estimated-call.ts, src/travel-aid/sent-stop-signals-cache.ts, src/travel-details-screens/DepartureDetailsScreenComponent.tsx, src/travel-details-screens/components/TripSection.tsx, src/travel-details-screens/types.ts, src/travel-details-screens/use-departure-data.ts, src/travel-details-screens/utils.ts
Quay id doesn't uniquely identify a call in a service journey when
the service journeys visits the same quay twice. This change starts
using stopPositionInPattern to identify uniquely a call in a service
journey, as advices by Entur.
=> fix: Use stopPositionInPattern instead of quay id

package.json, src/components/bottom-sheet/AnimatedBottomSheet.tsx, src/components/button/Button.tsx, src/components/icon-box/utils.ts, src/components/label-info/LabelInfo.tsx, src/components/map/components/BackArrow.tsx, src/components/theme-icon/NotificationIndicator.tsx, src/components/vipps-login-button/VippsLoginButton.tsx, src/fare-contracts/carnet/CarnetFooter.tsx, src/stacks-hierarchy/Root_ExtendedOnboardingStack/Root_ExtendedOnboardingStack.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FareProductHeader.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductAliasChip.tsx, src/theme/colors.ts, src/travel-details-screens/DepartureDetailsScreenComponent.tsx, src/travel-details-screens/components/WaitSection.tsx, src/utils/use-transport-color.ts, yarn.lock
A small step ~for man~ in terms of code changes, but a huge~icon~ leap for ~mankind~ the OMS ✨
- Uses new tokens from the design systems, with a new color set
- Uses new assets, with icons from hugeicons
- Implements the `transport.shuttle` color for `transportSubMode: "shuttleBus"` (VM colors for AtB)
closes https://github.com/AtB-AS/kundevendt/issues/19401
closes https://github.com/AtB-AS/kundevendt/issues/19098
closes https://github.com/AtB-AS/kundevendt/issues/19586
=> feat: add hugeicons and update to new theme colors

package.json, yarn.lock
Makes the VM shuttle bus color blue instead of white in dark mode:
closes https://github.com/AtB-AS/kundevendt/issues/19401
=> chore: bump theme to 13.1.2

src/chat/use-intercom-metadata.ts, src/mobile-token/MobileTokenContext.tsx, src/mobile-token/hooks/use-load-native-token-query.tsx, src/mobile-token/types.ts
This fixes the issue with intercom update metadata logging, right now, the metadata for token is only updated when the user changes (login/logout), while what we want is to update it everytime the token status gets updated (renewal, error, creation, etc.).
In general:
- `updateMetadata()` is now a part of `MobileTokenContext`, with similar trigger to the ones in `GeolocationContext`.
- load native token query no longer calls the `updateMetadata()`.
- added a type for intercom token metadata (`attested | non-attested | error`).
=> fix: intecom update token metadata not working as intended

src/remote-config.ts
Excuse the amount of changes - I did some cleanup in remote-config.ts and sorted stuff alphabetically. The only real change is that `mapbox_sprite_url` was added (3009c14646d5ba60321b1533e592d65a37e3c8ab).
=> feat: add mapbox_sprite_url remote config variable

src/components/text/markdown-renderer.tsx
markdown-renderer can now display numbered (ordered) lists.
Needed for https://github.com/AtB-AS/kundevendt/issues/19831
PR https://github.com/AtB-AS/mittatb-app/pull/4936 should be merged first to see it in use.
=> feat: markdown renderer handles numbered lists

src/components/button/Button.tsx
Design has decided to make buttons in the app fully rounded. As this change is really quick and pretty risk free (as there are no functional changes), it is being done as a "quick issue".
This issue fixes point 1 and 2 described here:
https://github.com/AtB-AS/kundevendt/issues/19773
Just set button border radius to circle.
Some pictures from the app after this change:
=> feat: Border radius circle on buttons

src/global-messages/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/utils.ts
Closes AtB-AS/kundevendt#19786
There are no Figma sketches for this, but here is a screenshot:
=> feat: Added GlobalMessage to TripSearchScreen

src/components/button/Button.tsx
Design has decided to make border width on small buttons slim (1px). As this change is really quick and pretty risk free (as there are no functional changes), it is being done as a "quick issue".
This issue fixes point 3 described here:
https://github.com/AtB-AS/kundevendt/issues/19773
Border width set to slim.
Before/After:
<div>
</div>
=> feat: Slim border on small buttons

src/components/button/Button.tsx, src/components/empty-state/EmptyState.tsx, src/components/map/components/BackArrow.tsx, src/components/map/components/PositionArrow.tsx, src/components/map/components/ScanButton.tsx, src/components/map/components/bonus-program/BonusProgramMapButton.tsx, src/components/map/components/external-realtime-map/ExternalRealtimeMapButton.tsx, src/components/map/components/filter/MapFilter.tsx, src/components/map/components/mobility/ShmoTesting.tsx, src/favorites/FavoriteChips.tsx, src/place-screen/components/DateSelection.tsx, src/place-screen/components/StopPlaceAndQuaySelection.tsx, src/stacks-hierarchy/Root_ChooseTicketRecipientScreen/components/SendToOtherButton.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/CityZoneMessage.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx, src/storybook/stories/Button.stories.tsx, src/travel-details-screens/DepartureDetailsScreenComponent.tsx, src/travel-details-screens/components/PaginatedDetailsHeader.tsx
Design has decided to remove the compact mode for buttons. As this change is quick and pretty risk free (as there are no functional changes), it is being done as a "quick issue".
This issue fixes point 4 described here:
https://github.com/AtB-AS/kundevendt/issues/19773
Remove the `compact` param on buttons. Buttons that previously was compact should now be small.
Some before/after pictures from the app:
<div>
</div>
<div>
</div>
=> feat: Remove button compact param

src/components/button/Button.tsx
The border color on active buttons were not in sync between app and Figma. App used `interactiveColor.default` as border color, while Figma used `interactiveColor.outline`.
Change border color on active buttons to `interactiveColor.outline`
Before/after:
<div>
</div>
=> fix: Active button border color mismatch

src/components/sections/items/ToggleSectionItem.tsx, src/components/text/ThemeText.tsx, src/storybook/stories/Section.stories.tsx
Related to https://github.com/AtB-AS/kundevendt/issues/19831
Fixes bug: https://github.com/AtB-AS/mittatb-app/pull/4938#issuecomment-2604148912
before: 
after:
More accurate with design system, subtle change
before:
after:
=> fix: width of markdown rendering + ToggleSectionItem

src/translations/screens/subscreens/DepartureDetails.ts, src/travel-details-screens/use-realtime-text.ts
Closes https://github.com/AtB-AS/kundevendt/issues/18182
Shows `Passerte ${stopPlaceName} kl. ${time}` if bus is on time
Otherwise nothing is shown
=> fix: realtime text

src/fare-contracts/components/ValidTo.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FareContractsScreen.tsx
Carnets will sometimes come with several travel rights, where accesses are added up. E.g. a carnet with 20 uses are really two travel rights with 10 accesses each. To account for this, we should use the `flattenCarnetTravelRightAccesses` util instead of reading from the first travel right.
Related to https://github.com/AtB-AS/kundevendt/issues/4220
=> fix: support carnets with multiple TravelRights in ValidTo

package.json, yarn.lock
closes https://github.com/AtB-AS/kundevendt/issues/19919
After https://github.com/AfterShip/phone/pull/420, the issue with 9 digit phone numbers from Bosnia and Herzegovina is resolved by upgrading the phone package.
=> fix: upgrade `phone` to support 9 digit Bosnia and Herzegovina numbers

src/mobile-token/hooks/use-load-native-token-query.tsx, src/mobile-token/utils.ts
Fix issue with mobile token where the token gets recreated whenever issues happened during fetching the local token.
Also adds many more loggings.
So, what happened on the issue in 1.61.4 is that I added a function to detect if a user needs to start fresh, there was an issue for old users when their data was truncated from backoffice and the token is already deleted, where their local device still has the old token. It means that the user should just remove that local token, and then init a new token, problem solved.
The problem was this code: 
```
export const wipeToken = async (tokensIds: string[], traceId: string) => {
for (const id of tokensIds) {
logToBugsnag('Wiping token with id ' + id);
try {
await tokenService.removeToken(id, traceId);
} catch (err: any) {
/**
* There are cases …
```
=> fix: token issue fix and many more logging

src/components/sections/items/TextInputSectionItem.tsx, src/departure-list/section-items/line.tsx, src/fare-contracts/CompactFareContractInfo.tsx, src/fare-contracts/FareContractView.tsx, src/fare-contracts/PurchaseReservation.tsx, src/fare-contracts/ValidityLine.tsx, src/fare-contracts/ValidityTime.tsx, src/fare-contracts/__tests__/fare-contract-validity-units.test.ts, src/fare-contracts/carnet/CarnetFooter.tsx, src/fare-contracts/components/ValidityLine.tsx, src/fare-contracts/components/ValidityTime.tsx, src/fare-contracts/components/WithValidityLine.tsx, src/fare-contracts/details/DetailsContent.tsx, src/fare-contracts/modules/TravelInfoSectionItem.tsx, src/fare-contracts/types.ts, src/fare-contracts/utils.ts, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/PreassignedFareProductSummary.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/NonTransitResults.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx, src/time/TimeContext.tsx, src/translations/screens/FareContract.ts, src/translations/screens/Ticketing.ts, src/travel-details-screens/components/TripSection.tsx, src/travel-details-screens/components/TripSummary.tsx, src/travel-details-screens/components/WaitSection.tsx, src/utils/__tests__/date.test.ts, src/utils/date.ts
Fixes some bugs relating to AtB-AS/kundevendt#4220
The main issue was `TextInputSectionItem` and `LineItem` getting excessive padding due to the export from `use-section-item.ts`changing from `padding` to `paddingVertical` and `paddingHorizontal` ([see code here](https://github.com/AtB-AS/mittatb-app/commit/31f3280b3cfb4d52b54627daefa191c586219ec4#diff-704d1e9f5eb3e264a4abc336c07fe0913a48fb946a15c2f783a2f57396616344L30)). The underlying issue was setting a default value, which was not applicable in all cases and changing the generic component then lead to unintended consequences.
<div>
</div>
It now looks like this:
<div>
</div>
This PR also implements the design for reservations with status `reserving` and `rejected` according to …
=> fix: Bugs from FareContract inspection testing

src/components/sections/items/PhoneInputSectionItem.tsx, src/components/sections/items/TextInputSectionItem.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
Bug found while testing AtB-AS/kundevendt#4220
Makes `PhoneInputSectionItem` equal to `TextInputSectionItem`. Also added `PhoneInputSectionItem` to the Design System screen, because it was missing from there.
=> fix: Fixed verticalPadding on PhoneInputSectionItem

ios/departureWidget/Structs.swift, ios/departureWidget/WidgetViewModel.swift, src/favorites/types.ts, src/stacks-hierarchy/RootStack.tsx, src/stacks-hierarchy/utils.ts, src/travel-details-screens/types.ts
With #4893 the `stopId` field was removed from the favorite departure type, which broke the iOS widget. Removing references to this field makes the widget function again.
fixes https://github.com/AtB-AS/kundevendt/issues/19834
=> fix: update widget to use new favorite type

src/fare-contracts/__tests__/sort-fc-reservation-by-validity-creation.test.ts, src/fare-contracts/details/DetailsContent.tsx, src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FareContractsScreen.tsx, src/ticketing/__tests__/fixtures/carnet-farecontact.ts, src/ticketing/__tests__/fixtures/period-boat-farecontract.ts, src/ticketing/__tests__/fixtures/single-farecontract.ts, src/ticketing/types.ts
Some fields that are always present in Firestore, are not returned by the ticket service. After adding stricter Zod validation of fields, this caused tickets from the endpoint to fail validation. Since these fields were not used (in a significant way) in the app, I opted to treat them as deprecated and remove them from the app entirely.
At the same time, it shows that we should use the ticket service as source of truth for fare contract and travel right types in the app.
fixes comment https://github.com/AtB-AS/mittatb-app/pull/4971#issuecomment-2623942274
=> refactor: remove some unused FareContract/TraveRight fields

src/components/sections/items/PhoneInputSectionItem.tsx, src/components/sections/items/TextInputSectionItem.tsx
Follow up to AtB-AS/kundevendt#4220
Added back some Android-specific padding, since it turned out it was needed to get it _just_ right.
=> fix: Added back some Android-specific padding

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_BonusScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/TabNav_ProfileStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/navigation-types.ts, src/translations/index.ts, src/translations/screens/Profile.ts, src/translations/screens/subscreens/BonusProfile.ts, yarn.lock
Related to https://github.com/AtB-AS/kundevendt/issues/19827
Adds Bonus Screen as a page accessible from profile when bonus toggle is activated.
[Figma](https://www.figma.com/design/8aTgkQtYXm7l0QvGYSCdR0/Bonusprogram?node-id=1624-29625&t=SFhRfpLnzkdmkJdG-0)
NB: The right illustration is not available (yet)
=> feat: add bonus points screen from profile

src/fare-contracts/FareContractAndReservationsList.tsx, src/stacks-hierarchy/Root_ConsiderTravelTokenChangeScreen/Root_ConsiderTravelTokenChangeScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TravelTokenScreen/Profile_TravelTokenScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_AvailableFareContractsTabScreen.tsx, src/travel-token-box/TravelTokenBox.tsx
Moved the TravelTokenBox out of the FareContractAndReservationsList
component. This is to adhere to the single responsibility principle,
the component for listing fare contracts should not be responsible
for also showing token related info.
In addition removed the color parameter for the TravelTokenBox
since it was always themed to interactive color 2 and could just as
well be specified internally in the component.
=> refactor: Slight refactor for TravelTokenBox usage

src/components/empty-state/index.tsx, src/fare-contracts/FareContractAndReservationsList.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_AvailableFareContractsTabScreen.tsx, src/ticket-history/TicketHistoryScreenComponent.tsx
This refactor started when I wanted to make the 'mode' parameter
non-optional, since it wasn't intuitive what the default value was.
But then making it required made it obvious that the possible
modes (historic and sent) was not enough as in the my tickets tab
neither historic or sent was fitting.
All in all I decided to remove the mode parameter and make all of the
empty state config parametrised from the outside. This also removed
the circular dependency where ticket history screen used fare contract
list, and the fare contract list used the TicketHistoryMode type from
the ticket history screen.
Also cleaned up some props that either could be made required or
removed.
=> refactor: Cleaner configuration of empty state in fare contract list

src/ticket-history/TicketHistoryScreenComponent.tsx
Improve the ticket history performance by using FlatList instead of
ScrollView. Some notes on the solution:
- Using a default FlatList without special tuning or extra memoing
seems to improve performance adequately.
- A vertical scrolling FlatList can't be used inside a vertical
scroll ScrollView. This means that we couldn't use the
FullScreenView with the parallax scrolling effect as that requires
an animated ScrollView.
- Didn't change the active tickets tab as that would be a slightly
larger refactor since we would need to do some more changes to get
rid of the ScrollView there. Shouldn't be a problem as active
tickets tab doesn't render many fare contracts.
=> feat: Improve ticket history performance

src/components/button/Button.tsx
All small buttons have body secondary as their font typography
in Figma. Before this change the small tertiary button had body
primary as their font typography in the app.
=> fix: Align small tertiary button typography with Figma

.github/workflows/build-staging-android.yml
The change (`default: true`) in issue https://github.com/AtB-AS/mittatb-app/pull/5000 didn't help: https://github.com/AtB-AS/mittatb-app/actions/runs/13199924279
I think it's because the cache-step is checking the string value of "true".
=> fix: force build as strings

.github/workflows/build-staging-android.yml
The tries to set force build as `true` in https://github.com/AtB-AS/mittatb-app/pull/5000 and https://github.com/AtB-AS/mittatb-app/pull/5001 didn't work (e.g. see https://github.com/AtB-AS/mittatb-app/actions/runs/13200613990/job/36851521623).
It seems that when running the yml from a schedule, the dispatch inputs are not picked up. See e.g. https://stackoverflow.com/questions/72539900/schedule-trigger-github-action-workflow-with-input-parameters.
In this suggestion, either the dispatch input is used, or a default value of `true` is used.
=> fix: force true also on push for android

src/fare-contracts/FareContractAndReservationsList.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TicketHistoryScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketHistoryScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_AvailableFareContractsTabScreen.tsx, src/ticket-history/TicketHistoryScreenComponent.tsx
This is to adhere to the [coding guidelines](https://github.com/AtB-AS/docs-private/blob/main/kundevendt-development-guidelines.md#screen-reuse) that the screens are the
ones that should use the navigation object, so that child
components doesn't need to.
- [ ] Should be able to navigate to ticket details from front page
- [ ] Should be able to navigate to ticket details from my tickets tab
- [ ] Should be able to navigate to ticket details from expired ticket history
- [ ] Should be able to navigate to ticket details from sent ticket history
=> refactor: Decouple navigation object on fare contract lists

src/travel-details-screens/DepartureDetailsScreenComponent.tsx
ref. https://mittatb.slack.com/archives/CS3JNRXEV/p1738936949715109?thread_ts=1738931606.382689&cid=CS3JNRXEV
=> feat: swap favorite and map button on departure details

src/components/text/ThemeText.tsx, src/stacks-hierarchy/Root_TicketInformationScreen.tsx
Fixes an issue with markdown overflowing introduced by https://github.com/AtB-AS/mittatb-app/pull/4953
fixes https://mittatb.slack.com/archives/CR75QKX6G/p1739112362530579?thread_ts=1739111540.478569&cid=CR75QKX6G
=> fix: prevent markdown overflow in global messages

src/stacks-hierarchy/Root_ScooterHelp/Root_ContactScooterOperatorScreen.tsx, src/stacks-hierarchy/Root_ScooterHelp/Root_ScooterHelpScreen.tsx, src/stacks-hierarchy/Root_ScooterHelp/components/ConfirmationScreenComponent.tsx, src/translations/screens/ContactScooterOperator.ts
fixes comments from test on these issues: 
- https://github.com/AtB-AS/kundevendt/issues/19862#issuecomment-2637035407
- https://github.com/AtB-AS/kundevendt/issues/19943
Main changes:
- Header now have new color background and icons for back and close
- navigation now slides screen left/right for 'contact operator' and 'report parking violation' buttons
=> fix: scooter contact feedback

src/stacks-hierarchy/Root_AddEditFavoritePlaceScreen/Root_AddEditFavoritePlaceScreen.tsx, src/stacks-hierarchy/Root_LocationSearchByTextScreen/Root_LocationSearchByTextScreen.tsx, src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx, src/stacks-hierarchy/Root_LocationSearchByTextScreen/navigation-types.ts, src/stacks-hierarchy/Root_SearchStopPlaceScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_NearbyStopPlacesScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_NearbyStopPlacesScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NearbyStopPlacesScreen.tsx, src/utils/__tests__/use-persisted-bool-state.test.ts, src/utils/use-persisted-bool-state.ts
PO wanted to test having the only stop places initial state set to true to test how many people turns it off.
=> feat: Only stop places checked as default

src/favorites/FavoriteChips.tsx, src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx, src/stacks-hierarchy/RootStack.tsx, src/stacks-hierarchy/Root_LocationSearchByTextScreen/Root_LocationSearchByTextScreen.tsx, src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx, src/stacks-hierarchy/Root_SearchFavoritePlaceScreen.tsx, src/stacks-hierarchy/Root_SearchStopPlaceScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_NearbyStopPlacesScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_NearbyStopPlacesScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FavoriteListScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NearbyStopPlacesScreen.tsx, src/stacks-hierarchy/navigation-types.ts
https://github.com/AtB-AS/mittatb-app/pull/5003#issuecomment-2650172885
The reason for the bug was a misunderstanding regarding what the functionality of the `Root_SearchStopPlaceScreen` was. It wasn't for searching stop places, but for searching for favorite places in context of add favorite place flow.
- The first commit is the actual change that fixes the observed case.
- The second commit is renaming of a screen and some functions to be more clear that it belongs to the add favorite place flow.
=> refactor: Only stop places not checked by default when adding favorite place

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchPreference.tsx
@Mariblaas requested that we remove some padding around RadioSegments in travel search filters:
<div>
</div>
=> fix: remove redundant section around filter RadioSegments

src/components/message-info-text/MessageInfoText.tsx
closes https://github.com/AtB-AS/kundevendt/issues/20021
<div>
</div>
=> fix: prevent MessageInfoText overflow

src/fare-contracts/sections/FareContractInfoDetailsSectionItem.tsx
After https://github.com/AtB-AS/mittatb-app/pull/4991, the `{...props}` given to InspectionSymbol in fare contact details were no longer correct, resulting in an UFO inspection symbol 🛸👽
Fixed by passing `preassignedFareProduct` directly.
=> fix: provide correct props to InspectionSymbol in FareContract details

src/recent-fare-contracts/RecentFareContract.tsx
https://mittatb.slack.com/archives/C0116FMPX4Y/p1739353003234229?thread_ts=1739347072.253399&cid=C0116FMPX4Y
Show product name instead of product type config name as recent fare contract heading.
Before/After:
<div>
</div>
Also fixed a couple duplicate key errors in console.
=> fix: Show product name on recent fare contract

ios/AtbAppIntent/IntentHandler.swift, ios/departureWidget/Provider.swift, ios/departureWidget/Structs.swift, ios/departureWidget/WidgetViewModel.swift
fixes issue described in https://mittatb.slack.com/archives/C0116FMPX4Y/p1739351827212559
Note: This adds destination display with `frontText` and `via` to the widget, but I haven't added logic to actually display the `via` data, only `frontText`.
=> fix: use frontText instead of lineName in departures widget

src/stacks-hierarchy/Root_LocationSearchByTextScreen/hooks.ts, src/stacks-hierarchy/Root_LoginAvailableFareContractWarningScreen.tsx, src/stacks-hierarchy/Root_LoginOptionsScreen.tsx, src/stacks-hierarchy/Root_LoginPhoneInputScreen.tsx, src/stacks-hierarchy/Root_LoginRequiredForFareProductScreen.tsx, src/stacks-hierarchy/Root_PurchaseAsAnonymousConsequencesScreen.tsx, src/stacks-hierarchy/Root_ScooterHelp/Root_ContactScooterOperatorScreen.tsx, src/stacks-hierarchy/Root_ScooterHelp/Root_ScooterHelpScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_NearbyStopPlacesScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_NearbyStopPlacesScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NearbyStopPlacesScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx, src/stacks-hierarchy/navigation-types.ts, src/stacks-hierarchy/navigation-utils.ts
We have the possibility to specify a transition when navigating, but
using this functionality gave this warning:
"Non-serializable values were found in the navigation state"
Instead of passing the actual TransitionPreset object as a param, now
the param instead is a string which will be mapped to a
TransitionPreset object before usage.
In addition renamed the param to transitionOverride to signal that
the param is ment to be used only for overriding the transition
specified in the stack navigator.
=> refactor: Remove transitionPreset not serialisable warning

src/components/button/Button.tsx
When doing stuff in the `Button` component it was really hard to find out of the color selection flow, as we had the variables `backgroundColor`, `buttonColor`, `textColorBasedOnBackground`, `textColor`, `borderColor`, `backgroundColorValue`, in addition to the `DefaultModeStyles` with `ButtonSettings` for each mode. I tried to gather and simplify this into a more simple `getButtonColors` helper.
Tip: Strip whitespace in the PR diff
=> refactor: Simplify button color selection

src/mobile-token/MobileTokenContext.tsx, src/mobile-token/tokenService.ts
closes: https://github.com/AtB-AS/kundevendt/issues/19963
Changes: 
- Implement endpoint for sending token status to /token/v1/status.
- Send token status along with intercom metadata update.
- Add condition to send the token status when the query status is not `loading`, so that only the final error/success state will be sent. Without the query status, it will send the status update when the query is still on initialization/empty state.
Please let me know if checking for `query status !== 'loading'` is not the correct solution here, I've looked into `isLoading` and `isFetching` and it seems that checking on `isLoading` is the way to go.
=> feat: implement token status endpoint

src/components/sections/items/LinkSectionItem.tsx, src/components/sections/items/RadioSectionItem.tsx, src/components/sections/use-section-item.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
Adds active and interActiveColor as props for all section items
Uses active for radio button section items instead of separate styling
Part of https://github.com/AtB-AS/kundevendt/issues/19988
=> feat: add active and interActiveColor to section item

src/mobile-token/tokenService.ts, src/mobile-token/utils.ts
part of https://github.com/AtB-AS/kundevendt/issues/19973
Currently reattestation of mobile token leads to a `reset` instead, in this PR I added a handling so that reattestation issues are handled appropriately.
The problem is that inside the `validate` call, we have 2 function. The outer part is provided from the SDK to add a reattestation header to wrap the actual validate function, while the inner part is calling the validate endpoint. (see the code)
- If we put `catch(handleError)` on the inner part: Reattestation works, Renewal doesn't work.
- If we put `catch(handleError)` on the outer part: Reattestation doesn't work, Renewal works.
So the solution is to differentiate the error handling for both part. Reattestation is handled on the inner part, while Renewal and others are handled …
=> fix: handle reattestation error during validate

package.json, src/bonus/BonusPriceTag.tsx, src/configuration/FirestoreConfigurationContext.tsx, src/configuration/converters.ts, src/mobility/__tests__/use-is-eligible-for-benefit.test.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_BonusScreen.tsx, src/translations/screens/subscreens/BonusProgram.ts, yarn.lock
Resolves feedback from testing and design on:
- https://github.com/AtB-AS/kundevendt/issues/19827
Specifically:
- accessibility improvements
- configurable text from firestore
- improved error messages
- Trondheim Bysykkel -> Trondheim City Bike for english
=> fix: bonus profile screen feedback

src/mobility/components/BikeStationBottomSheet.tsx, src/mobility/utils.ts
Adds use of PayWithBonusPointsCheckbox in BikeStation Bottom sheet.
Will display checkbox if an active BonusProduct for the given operator and form factor exists AND isBonusProgramEnabled is true
=> feat: use PayWithBonusPointsCheckbox for Trondheim bysykkel

.github/workflows/build-staging-android.yml, .github/workflows/tsc.yml
Looks like v2 of the cache action has been deprecated, so migrating to v3. There is a v4 as well, but since we still use node 18 some places, it might make sense to stay at v3 for now.
Failing build: https://github.com/AtB-AS/mittatb-app/actions/runs/13628983280/job/38092354264?pr=5051
=> ci: use `actions/cache@v3`

src/components/icon-box/TransportationIconBox.tsx, src/modules/fare-contracts/components/InspectionSymbol.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductTile.tsx, src/utils/use-transport-color.ts
The `useThemeColorForTransportMode` util wasn't really serving a purpose that the `useTransportColor` doesn't cover, so removing it as an export from `use-transport-color.ts`. 
No functional changes, but should make sure that
=> refactor: remove use of useThemeColorForTransportMode

.github/workflows/tsc.yml, src/modules/fare-contracts/components/TravelInfoSectionItem.tsx
The main change of this PR to resolve the bug was changing from this
```ts
useGetPhoneByAccountIdQuery(fc.customerAccountId)
```
to this:
```ts
useGetPhoneByAccountIdQuery(isSent ? fc.customerAccountId : undefined)
```
The rest is just a refactor to encapsulate the logic regarding showing the sent to phone number.
=> fix: Only query phone number for sent fcs

src/mobility/components/BikeStationBottomSheet.tsx, src/mobility/components/PayWithBonusPointsCheckbox.tsx, src/translations/screens/subscreens/BonusProgram.ts
Fixes accessibility role + state + label on PayWithBonusPointsCheckbox
Also fixes the name of a useState variable to not start with 'use'.
=> fix: accessibility pay with bonus points checkbox

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseTariffZonesSearchByMapScreen.tsx, src/utils/__tests__/use-param-as-state.test.ts, src/utils/use-param-as-state.ts
Use state for the purchase selection object instead of relying on `setParams`. This is to reduce PostHog screen events, which are created when using `setParams`.
=> refactor: Use state for purchase selection

src/place-screen/PlaceScreenComponent.tsx
There was already an error message in the departures view, but it didn't show if no quays. Changed the logic so the error is shown also if no quays.
Before/After:
<div>
</div>
=> feat: Message if no departures (no quays) for a stop place

src/components/button/Button.tsx
The parameter was not used in the app, and also the component in
Figma doesn't support different izon sizes.
Nothing to test.
=> refactor: Remove button icon size parameter

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
https://mittatb.slack.com/archives/C0116FMPX4Y/p1740747250532429
<div>
</div>
=> fix: Missing requires booking text on trip result

src/utils/bugsnag-utils.ts
In response to https://mittatb.slack.com/archives/C0116FMPX4Y/p1741270241971609
=> fix: add an object check on errorToMetadata function

src/mobile-token/MobileTokenContext.tsx
With the introduction of non-attested tokens in SDK v3.x.x, we can now use mobile token on iOS Simulators.
This PR will enable that functionality. 🎉
=> feat: enable mobile token on iOS simulator

src/mobile-token/abtClientLogger.ts
Ref: [Slack thread](https://mittatb.slack.com/archives/C03DTC05VRQ/p1741605296772459?thread_ts=1741602504.740099&cid=C03DTC05VRQ)
Also maybe part of https://github.com/AtB-AS/kundevendt/issues/20215
Thomas from Entur notified us that our logging leaves many details out, so he asked if there are possibilities to improve it.
This PR will update the breadcrumb logging as shown below, hopefully will expose the `metadata` part more, and shows the `stack` if any.
from
```
error: (msg, err, metadata?) => {
logToBugsnag('Mobiletoken sdk info message: ' + msg, metadata);
const onError = toOnErrorCallback('warning', msg, metadata);
if (err) notifyBugsnag(err, {errorGroupHash: 'token', metadata: onError});
}
```
to
```
error: (msg, err, metadata?) => {
logToBugsnag(`Mobiletoken sdk error message: …
```
=> fix: improve mobile token error logging

.github/actions/ios-build-setup/action.yml, .github/actions/setup-certs/action.yml, .github/actions/update-devices/action.yml, .github/workflows/build-staging-android.yml, .github/workflows/build-store-android.yml
Builds are failing after https://github.com/AtB-AS/mittatb-app/pull/5041: https://github.com/AtB-AS/mittatb-app/actions/runs/13833005678/job/38701432685
=> ci: upgrade github actions to ruby 3.1.0

android/app/src/main/java/no/mittatb/MainActivity.kt
closes https://github.com/AtB-AS/kundevendt/issues/20247
This PR will make our Android App to intercept all NFC reading when it is in foreground, no new libraries included, only added some native code.
=> feat: intercept NFC reading when app is in foreground

src/mobile-token/DebugTokenServerAddress.tsx, src/mobile-token/tokenService.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/storage/StorageModel.tsx
closes https://github.com/AtB-AS/kundevendt/issues/20084
Pretty much self-explanatory, adds debug menu for specifying the mobile token server endpoint.
If there's a better alternative than using the `storage` function I would love to know more about it 😄 
[mobile token debug menu](https://github.com/user-attachments/assets/7388199e-0781-4877-9f66-8d5e9a62ff08)
=> feat: add debug menu to specify endpoint for mobile token server

src/components/map/ExploreLocationMap.tsx, src/components/map/Map.tsx, src/components/map/MapV2.tsx, src/components/map/hooks/use-decide-camera-focus-mode.tsx, src/components/map/hooks/use-map-selection-change-effect.tsx, src/components/map/hooks/use-update-bottom-sheet-when-selected-entity-changes.tsx, src/components/map/index.ts, src/components/map/types.ts, src/components/map/utils.ts, src/stacks-hierarchy/Root_LocationSearchByMapScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_RootScreenV2.tsx
This cleans up the code by separating the explore location mode in the map to its own component, and fixes the bug where an item on the map was selected when clicked.
| Before (icons minimized when they shouldn't be) | After |
| <img width="200" src="https://github.com/user-attachments/assets/2c384d13-85f2-4cff-93e1-4071ac34d573" /> | <img width="200" src="https://github.com/user-attachments/assets/f46c6374-79b7-4d21-a2dc-73603690d110" /> |
Part of https://github.com/AtB-AS/kundevendt/issues/19216
=> Separate explore location map

src/components/map/ExploreLocationMap.tsx, src/components/map/Map.tsx, src/components/map/MapConfig.ts, src/components/map/MapV2.tsx, src/components/map/hooks/use-map-view-config.ts, src/components/map/index.ts, src/stacks-hierarchy/Root_ScooterHelp/components/UserCoordinatesMap.tsx, src/tariff-zones-selector/TariffZonesSelectorMap.tsx, src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx, src/travel-details-map-screen/components/CompactTravelDetailsMap.tsx
This uses the new map for all remaining maps in the app, supporting everything as before + dark mode as well.
| <img width="200" src="https://github.com/user-attachments/assets/66b1d934-6edf-4d7f-b2a2-ed344bbfc030" /> | <img width="200" src="https://github.com/user-attachments/assets/9ba199c0-c6f9-42e8-96c2-b12badf37c6f" /> |
| <img width="200" src="https://github.com/user-attachments/assets/ebdf8cc9-4519-4752-badb-4e5a3eed04a8" /> | <img width="200" src="https://github.com/user-attachments/assets/d50974fc-1707-4089-a34c-6edd63eb8a75" /> |
| <img width="200" src="https://github.com/user-attachments/assets/fe799ab2-0f0a-4baa-9cf0-913aa4a2ab5a" /> | <img width="200" src="https://github.com/user-attachments/assets/e0961884-3d74-423c-a82d-75c2d6142776" /> …
=> feat: map v2 remaining maps

src/components/map/ExploreLocationMap.tsx, src/components/map/Map.tsx, src/components/map/MapV2.tsx, src/components/map/hooks/use-map-view-config.ts, src/stacks-hierarchy/Root_ScooterHelp/components/UserCoordinatesMap.tsx, src/tariff-zones-selector/TariffZonesSelectorMap.tsx, src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx, src/travel-details-map-screen/components/CompactTravelDetailsMap.tsx
Stations were included in this map in https://github.com/AtB-AS/mittatb-app/pull/5084, but wasn't there from before, so shouldn't be there now at least.
=> fix: Remove Stations From TravelDetailsMapScreenComponent

src/components/button/Button.tsx
There was an issue in the app where the loading indicator on buttons don't get the correct color, and would sometimes be almost invisible:
This fixes this by setting it to the same color as the text color:
<div>
</div>
- You can use storybook to verify this :)
=> fix: use correct text color for button loading indicator

src/components/sections/items/CounterSectionItem.tsx, src/components/sections/use-section-item.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/MultipleTravellersSelection.tsx
Reverts a change made in https://github.com/AtB-AS/mittatb-app/pull/4896. Seems the padding change to spacious sections is no longer needed for fare contracts. This makes padding even for sections 
- in the following bottom sheets:
- External realtime map sheet
- Activate now
- Consume carnet
- Situations
- the mobile token toggle radio buttons (which is due to change anyway)
- the "multiple traveller selection" component in the purchase flow was spacious, but it was overridden by internal styles. I cleaned this up a bit.
<div>
</div>
=> fix: make spacing even on spacious sections

src/mobile-token/MobileTokenContext.tsx, src/mobile-token/hooks/use-load-native-token-query.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
closes https://github.com/AtB-AS/kundevendt/issues/20216
some reference that may be useful: https://mittatb.slack.com/archives/C079LPXV1NF/p1742217909662349
> ~~Requires https://github.com/AtB-AS/mittatb-app/pull/5079 and https://github.com/AtB-AS/abt-token-server/pull/95 to be merged first~~ (NOW MERGED)
This PR will remove the `validate()` function from the app, also removes the `Validate token` debug menu.
For handling of the current validate function: 
Handled by https://github.com/AtB-AS/mittatb-app/pull/5079 and https://github.com/AtB-AS/abt-token-server/pull/95 
`MobileTokenContext` now handles the renewal and resetting of token as needed. In order to detect this, it will need to check if the local token exists on the remote, if local token doesn't exist on remote, assume that it …
=> refactor: remove validate function from mobile token process

src/components/message-info-text/MessageInfoText.tsx, src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_TravelTokenScreen/Profile_TravelTokenScreen.tsx, src/token-toggle-info/TokenToggleInfo.tsx
Refactors parts of the token toggle styling, which had some outdated solutions, in addition to being out of sync with [figma](https://www.figma.com/design/zdZwvobgpEWSagKt0tderx/App?node-id=15538-66699&t=xaRfD4CVRy4cliEJ-0). It's still not quite in line with figma, but a bit closer.
<div>
</div>
=> refactor: update token toggle styling

src/translations/screens/FareContract.ts
Updates texts to be more in line with https://www.figma.com/design/ufJRKSCxQzNpFVlrKsdaKd/Skoleskyss?node-id=382-2105&t=7qiXey5kaa87n47b-0
part of https://github.com/AtB-AS/kundevendt/issues/20063
=> feat: update carnet texts to use "billetter" instead of "klipp"

ios/Podfile
it seems like the builds are failing (not while compiling) but instead when uploading the IPA to apple,
https://github.com/AtB-AS/mittatb-app/actions/runs/14058318894/job/39362780748
I found this:
https://github.com/mapbox/mapbox-maps-ios/issues/2233
there is a workaround but the recommendation is:
`We released Maps v10.19.0 version which doesn't contain bitcode anymore in it's binaries. I'd suggest you to give it a try and get rid of workarounds.`
=> fix: Change MapBox version to 10.19.0 to avoid push to apple issues

src/storybook/stories/Section.stories.tsx
From implementation of https://github.com/AtB-AS/kundevendt/issues/18735.
I hope it added some visible functionality for `RadioGroupSection` and `RadioSectionItem` components.
| Radio Section | Listed Section Items |
|--------|--------|
| ![simulator_screenshot_D9A60063-8B29-4DB8-97EC-23A0D553B6A7](https://github.com/user-attachments/assets/c566990f-8590-4c7a-b1a7-e317dee423b7) | ![simulator_screenshot_205D63DA-4359-45A3-BF4A-C4C44BF8393E](https://github.com/user-attachments/assets/4bac21b3-5556-402c-8911-3415af33b4f5) |
=> fix: edit storybook radio button

src/mobile-token/MobileTokenContext.tsx, src/mobile-token/hooks/use-validate-token.tsx, src/mobile-token/index.ts, src/mobile-token/types.ts
fixes https://github.com/AtB-AS/kundevendt/issues/20216#issuecomment-2747889695
This PR will add logic for token renewal based on remote token details and device details. The remote token details came from this PR https://github.com/AtB-AS/abt-token-server/pull/96. 
Token renewal logic:
- Get local token
- Get remote tokens
- Check if local token id exists on remote tokens
- Get the remote token that has the same id as local
- Find the details of that remote token, and compare to the current device situation (app version, OS level, device ID, etc.).
- If any of the details are different between device situation and remote token details, renew the token.
I made a custom hook for this PR and moved all renewal/reset logic into the hook `use-validate-token`.
=> feat: add token renewal logic based on token and device details

src/mobile-token/MobileTokenContext.tsx, src/mobile-token/hooks/use-list-remote-tokens-query.tsx, src/mobile-token/hooks/use-preemptive-renew-token-mutation.tsx
part of https://github.com/AtB-AS/kundevendt/issues/20216#issuecomment-2747955834
Uses `securecontainer` string instead of whole native token object for list remote token query.
This should be merged before https://github.com/AtB-AS/mittatb-app/pull/5104
=> refactor: use secure container for list remote token query

.github/actions/ios-build-setup/action.yml, .github/actions/setup-certs/action.yml, .github/actions/update-devices/action.yml, .github/workflows/build-staging-android.yml, .github/workflows/build-store-android.yml
On the previous version we updated the ruby version but seems like we need to tell the ruby version action that the cache has changed or we need to reset it according to https://github.com/ruby/setup-ruby?tab=readme-ov-file#caching-bundle-install-manually this is because the build are stick on old versions of ruby.
=> chore: Update cache version to 2 to take the new ruby version

src/modules/fare-contracts/FareContractAndReservationsList.tsx
Order ID isn't a unique key for school tickets and frikort, since the order id is `""`. This caused duplicate tickets to appear in active tickets when a school ticket was activated.
=> fix: use fare contract id as key in active tickets list

src/mobility/components/BikeStationBottomSheet.tsx, src/modules/bonus/api/api.ts, src/modules/bonus/components/PayWithBonusPointsCheckbox.tsx, src/modules/bonus/components/UserBonusBalance.tsx, src/modules/bonus/components/index.tsx, src/modules/bonus/index.tsx, src/modules/bonus/queries/get-bonus-balance-query.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_BonusScreen.tsx, src/translations/screens/subscreens/BonusProgram.ts
closes https://github.com/AtB-AS/kundevendt/issues/19986
The bonus point balance is now retrieved from the bonus service backend
Also add loading and error views when unable to get bonus points:
=> feat: get bonus balance from bonus service

scripts/android/run-android.sh
This PR will fix an issue when you want to run the app on Android using `yarn android` for the OMS partner. (e.g. if you run `yarn setup dev troms/nfk/fram`)
The error is:
```
Cannot locate tasks that match 'app:installDebug' as task 'installDebug' is ambiguous in project ':app'.
Candidates are: 'installAppDebug', 'installAppDebugAndroidTest', 'installBeaconsDebug', 'installBeaconsDebugAndroidTest'. 
```
The fix is just to add `-mode=appDebug` if the `KETTLE_API_KEY` doesn't exist in the `.env` file
=> chore: add mode specifier

src/modules/fare-contracts/PurchaseReservation.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FareContractsScreen.tsx
There was a bug with flex layout in reservations, where the "Go to vipps for payment" would get 0 width, and a lot of height on android. The theory is that this could lead to double purchases because users couldn't find their active ticket, because it's hidden below a reservation.
closes https://github.com/AtB-AS/kundevendt/issues/20293
<div>
</div>
=> fix: give vipps button on reservations some width to prevent overflow

src/operator-config/index.ts, src/travel-details-screens/TripDetailsScreenComponent.tsx, src/travel-details-screens/utils.ts
Background: https://mittatb.slack.com/archives/C025NUF4WA0/p1745320924053039
=> feat: ignore ferry in from travel search to ticketing

src/components/bottom-sheet/AnimatedBottomSheet.tsx, src/components/bottom-sheet/BottomSheetContainer.tsx, src/components/bottom-sheet/BottomSheetContext.tsx, src/components/bottom-sheet/BottomSheetHeader.tsx, src/components/map/MapConfig.ts, src/components/map/MapV2.tsx, src/components/map/components/external-realtime-map/ExternalRealtimeMapSheet.tsx, src/components/map/hooks/use-active-shmo-booking.tsx, src/components/map/hooks/use-auto-select-map-item.tsx, src/components/map/hooks/use-control-styles.ts, src/components/map/hooks/use-map-selection-change-effect.tsx, src/components/map/hooks/use-trigger-camera-move-effect.tsx, src/components/map/hooks/use-update-bottom-sheet-when-selected-entity-changes.tsx, src/components/map/utils.ts, src/mobility/components/BicycleSheet.tsx, src/mobility/components/BikeStationBottomSheet.tsx, src/mobility/components/CarSharingStationBottomSheet.tsx, src/mobility/components/ParkAndRideBottomSheet.tsx, src/mobility/components/filter/MapFilterSheet.tsx, src/mobility/components/sheets/ActiveScooterSheet.tsx, src/mobility/components/sheets/FinishedScooterSheet.tsx, src/mobility/components/sheets/ScooterSheet.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_RootScreenV2.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/20077
* moved bottomsheet above tabbar on demand
* made bottomsheet close when navigating away from the maptab
you could review commit for commit
=> feat: move bottomsheet above tabbar

README.md
`bundle exec pod install` should be used instead of the `npx pod-install
ios` due to how dependencies are managed in the commands.
=> docs: update problem fixing command

src/components/map/MapV2.tsx, src/components/map/hooks/use-control-styles.ts
import {useBottomTabBarHeight} from '@react-navigation/bottom-tabs'
useBottomTabBarHeight was used in a component thats used multiple places, but it needs to be used in a tab screen component. So in some cases it was undefined. 
Fixed it by passing it as a prop with default value 0. So its only affected when used in the targeted screen component
Closes http://github.com/AtB-AS/kundevendt/issues/20077
=> fix: fixed undefined tabbarheight

src/modules/fare-contracts/__tests__/fare-contract-validity-units.test.ts, src/modules/fare-contracts/fare-contract-validity-units.ts
Quickwin: Clarified with @Aliaaen that counting seconds from one hour and down on fare contracts is a bit excessive, and can cause some some layout shifting every second due to line breaks. Instead, this PR will hide seconds when validity time is >10 minutes.
=> feat: hide fare contract validity seconds when >10 minutes

src/components/map/hooks/use-map-symbol-styles.ts, src/components/map/mapbox-styles/pin-types.ts
Tier has merged with Dott, and the system id now starts with `dott` instead of `tier`.
<div>
</div>
<div>
</div>
=> feat: Support dott instead of tier map icon

src/translations/screens/FareContract.ts
We got some feedback that we should use "cancel" for refunds on English in the app. Still using "angre" in Norwegian.
=> feat: use 'cancel' instead of 'undo' for ticket refunds

src/in-app-browser/in-app-browser.tsx, src/modules/fare-contracts/utils.ts, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/use-cancel-payment-mutation.ts, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/use-reserve-offer-mutation.ts, src/ticketing/api.ts, src/ticketing/types.ts, src/translations/screens/subscreens/PurchaseConfirmation.ts
_Might make sense to review one commit at a time_
This PR allows the user to cancel ongoing payments, and prevents several purchase flows going at once. 
Also sets a `isUser` query parameter for all cancel calls, indicating whether or not it was manually triggered by the user. This should allow us to monitor the amount of people who use the button.
https://github.com/user-attachments/assets/b850216c-88f6-4316-85fe-f4a4057dc629
closes https://github.com/AtB-AS/kundevendt/issues/20293
=> feat: let the user cancel ongoing payments

src/modules/fare-contracts/components/RefundBottomSheet.tsx, src/modules/fare-contracts/details/DetailsContent.tsx, src/ticketing/types.ts
Changing the casing of `is_refundable` → `isRefundable`. We figured it was better to do this change now before refund is released to users, to be consistent with the casing in the responses from backend.
Backend PR: https://github.com/AtB-AS/sales/pull/43
=> refactor!: change casing of refund options response

src/modules/bonus/api/api.ts
Closes https://github.com/AtB-AS/kundevendt/issues/19986#issuecomment-2786117709
Fix the issue that Number(null) is 0, when null in bonus balance should be displayed as --
=> fix: bonus balance null value

src/mobile-token/MobileTokenContext.tsx, src/mobile-token/hooks/use-list-remote-tokens-query.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
Adding this menu to help the testers test simulating no remote tokens that are inspectable. 
Helps in testing this screen
=> feat: add debug menu for simulating remote token inspectability

src/components/map/components/national-stop-registry-features/nsr-layers.ts, src/components/map/mapbox-styles/pin-types.ts
Fixes a bug where the ferry icon was used for boat as well in the map.
| <img width="200" src="https://github.com/user-attachments/assets/bb64ffd6-176c-4497-9a41-e4c898483b36" /> | <img width="200" src="https://github.com/user-attachments/assets/a15ba379-7cff-41db-854a-2865f4ae6bfe" /> |
=> fix: Use boat icon instead of ferry icon for boat

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_RootScreenV2.tsx
There was a shmo featureflag wrapped around the focusEffect telling the bottomsheet to close when navigating. If this was going to stay we needed to add a featureflag for the tabHeight that pushed the bottomsheet up aswell, making it impossible to navigate in the tabs without the featureflag on
=> fix: Issue where bottomsheet stays open when navigating away from maptab

src/api/utils.ts, src/modules/fare-contracts/components/ConsumeCarnetBottomSheet.tsx, src/translations/screens/FareContract.ts
Adds a school-ticket specific error message based on https://github.com/AtB-AS/ticket/pull/29 and https://www.figma.com/design/ufJRKSCxQzNpFVlrKsdaKd/Skoleskyss?node-id=510-19558&t=c3Lu2M3gXCnmeb4T-0
=> feat: add error message for school ticket consumption

src/recent-fare-contracts/use-recent-fare-contracts.ts
Fixes a crash that happens when you have "Recent Tickets" purchased in around 2024, I think the newly updated recent tickets endpoint caused this, so we need to guard this by checking if the zones are defined or not in the code.
To test this, use test account 45645645 and open the ticket purchase screen.
Backend team will make a fix as well on their side.
Acceptance Criteria: 
- [ ] App does not crash if the recent ticket doesn't have zones, try account 45645645
=> fix: don't read zones if there are no zones on recent ticket results.

src/modules/payment/ExpiryMessage.tsx, src/modules/payment/SinglePaymentMethod.tsx, src/modules/payment/index.ts, src/modules/payment/previous-payment-utils.ts, src/modules/ticketing/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentMethodsScreen.tsx, src/translations/screens/subscreens/PaymentMethods.ts
Add functionality to show card or registration expiry dates, displaying appropriate messages for expired or soon-to-expire payment cards.
<p>
</p>
</details> 
closes https://github.com/AtB-AS/kundevendt/issues/20096
=> feat: show expiry message for saved payment card

ios/departureWidget/Views/ChipView.swift, ios/departureWidget/Views/DepartureTimesView.swift, ios/departureWidget/Views/WidgetInfoView.swift
This fixes an issue where the widget would have unreadable information if tinted/accented mode is enabled on iOS 18.
=> fix: support tinted variant of widget

src/modules/native-bridges/widget-updater.ts
Fixes issue `Cannot read property 'refreshWidgets' of null` from [BugSnag](https://app.bugsnag.com/atb-as/mittatb/errors?filters[event.since]=all&filters[app.release_stage][]=store&filters[app.release_stage][]=production&filters[search][]=refresh&filters[search][]=widgets&filters[app.type]=android)
1. Go to departures/avganger
2. Select any bus stops
3. Select any bus departures
4. Mark as favorite
5. Select any options that are shown on the bottom sheet
6. App crashes
=> fix: prevent crash on Android when selecting favorite departure

src/components/date-selection/DatePickerSheet.tsx, src/components/date-selection/DateSelection.tsx, src/components/date-selection/index.ts, src/components/date-selection/types.ts, src/date-picker/index.ts, src/date-picker/types.ts, src/modules/map/components/DeparturesDialogSheet.tsx, src/screen-components/place-screen/PlaceScreenComponent.tsx, src/screen-components/place-screen/components/QuayView.tsx, src/screen-components/place-screen/components/StopPlacesView.tsx, src/screen-components/place-screen/index.tsx, src/screen-components/place-screen/types.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/StartTimeSelection.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/use-favorite-departure-data.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-non-transit-trips-query.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/utils.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/types.ts
The DateSelection-component is widely used in the app, not just in the place-screen component. For this reason I propose moving it in together with the `DatePickerSheet`, since those two are very reliant on each other. 
Also renamed the component to `date-selection`, since the component is a little broader than just picking a date (previous day, next day, now etc).
=> refactor: Moved DateSelection from place-screen to date-picker

ios/atb.xcodeproj/project.pbxproj
Some of the features used in c0d3da03 requires iOS 16, and makes the build fail, since it targets iOS 15 and above. It's easier to bump the minimum version than to add version checks, and will affect a negligible amount of users, so I propose we do that for the widget and intent. (not the app itself)
=> fix: set minimum iOS version for widget to 16.6

package.json, yarn.lock
fixes issue that is related to zod for shared mobility.
- config-specs 5.13.0 has build issue, although apparently it is working for the shared mobility.
- config-specs 5.15.0 fixes this build issue, but it breaks the functionality from 5.13.0
- config-specs 5.16.0 fixes the build issue, and restore the functionality for shared mobility. ⬅️ **THIS PR**
=> fix: shared mobility fetching issue from firestore

src/modules/mobile-token/hooks/use-validate-token.tsx, src/modules/mobile-token/tokenService.ts
closes https://github.com/AtB-AS/kundevendt/issues/20603
The changing of endpoint itself is trivial, but to make this work, it requires the PR below from Platform Team (all merged and ready)
- [Fixing cleanup function](https://github.com/AtB-AS/token/pull/29), before the PR, the newly activated token is immediately removed, causing the token to always turn to fallback state.
- [Expose device details](https://github.com/AtB-AS/token/pull/28), without this PR, tokens will always be renewed once it is activated, because the logic check returns undefined.
- [Change to v1 instead of v4](https://github.com/AtB-AS/token/pull/27), fixes routing issue
- [Add inspection](https://github.com/AtB-AS/token/pull/25), fixes missing inspection issue.
=> feat: change to new token server endpoint

src/modules/ticketing/TicketingContext.tsx, src/modules/ticketing/use-fare-contracts.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_AvailableFareContractsTabScreen.tsx
The fare contracts pull-to-refresh feature was using some old state for the `refreshing` param, that was always false. We should instead use the `isRefetching` value from useQuery.
=> fix: use correct state for fare contract pull-to-refresh spinner

src/modules/fare-contracts/FareContractAndReservationsList.tsx, src/modules/fare-contracts/__tests__/sort-fc-or-reservation.test.ts, src/modules/fare-contracts/index.ts, src/modules/fare-contracts/sort-fc-or-reservation.ts, src/screen-components/ticket-history/TicketHistoryScreenComponent.tsx
Had a talk with @Mariblaas, and we agreed that it doesn't make sense to show reservations at the top of ticket history. We should rather always sort by creation date, so that the user doesn't have to scroll past lots of old cancelled payments before reaching their previous purchase.
=> feat: sort ticket history page by creation

src/modules/map/hooks/use-active-shmo-booking.tsx, src/modules/mobility/components/ShmoTripCard.tsx, src/modules/mobility/components/sheets/ActiveScooterSheet.tsx, src/modules/mobility/queries/use-active-shmo-booking-query.tsx
Closes http://github.com/AtB-AS/kundevendt/issues/20598
We need to handle cases where entur force end the trip without a user action. So if entur ends the trip, they will set the booking to FINISHED so we skip the photo stage and just closes the scootersheet and cleans up the state
=> feat: added forceEnd when there is no active booking

src/api/use-subscription.ts, src/modules/event-stream/handle-stream-event.ts, src/modules/event-stream/index.ts, src/modules/event-stream/types.ts, src/modules/event-stream/use-setup-event-stream.ts, src/modules/feature-toggles/toggle-specifications.ts, src/modules/remote-config/remote-config.ts, src/modules/ticketing/TicketingContext.tsx, src/modules/ticketing/api.ts, src/modules/ticketing/use-fare-contracts.ts, src/queries/ReactQueryProvider.tsx, src/queries/index.ts, src/queries/use-setup-react-query-window-focus.tsx, src/stacks-hierarchy/RootStack.tsx, src/utils/__tests__/json-string-to-object.test.ts, src/utils/object.ts
This implements the first iteration of using the [stream service](https://github.com/AtB-AS/stream/) to rely on websocket events to fetch fare contracts from the backend, outside of firestore. It's feature toggled, which means we'll be able to roll out gradually.
It works like this: 
1. On app launch, a websocket connection is created to `/stream/v1`. The thought is to keep this connection open as long as the app is running.
2. When the app receives a message on the format `{ event: "FARE_CONTRACT" }`, we tell the react query client to invalidate queries with queryKey `"FETCH_FARE_CONTRACTS"`, which will make fare contract data stale globally, and cause a reload wherever it's used.
4. In the ticketing context, we'll ignore fare contract snapshots from Firestore (as long as the feature …
=> feat: use stream service to reload fare contracts

src/modules/map/components/SelectedFeatureIcon.tsx, src/modules/map/components/mobility/GeofencingZones.tsx, src/modules/map/components/mobility/VehiclesAndStations.tsx, src/modules/map/components/national-stop-registry-features/NationalStopRegistryFeatures.tsx, src/modules/map/hooks/use-mapbox-json-style.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/20702
There is a problem in mapbox that `layerIndex` doesn't work.
However, using `aboveLayerId` works well.
In this PR, new placeholder layers are added so that we have full control over the layer order.
Current order, from bottom to top:
```ts
const slotLayerIds: MapSlotLayerId[] = [
MapSlotLayerId.GeofencingZones, // bottom
MapSlotLayerId.Vehicles,
MapSlotLayerId.Stations,
MapSlotLayerId.NSRItems,
MapSlotLayerId.SelectedFeature, // top
];
```
How to place a `SymbolLayer`:
```ts
aboveLayerID={MapSlotLayerId.Stations}
```
=> feat: Add Slot Layers

src/screen-components/travel-details-screens/DepartureDetailsScreenComponent.tsx
refer to this slack message: https://mittatb.slack.com/archives/C0116FMPX4Y/p1748107469811009
The app crashes because no polyline data is received from the BFF, so the solution here should be to hide the "Show Trip" button if we don't receive any polyline data from BFF. Which should completely fix this bugsnag issue: https://app.bugsnag.com/atb-as/mittatb/errors/6788c603c88e184232652ed0?filters[event.since]=all&filters[app.release_stage]=store
I have put a fix from the BFF side here: https://github.com/AtB-AS/atb-bff/pull/390
=> fix: hide `Show Trip` button if no polyline is received

package.json
Builds are failing randomly, but more recently, and it might be because some machines have different versions of yarn, and the workspace is something needed for recent versions of yarn.
=> fix: Remove yarn workspace

src/modules/map/MapContext.tsx, src/modules/mobility/components/sheets/ScooterSheet.tsx, src/modules/mobility/components/sheets/SelectShmoPaymentMethodsSheet.tsx, src/modules/payment/hooks/use-selected-shmo-payment-method.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/20604
Ended up reworking how we keep track of paymentcards in the shmo payment bottomsheet. Now we only rely on the last used card, and when we select cards in the bottomsheet we save the card to last used instead of setting it to state
=> feat: simplified the previous payment logic

src/api/utils.ts, src/modules/mobile-token/MobileTokenContext.tsx, src/modules/mobile-token/hooks/use-get-signed-token-query.tsx, src/modules/mobile-token/hooks/use-load-native-token-query.tsx, src/modules/mobile-token/hooks/use-preemptive-renew-token-mutation.tsx, src/modules/mobile-token/tokenService.ts, src/modules/mobile-token/utils.ts
closes https://github.com/AtB-AS/kundevendt/issues/20605
This adds implementation of error handling for the new token server endpoint.
Also in this PR:
- More inline documentation for various mobile-token related functions & hooks
- Removes redundant error checking
- use `nullish` instead of `optional` for the `ErrorResponse`
=> feat: new mobile token endpoint error handling

package.json, yarn.lock
closes https://github.com/AtB-AS/kundevendt/issues/20755
Theme package is updated because asset 17.2.2 requires theme 14.0.1
=> feat: update assets for better contrast

src/modules/mobility/queries/use-bike-station-query.tsx, src/modules/mobility/queries/use-car-station-query.tsx, src/modules/mobility/queries/use-vehicle-query.tsx
E.g. when scanning a vehicle very shortly after someone else has parked it, the GBFS data may not be updated yet.
If so, the user will get an error, and because of caching, this would continue to show as a missing vehicle even after the data has been updated.
To fix this, vehicles and stations are always refetched with this PR.
Acceptance Criteria:
Every time a bottom sheet is opened, a new request should be sent to get the data
=> fix: Always refetch shmo items on mount

src/modules/bonus/components/EarnedBonusPointsSectionItem.tsx, src/modules/fare-contracts/FareContractView.tsx, src/translations/screens/subscreens/BonusProgram.ts
closes: https://github.com/AtB-AS/kundevendt/issues/19985
fixes bug: https://github.com/AtB-AS/kundevendt/issues/19985#issuecomment-2962210679
- Tickets in ticket history overview now never displays points earned
fixes bug: https://github.com/AtB-AS/kundevendt/issues/19985#issuecomment-2962259569
- Issues related to line change when rendering bold markdown text is solved by not using markdown, rather splitting text and using `typography="body__tertiary--bold" ` for bold text
=> fix: bonus points on ticket issues

src/modules/bonus/components/PayWithBonusPointsCheckbox.tsx, src/modules/bonus/components/UserBonusBalance.tsx, src/modules/mobility/components/BikeStationBottomSheet.tsx, src/modules/mobility/components/CarSharingStationBottomSheet.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_BonusScreen.tsx, src/translations/screens/subscreens/BonusProgram.ts
closes: https://github.com/AtB-AS/kundevendt/issues/20886
Updates design and fixes related to bonus. Specifically:
On the profile page:
1. Put bonus products in same section (instead of separate sections)
For the checkbox on Bonus products in bottom sheets:
1. fix so that the checkbox is always unchecked when it is disabled
2. Change from 'Du har 42 ★' to 'Du har 42 poeng'
=> fix: bonus product design and checkbox text and functionality

README.md
`cd -` navigates to the previous directory, which is the ios directory when we use `cd ../android` in the previous step.
=> docs: update rebuild command

package.json, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_BonusScreen.tsx, src/theme/ThemedAssets.tsx, yarn.lock
closes https://github.com/AtB-AS/kundevendt/issues/20669
Adds correct illustrations to bonus profile page
=> feat: add bonus illustrations

src/screen-components/travel-details-screens/DepartureDetailsScreenComponent.tsx, src/screen-components/travel-details-screens/components/Trip.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
Adds `publicCode` / `publicCodes` as strings to departure details, trip details and trip results, so that we can add global messages for specific line numbers.
Also adds `publicCodeAsNumber` to departure details, so line numbers in a range can be targeted, which can be useful for cases like 100-999 for regional buses. This is harder to do with the rule engine when there is more than one public code.
=> feat: add publicCode to global message contexts

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
Items under "My account" should have medium padding according to [Figma](https://www.figma.com/design/zdZwvobgpEWSagKt0tderx/App?node-id=33082-21132&t=OObkchPhDTYuvzb3-0). 
<div>
</div>
=> fix: update padding on top section in my profile

src/modules/map/hooks/use-map-symbol-styles.ts
Closes https://github.com/AtB-AS/kundevendt/issues/20290
Now every type of map icon is minimized when another map item is selected, including vehicle clusters.
A `+` is shown instead of the cluster count in this state.
| <img width="250" src="https://github.com/user-attachments/assets/ed18414a-6963-42d8-a816-6980c5b89d15" /> | <img width="250" src="https://github.com/user-attachments/assets/92408339-8fc1-4561-8f6f-a577f4a918fd" /> |
| <img width="250" src="https://github.com/user-attachments/assets/4a5e5712-51db-4e67-ac8b-43ce931109e2" /> | <img width="250" src="https://github.com/user-attachments/assets/b9628225-abee-4530-9c07-8814cc2da53c" /> |
=> feat: Minimize vehicle clusters

src/stacks-hierarchy/Root_SmartParkAndRide/Root_SmartParkAndRideAddScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/translations/screens/Profile.ts, src/translations/screens/subscreens/SmartParkAndRide.ts
Reorganize the profile page layout by moving the enrollment link section to improve user navigation. Update text for the Smart Park & Ride label to reflect the correct translation.
=> fix(spar): move profile page link

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SmartParkAndRideScreen.tsx
Use the existing util function, `spellOut`, instead of adding periods to the a11y label. Android didn't handle the periods well.
related https://github.com/AtB-AS/kundevendt/issues/20818
=> fix: use util function for license plate a11y text

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_BonusScreen.tsx, src/translations/screens/subscreens/BonusProgram.ts
closes https://github.com/AtB-AS/kundevendt/issues/21045
Adds feedback button to Intercom to bonus page.
=> feat: add feedback button to Bonus Screen

src/translations/screens/subscreens/Enrollment.ts
closes https://github.com/AtB-AS/kundevendt/issues/21088
Updates header text for new concepts screen.
Also removes unused text.
=> fix: rename new concepts header and remove unused text

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_EnrollmentScreen.tsx
closes: https://github.com/AtB-AS/kundevendt/issues/21088#issuecomment-3018587810
Adds KeyboardAvoidingView to Enrollment screen so user can see input field with keyboard even with 2x screen.
Before: with 2x zoom user can not scroll down to see input field when keyboard is present
After: user can scroll all the way down with keyboard present (also I'm listening to Åge Aleksandersen in this screenshot, but ignore that difference 🙈)
=> fix:scroll with keyboard on 2x view enrollment screen

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchFiltersBottomSheet.tsx, src/translations/screens/TripSearch.ts
closes https://github.com/AtB-AS/kundevendt/issues/21033
This removes the checkbox to save travel search filters in the bottom sheet, and instead uses what seems to be sensible defaults: Walking speed and transfer time is always stored between searches, while transport modes are always reset between each search.
=> feat: persist travels search preferences, reset mode filters

src/modules/popover/types.ts, src/modules/travel-search-filters/index.tsx, src/modules/travel-search-filters/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/CityZoneMessage.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-travel-search-filters-state.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-trips-query.ts, src/translations/components/OneTimePopOver.ts
- Stores the dismissed state only per travel search, and not permanently in filters. This fixes https://github.com/AtB-AS/kundevendt/issues/21086
- Cleans up some filter logic that we don't need anymore when flexible transport isn't an option.
- Removes the illustration in the info box, to make it more compact.
<div>
</div>
fixes https://github.com/AtB-AS/kundevendt/issues/21086
=> fix: use local state to show and hide flex transport info

src/modules/smart-park-and-ride/api/api.ts, src/modules/smart-park-and-ride/index.tsx, src/modules/smart-park-and-ride/queries/use-delete-vehicle-registration-mutation.ts, src/stacks-hierarchy/Root_SmartParkAndRide/Root_SmartParkAndRideEditScreen.tsx, src/translations/screens/subscreens/SmartParkAndRide.ts
> [!WARNING]
> This PR is dependent on https://github.com/AtB-AS/spar/pull/8 to work.
Implement functionality to delete vehicle registrations, including a confirmation dialog and associated hooks for managing the deletion process.
<p>
</p>
</details> 
fixes https://github.com/AtB-AS/kundevendt/issues/20887
=> feat(spar): delete vehicle registration

e2e/test/pageobjects/travelsearch.filter.page.ts, e2e/test/specs/travelsearch.filter.e2e.ts, src/components/radio/RadioSegments.tsx
A fix for the E2E filter tests after https://github.com/AtB-AS/mittatb-app/pull/5300:
- Transport mode filters should NOT be saved for next search
- Preferences like walk speed should be saved for next search
NOTE! Added a test-id on the filter preferences.
=> test: fix e2e filter tests

src/stacks-hierarchy/Root_SmartParkAndRide/Root_SmartParkAndRideAddScreen.tsx, src/stacks-hierarchy/Root_SmartParkAndRide/Root_SmartParkAndRideEditScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SmartParkAndRideScreen.tsx, src/translations/screens/subscreens/SmartParkAndRide.ts
Implement error handling to display messages when editing or deleting vehicle registrations fails. 
Note: I am aware that both of the error messages are showing at the same time, if the user gets in a situation that can provoke both errors at the same time. I see it as okay.
<p>
</p>
</details>
=> feat(spar): show error when edit/delete fails

src/stacks-hierarchy/Root_ConsiderTravelTokenChangeScreen/Root_ConsiderTravelTokenChangeScreen.tsx, src/stacks-hierarchy/Root_ConsiderTravelTokenChangeScreen/components/NoTravelTokenInfo.tsx, src/stacks-hierarchy/Root_PurchaseAsAnonymousConsequencesScreen.tsx
Fixes observations from https://mittatb.slack.com/archives/C0116FMPX4Y/p1751958946526719
=> fix: use expanded true for buttons in onboarding screens

src/modules/bonus/enrollment/BonusOnboarding_BuyTickets.tsx, src/modules/bonus/enrollment/BonusOnboarding_Download.tsx, src/modules/bonus/enrollment/BonusOnboarding_MoreTravelMethods.tsx, src/modules/bonus/enrollment/BonusOnboarding_WelcomeScreen.tsx
This seems to work!
I think this shows that we should be careful using component.name in the future, seems to not work as expected in production on iOS
=> fix: sending in component name as string

src/components/sections/items/ExpandableSectionItem.tsx, src/components/sections/items/LinkSectionItem.tsx, src/components/sections/items/ToggleSectionItem.tsx, src/components/tag/Tag.tsx, src/modules/bonus/components/EarnedBonusPointsSectionItem.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx, src/translations/components/TagInfo.ts
Addresses comment: https://github.com/AtB-AS/kundevendt/issues/19985#issuecomment-2962270032
Voice over now says 'new functionality' or 'beta functionality' to be more descriptive for voice over users.
=> feat: add voice over to label/Tag

src/components/sections/items/LinkSectionItem.tsx, src/components/theme-icon/ThemeIcon.tsx, src/components/theme-icon/index.ts, src/modules/fare-contracts/components/ActivateNowSectionItem.tsx, src/modules/fare-contracts/components/ConsumeCarnetSectionItem.tsx, src/modules/fare-contracts/components/RefundSectionItem.tsx, src/modules/storybook/stories/Section.stories.tsx, src/screen-components/favorite-departures/FavoriteDeparturesScreenComponent.tsx, src/screen-components/place-screen/components/QuaySection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcement.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_BonusScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DeleteProfileScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FavoriteListScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_HelpAndContactScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_InformationScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentMethodsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PrivacyScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SettingsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SmartParkAndRideScreen.tsx
Adds `rightIcon` and `leftIcon` props to LinkSectionItem, using the same patterns as the Button component, as well as adds icons to the Profile and Settings page.
closes https://github.com/AtB-AS/kundevendt/issues/20067
=> feat: add icons to LinkSectionItems in Profile

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SmartParkAndRideScreen.tsx, src/translations/screens/subscreens/SmartParkAndRide.ts
Added a conditional check to hide the add button if the number of registered vehicles has been met, and show information text if so.
<p>
</p>
</details>
=> feat(spar): hide add button if max no. of vehicles

__mocks__/hooks.ts, __mocks__/imports.ts, __tests__/utils.test.ts, src/modules/fare-contracts/__tests__/fare-contract-validity-units.test.ts, src/screen-components/travel-details-screens/__tests__/get-should-show-live-vehicle.test.ts, src/screen-components/travel-details-screens/__tests__/has-short-wait-time-and-not-guaranteed-correspondance.test.ts
By putting mocks of common imports and hooks in `__mocks__/`, they will apply to all tests in the repo. This way, we can be slightly less careful about which imports are present in the files we tests.
=> test: extract jest mocks to __mocks__ folder

src/modules/time/TimeContext.tsx, src/modules/time/index.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
Some logic that to update the time context's `now` was overwritten in https://github.com/AtB-AS/mittatb-app/pull/5342, so adding it back here. Also improves on some names and comments, and add display of server time offset in the debug menu 🕺
=> fix: update time context every second

src/components/screen-header/chat/ContactSheet.tsx, src/components/screen-header/chat/use-chat-icon.tsx, src/components/theme-icon/NotificationIndicator.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/translations/screens/Profile.ts
- Adds a "Gi tilbakemeldinger om appen" section item to Profile
- Adds a notification indicator to the Profile icon in the tab bar that shows when the user has received a intercom message.
- Changes intercom notifications to be red/error, instead of green/valid.
- Some changes to notification indicators in general, done together with @oyvindmikkelsenatb
- Offsets the notification indicator slightly away from the icon (globally).
- Changes the travel search filter notification indicator to be blue/info instead of green/valid.
closes https://github.com/AtB-AS/kundevendt/issues/20068
=> feat: add feedback section item in Profile

src/modules/smart-park-and-ride/api/api.ts
Adds a `skipErrorLogging` for the search vehicle endpoint. We don't need error logging for failed searches.
=> fix(spar): skip error logging when 400 for search-vehicle

src/modules/smart-park-and-ride/onboarding/SmartParkAndRideOnboarding_AutomaticRegistrationScreen.tsx, src/modules/smart-park-and-ride/onboarding/SmartParkAndRideOnboarding_InformationScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SmartParkAndRideScreen.tsx, src/translations/screens/subscreens/SmartParkAndRide.ts
Add section to inform the user how it works. It navigates to the onboarding stack.
<p>
</p>
</details> 
fixes https://github.com/AtB-AS/kundevendt/issues/20819
=>  feat(spar): add information page 

src/components/line-with-vertical-bars/LineWithVerticalBars.tsx, src/modules/fare-contracts/components/WithValidityLine.tsx
Fix for the pixel peepers on the fare contract validity line. The line would overflow by 1px horizontally due to the section item border, and the animated lines would disappear a bit too early.
https://github.com/user-attachments/assets/f302873b-84eb-4753-abbc-edfc2d65301b
https://github.com/user-attachments/assets/716664ff-eedb-40e7-b2bb-35566cd40c7d
=> fix: improve validity line animation

src/screen-components/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx
Small issue found by @hanne-at-atb . Missing SafeAreaInsets on SelectTravelTokenScreenComponent. 
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
=> fix: Added safeAreaInsets in SelectTravelTokenScreenComponent

package.json, yarn.lock
Fixes another issue found while testing https://github.com/AtB-AS/kundevendt/issues/20064
Now looks like this: 
<details>
</details>
=> fix: Bump design system to 18.3.1 to fix swapped icons and colors

src/modules/mobility/queries/use-geofencing-zones.tsx
Geofencing zone data has been observed to be changed by operators more often than expected.
E.g. by adding slow zones in the morning and evening if there is a chance of frost.
Due to the bug discovered and fixed in https://github.com/AtB-AS/mittatb-app/pull/5348, it turns out we used to have a cache time of only 12 minutes. After the fix it is 12 hours, but now setting it to 1 hour instead.
=> fix: Use cacheTime 1 hour for geofencing zones

src/stacks-hierarchy/Root_SmartParkAndRide/Root_SmartParkAndRideAddScreen.tsx
Add focus handling to the title heading for the add screen. This is to fix the focus of e.g. VoiceOver, so that the focus is not on the button, but on the heading.
fixes https://github.com/AtB-AS/kundevendt/issues/20815
=> fix(spar): focus heading on add screen

src/translations/screens/subscreens/Enrollment.ts
closes https://github.com/AtB-AS/mittatb-app/pull/5380
resolves [discussion](https://github.com/AtB-AS/mittatb-app/pull/5380#issuecomment-3204789905) with @hanne-at-atb & @hannahATB
=> fix: updating enrollment text to say with users

src/components/screen-header/use-ticket-info.tsx, src/modules/configuration/FirestoreConfigurationContext.tsx, src/modules/fare-contracts/FareContractView.tsx, src/modules/fare-contracts/components/FareContractDescription.tsx, src/modules/fare-contracts/components/FareContractFromTo.tsx, src/modules/fare-contracts/components/ProductName.tsx, src/modules/fare-contracts/components/TravelInfoSectionItem.tsx, src/modules/fare-contracts/components/WithValidityLine.tsx, src/modules/notifications/use-has-fare-contract-with-activated-notification.tsx, src/modules/ticketing/use-fare-contracts.ts, src/modules/ticketing/use-get-fare-products-query.tsx, src/recent-fare-contracts/use-recent-fare-contracts.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByAlias.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByProducts.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-product-alternatives.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/CompactFareContracts.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FareContractsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_AvailableFareContractsTabScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContracts.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx, src/stacks-hierarchy/Root_TicketInformationScreen/Root_TicketInformationScreen.tsx, src/utils/durations.ts
- Uses `useGetFareProductsQuery` instead of `useFirestoreConfigurationContext` for all uses of `preassignedFareProducts`
- Persists fare products in local storage, which is cached for one week, the same as fare contracts.
- Makes pull to refresh on the active tickets and purchase tab reload preassigned fare products.
- Removes the reliance of firestore data entirely.
Note: If we want to keep the fallback to firestore data for a bit longer, 143ea65e4b6e0d2a737367ef6d4b253dd5a5ea21 can be reverted.
closes https://github.com/AtB-AS/kundevendt/issues/17568
=> feat: use products api instead of firestore

src/components/bottom-sheet/AnimatedBottomSheet.tsx
Fixes https://github.com/AtB-AS/kundevendt/issues/21415
The black status bar on the top should be gone after this change.
The fix is to always paint something (even though invisible) everywhere on the screen, which wasn't necessarily the case with the existing AnimatedBottomSheet.
The first video in the issue may not be fixed though, but likely will be in https://github.com/AtB-AS/kundevendt/issues/18903.
Specifically targets fixing this problem:
<video width="250" src="https://github.com/user-attachments/assets/7971bb03-df21-4f4f-9217-ffb14b2ccc48" />
=> fix: alwaysPaintOnEntireScreenToAvoidFlicker

package.json, yarn.lock
While working with https://github.com/AtB-AS/mittatb-app/pull/5318, I noticed that we only have zod available through indirect dependencies.
Added with `yarn add zod@^3.24.4`, since that was the selected version we happened to be on from before (causing no change to yarn.lock)
=> Add zod to package.json

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_InformationScreen.tsx, src/translations/screens/Profile.ts
After a meeting with FRAM, we decided to include a link to service disruptions on Profile.
=> feat: add service disruption link to profile information screen

src/modules/smart-park-and-ride/components/LicensePlateSection.tsx
Increase the maximum length for license plate input from 9 to 14 characters to accommodate longer license plate formats.
partly fixes https://github.com/AtB-AS/kundevendt/issues/21101
=> fix(spar): update max length of license plate input

src/modules/mobile-token/hooks/use-get-signed-token-query.tsx
This fixes an issue with stale Aztec codes when someone closes the app and reopens directly to ticketing details where the barcode is visible. This should work as `useSetupReactQueryWindowFocus` is used in root view.
NOTE: I am still unable to get the app running locally, so I haven't verified the fix my self. 😬
---
From Slack:
> The Aztec is replaced every X seconds (currently 10?). But the content it self is valid for Y seconds. When validating now we some times get error ("Ugyldig kortinnhold" in MT Buss. Essentially no travel right). I think this is might be due to that the read barcode becomes invalid when trying to be validated. For instance, if X = Y and it took 4 seconds to parse and read the barcode, you could have situations where right before the Aztec is replaced, it will be …
=> fix: refresh mobile token on window focus always

src/modules/fare-contracts/details/Barcode.tsx, src/modules/remote-config/remote-config.ts
For the FRAM Aztec rollout, we'd like to be able to tweak dimensions via remote config.
Defined `aztec_code_max_height` and `aztec_code_padding` for this. The current values have been preserved as defaults. 
~~The default setup using `themes['light'].spacing.large` doesn't seem ideal, so open to other approaches!~~
Initial proposal (first commit):
> Since the padding default is retrieved from `theme`, we can't give a proper default from the start (`RemoteConfigContextProvider` is not wrapped by `ThemeContextProvider`). Also, remote config only supports `string | number | boolean` defaults. I chose to use `Number.MIN_SAFE_INTEGER` as a `undefined`/`null` alternative. `NaN` would make more sense, but causes errors in React Native. Also, `Number.MIN_SAFE_INTEGER` will have the safe effect as …
=> feat(aztec): remote configurable aztec code dimensions

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/AnnouncementSection.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/AnnouncementSheet.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx, src/translations/screens/Dashboard.ts
=> feat: update announcements styling

package.json, src/modules/smart-park-and-ride/enrollment/SmartParkAndRideOnboarding_AutomaticRegistrationScreen.tsx, src/modules/smart-park-and-ride/enrollment/SmartParkAndRideOnboarding_InformationScreen.tsx, src/screen-components/smart-park-and-ride/Root_SmartParkAndRideAddScreenComponent.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_SmartParkAndRideScreen.tsx, src/theme/ThemedAssets.tsx, yarn.lock
Introduce new themed car illustrations for the Smart Park and Ride onboarding screens and update the dependency for asset generation.
<p>
|Before|After|
|---|---|
|<img width="1206" height="2622" alt="image" src="https://github.com/user-attachments/assets/1eb24ead-23ea-4714-a112-97c537858448" />|<img width="1206" height="2622" alt="image" src="https://github.com/user-attachments/assets/643b45fd-6ace-48b9-a2d4-93143cd2c2a2" />|
|<img width="1206" height="2622" alt="image" src="https://github.com/user-attachments/assets/cf5df15f-3598-4722-9091-0a7b3319b5e6" />|<img width="1206" height="2622" alt="image" src="https://github.com/user-attachments/assets/86aa2a15-a934-43ac-b614-ddad71ee991a" />|
|<img width="1206" height="2622" alt="image" …
=> feat(spar): add new illustrations for Smart Park and Ride 

src/modules/fare-contracts/FareContractView.tsx, src/modules/fare-contracts/components/ActivateNowBottomSheet.tsx, src/modules/fare-contracts/components/ActivateNowSectionItem.tsx, src/modules/fare-contracts/components/ConsumeCarnetBottomSheet.tsx, src/translations/screens/FareContract.ts
Task from markhor shaving hours: Updates design of activate single ticket to try to reduce the amount of tickets activated by mistake.
- Adds interactive color to "Start ticket now" button, and moves it below the details button.
- Adds cancel button to activate and consume bottom sheet.
https://github.com/user-attachments/assets/dfdd65e1-1e98-4187-b3ce-839d86b57633
=> feat: add cancel button to consume and activate fc bottom sheet

src/components/text/ThemeText.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_AppearanceScreen.tsx, src/theme/ThemeContext.tsx, src/translations/screens/subscreens/AppearanceSettings.ts
As a suggestion from _markhor shaving hours_, it was proposed to change the two toggles on the appearance settings screen to three radio buttons instead. While working on this, I found the ThemeContext quite hard to understand, so I renamed some fields, and refactored it quite a bit to fit the new kind of selection 🤓
<div>
</div>
=> feat: update appearance settings page

src/api/identity.ts, src/modules/mobility/components/ShmoActionButton.tsx, src/modules/mobility/components/onboarding/AgeVerificationScreenComponent.tsx, src/modules/mobility/components/sheets/ScooterSheet.tsx, src/modules/mobility/index.ts, src/modules/mobility/queries/use-complete-age-verification-mutation.tsx, src/modules/mobility/queries/use-get-age-verification-query.tsx, src/modules/mobility/use-shmo-requirements.tsx, src/stacks-hierarchy/Root_ShmoOnboardingScreen.tsx, yarn.lock
closes https://github.com/AtB-AS/kundevendt/issues/21511
Uses legal age per operator from firestore.
If no value is set for operator in firestore, the legal age is assumed to be 0.
=> feat: use legal age from firestore

src/components/screen-footer/FullScreenFooter.tsx, src/modules/fare-contracts/components/ActivateNowBottomSheet.tsx, src/modules/fare-contracts/components/ConsumeCarnetBottomSheet.tsx, src/modules/fare-contracts/components/RefundBottomSheet.tsx, src/modules/fare-contracts/details/DetailsContent.tsx, src/stacks-hierarchy/Root_PurchaseHarborSearchScreen/Root_PurchaseHarborSearchScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/AnnouncementSheet.tsx, src/stacks-hierarchy/Root_TicketInformationScreen/Root_TicketInformationScreen.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/21412
Since Android 15 the bottom navbar (onscreen/software) has changed behavior. Before 15 the area behind/"under" the navbar was not drawable area, but since 15 it is. Android calls it "edge-to-edge enforcement". 
To handle the previous situation we have a lot of `Math.max(bottomSafeAreaInset, theme.spacing.medium)` which in practice meant that for Android we used `theme.spacing.medium` while for iOS we used `bottomSafeAreaInset`. But after the change that falls down and some screens now don't have any padding any more, or UI elements are hidden behind the navbar 
<details>
<summary>Before and after images</summary>
| <img width="200" src="https://github.com/user-attachments/assets/fe02736a-8099-4e1 …
=> fix: Fixed bottom navbar hiding some UI elements 

src/modules/smart-park-and-ride/queries/use-get-vehicle-registrations-query.ts
The RefreshControl's refreshing state was showing every time the screen was entered. This was fixed by setting the stale time of the query so that the refetching does not occur each time. The data is updated when manually refetching or when the query is invalidated.
=> fix(spar): set stale time of vehicle registrations query

src/modules/mobility/queries/use-active-shmo-booking-query.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/21087
When the phone is locked when on a trip, it does not get updates about the live pricing. If a user ends the trip after picking up the phone, they might have a stale price, so the jump from that stale price the one in the receipt summary might be a big jump to the user. So we try to keep the live pricing (and active booking) as updated as possible with this fix.
=> fix: update live pricing when reconnecting or gaining focus

src/modules/mobile-token/hooks/use-validate-token.tsx
The assumption is that this is unnecessary in practice, so it's better to avoid hard coding the version.
Follow up to #5453
=> fix: remove internal MOBILE_TOKEN_LIBRARY_VERSION check

src/components/PhotoCapture/PhotoCapture.tsx, src/components/PhotoCapture/ScreenContainer.tsx, src/stacks-hierarchy/Root_ScanQrCodeScreen.tsx, src/stacks-hierarchy/Root_ScooterHelp/Root_ParkingViolationsQrScreen.tsx, src/translations/screens/ParkingViolations.ts, src/translations/screens/subscreens/MobilityTexts.ts
Closes https://github.com/AtB-AS/kundevendt/issues/21308
Adds `overrideThemeName` prop to `ScreenContainer` which is used for Camera screens so they are always dark
Also: updates the texts for taking photos of e-scooters, as they were defined _almost_ the same in two places.
- Considered just making them the same. Opted against it since you _could_ want to add something specific about parking or invalid parking in the future
| camera screens before | camera screens after |
|------------------------|-----------------------|
| <img width="200" alt="image" src="https://github.com/user-attachments/assets/04712aa3-1467-4de9-8990-7ceb505f9548" /> | <img width="200" alt="image" src="https://github.com/user-attachments/assets/84fa54cc-263e-409a-9550-9289dc1e3427" />
=> feat: always black border on camera screen

src/modules/analytics/types.ts, src/modules/announcements/index.ts, src/modules/announcements/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/AnnouncementSection.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/AnnouncementSheet.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/hooks.ts
Also refactor types a bit in an effort to make it more statically typed and clearer to understand
In order to support button for carpooling bottom sheet announcement.
<details><summary>From future design component changes</summary>
<p>
Named button primary to allow for a secondary button down the road, as per new guidelines for bottom sheet:
</p>
</details>
=> feat: Add own action button for bottom sheet

android/README.md
Took some notes while working on https://github.com/AtB-AS/kundevendt/issues/21713, and thought it might be useful for the next person who need to debug android builds. (Including myself)
=> docs: add some notes on building android
