AtB-AS/mittatb-app

src/components/button/index.tsx
src/components/disappearing-header/index.tsx
src/components/search-button/index.tsx
src/favorite-chips/index.tsx
src/favorites/index.tsx
src/screens/Assistant/DateInput.tsx
src/screens/Assistant/FadeBetween.tsx
src/screens/Assistant/index.tsx
src/screens/Nearby/index.tsx
src/screens/Profile/AddEditFavorite/index.tsx
src/screens/Ticketing/Purchase/Payment/CreditCard/index.tsx
src/screens/Ticketing/Purchase/Payment/Vipps/index.tsx
src/screens/Ticketing/Purchase/Travellers/index.tsx
src/screens/Ticketing/Splash/InviteModal.tsx
src/screens/Ticketing/Splash/index.tsx
src/screens/Ticketing/Tickets/Tabs.tsx
src/theme/colors.ts

Also fix issues with FavoriteIcons fill color, and allow Button to control icon fill (shouldn't use ThemeIcon in that case).
Added FadeBetween to fade between two children. Also removed explicit marginBottom on Buttons.

feat: Update favorite chips to use Button

---

src/api/serviceJourney.ts
src/screens/Nearby/NearbyResults.tsx
src/screens/TripDetailsModal/DepartureDetails/index.tsx
src/screens/TripDetailsModal/Details/TransportDetail.tsx

Resolves #687 
Dependant on https://github.com/AtB-AS/atb-bff/pull/53. Must be in production first.

fix: issue with departure view a head of time

---

src/components/map/BackArrow.tsx
src/components/map/PositionArrow.tsx
src/location-search/LocationResults.tsx
src/location-search/LocationSearch.tsx
src/location-search/map-selection/LocationBar.tsx
src/location-search/map-selection/index.tsx
src/screens/TripDetailsModal/Map/index.tsx

- Fixes #670 
- Fixes #671
- Fixes #719 
Note: I've not yet redefined the window flow here. It is still a modal. I think we should talk about the navigation flow at some point.
Examples:

fix: Sync design for search location modal

---

src/components/disappearing-header/index.tsx
src/screens/Assistant/FadeBetween.tsx
src/screens/Assistant/index.tsx
src/screens/Nearby/index.tsx

Less errored fix (and less code), reverting the old fix. Still an issue, but I don't think it is blocking, even though it is annoying:

fix: less buggy workaround animating header (but still not perfect)

---

yarn.lock

Just did `rm -rf node_modules && yarn` on master branch

fix: Yarn.lock

---

package.json
src/components/location-icon/index.tsx
src/components/transportation-icon/index.tsx
src/screens/Assistant/ResultItem.tsx
src/screens/TripDetailsModal/DepartureDetails/index.tsx
src/utils/transportation-color.ts
yarn.lock

Necessary for retrieving tariff zones on geolocation features venues.

chore: Upgrade Entur SKD

---

src/api/geocoder.ts
src/geocoder/use-geocoder.ts
src/screens/Ticketing/Purchase/TariffZones/index.tsx
src/screens/Ticketing/Purchase/Travellers/index.tsx
src/screens/Ticketing/Purchase/index.tsx
src/tariff-zone-search/TariffZoneSearch.tsx
src/tariff-zone-search/VenueResults.tsx
src/translations/screens/subscreens/TariffZoneSearch.ts
src/translations/screens/subscreens/TariffZones.ts

feat: Search for venues when selecting tariff zone

---

src/screens/TripDetails/DepartureDetails/index.tsx
src/translations/screens/subscreens/DepartureDetails.ts

Corrected time/label alignment on middle rows,
Added some missing translations in header

fix: QA adjustments to departure details

---

src/components/sections/counter-input.tsx
src/screens/Ticketing/Purchase/TariffZones/index.tsx
src/screens/Ticketing/Purchase/Travellers/index.tsx
src/tariff-zone-search/TariffZoneResults.tsx
src/tariff-zone-search/VenueResults.tsx
src/translations/components/Section.ts
src/translations/index.ts
src/translations/screens/subscreens/TariffZoneSearch.ts
src/translations/screens/subscreens/TariffZones.ts
src/translations/screens/subscreens/Travellers.ts

Improve accessibility and use internationalization for Travellers
screen.

feat: Improve accessibility for Travellers screen

---

ios/Podfile.lock
package.json
src/components/button/index.tsx
src/components/sections/counter-input.tsx
src/preferences/types.ts
src/screens/Nearby/NearbyResults.tsx
src/screens/Profile/FavoriteDepartures/index.tsx
src/screens/Profile/FavoriteList/SortFavorites.tsx
src/screens/Profile/FavoriteList/index.tsx
src/screens/Profile/Home/index.tsx
src/screens/Profile/Language/index.tsx
src/screens/Profile/index.tsx
src/screens/Ticketing/Purchase/TariffZones/index.tsx
src/screens/Ticketing/Purchase/Travellers/index.tsx
src/screens/TripDetails/DepartureDetails/index.tsx
src/screens/TripDetails/components/TripSummary.tsx
src/tariff-zone-search/TariffZoneResults.tsx
src/tariff-zone-search/VenueResults.tsx
src/translations/LanguageContext.tsx
src/translations/commons.ts
src/translations/components/Section.ts
src/translations/index.ts
src/translations/screens/Profile.ts
src/translations/screens/subscreens/DepartureDetails.ts
src/translations/screens/subscreens/LanguageSettingsTexts.ts
src/translations/screens/subscreens/TariffZoneSearch.ts
src/translations/screens/subscreens/TariffZones.ts
src/translations/screens/subscreens/Travellers.ts
src/translations/screens/subscreens/TripDetails.ts
yarn.lock

* bottom padding in favorite lists ([#816](https://github.com/AtB-AS/mittatb-app/issues/816)) ([baa680e](https://github.com/AtB-AS/mittatb-app/commit/baa680e89a5ac06162b81425c2ca53d84db3d0a0))
* fixes padding on initial state for departures. fixes [#811](https://github.com/AtB-AS/mittatb-app/issues/811) ([#819](https://github.com/AtB-AS/mittatb-app/issues/819)) ([522ff05](https://github.com/AtB-AS/mittatb-app/commit/522ff054e07ee0504d9762aa67fba66e48166221))
* QA adjustments on improved voiceover ([#817](https://github.com/AtB-AS/mittatb-app/issues/817)) ([9d5da87](https://github.com/AtB-AS/mittatb-app/commit/9d5da87abc5b0ec074ce1f9e8d28c5b5a21d1ee9))
* QA adjustments to departure details ([#797](https://github.com/AtB-AS/mittatb-app/issues/797)) …

chore: [Sync] New release to alpha channel

---

src/components/sections/section.tsx
src/tariff-zone-search/TariffZoneMapSelection.tsx
src/tariff-zone-search/TariffZoneSearch.tsx
src/tariff-zone-search/index.tsx
src/translations/index.ts
src/translations/screens/subscreens/TariffZoneMapSelection.ts

Simple implementation, with not-so-pretty zone labels and non-optimal selection method. Can be merged mainly for enabling @pettersuul to get a feel for it while improving the design.

feat: Simple tariff zone map selection

---

src/components/optional-day-header/index.tsx
src/components/theme-icon/index.tsx
src/screens/Assistant/ResultItem.tsx
src/screens/Assistant/Results.tsx
src/theme/colors.ts
src/translations/dictionary.ts
src/translations/screens/Assistant.ts
src/utils/accessibility.ts

Closes #250 
Update to result item view in accordance to new design
Also add support for icon sizing
And screen reader hidden utility (because of high potential of reuse)

feat: Updated view for travel suggestions

---

ios/Podfile.lock
src/RemoteConfigContext.tsx
src/remote-config.ts
src/screens/Ticketing/Splash/index.tsx
src/screens/Ticketing/Tickets/Tabs.tsx
src/screens/Ticketing/Tickets/UpgradeSplash.tsx
src/translations/index.ts
src/translations/screens/UpgradeSplash.ts

feat: Feature toggle for ticket purchasing

---

src/location-search/LocationSearch.tsx

fix: margin on message box for search result

---

src/message-box/index.tsx
src/screens/Ticketing/Purchase/Confirmation/index.tsx
src/screens/Ticketing/Purchase/Overview/index.tsx
src/screens/Ticketing/Purchase/Overview/use-offer-state.ts
src/translations/components/MessageBox.ts
src/translations/screens/subscreens/PurchaseConfirmation.ts
src/translations/screens/subscreens/PurchaseOverview.ts

fix: Allow user to try again when offerSearch fail

---

src/components/disappearing-header/content.tsx
src/components/sections/button-input.tsx
src/screens/Profile/AddEditFavorite/AddForm.tsx
src/screens/TripDetails/DepartureDetails/use-departure-data.ts
src/translations/screens/subscreens/DepartureDetails.ts

- Icon on favorite screen is now cross not arrow.
- increases padding on section input button to allow for breaking long lines.
- Fixes issue with animated content header for details view on android (map taking half height)

fix: misc visual fixes after qa

---

src/chat/use-chat-unread-count.ts
src/utils/use-is-screen-reader-enabled.ts

Not sure if this is the best way. But got annoyed at getting this warning all the time 😬

fix: Fix annoying unmounted race condition on startup

---

src/screens/Ticketing/Ticket/ValidityHeader.tsx

fix: Fix validity header text overflow

---

src/screens/Ticketing/Ticket/ValidityHeader.tsx

From:
2 days and 4 hours and 14 minutes
To:
2 days, 4 hours and 14 minutes

fix: Fix validity header duration text

---

patches/@react-native-mapbox-gl+maps+8.1.0.patch

fix: Map panning bug

---

src/components/message-box/index.tsx
src/components/theme-icon/theme-icon.tsx
src/error-boundary/ComponentErrorView.tsx
src/location-search/LocationSearch.tsx
src/screens/Assistant/Results.tsx
src/screens/Nearby/NearbyResults.tsx
src/screens/Profile/AddEditFavorite/AddForm.tsx
src/screens/Profile/DesignSystem.tsx
src/screens/Profile/FavoriteDepartures/index.tsx
src/screens/Profile/FavoriteList/SortFavorites.tsx
src/screens/Profile/FavoriteList/index.tsx
src/screens/Profile/Home/index.tsx
src/screens/Profile/Login/ConfirmCode.tsx
src/screens/Profile/Login/PhoneInput.tsx
src/screens/Profile/index.tsx
src/screens/Ticketing/Purchase/Confirmation/index.tsx
src/screens/Ticketing/Purchase/Overview/index.tsx
src/screens/Ticketing/Purchase/Payment/CreditCard/index.tsx
src/screens/Ticketing/Purchase/Payment/Vipps/index.tsx
src/screens/Ticketing/Purchase/TariffZones/search/index.tsx
src/screens/Ticketing/Splash/InviteModal.tsx
src/screens/Ticketing/Ticket/Details/ReceiptScreen.tsx
src/screens/Ticketing/Tickets/Tabs.tsx
src/screens/Ticketing/Tickets/UpgradeSplash.tsx
src/screens/TripDetails/components/TripMessages.tsx
src/screens/TripDetails/components/TripSection.tsx
src/screens/TripDetails/components/WaitSection.tsx
src/situations/index.tsx
src/theme/colors.ts
src/theme/index.ts

This updates the` MessageBox` component and `ThemeIcon` component with new Statuses colors as per the Design System. Also adds a hidden tab in Profile which shows different components (icons, texts, buttons, and message boxes).

refactor: updates color for message box and icons

---

src/assets/svg/icons/transportation/Wait.tsx
src/screens/Ticketing/Ticket/ValidityHeader.tsx
src/screens/Ticketing/Ticket/ValidityIcon.tsx
src/screens/Ticketing/Ticket/ValidityLine.tsx
src/screens/Ticketing/Ticket/index.tsx
src/translations/screens/Ticket.ts

The validity icon, text and line were not fully synced with the design.
In addition there was a bug where the expired timestamp were wrong
because of a seconds/milliseconds error.

feat: Fix validity elements

---

src/RemoteConfigContext.tsx
src/remote-config.ts
src/screens/Ticketing/Purchase/Confirmation/index.tsx
src/translations/screens/subscreens/PurchaseConfirmation.ts

Because of corona the VAT is temporary reduced from 12% to 6%. After
this PR we can change the VAT percent in RemoteConfig instead of having
an app release.

feat: VAT (mva) defined in RemoteConfig

---

src/screens/Ticketing/Purchase/Confirmation/index.tsx
src/screens/Ticketing/Purchase/Overview/index.tsx
src/screens/Ticketing/Purchase/Overview/use-offer-state.ts

feat: Handle emtpy offers response as error

---

src/screens/Ticketing/Ticket/Details/DetailsContent.tsx
src/translations/screens/Ticket.ts

The refund functionaility is not yet implemented, and having a disabled
link for refunding ticket has been reported as confusing for the users.

feat: Remove disabled refund link

---

src/alerts/AlertsContext.tsx

Added boolean active on alerts in Firestore for easier turning them on
and off.

feat: Filter on active flag on alerts

---

package.json
yarn.lock

fix: updates @atb-as/theme to fix dark mode contrast. fixes #1012

---

src/api/client.ts
src/api/headers.ts
src/api/utils.ts
src/auth/AuthContext.tsx
src/chat/metadata.ts
src/index.tsx

Logging out the Firebase uid so we can better debug for specific users.

feat: Log Firebase Auth Id in Intercom, Bugsnag and API

---

ios/Podfile.lock
package.json
src/screens/Assistant/FadeBetween.tsx
src/screens/Profile/Home/index.tsx
src/translations/screens/Profile.ts
src/utils/run-timing.ts
src/utils/use-copy-with-countdown.tsx
yarn.lock

Display install-id below furthest down in the Profile-tab. Make it clickable to copy the text, and display alert when you do. Alert text fades out after a bit.
https://user-images.githubusercontent.com/4932625/112430537-96a7cc00-8d3e-11eb-8637-34804ffdd12d.mov

feat: Display installid in Profile-tab

---

src/components/sections/counter-input.tsx
src/components/sections/section-utils/use-section-item.ts
src/screens/Ticketing/Purchase/Travellers/MultipleTravellersSelection.tsx

When selecting multiple travellers it has been reported some usability
issues. These have been fixed by:
- Adding more spacing in the component
- Increasing hitslop for minus/plus button to 12
- Making the minus button disabled when count 0
- Accessibility reader improvements

feat: Improve usability travellers selection

---

src/screens/Profile/Home/index.tsx

feat: Add app version + build number in profile

---

src/screens/Assistant/index.tsx
src/screens/Ticketing/Purchase/index.tsx

Screen transition from Assistant to Trip Details should follow design and behavior from ios.

fix: transitions on android infered from design

---

src/screens/Ticketing/Purchase/Overview/index.tsx
src/screens/Ticketing/Tickets/index.tsx
src/translations/screens/Tickets.ts

added a11y labels for values in the form
added some more helpful labels for ticketing
closes #1158

fix: #1158 a11y read values in buy ticket form

---

src/components/sections/link-item.tsx

fix: #1155 Disable links for disabled form fields in buy ticket form

---

src/navigation/TabNavigator.tsx

setter label-farge med riktig option
closes #1165

fix: contrast on bottom tab navigator

---

src/utils/navigation.tsx

fix: extra padding for bottom navigation on android

---

src/screens/Assistant/ResultItem.tsx

fix: Informative a11y labels on assistant search results

---

src/screens/Ticketing/Purchase/TariffZones/index.tsx

fix: tariff zones flex layout for screen reader

---

src/components/button/index.tsx
src/components/screen-header/full-header.tsx
src/components/text/index.tsx
src/screens/Ticketing/Tickets/TicketInformationalOverlay.tsx
src/screens/Ticketing/Tickets/index.tsx
src/storage/index.ts
src/theme/colors.ts
src/translations/screens/Tickets.ts

This ticket informational screen appears first time the user navigates
to the tickets screen. If the user accepts the presented information,
the informational screen is removed and the user may use the ticketing
functionality.

feat: New ticket informational screen

---

src/departure-list/section-items/more.tsx
src/screens/Ticketing/Ticket/Details/DetailsContent.tsx
src/translations/screens/Tickets.ts

fix: role=button for UU

---

src/screens/Onboarding/WelcomeScreen.tsx
src/screens/Onboarding/index.tsx
src/translations/screens/Onboarding.ts

chore: update onboarding texts

---

src/components/screen-header/index.tsx
src/location-search/map-selection/index.tsx
src/navigation/TabNavigator.tsx
src/screens/Profile/Home/index.tsx
src/translations/dictionary.ts
src/translations/screens/Profile.ts

fix: UU AtB as ATB for a11y

---

src/location-search/LocationSearch.tsx
src/screens/Profile/Home/index.tsx
src/translations/screens/Profile.ts

fix: a11y labels and prevent auto focus on add favourites

---

src/screens/Profile/FavoriteList/SortFavorites.tsx
src/screens/Profile/FavoriteList/SortableListFallback.tsx
src/utils/use-focus-on-load.ts

fixes #1192, fixes #1191, fixes #1189

fix: accessibility for favorites and page title focus on scale transitions

---

src/RemoteConfigContext.tsx
src/index.tsx
src/remote-config.ts
src/screens/Ticketing/Splash/Info.tsx
src/screens/Ticketing/Splash/index.tsx
src/screens/Ticketing/index.tsx
src/tickets/TicketContext.tsx

- Re-enabled ticketing  remote config toggle, to cater for other organisations using the app, where ticketing is not yet implemented in backend.
-  Also removed beta code button on ticketing splash screen since it is not in use anymore.

feat: Re-enabled ticketing toggle and removed beta code button on ticketing splash screen

---

src/translations/screens/subscreens/Information.ts

fix: update ticketing texts

---

src/translations/screens/Tickets.ts

fix: update text Purchase Again

---

src/AppContext.tsx
src/screens/Ticketing/Tickets/Tabs.tsx
src/screens/Ticketing/Tickets/TicketInformationalOverlay.tsx
src/translations/screens/Tickets.ts

Flyttet ticketing states fra component state til app context
fixes #1274

fix: enable ticketing overlay reset

---

src/AppContext.tsx

Fikser feil hvor billetteringssplash vises selv om bruker har godtatt.

fix: issue with splash not being marked as accepted

---

ios/Podfile.lock
src/screens/Nearby/Nearby.tsx
src/screens/Nearby/state.ts

Fikser feil oppdaget i QA av #1328

fix: Feil oppdaget i QA fra #1328

---

src/components/button/index.tsx

disabled buttons are now accessible.
fixes #1194

feat: disabled buttons should be accessible

---

src/components/disappearing-header/index.tsx

fix: fix visual bug where a line would show up in Assistant

---

src/translations/screens/Tickets.ts

Oppdaterer tekst fra _"Betingelser gjelder."_ til _"I en periode gjelder enkelte vilkår for billettkjøp i appen."_
Engelsk _"Some conditions apply."_ til _"For a period, some conditions apply for ticket purchase in the app."_
fixes #1393

fix: update text about conditions around ticket purchase

---

src/components/disappearing-header/index.tsx
src/screens/Assistant/Assistant.tsx
src/screens/Assistant/FadeBetween.tsx

fix: animation heights causes timing issues

---

src/screens/Assistant/Assistant.tsx

fix: block SR search status update when not in focus

---

src/screens/Ticketing/Ticket/Details/ReceiptScreen.tsx
src/translations/screens/Ticket.ts
src/utils/validation.ts

feat: accessible error messages on receipt

---

src/screens/Ticketing/Ticket/Details/DetailsContent.tsx
src/translations/screens/Ticket.ts

feat: accessible QR code

---

src/LocaleProvider.tsx
src/components/sections/date-input/index.android.tsx
src/components/sections/date-input/index.ios.tsx
src/components/sections/time-input/index.ios.tsx
src/index.tsx
src/screens/Assistant/journey-date-picker/index.tsx
src/translations/LanguageContext.tsx
src/translations/commons.ts

fix: locale provider providing correct region (affects ios)

---

src/components/sections/location-input.tsx

fix: TB announces previous results on empty field

---

src/AppContext.tsx
src/RemoteConfigContext.tsx
src/storage/index.ts

fix: More frequent remote config fetches

---

src/translations/screens/subscreens/TripDetails.ts

fix: Unavailable tickets for legs text

---

src/screens/Assistant/Assistant.tsx

fix: do not autoset geolocation if already set

---

src/components/sections/action-item.tsx
src/screens/Profile/Appearance/index.tsx

fix: Switch  anim bug and Switch toggle state bug (android)

---

src/chat/ContactSheet.tsx
src/chat/use-chat-icon.tsx
src/components/bottom-sheet/BottomSheetContext.tsx

fix: accessibility for chat icon

---

src/screens/Nearby/Nearby.tsx

Oppdatert styling etter tilbakemeldinger.

feat: update styling on departures time selection buttons

---

src/chat/ContactSheet.tsx
src/translations/screens/subscreens/ContactSheet.ts

Intercom ikon på ContactSheet vises nå kun når der er uleste meldigner. Oppdaterte også noe tekst på ContactSheet rundt Intercom.

feat: update intercom button to only show icon when unread

---

src/translations/components/Section.ts
src/translations/screens/subscreens/LocationSearch.ts

fix: shorter placeholder texts

---

src/screens/Profile/AddEditFavorite/EmojiSheet.tsx

fix: emoji support for various android versions

---

src/screens/TripDetails/DepartureDetails/index.tsx
src/screens/TripDetails/components/TripSection.tsx
src/translations/screens/subscreens/DepartureDetails.ts

feat: Melding om Ingen avstigning på holdeplasser som ikke tillater det

---

src/setup.ts

Relatert til #1607, vil man få en race condition når man sletter anonym bruker etter installasjon. Legger til `await` for å forhindre dette.

fix: await anonymous user deletion to prevent race condition

---

src/screens/Ticketing/Purchase/Payment/SelectPaymentMethod/index.tsx
src/translations/screens/subscreens/SelectPaymentMethodTexts.ts

Voiceover and talkback missed some states during selection of payment method and saving.

fix: Added accessibility options to buttons

---

src/remote-config.ts
src/screens/Onboarding/index.tsx
src/screens/Profile/Home/index.tsx
src/screens/Ticketing/Tickets/Tabs.tsx

Uten onboarding, for en stille lansering av logg inn

feat: Enable login by default

---

src/assets/svg/icons/ticketing/PaymentBrand.tsx
src/components/bottom-sheet/BottomSheetContainer.tsx
src/preferences/types.ts
src/screens/Ticketing/Purchase/Confirmation/index.tsx
src/screens/Ticketing/Purchase/Payment/SelectPaymentMethod/index.tsx
src/screens/Ticketing/Purchase/types.ts
src/translations/screens/subscreens/PurchaseConfirmation.ts
src/translations/screens/subscreens/SelectPaymentMethodTexts.ts

fix: rework og refactor av lagrede bankkort

---

package.json
src/api/client.ts
src/api/utils.ts
yarn.lock

Including some necessary changes as config.headers now is typed as
optional.

chore: Update axios to 0.23.0

---

.gitignore
ios/Podfile.lock
src/screens/Ticketing/Ticket/Details/QrCode.tsx
src/translations/screens/Ticket.ts

feat: Simple countdown for QR-code 

---

src/screens/Profile/DesignSystem.tsx

Tenkte det kunne vært nyttig å hatt en oversikt over alle farger på design-system skjermen?

feat: add buttons with every theme color to design system

---

src/screens/Profile/ExpiredTickets/index.tsx
src/screens/Profile/Home/index.tsx
src/screens/Profile/index.tsx
src/screens/Ticketing/Tickets/Tabs.tsx
src/screens/Ticketing/Tickets/index.tsx
src/translations/screens/Profile.ts
src/translations/screens/Tickets.ts
src/translations/screens/subscreens/ExpiredTickets.ts

Denne løser to problemer:
1. Enkel løsning på problemet hvor mange utløpte billetter gjør appen tregere
2. Går (veldig delvis) over til nytt design og billetteringsflyt hvor utløpte billetter uansett skal flyttes til Mitt AtB-fanen

feat: Move expired tickets to My AtB tab

---

yarn.lock

Ble noe kluss med forrige versjon av design-system, så prøver igjen.

chore: upgrade theme to version 5.0.2

---

src/screens/Assistant/Assistant.tsx
src/screens/Assistant_v2/Assistant.tsx

feat: update assistant search button color

---

src/screens/Assistant/Assistant.tsx
src/screens/Assistant_v2/Assistant.tsx

feat: back resets Assistant view

---

yarn.lock

Forandringer fra https://github.com/AtB-AS/design-system/pull/16

chore: upgrade design system to 5.0.3

---

src/components/sections/favorite-departure-item.tsx

fix: alignment of favorite-departure-item

---

src/utils/navigation.tsx

fix: Added startScreen as dependency

---

src/components/sections/section-separator.tsx
src/screens/Ticketing/Ticket/Carnet/index.tsx
src/screens/Ticketing/Ticket/ValidityLine.tsx

https://user-images.githubusercontent.com/1774972/146539370-bad4c13f-12c6-47e3-996d-5901e85b38cc.mov

fix: replace dash with SectionSeparator to improve performance

---

scripts/android/register-app-version.sh
scripts/ios/register-app-version.sh

chore: Add X-Correlation-Id in register script

---

src/screens/Profile/Home/index.tsx
src/tickets/types.ts

For å kunne vise developer-menyen i prod

feat: Firestole debug flag on customer

---

src/api/types/generated/QuayDeparturesQuery.ts
src/api/types/generated/StopQuayDeparturesQuery.ts

Oppdatert typer etter https://github.com/AtB-AS/atb-bff/pull/108

chore: update departure query types

---

src/screens/Profile/Information/TicketingInformation.tsx
src/translations/screens/subscreens/Information.ts

chore: update bicycle info

---

src/screens/Profile/Home/index.tsx
src/translations/screens/Profile.ts

feat: add beta section to settings

---

src/components/day-label/index.tsx
src/screens/Assistant/Results.tsx
src/screens/Assistant_v2/Results.tsx
src/translations/screens/Assistant.ts

feat: Alltid vis "I dag" som header på dagens søkeresultater

---

src/components/transportation-icon/index.tsx
src/screens/Assistant_v2/ResultItem.tsx

feat: display line number inside transportation icon bubble

---

src/screens/Departures/StopPlaceScreen.tsx
src/utils/date.ts

ref https://github.com/AtB-AS/mittatb-app/issues/1964#issuecomment-1011996181

feat: a11y improvement of departure time

---

src/remote-config.ts
src/screens/Profile/Home/index.tsx

- Add privacy policy to remote config, such that a new app build is not required if url needs to change.

ci: fetch privacy policy url from remote config

---

src/screens/Ticketing/Purchase/Overview/index.tsx
src/screens/Ticketing/Purchase/Product/ProductSheet.tsx

fix: Added logic to send in selectable products.

---

.github/workflows/build-staging-android.yml
.github/workflows/build-staging-ios.yml

PS! Requires AtB to add ABT_ENTUR_CLIENT_ID_STAGING and ABT_ENTUR_CLIENT_SECRET_STAGING to their Github Actions Environment before merge.

chore: enable entur app registration for staging nfk

---

src/screens/Departures/StopPlaceScreen.tsx

Bitteliten fiks etter tilbakemelding fra Hilde om at padding mellom quays er for liten i nye avganger

feat: update quay section padding

---

src/screens/Profile/Home/index.tsx

fix: Move OTP2 toggle to dev menu

---

package.json
src/screens/Profile/Home/index.tsx
src/translations/screens/Profile.ts
yarn.lock

Ref https://mittatb.slack.com/archives/C02EEG7D8EL/p1644318153631309
Flytter kundenummer over "Logg inn", og gjør telefonnummer mer likt kundenummer

fix: Move customer number, make phone number similar

---

src/screens/Assistant_v2/Assistant.tsx
src/screens/Assistant_v2/use-trips-query.ts

fix: disable "Load more" when JP heuristics fails

---

package.json
yarn.lock

Minor change: https://github.com/AtB-AS/design-system/releases/tag/%40atb-as%2Fgenerate-assets%402.4.0
Og patch fikser noe scripting og endrer bildet for NFK. Skal ikke påvirke AtB app noe.

fix: updates design system for illustration fix NFK

---

src/screens/Profile/Home/index.tsx

Don't show info and prices if ticketing is not enabled

fix: only show info and prices section if ticketing is enabled

---

ios/Podfile.lock

Glemte å legge ved oppdatering av podfile i #2145, med react-native-slider
fixes #2019

chore: add react-native-slider pod

---

package.json
yarn.lock

Oppdaterer illustrasjoner i henhold til feedback fra Byraa.
Påvirker ikke AtB

chore: updates design-system for nfk illustrations

---

src/auth/AuthContext.tsx
src/login/ConfirmCode.tsx

feat: force resend confirmation code

---

src/screens/Assistant_v2/Results.tsx
src/screens/Assistant_v2/types.tsx
src/screens/Assistant_v2/use-trips-query.ts
src/screens/TripDetails_v2/Details/index.tsx

fix: filter duplicate tripPatterns

---

src/screens/Profile/Home/index.tsx

fix: Move toggle for experimental trip search

---

src/components/transportation-icon/index.tsx
src/screens/Assistant/ResultItem.tsx
src/screens/Assistant_v2/ResultItem.tsx
src/translations/screens/Assistant.ts

feat: collapsable legs on travel search

---

src/screens/Ticketing/Purchase/Overview/index.tsx
src/screens/Ticketing/Ticket/Details/DetailsScreen.tsx
src/tickets/utils.ts
src/translations/screens/subscreens/PurchaseOverview.ts

Legger til melding om samarbeidsbilletten også for periodebilletter. 
Også en fiks av at meldingsboksen forsvinner utenfor skjemen når der ikke er nok plass. Litt usikker på om å legge til en tom `FullscreenFooter` er beste måten å gjøre det på, men det ser ut til å fungere greit.
closes #2155

feat: add train notice on period tickets

---

src/screens/Profile/TravelToken/index.tsx
src/translations/components/TravelTokenBox.ts
src/translations/screens/subscreens/TravelToken.ts
src/travel-token-box/index.tsx

- move ErrorMessages as part of TravelTokenBox
- correct messages

fix: reusable TravelTokenBox

---

src/screens/Ticketing/Ticket/Details/QrCode.tsx
src/screens/Ticketing/Ticket/TicketInfo.tsx
src/translations/screens/Ticket.ts

- correct QR code error message
- remove token info text on tickets

fix: hide token info on tickets, device or tcard texts

---

src/screens/Profile/DebugInfo/index.tsx

Legger til liste over tokens med metadata i debug menyen

feat: add travelTokens section to debug menu

---

src/mobile-token/MobileTokenContext.tsx
src/screens/Ticketing/Purchase/Overview/index.tsx
src/translations/screens/subscreens/PurchaseOverview.ts

show warning for tokens if not insepctable
show warning for Profiled travelcard

fix: travel card token warning

---

.github/workflows/build-staging-android.yml

fix: fixes cache key syntax

---

e2e/tests/departuresV1.e2e.ts
e2e/tests/departuresV2.e2e.ts
e2e/tests/myprofile.e2e.ts
e2e/tests/onboarding.e2e.ts
e2e/tests/tickets.e2e.ts
e2e/tests/travelsearch.e2e.ts
e2e/tests/travelsearchV1.e2e.ts
e2e/tests/travelsearchV2.e2e.ts
e2e/utils/commonHelpers.ts
e2e/utils/departures.ts
e2e/utils/expectHelpers.ts
e2e/utils/interactionHelpers.ts
e2e/utils/jestAssertions.ts
e2e/utils/myprofile.ts
e2e/utils/travelsearch.ts
src/components/sections/location-input.tsx
src/departure-list/DeparturesList.tsx
src/screens/Departures/NearbyPlaces.tsx
src/screens/Departures/PlaceScreen.tsx
src/screens/Departures/QuayView.tsx
src/screens/Departures/StopPlaceView.tsx
src/screens/Departures/components/DateNavigator.tsx
src/screens/Departures/components/EstimatedCallItem.tsx
src/screens/Departures/components/QuaySection.tsx
src/screens/Departures/components/StopPlaceItem.tsx

E2E-tester av avgangsvisningen. Dette innebærer følgende endringer:
- Lagt til test-ID på en del av elementene på Avganger v2 (dette er allerede gjort på Avganger v1 av Christian)
- Lagd flere hjelpefunksjoner for testene
- Refaktorisert litt på de eksisterende testene
- Initielle tester for Avganger v1 og v2

test: e2e-tests for the departure view

---

src/api/serviceJourney.ts
src/api/types/generated/journey_planner_v3_types.ts
src/api/types/serviceJourney.ts
src/screens/TripDetails_v2/DepartureDetails/index.tsx

https://github.com/AtB-AS/mittatb-app/issues/1944

fix: use v2 endpoints for map data

---

.github/workflows/test-e2e-ios.yml

Remove trace logging for e2e tests

fix: remove trace logging in test-e2e-ios.yml

---

.github/workflows/build-store-android.yml

Fiks av bygg https://github.com/AtB-AS/mittatb-app/runs/5752382662?check_suite_focus=true

build: add JAVA_HOME to GitHub env for store build

---

.github/workflows/build-store-android.yml
fastlane/Fastfile
fastlane/README.md

Fikser problemet med manglende package name ved publisering til google play internal track.

ci: added package name to fastlane build step

---

docs/BuildOnLocalDevice.md

Legger til docs for å teste app på egen device

docs: add build docs

---

src/configuration/FirestoreConfigurationContext.tsx
src/configuration/defaults.ts
src/reference-data/defaults.ts
src/remote-config.ts
src/screens/Ticketing/Purchase/Confirmation/index.tsx

Lukker https://github.com/AtB-AS/mittatb-app/issues/2475
This issue will refactor the values in configuration/other/vatPercent

chore: Use of VAT Percent attribute from Firestore

---

src/screens/Profile/Home/index.tsx
src/translations/dictionary.ts
src/utils/accessibility.ts

Closes https://github.com/AtB-AS/mittatb-app/issues/2126
The solution works well for both platforms

fix: Client number should be read as number digit by digit, not with thousands

---

src/components/feedback/index.tsx

Fixing QA comments mentioned in https://github.com/AtB-AS/mittatb-app/issues/2345#issuecomment-1108201466

Fix QA comments on Feedback component

---

src/components/ticket-illustration/index.tsx
src/screens/Ticketing/Tickets/AvailableTickets/AvailableTickets.tsx
src/screens/Ticketing/Tickets/AvailableTickets/Ticket.tsx

fix: Themed ticket illustrations

---

src/screens/Ticketing/Tickets/RecentTickets/RecentTicketComponent.tsx

Tar i bruk Themetext type="label_uppercase" og rydder opp i litt gammel moro.

fix: recent-ticket use label_uppercase type

---

package.json
yarn.lock

Oppdatert til versjon som har ny ChatUnread-ikon https://github.com/AtB-AS/design-system/pull/40

chore: update @atb-as/generate-assets

---

src/components/transportation-icon/index.tsx
src/screens/Ticketing/Tickets/AvailableTickets/Ticket.tsx
src/translations/screens/Tickets.ts

refactor: texts and tweaks for Available Tickets

---

src/screens/Ticketing/Tickets/RecentTickets/RecentTicketComponent.tsx
src/translations/screens/subscreens/RecentTicketsTexts.ts

code will not break when translations are added

refactor: more robust translation of transport modes

---

src/screens/Ticketing/Tickets/RecentTickets/RecentTicketComponent.tsx

Tar i bruk repeatPurchase oversetting som falt ut etter dette: https://github.com/AtB-AS/mittatb-app/pull/2567/commits/5e1f01907099bb9bc2f7c3ae0bb73be8b9952abc

refactor: use repeatPurchase translation

---

src/screens/Ticketing/Tickets/AvailableTickets/AvailableTickets.tsx
src/screens/Ticketing/Tickets/RecentTickets/RecentTickets.tsx
src/screens/Ticketing/Tickets/Tabs.tsx

refactor: fix tickets scroll

---

src/screens/Ticketing/Purchase/Overview/components/Summary.tsx
src/screens/Ticketing/Purchase/Overview/index.tsx
src/translations/screens/subscreens/PurchaseOverview.ts
src/utils/numbers.ts

Tickets after implementing:
<div>
</div>

feat: New summary component in ticket purchase overview

---

src/api/delete_profile.ts
src/components/sections/link-item.tsx
src/screens/Profile/DeleteProfile/index.tsx
src/screens/Profile/DesignSystem.tsx
src/screens/Profile/Home/index.tsx
src/screens/Profile/index.tsx
src/translations/screens/subscreens/DeleteProfile.ts

feat: Delete User Profile

---

src/translations/dictionary.ts
src/translations/screens/Profile.ts
src/translations/screens/subscreens/Login.ts

This PR does exactly the same as #2651, but now based on master instead of `release/1.19`

refactor: Replace orgSpecific My Reis headings

---

package.json
yarn.lock

Should solve #2682
New NFK background photo have been added to design system here: https://github.com/AtB-AS/design-system/commit/465173b619871226f0a244d94000d2dc0ba2b1cc 
Upgrading the package in the app so that the new image is actually used in the app.

refactor: use new NFK background photo

---

src/remote-config.ts
src/screens/Profile/Home/index.tsx

Everything from #2639 except requesting merge to master instead of `release/1.19`
NFK-menu:

refactor: remove login elements if login is disabled

---

src/screens/Departures/NearbyPlaces.tsx

Ref. [tråd på slack](https://mittatb.slack.com/archives/CS3JNRXEV/p1652881920003489)
https://user-images.githubusercontent.com/1774972/169061833-bce7266e-49df-4fdd-86fd-686fc2de3c1a.mp4
Also fixes missing list description when searching with favorites

fix: departures auto navigation for favorites

---

src/components/sections/radio-section.tsx
src/screens/Ticketing/Purchase/Travellers/SingleTravellerSelection.tsx
src/translations/screens/subscreens/PurchaseOverview.ts

Fixes QA feedback from https://github.com/AtB-AS/kundevendt/issues/129. Added a11y hint to SingleTravellerSelection.

refactor: add SingleTravellerSelection a11yHint

---

e2e/tests/tickets.e2e.ts
e2e/utils/tickets.ts
src/components/sections/counter-input.tsx
src/screens/Ticketing/Purchase/Overview/index.tsx
src/screens/Ticketing/Purchase/Travellers/MultipleTravellersSelection.tsx

Some e2e tests failed when the new traveller selection component was introduced. This fixes this by adding scroll in the buy process and some extra test-ids for verification.

test: e2e tests for new traveller selection

---

src/components/sections/action-item.tsx
src/components/sections/counter-input.tsx
src/components/sections/radio-section.tsx
src/preferences/types.ts
src/screens/Ticketing/Purchase/Overview/components/TravellerSelection.tsx
src/screens/Ticketing/Purchase/Travellers/MultipleTravellersSelection.tsx
src/screens/Ticketing/Purchase/Travellers/SingleTravellerSelection.tsx
src/screens/Ticketing/Purchase/Travellers/use-user-count-state.ts
src/translations/index.ts
src/translations/screens/subscreens/TicketTraveller.ts

closes https://github.com/AtB-AS/kundevendt/issues/13

refactor: add toggleable Traveller info on ticket purchase 

---

.github/workflows/build-store-android.yml
.github/workflows/build-store-ios.yml

Reverts AtB-AS/mittatb-app#2733

Revert "build: conditional build to store based on org and release tag"

---

docs/Release.md

Adds info about changes from #2738

docs: add information about org specific releases

---

src/translations/components/CancelledDeparture.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/1686

fix: fix typo in norwegian text

---

src/screens/Ticketing/Tickets/RecentTickets/RecentTickets.tsx

Ref: https://github.com/AtB-AS/kundevendt/issues/1666
Before: 
After:
Figma Link: https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App-1.2?node-id=6648%3A45714

feat: add repeat purchase header to differentiate correctly between actions

---

src/translations/screens/Ticket.ts

Fix for comment on https://github.com/AtB-AS/kundevendt/issues/220

fix: make warning messages consistent

---

src/api/client.ts
src/mobile-token/tokenService.ts

Fixes: https://github.com/AtB-AS/kundevendt/issues/1904

feature: add timeout to mobile token api calls

---

src/remote-config.ts

flex ticketing is available from remote config
https://github.com/AtB-AS/kundevendt/issues/1956

refactor: prepare remote config for flex ticketing

---

src/screens/Ticketing/Purchase/Payment/CreditCard/use-terminal-state.ts

Should solve remaining Android bug from https://github.com/AtB-AS/kundevendt/issues/108. Explanation can be found in issue.

fix: handle payment callback from Android urls

---

src/translations/screens/subscreens/Login.ts

fix: add 60 and 90 day ticket in periodic ticket info

---

src/screens/Profile/Home/index.tsx
src/screens/Profile/PaymentOptions/index.tsx
src/screens/Profile/index.tsx
src/screens/Ticketing/Purchase/Payment/SelectPaymentMethod/index.tsx
src/screens/Ticketing/Purchase/utils.ts
src/tickets/api.ts
src/translations/screens/Profile.ts
src/translations/screens/subscreens/PaymentOptions.ts

resolves https://github.com/AtB-AS/kundevendt/issues/106

feat: remove payment options from profile

---

src/translations/screens/subscreens/PurchaseOverview.ts

Should solve https://github.com/AtB-AS/kundevendt/issues/2033

fix: improved warning message when device is not active ticket bearer

---

src/api/departures/types.ts
src/departure-list/section-items/FavoriteDialogSheet.tsx
src/departure-list/section-items/line.tsx
src/favorites/types.ts
src/screens/Departures/PlaceScreen.tsx
src/screens/Departures/QuayView.tsx
src/screens/Departures/StopPlaceView.tsx
src/screens/Departures/components/EstimatedCallItem.tsx
src/screens/Departures/components/QuaySection.tsx
src/screens/Departures/components/ToggleFavouriteDeparture.tsx

Solves https://github.com/AtB-AS/kundevendt/issues/149
**Note:** 
Used most of the code from Favourites implemented in Departures v1 except the Toggle favourite Button. Old one is based on old types taken from SDK/used in old departures. 
Dint modify the old one because it is anyway going to be discarded soon. Also dint want to disturb the old flow and hence kept it as-is for testing behaviour of new one as compared to old one. 
**Screenshots:** 
<div>
</div>

feat: add and remove favourites in departures v2

---

src/screens/TripDetails/DepartureDetails/index.tsx
src/screens/TripDetails/index.tsx

Solves https://github.com/AtB-AS/kundevendt/issues/2064

feat: navigate to correct departure versioned screen on quay select in trip details

---

src/translations/screens/subscreens/PurchaseOverview.ts

Solves https://github.com/AtB-AS/kundevendt/issues/2067

feat: modify message regarding single tickets not being available for night tickets

---

src/components/feedback/index.tsx
src/screens/TripDetails/components/Trip.tsx

Solves https://github.com/AtB-AS/kundevendt/issues/2066

fix:add small margin on bottom of feedback component

---

src/screens/Ticketing/Tickets/TicketsScrollView.tsx
src/translations/screens/Tickets.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2079
Before: 
<div>
</div>
After: 
<div>
</div>

fix: add info box instead of text only

---

src/screens/Onboarding/IntercomInfo.tsx
src/screens/Onboarding/WelcomeScreen.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/1916#issuecomment-1210296225 
<div>
</div>

fix:fix minor UI bugs

---

src/translations/screens/Tickets.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2079#issuecomment-1210555081

fix:add missing full stop

---

src/chat/metadata.ts
src/navigation/TabNavigator.tsx
src/preferences/types.ts
src/screens/Assistant/index.tsx
src/screens/Dashboard/Dashboard.tsx
src/screens/Dashboard/TripSearch.tsx
src/screens/Dashboard/index.tsx
src/screens/Profile/Home/index.tsx
src/translations/index.ts
src/translations/screens/Dashboard.ts
src/translations/screens/Profile.ts
src/translations/screens/TripSearch.ts

toggle in Profile to activate new front page
Navigation and blank pages for Dashboard and Travel Search

feature toggle + blank slates

---

package.json
src/screens/Dashboard/Dashboard.tsx
yarn.lock

add background graphics to Dashboard

refactor: add backdrop to Dashboard

---

src/screens/Dashboard/CompactTickets.tsx

fix color of compact ticket heading

refactor: fix heading color

---

src/global-messages/GlobalMessagesContext.tsx
src/global-messages/converters.ts
src/screens/Departures/AllStopsOverview.tsx

resolves https://github.com/AtB-AS/kundevendt/issues/2219
fixes https://github.com/AtB-AS/kundevendt/issues/2200
Adds type validation of global messages similarly to how it's implemented in the webshop.
Also fixes that duplicate messages are shown in departures v2.

feat: add global message data validation

---

src/navigation/TabNavigator.tsx
src/screens/Dashboard/CompactTickets.tsx
src/screens/Dashboard/Dashboard.tsx
src/translations/screens/Dashboard.ts
src/translations/screens/Tickets.ts

Closes https://github.com/AtB-AS/kundevendt/issues/1880
If no tickets are available shows a button to buy.

feat: Buy ticket button

---

src/translations/screens/Ticket.ts
src/translations/screens/subscreens/MobileTokenOnboarding.ts
src/translations/screens/subscreens/TravelToken.ts

refactor: Some token text improvements

---

src/tickets/firestore.ts

Related to debugging https://github.com/AtB-AS/kundevendt/issues/1776
Add log for every reservation that is older than 1 minute ago at the time of discovery.

chore: adds logging on "old" reservations

---

src/translations/screens/Ticket.ts

ref https://github.com/AtB-AS/kundevendt/issues/2246#issuecomment-1222335747

refactor: update no inspection ticket icon texts

---

src/tickets/firestore.ts

This reverts commit 7979014df9b797f59c5d63c4cb89eb4a22323318.
This seems to produce a lot of false positives and make more noise than actual valuable logging after running a while.

chore: Revert "chore: adds logging on "old" reservations (#2868)"

---

src/screens/Ticketing/Purchase/Confirmation/index.tsx
src/screens/Ticketing/Purchase/Overview/index.tsx
src/screens/Ticketing/Ticket/utils.ts
src/translations/screens/Ticket.ts
src/translations/screens/subscreens/PurchaseOverview.ts

fixes https://github.com/AtB-AS/kundevendt/issues/2216
https://user-images.githubusercontent.com/1774972/186646349-5d33175f-21ca-4f63-a6f7-511825bd6fc2.MP4

feat: warn other device is inspectable on confirmation screen

---

src/login/in-app/ConfirmCodeInApp.tsx

Solves navigation bug in https://github.com/AtB-AS/kundevendt/issues/2032

refactor: rely on tab navigator to trigger mobile token onboarding

---

src/components/activity-indicator-overlay/index.tsx
src/screens/Profile/Home/index.tsx

Solves https://github.com/AtB-AS/kundevendt/issues/1906
https://user-images.githubusercontent.com/29625161/187071549-4150508a-03af-414c-9707-2c6e87c8f65c.mov
https://user-images.githubusercontent.com/29625161/187071551-dcfd54b9-a15f-432a-b7d0-a18baa64b587.mov

fix: add spinner during logout

---

src/navigation/TabNavigator.tsx
src/screens/AnonymousTicketPurchase/ConsequencesScreen.tsx
src/screens/AnonymousTicketPurchase/components/Actions.tsx
src/screens/MobileTokenOnboarding/components/MobileToken.tsx
src/screens/MobileTokenOnboarding/utils.ts
src/screens/Profile/Home/index.tsx
src/screens/Ticketing/Purchase/index.tsx

Solves bug in https://github.com/AtB-AS/kundevendt/issues/2032

refactor: navigate to correct stack after login

---

src/api/client.ts
src/api/headers.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2346

fix: add app version as header to all api calls

---

ios/Podfile.lock
src/mobile-token/MobileTokenContext.tsx
src/screens/Dashboard/CompactTickets.tsx
src/screens/Dashboard/Dashboard.tsx
src/screens/Ticketing/Ticket/Carnet/CarnetDetails.tsx
src/screens/Ticketing/Ticket/CompactTicketInfo.tsx
src/screens/Ticketing/Ticket/Component/LoadingSymbol.tsx
src/screens/Ticketing/Ticket/TicketInfo.tsx
src/screens/Ticketing/Ticket/utils.ts
src/screens/Ticketing/Tickets/ActiveTickets/ActiveTickets.tsx
src/tickets/utils.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/1880

refactor: Compact ticket fixes

---

src/screens/Ticketing/Purchase/Overview/index.tsx
src/screens/Ticketing/Purchase/index.tsx
src/screens/Ticketing/Tickets/RecentTickets/RecentTickets.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/1774

feat: Redirect the user to purchase overview and prefill fields with the previously purchased ticket

---

src/components/theme-icon/theme-icon.tsx
src/screens/Ticketing/Ticket/Component/InspectionSymbol.tsx

Resolves https://github.com/AtB-AS/kundevendt/issues/330

refactor: Fix wrong text color on non-filled inspection symbol

---

.github/workflows/build-staging-android.yml
.github/workflows/build-staging-ios.yml
.github/workflows/build-store-android.yml
.github/workflows/build-store-ios.yml

Resolves https://github.com/AtB-AS/kundevendt/issues/2367

build: Increase GH Actions timeout to 180min

---

src/screens/Dashboard/CompactTickets.tsx
src/screens/Ticketing/Ticket/CompactTicketInfo.tsx
src/tickets/utils.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/1880

refactor: Compact ticket non inspectable and accessibility fixes

---

src/screens/Dashboard/DeparturesWidget.tsx

when the user updates her favourites we do a data request to BFF to update the list.
but we make no request if the user has no favourites.
this causes the list to display the last favourite, even if it is removed.
this PR blanks the list when the user has no favourites.
also refactored better variabel names

refactor: blank favourites list when user deletes all favourites

---

package.json
src/screens/Dashboard/DeparturesWidget.tsx
yarn.lock

Closes https://github.com/AtB-AS/kundevendt/issues/2398 
Added illustration for favourite departures widget when no favourites are selected.

feat: illustration for favourite departures widget

---

.github/workflows/test-e2e-ios.yml
e2e/tests/account.e2e.ts
e2e/tests/departuresV2.e2e.ts
e2e/tests/myprofile.e2e.ts
e2e/tests/onboarding.e2e.ts
e2e/tests/tickets.e2e.ts
e2e/tests/travelsearch.e2e.ts
e2e/utils/account.ts
e2e/utils/interactionHelpers.ts
e2e/utils/myprofile.ts
e2e/utils/onboarding.ts
src/login/LoginOptionsScreen.tsx
src/screens/AnonymousTicketPurchase/components/Actions.tsx
src/screens/Departures/components/EstimatedCallItem.tsx

The E2E tests have not been running for a while. This task is to make a subset of the tests (the most important of the existing tests) to run again.

test: make the e2e run

---

src/components/message-box/index.tsx
src/translations/components/MessageBox.ts

Closes https://github.com/AtB-AS/kundevendt/issues/1997
Ref https://github.com/AtB-AS/kundevendt/issues/1997#issuecomment-1240437573

refactor: fix screenreader issue in dismissable alerts

---

src/translations/components/MessageBox.ts

Closes https://github.com/AtB-AS/kundevendt/issues/1997#issuecomment-1245280792

refactor: improvise screen reader text in message box

---

src/components/sections/favorite-departure-item.tsx
src/screens/Assistant/SelectFavouritesBottomSheet.tsx
src/screens/Dashboard/DeparturesWidget.tsx
src/translations/components/Section.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/1877

refactor: Improve accessibility on dashboard

---

src/screens/Assistant/SelectFavouritesBottomSheet.tsx

Adds submode to favorite selection list on dashboard
ref. https://github.com/AtB-AS/kundevendt/issues/2448

refactor: use submode param for SelectableFavouriteDeparture

---

src/components/button/index.tsx
src/screens/Assistant/SelectFavouritesBottomSheet.tsx
src/screens/Dashboard/DeparturesWidget.tsx
src/utils/use-focus-on-load.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/2350

refactor: Improve focus handling on dashboard favourites bottom sheet

---

src/screens/Dashboard/Dashboard.tsx

Closing https://github.com/AtB-AS/kundevendt/issues/2485
Hides tickets in dashboard when !enable_ticketing. Solves issue for NFK, and later FRAM.

Hide dashboard tickets when ticketing is disabled

---

src/navigation/TabNavigator.tsx
src/remote-config.ts
src/screens/Dashboard/use-new-frontpage.ts
src/screens/Profile/Home/index.tsx

Developers may still override this value in the developer menu.
Fixes: https://github.com/AtB-AS/kundevendt/issues/2489

refactor: Add remote config toggle for new frontpage

---

src/screens/Ticketing/Ticket/Component/TicketStatusSymbol.tsx
src/screens/Ticketing/Tickets/TicketReservation.tsx
src/translations/screens/Tickets.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2090

refactor: improve accessibility for rejected tickets

---

src/location-search/map-selection/index.tsx

Fix so navigation from Map selection won't replace existing location searches. Fixes result from QA at https://github.com/AtB-AS/kundevendt/issues/1560#issuecomment-1250955102

fix: navigation from maps

---

yarn.lock

We have some audit issues. Not all of them can be fixed as of now but this handles the ones that we can fix. After updating theme and generate-assets the two remaining critical issues (ts-deepmerge)

chore: fix some audit issues

---

fastlane/Fastfile
ios/Podfile.lock
package.json
scripts/android/upload-sourcemaps.sh
src/screens/Assistant/journey-date-picker/index.tsx
src/screens/Dashboard/journey-date-picker/index.tsx
src/screens/Profile/AddEditFavorite/EmojiSheet.tsx
src/screens/Ticketing/Purchase/TariffZones/index.tsx
src/screens/Ticketing/Purchase/TariffZones/search/index.tsx
yarn.lock

Related: https://github.com/AtB-AS/mittatb-app/pull/2880
Fixes things commented on here https://github.com/AtB-AS/kundevendt/issues/1560
- Issue with icons not updating (changing color etc)
- Crashing emoji menu
- Issues with updating arrival/departure time for assistant and dashboard
- Crashing zone select

fix: issues after QA of #2880

---

src/screens/Ticketing/Purchase/Overview/use-offer-state.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2533

refactor: add auth header to zone offer API

---

src/screens/Ticketing/Tickets/TicketReservation.tsx
src/translations/screens/Tickets.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2090
1. [Fix the header for bigger fonts](https://github.com/AtB-AS/kundevendt/issues/2090#issuecomment-1253496145)
2.
[Add different payment type for Visa and Mastercard](https://github.com/AtB-AS/kundevendt/issues/2090#issuecomment-1253366728)
<div>
</div>
3. [Fix time format to be in sync with ticket details screen](https://github.com/AtB-AS/kundevendt/issues/2090#issuecomment-1253432010)
<div>
</div>

refactor: fix rejected reservation bugs

---

.github/actions/ios-build-setup/action.yml
.github/workflows/build-staging-android.yml
.github/workflows/build-store-android.yml
scripts/android/override-config-files.sh
scripts/android/replace-bundle.sh
scripts/ios/override-config-files.sh

Fixes cache case and manual replacing of bundle for Android.
This will split override config files to use built in UNIX tools and to only do work that is needed for Android for instance.
---
Running example: https://github.com/AtB-AS/mittatb-app/actions/runs/3111071649/jobs/5042946106

ci: fix replace bundle android and cache case

---

src/screens/Ticketing/Ticket/Details/Barcode.tsx
src/translations/screens/Ticket.ts
src/utils/use-interval.ts

Removed as we want same UI for both static barcode and mobile token barcode.
Fixes https://github.com/AtB-AS/kundevendt/issues/1681

refactor: Remove barcode countdown

---

src/screens/TripDetails/components/TripSection.tsx

fixes https://github.com/AtB-AS/kundevendt/issues/2615

fix: conditionally navigate to departures v2 from TripDetails

---

src/screens/Nearby/state.ts

ref. https://github.com/AtB-AS/mittatb-app/pull/2993#discussion_r991918926

refactor: refactor getPayloadLocation

---

package.json
src/screens/Map/MapScreen.tsx
src/screens/Map/components/MapDisabledForScreenReader.tsx
src/theme/ThemedAssets.tsx
src/translations/components/Map.ts
yarn.lock

resolves https://github.com/AtB-AS/kundevendt/issues/2474
Disables map page when screen reader is enabled, and shows this screen instead:

feat: disable map when using screen reader

---

src/screens/Profile/TravelToken/ChangeTokenAction.tsx
src/screens/Profile/TravelToken/FaqSection.tsx
src/translations/screens/subscreens/TravelToken.ts
src/utils/date.ts

Closes minor comments on https://github.com/AtB-AS/kundevendt/issues/2511
- https://github.com/AtB-AS/kundevendt/issues/2511#issuecomment-1280391046
- https://github.com/AtB-AS/kundevendt/issues/2511#issuecomment-1280397736
- https://github.com/AtB-AS/kundevendt/issues/2511#issuecomment-1280406467
- https://github.com/AtB-AS/kundevendt/issues/2511#issuecomment-1280414309
- https://github.com/AtB-AS/kundevendt/issues/2511#issuecomment-1280736615

refactor: token toggle UI improvements

---

.github/workflows/inspect-variable.yml

Resolves https://github.com/AtB-AS/kundevendt/issues/2240

build: GH Actions workflow to inspect variable

---

src/screens/Map/index.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/2375

refactor: Update navigation stack to include trip details

---

src/components/map/Map.tsx
src/components/map/components/DeparturesDialogSheet.tsx
src/components/map/hooks/use-decide-camera-focus-mode.tsx
src/components/map/hooks/use-map-selection-change-effect.tsx
src/components/map/hooks/use-trigger-camera-move-effect.tsx
src/components/map/hooks/use-update-bottom-sheet-when-selected-stop-place-changes.tsx
src/components/map/types.ts
src/components/map/utils.ts
src/geocoder/use-reverse-geocoder.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2375

refactor: Fix an issue regarding choosing the wrong feature when selecting the bus stop

---

.github/workflows/test-e2e-ios.yml
e2e/tests/tickets.e2e.ts
e2e/utils/tickets.ts

Change from the not existing test-id `purchaseOverviewScrollView` to `ticketingScrollView`

test: e2e fails due to a wrong test-id

---

src/components/touchable-opacity-or-view/TouchableOpacityOrView.tsx
src/screens/Dashboard/DeparturesWidget.tsx
src/screens/Dashboard/NearbyStopPlacesScreen.tsx
src/screens/Departures/PlaceScreen.tsx
src/screens/Departures/components/EstimatedCallItem.tsx
src/screens/Departures/components/ToggleFavouriteDeparture.tsx
src/screens/Profile/FavoriteDepartures/index.tsx
src/translations/screens/Departures.ts
src/translations/screens/subscreens/FavoriteDepartures.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2592
https://github.com/AtB-AS/kundevendt/issues/2592#issuecomment-1303217473

refactor: fix improve favourites bugs

---

src/screens/Departures/components/QuaySection.tsx

This is to fix the issue with the missing rounded corner on the first most departure.

refactor: Change departures headers to full width

---

src/components/feedback/SubmittedComponent.tsx

Closing https://github.com/AtB-AS/kundevendt/issues/2815

refactor: replace support icon when Intercom is disabled

---

src/screens/Departures/components/QuaySection.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/2592#issuecomment-1307255488

refactor: should always show more items link for departure mode

---

src/api/client.ts
src/api/utils.ts
src/components/map/components/DeparturesDialogSheet.tsx
src/departure-list/DeparturesList.tsx
src/geocoder/use-reverse-geocoder.ts
src/screens/Departures/QuayView.tsx
src/screens/Departures/StopPlaceView.tsx
src/screens/Departures/components/QuaySection.tsx
src/screens/Departures/state/quay-state.ts
src/screens/Departures/state/stop-place-details-state.ts
src/screens/Departures/state/stop-place-state.ts
src/translations/screens/Departures.ts
src/translations/screens/Nearby.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2375

refactor: Add timeout and exception handler for major departures requests 

---

ios/Podfile.lock

Its attempts to fix and issue after an update to react-native.

fix: Update Podfile.lock

---

src/screens/Dashboard/TripSearch.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/2376

fix: update TripSearch to align text to the centre

---

src/components/map/components/DeparturesDialogSheet.tsx
src/components/map/hooks/use-decide-camera-focus-mode.tsx
src/components/map/hooks/use-map-selection-change-effect.tsx
src/components/map/hooks/use-update-bottom-sheet-when-selected-stop-place-changes.tsx
src/components/map/types.ts

Show the walking distance in meters to selected bus stop in the bottom sheet in the map.
closes https://github.com/AtB-AS/kundevendt/issues/2559

feat: show walking distance to stop in map

---

src/screens/Departures/components/EstimatedCallItem.tsx
src/screens/Departures/components/QuaySection.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/2376

Fix: Include Map mode in the conditions

---

package.json
src/components/screen-header/index.tsx
src/screens/Departures/DeparturesOnboardingScreen.tsx
yarn.lock

Also fixed an error with the general header screen reader focus for Android phones.
Resolves https://github.com/AtB-AS/kundevendt/issues/2721

refactor: A11y fixes on departures v2 onboarding

---

src/departure-list/section-items/quay-header.tsx
src/screens/Departures/StopPlaceView.tsx
src/screens/Departures/components/StopPlaceItem.tsx
src/utils/location.ts

Show distance in map and departures as km when more than 1000 m.
https://github.com/AtB-AS/kundevendt/issues/2559#issuecomment-1319667272

fix: show distance in km when over 1000 m

---

e2e/tests/account.e2e.ts
src/assets/information-data/ticketInspectionInformation.json
src/screens/Ticketing/FareProducts/index.tsx
src/translations/screens/Ticketing.ts
src/translations/screens/subscreens/Information.ts

Change name of "Valid" tab to "Active" in English
https://github.com/AtB-AS/kundevendt/issues/2185

fix: change "Valid" tab to "Active"

---

src/assets/information-data/ticketingInformation.json
src/translations/screens/subscreens/Information.ts

Update ticket information with information about 3 hour ticket
Close https://github.com/AtB-AS/kundevendt/issues/2210

refactor: update ticket information text with 3 hour ticket

---

src/api/departures/types.ts
src/api/types/generated/NearestStopPlacesQuery.ts
src/api/types/generated/QuayDeparturesQuery.ts
src/api/types/generated/StopQuayDeparturesQuery.ts
src/api/types/generated/StopsDetailsQuery.ts
src/api/types/generated/TripsQuery.ts
src/api/types/generated/departure-favorites.ts
src/api/types/generated/fragments/situations.ts
src/api/types/generated/journey_planner_v3_types.ts
src/api/types/generated/serviceJourney.ts
src/api/types/trips.ts
src/screens/TripDetails/DepartureDetails/index.tsx
src/screens/TripDetails/DepartureDetails/use-departure-data.ts
src/screens/TripDetails/components/TripSection.tsx
src/situations/types.ts

Main change is reusing the same shared SituationFragment for all queries
asking for situation messages.

refactor: Update gql types from bff

---

src/screens/Departures/components/StopPlaceItem.tsx
src/situations/SituationWarningIcon.tsx
src/situations/utils.ts
src/translations/screens/Departures.ts

Screenshot where Sluppen has situation message:

feat: Add situation warning icon to stop place

---

src/reference-data/defaults/preassigned-fare-products.json
src/reference-data/types.ts
src/screens/Ticketing/FareContracts/utils.ts
src/screens/Ticketing/FareProducts/AvailableFareProducts/AvailableFareProducts.tsx
src/screens/Ticketing/FareProducts/PurchaseTab.tsx
src/screens/Ticketing/Purchase/utils.ts
src/translations/screens/Ticketing.ts
src/translations/screens/subscreens/PurchaseConfirmation.ts
src/translations/screens/subscreens/PurchaseOverview.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2493

feat: Add night ticket button

---

src/components/sections/message-item.tsx

Background: https://github.com/AtB-AS/kundevendt/issues/147#issuecomment-1327176053

refactor: Fix message item text overflow

---

src/screens/TripDetails/DepartureDetails/index.tsx

Resolves https://github.com/AtB-AS/kundevendt/issues/2916
Before/After
<div>
</div>

refactor: New row for each quay sitation in DepartureDetails

---

src/chat/ContactSheet.tsx
src/components/button/index.tsx
src/components/feedback/SubmittedComponent.tsx
src/components/map/components/BackArrow.tsx
src/components/map/components/MapControls.tsx
src/components/map/components/PositionArrow.tsx
src/departure-list/section-items/FavoriteDialogSheet.tsx
src/departure-list/section-items/line.tsx
src/favorite-chips/index.tsx
src/login/ActiveFareContractPrompt.tsx
src/login/ConfirmCode.tsx
src/login/LoginOnboarding.tsx
src/login/PhoneInput.tsx
src/login/SkipLoginWarning.tsx
src/screens/Assistant/SelectFavouritesBottomSheet.tsx
src/screens/Dashboard/DeparturesWidget.tsx
src/screens/Departures/components/DateSelection.tsx
src/screens/Nearby/DepartureTimeSheet.tsx
src/screens/Profile/AddEditFavorite/AddForm.tsx
src/screens/Profile/DesignSystem.tsx
src/screens/Profile/Enrollment/index.tsx
src/screens/Profile/FavoriteList/SortFavorites.tsx
src/screens/Ticketing/FareProducts/TicketingInformationalOverlay.tsx
src/screens/Ticketing/Purchase/Confirmation/index.tsx
src/screens/Ticketing/Purchase/Overview/components/Summary.tsx
src/screens/Ticketing/Purchase/Payment/SelectPaymentMethod/index.tsx
src/screens/Ticketing/Purchase/TravelDate/TravelDateSheet.tsx
src/screens/TripDetails/Map/CompactMap.tsx
src/screens/TripDetails/components/PaginatedDetailsHeader.tsx

Add possibility to have icons on left and right side of buttons, for realtime.
https://github.com/AtB-AS/kundevendt/issues/2947

feat: add left and right icons to button

---

src/translations/screens/subscreens/PurchaseOverview.ts

Closes https://github.com/AtB-AS/kundevendt/issues/2496#issuecomment-1346609793

fix: Update typo on night ticket

---

src/translations/screens/subscreens/PurchaseOverview.ts

A small change only for Norwegian.

fix: change to totalt in norwegian

---

src/screens/Departures/QuayView.tsx

Same as https://github.com/AtB-AS/mittatb-app/pull/3110, but also for QuayView

fix: update header margins in QuayView

---

src/screens/Profile/DebugInfo/index.tsx

https://user-images.githubusercontent.com/1774972/207896171-43062fab-995a-4b5d-8620-de707a5f58de.mp4

feat: make objects and long strings in debug collapsible

---

src/screens/TripDetails/components/TripSection.tsx

ref. https://github.com/AtB-AS/kundevendt/issues/2949#issuecomment-1354629925

fix: add flex to realtimeText

---

src/components/bottom-sheet/BottomSheetContext.tsx
src/utils/use-focus-on-load.ts

Resolves https://github.com/AtB-AS/kundevendt/issues/3078

refactor: Improve screen reader focus

---

src/screens/Profile/DebugInfo/index.tsx

feat: add RemoteConfig to debug menu

---

src/utils/date.ts

Update full date and time format to visibly separate time from date.
<details>
</details>
https://github.com/AtB-AS/kundevendt/issues/2909

feat: update format of full date and time

---

src/screens/Ticketing/FareProducts/AvailableFareProducts/AvailableFareProducts.tsx
src/screens/Ticketing/FareProducts/AvailableFareProducts/FareProductTile.tsx
src/screens/Ticketing/FareProducts/PurchaseTab.tsx
src/screens/Ticketing/FareProducts/RecentFareProducts/RecentFareContractComponent.tsx
src/screens/Ticketing/FareProducts/RecentFareProducts/RecentFareContracts.tsx
src/translations/screens/Ticketing.ts
src/translations/utils.ts

Get the names and descriptions for the FareProductTiles from the new FareProductTypeConfigs in FireStore.

refactor: Fare product texts from FireStore

---

src/translations/screens/subscreens/TravelToken.ts

Update faq with changed/new information.
Close https://github.com/AtB-AS/kundevendt/issues/2869

refactor: Update token toggle faq

---

src/screens/Ticketing/FareContracts/CompactFareContractInfo.tsx

Update text color of ticket details on front page to match figma sketches.
https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?node-id=10909%3A50570&t=ILKZ9Ji3OPLdJj8S-4
<details>
</details>
https://github.com/AtB-AS/kundevendt/issues/2740

refactor: Update text color of ticket details to match sketches

---

src/translations/screens/subscreens/TicketTraveller.ts

Closing https://github.com/AtB-AS/kundevendt/issues/3043
Changes text for student max age at NFK and FRAM (they're the same)
Verified for NFK:

Change student max age in app for NFK and FRAM

---

e2e/tests/travelsearch.e2e.ts
e2e/utils/myprofile.ts

Remove frontpage toggle as it has been removed in the code.

test: remove frontpage toggle

---

e2e/utils/testData.ts

Update ticket prices after price increase 02.01.23.

test: update ticket prices

---

src/screens/TripDetails/components/Time.tsx
src/utils/use-pollable-resource.ts

When merging the release branch some errors were added to master since quite a bit of refactoring and additional linting rules have been added since the release branch was created.

refactor: Lint fixes

---

package.json
src/screens/Dashboard/TravelSearchFilterOnboardingScreen.tsx
src/screens/Dashboard/TripSearch.tsx
src/screens/Dashboard/index.tsx
src/screens/Dashboard/types.ts
src/screens/Dashboard/use-travel-search-filters-enabled.ts
src/screens/Profile/DebugInfo/index.tsx
src/storage/index.ts
src/translations/screens/TripSearch.ts
yarn.lock

Add onboarding for travel search filters
<details>
</details>
Close https://github.com/AtB-AS/kundevendt/issues/3103

feat: Add travel search filter onboarding

---

src/screens/Dashboard/TripSearch.tsx

Background: https://github.com/AtB-AS/kundevendt/issues/3104#issuecomment-1370645686

refactor: A11yLabel on trip search time button

---

src/translations/screens/TripSearch.ts

Only show onboarding text for filters ready in first iteration: https://github.com/AtB-AS/mittatb-app/pull/3182#discussion_r1061237205
<details>
</details>
https://github.com/AtB-AS/kundevendt/issues/3103

refactor: Change filter onboarding text

---

src/screens/Departures/PlaceScreen.tsx
src/translations/screens/Departures.ts

Handle receiving error on empty stop place result.
<details>
</details>
https://github.com/AtB-AS/atb-bff/pull/207
Close https://github.com/AtB-AS/kundevendt/issues/2558

fix: Handle error when fetching removed stop place

---

src/screens/Departures/PlaceScreen.tsx

Replace missing code
https://github.com/AtB-AS/mittatb-app/pull/3189/files#diff-b918b724f4960c1458fa4520e25ebd587ebeb37ae91719c4ff95882aec1dce94L52-L55
https://github.com/AtB-AS/kundevendt/issues/2558

fix: replace code

---

src/screens/Departures/PlaceScreen.tsx

https://github.com/AtB-AS/kundevendt/issues/2558

fix: Set place data earlier

---

src/screens/Ticketing/Purchase/Payment/CreditCard/use-terminal-state.ts
src/ticketing/api.ts
src/ticketing/types.ts

Update endpoints for ticketing v3 
Close https://github.com/AtB-AS/kundevendt/issues/2952

fix: updates endpoints for tickets to v3

---

src/components/button/Button.tsx
src/components/sections/items/ExpandableSectionItem.tsx
src/screens/Profile/DesignSystem.tsx

New button type pill according to how it is specced in Figma. Also some refactoring of the in-app design system to have a better representation of the different buttons.
Examples:

refactor: New button type pill

---

src/departure-list/section-items/line.tsx
src/screens/Departures/components/use-on-mark-favourite-departures.tsx
src/translations/screens/Nearby.ts

Show warning before deleting favourite
<details>
</details>
Close https://github.com/AtB-AS/kundevendt/issues/2594

feat: Give warning before deleting favourite from departures

---

src/screens/Ticketing/FareProducts/RecentFareProducts/RecentFareContractComponent.tsx
src/screens/Ticketing/FareProducts/RecentFareProducts/RecentFareContracts.tsx
src/screens/Ticketing/FareProducts/use-recent-fare-contracts.ts
src/screens/Ticketing/Purchase/Overview/components/ProductSelectionByProducts.tsx

Mentioned on https://github.com/AtB-AS/kundevendt/issues/3068
This PR shows night tickets on recent purchases.

fix: Night tickets should be presented on Recent Purchases view

---

src/components/vipps-login-button/VippsLoginButton.tsx
src/login/LoginOptionsScreen.tsx

https://mittatb.slack.com/archives/CSFC6PG23/p1673591379933579
Simplified the css to have better control. It fixed the error, without me using any time on researching which of the changes that fixed it.
Before/After:
<div>
</div>

refactor: Fix Vipps login button issues

---

package.json
yarn.lock

Upgrade typescript and react dependencies
https://github.com/AtB-AS/kundevendt/issues/3232

feat: Upgrade typescript and react

---

__tests__/utils-test.ts
src/reference-data/types.ts
src/reference-data/utils.ts
src/utils/compare-version.ts

Add check for min and max version in fare product
Close https://github.com/AtB-AS/kundevendt/issues/2914

feat: Add check for min and max version in fare product

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
src/translations/screens/subscreens/TripDetails.ts
src/travel-details-screens/components/Trip.tsx
src/travel-details-screens/components/TripSection.tsx
src/travel-details-screens/utils.ts

- Handle leg with insignificant walk distance
- Handle walk leg with wait time - show short walk instead of empty space
<details>
<summary>Screenshots of fixed ghost start leg</summary>
</details>
<details>
<summary>Screenshots of fixed ghost leg with wait time and short walk</summary>
</details>
Close https://github.com/AtB-AS/kundevendt/issues/2608

fix: Handle empty ghost legs

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_PlaceScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_PlaceScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_PlaceScreen.tsx

- Always push when navigating to new departures.
- Fixed an error when navigating from LocationSearch to TripSearch.

refactor: Some navigation fixes

---

src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx
src/nearby-stop-places/index.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_FavoriteDeparturesScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_NearbyStopPlacesScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_PlaceScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/navigation-types.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_NearbyStopPlacesScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/TabNav_DeparturesStack.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/navigation-types.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_FavoriteDeparturesScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NearbyStopPlacesScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/types.ts

There was found some errors on the NearbyStopPlacesScreen navigation, especially on it in context of select favourite departures. The NearbyStopPlaces component was rebranded to a full screen component, which hopefully fixes this.

refactor: Fixes to stop place navigation

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Purchase/Confirmation/index.tsx
src/ticketing/types.ts
src/translations/screens/subscreens/PurchaseConfirmation.ts

feat: Original price in confirmation screen

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_JourneyDatePickerScreen.tsx

Based on this comment:
https://github.com/AtB-AS/mittatb-app/pull/3225#issuecomment-1405551974

refactor: Fix journey date picker not merging params

---

src/components/info-chip/InfoChip.tsx
src/components/info-chip/index.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/Component/FareContractDetail.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/FareContractInfo.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareProducts/RecentFareProducts/RecentFareContractComponent.tsx

Add a new shared component "InfoChip" which replaces the similar component used on recent fare product and on fare contract.
The InfoChip component is styled with the active color of an interactive color.

refactor: Add info chip component

---

ios/departureWidget/DepartureWidget.swift
ios/departureWidget/Views/DepartureTimesView.swift
ios/departureWidget/Views/WidgetInfoView.swift

After some input from @cbrevik, @oyvindmikkelsenatb and user-tests we decided to add "..." to the fade. 
Also removes the small widget. All the code for it is till there, but it will not be available for the users.

fix: Added "..." to the fade and found a better solution to how the fade is created. 

---

src/components/sections/items/FavoriteDepartureSectionItem.tsx
src/components/transportation-icon/TransportationIcon.tsx
src/departure-list/section-items/line.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/SelectFavouritesBottomSheet.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/Component/TransportMode.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareProducts/RecentFareProducts/RecentFareContractComponent.tsx

Make transportation icon take a style prop and move margin out
https://github.com/AtB-AS/mittatb-app/pull/3258#discussion_r1093077064

chore: Move margin out of transportation icon component

---

src/remote-config.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultitemOld.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/Results.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use_new_travel_search_enabled.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
src/storage/index.ts

Add destination icon
- Remove scroll view
- Put a minimum size on line to destination icon
- Make left side of line/left line grow to fit view
<details>
</details>

feat: Add destination icon

---

src/components/map/hooks/use-realtime-map-enabled.ts
src/remote-config.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx
src/storage/index.ts

closes https://github.com/AtB-AS/kundevendt/issues/3403

chore: add feature switch for realtime map

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx

Add walk duration in minutes to walk icon in trip search
<details>
</details>

feat: Add walk duration to walk icon

---

src/translations/screens/Onboarding.ts

fix: replace onboarding text nfk

---

package.json
yarn.lock

Closing https://github.com/AtB-AS/kundevendt/issues/3453
Including changed images from https://github.com/AtB-AS/design-system/pull/102
Should be (and seems) unchanged for AtB.

fix: show NFK image on NFK departure onboarding

---

src/stacks-hierarchy/Root_MobileTokenOnboarding/MobileTokenOnboarding_FlexibilityInfoScreen.tsx
src/stacks-hierarchy/Root_MobileTokenOnboarding/MobileTokenOnboarding_OptionsInfoScreen.tsx
src/stacks-hierarchy/Root_MobileTokenOnboarding/MobileTokenOnboarding_SelectTravelTokenScreen.tsx
src/stacks-hierarchy/Root_MobileTokenOnboarding/MobileTokenOnboarding_TicketSafetyInfoScreen.tsx
src/stacks-hierarchy/Root_MobileTokenOnboarding/Root_MobileTokenOnboardingStack.tsx
src/stacks-hierarchy/Root_MobileTokenOnboarding/components/InspectableTokenInfo.tsx

The SelectTravelTokenScreen was missing from the MobileTokenOnboarding stack.

fix: Fix SelectTravelTokenScreen in MobileTokenOnboarding

---

src/place-screen/hooks/use-quay-data.ts
src/place-screen/hooks/use-stop-place-state.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/use-favorite-departure-data.ts
src/utils/use-refresh-on-focus.ts

ref. https://github.com/AtB-AS/kundevendt/issues/3250#issuecomment-1431349645
resolves https://github.com/AtB-AS/kundevendt/issues/3250

fix: prevent useRefreshOnFocus crash when used in bottom sheet

---

.github/workflows/test-e2e-ios.yml

Forgot to uncomment the run on push to master in PR https://github.com/AtB-AS/mittatb-app/pull/3259.

test: e2e on push to master

---

.github/actions/ios-build-setup/action.yml
.github/workflows/build-staging-ios.yml
.github/workflows/build-store-ios.yml
fastlane/Fastfile

Those changes expect to fix the cache issue regarding certificates and replacing the ipa bundle

refactor: Rewrite and update cache libraries to fix the build cache issue

---

src/place-screen/hooks/use-quay-data.ts
src/place-screen/hooks/use-stop-place-state.ts

Fix from QA: https://github.com/AtB-AS/kundevendt/issues/3252#issuecomment-1436587899

fix: filter departure realtime on favorites when focused

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx

Fix app crash and improve reader

fix: Fix app crash and improve reader

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/TravelSearchFiltersBottomSheet.tsx

https://github.com/AtB-AS/kundevendt/issues/3108#issuecomment-1437010479
https://github.com/AtB-AS/kundevendt/issues/3108#issuecomment-1437026694

fix: Make save-button part of scrollview

---

src/components/map/components/DeparturesDialogSheet.tsx
src/place-screen/hooks/use-quay-data.ts
src/place-screen/hooks/use-stop-place-state.ts

ref. https://github.com/AtB-AS/kundevendt/issues/3250#issuecomment-1434431109

fix: enable realtime calls for Map bottom sheet

---

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx

Close https://github.com/AtB-AS/kundevendt/issues/3513

fix: Make payment button not disappear

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx

fix: Get detailed quay name in header and on screenreader

---

src/api/departures/departure-group.ts
src/api/departures/index.ts
src/api/departures/types.ts
src/departure-list/section-items/line.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/use-favorite-departure-data.ts

Show cancelled departures on front page favourites.
Design as discussed with @oyvindmikkelsenatb 
<details>
<summary<Screenshot</summary>
</details>
https://github.com/AtB-AS/atb-bff/pull/223
Close https://github.com/AtB-AS/kundevendt/issues/3271

feat: Show cancelled departures on front page favorites

---

src/travel-details-screens/DepartureDetailsScreenComponent.tsx
src/travel-details-screens/use-current-trip-pattern-with-updates.ts

closes https://github.com/AtB-AS/kundevendt/issues/3201

chore: update polling interval to 20s for details screens

---

src/departure-list/section-items/line.tsx
src/translations/components/CancelledDeparture.ts
src/translations/screens/Nearby.ts

https://github.com/AtB-AS/kundevendt/issues/3271

feat: Add screenreader message about cancelled departures

---

src/place-screen/components/StopPlaceView.tsx

Move feedback component under all quays on departures.
Close https://github.com/AtB-AS/kundevendt/issues/3221

fix: Move feedback component under all quays

---

src/api/types/generated/TripsQuery.ts
src/travel-details-screens/components/TripSection.tsx

closes https://github.com/AtB-AS/kundevendt/issues/3567

fix: use serviceJourneyEstimatedCalls for realtime position

---

package.json
src/utils/use-transportation-color.ts
yarn.lock

closes https://github.com/AtB-AS/kundevendt/issues/2832
<div>
</div>

feat: add airport express transport color

---

src/travel-details-screens/TripDetailsScreenComponent.tsx

Change look of purchase ticket button according to new design, always be accessible @oyvindmikkelsenatb 
Close https://github.com/AtB-AS/kundevendt/issues/3538

feat: Change button to always be accessible

---

src/reference-data/defaults/fare-product-type-config.json
src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripDetailsScreen.tsx
src/translations/screens/subscreens/PurchaseOverview.ts
src/travel-details-screens/TripDetailsScreenComponent.tsx

Add logic for purchase button
- Send user to ticket purchase
- Send travel date as start time for ticket if in the future
- Set single ticket time selection mode as datetime in config to start ticket in future
- Send zones to ticket purchase to get correct price and zones for ticket
Close https://github.com/AtB-AS/kundevendt/issues/3539

feat: Add logic for purchase button

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx

Use goBack function to go back to correct page on cancel, for instance back to trip details when purchasing ticket from travel search
Close https://github.com/AtB-AS/kundevendt/issues/3540

feat: Use goBack function to go back to correct page on cancel

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/navigation-types.ts
src/translations/screens/subscreens/PurchaseOverview.ts
src/travel-details-screens/TripDetailsScreenComponent.tsx

Add information message when purchasing ticket from travel search
Close https://github.com/AtB-AS/kundevendt/issues/3535

feat: Add information message when purchasing ticket from travel search

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/Results.tsx

Closes: https://github.com/AtB-AS/kundevendt/issues/3579

fix: Removed left padding on error message box in trip search

---

src/travel-details-screens/TripDetailsScreenComponent.tsx

https://github.com/AtB-AS/kundevendt/issues/3539#issuecomment-1455874940

fix: Use ticket start time of first non foot leg

---

src/api/types/generated/fragments/vehicles.ts
src/vehicles/components/OperatorLogo.tsx
src/vehicles/components/PricingPlan.tsx
src/vehicles/components/ScooterSheet.tsx
src/vehicles/components/VehicleStat.tsx

https://github.com/AtB-AS/kundevendt/issues/3545

feat: Scooter sheet redesign

---

src/travel-details-screens/TripDetailsScreenComponent.tsx

https://github.com/AtB-AS/kundevendt/issues/3539

feat: Add venue name to tariff zone

---

src/translations/screens/subscreens/TripDetails.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/3224
feat: Rephrased texts to include total in wording for trip time and walking distance

feat: Rephrased texts for total trip time / walking distance

---

src/travel-details-screens/TripDetailsScreenComponent.tsx

- Don't sell tickets if wait time between legs is too long
https://github.com/AtB-AS/kundevendt/issues/3539#issuecomment-1460328431
- Fix stop place names 
https://github.com/AtB-AS/kundevendt/issues/3539#issuecomment-1460236746

feat: Don't show purchase button on too long wait time

---

src/translations/screens/subscreens/PurchaseOverview.ts

https://github.com/AtB-AS/kundevendt/issues/3536

fix: update "holeplass"

---

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_PurchasePaymentWithCreditCardScreen/Root_PurchasePaymentWithCreditCardScreen.tsx
src/stacks-hierarchy/Root_PurchasePaymentWithVippsScreen/Root_PurchasePaymentWithVippsScreen.tsx
src/stacks-hierarchy/Root_PurchaseTariffZonesSearchByTextScreen/Root_PurchaseTariffZonesSearchByTextScreen.tsx

Closes: https://github.com/AtB-AS/kundevendt/issues/3048

fix: Changed background color in ticketing pages for dark mode

---

src/auth/AuthContext.tsx

Log auth errors to bugsnag
Close https://github.com/AtB-AS/kundevendt/issues/3258

chore: Add logging of auth error to bugsnag

---

src/components/theme-icon/NavigationIcon.tsx
src/remote-config.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/FlexTicketDiscountInfo.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
src/translations/screens/subscreens/PurchaseOverview.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/3400 
Note: Endringer for remote config må gjøres for nytt felt (flex_ticket_url) i produksjon når dette å prodsettes.

feat: Adjusted text about flexible tickets and added LinkSection for more information on the discount model

---

src/travel-details-screens/TripDetailsScreenComponent.tsx

Show purchase button if total wait time is less than an hour rather than for each individual leg
https://github.com/AtB-AS/kundevendt/issues/3539#issuecomment-1466324741

chore: Show purchase button based on total wait time

---

src/favorites/use-on-mark-favourite-departures.tsx
src/place-screen/PlaceScreenComponent.tsx
src/place-screen/components/EstimatedCallItem.tsx
src/place-screen/components/QuaySection.tsx
src/place-screen/components/QuayView.tsx
src/place-screen/components/StopPlaceView.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_PlaceScreen.tsx

Automatically add favourite to front page when added from front page
Close https://github.com/AtB-AS/kundevendt/issues/2804
(https://github.com/AtB-AS/kundevendt/issues/2804#issuecomment-1410304647)

feat: Show favourite on front page

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/PurchaseReservation.tsx
src/ticketing/types.ts

Don't show reservations for subaccounts
Close https://github.com/AtB-AS/kundevendt/issues/2765

fix: Don't show reservations for subaccounts

---

ios/departureWidget/Views/DepartureTimesView.swift

Denne er approved av Sebastian og design-duo

feat: new icon for widget

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx

fixes https://github.com/AtB-AS/kundevendt/issues/3747

fix: update unavailable night ticket message box

---

src/components/icon-box/CounterIconBox.tsx
src/components/icon-box/TransportationIconBox.tsx
src/stacks-hierarchy/Root_OnboardingStack/Onboarding_IntercomInfoScreen.tsx
src/stacks-hierarchy/Root_OnboardingStack/Onboarding_WelcomeScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
src/travel-details-screens/DepartureDetailsScreenComponent.tsx

Added some test-ids for e2e testing.

test: add test-ids

---

.github/workflows/build-staging-ios.yml

Fixing issue https://github.com/AtB-AS/mittatb-app/pull/3458#issuecomment-1505053524

build: change workflow condition check for FRAM

---

src/components/bottom-sheet/BottomSheetContainer.tsx
src/components/sections/items/FavoriteDepartureSectionItem.tsx
src/departure-list/section-items/FavoriteDialogSheet.tsx
src/favorite-departures/FavoriteDeparturesScreenComponent.tsx
src/favorites/FavouriteDepartureToggle.tsx
src/nearby-stop-places/components/StopPlaces.tsx
src/service-disruptions/ServiceDisruptionSheet.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/CompactFareContracts.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/SelectFavouritesBottomSheet.tsx

Adding test-ids for the front page and add/edit/remove favorite departures flow.

test: adding new test ids

---

src/components/map/components/mobility/Stations.tsx
src/components/map/components/mobility/Vehicles.tsx

Requires upload of new icons to Mapbox Studio prod before release

fix: New mobility icons

---

src/components/screen-view/ScreenWithLargeHeader.tsx

Fix Android app crash on departure details screen and trip details screen

fix: Ensure accessible with focusRef

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/DayLabel.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx

Closes: https://github.com/AtB-AS/kundevendt/issues/3618
Looking like:

style: applied smaller spacings in travel search

---

src/translations/screens/FareContract.ts
src/translations/screens/subscreens/DeleteProfile.ts
src/translations/screens/subscreens/PaymentOptions.ts

I found a few typos that should be corrected 🖊️

fix: Fixed typo in words

---

src/components/button/Button.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/SelectedFiltersButtons.tsx

With changes:
Without changes:

fix: pill filter button in 200% zoom

---

src/components/divider/Divider.tsx
src/components/divider/index.ts
src/components/map/Map.tsx
src/travel-details-screens/DepartureDetailsScreenComponent.tsx
src/travel-details-screens/TripDetailsScreenComponent.tsx
src/travel-details-screens/components/Time.tsx
src/travel-details-screens/components/Trip.tsx
src/travel-details-screens/components/TripSummary.tsx

Partly closes: https://github.com/AtB-AS/kundevendt/issues/3680 
* Moved map under travel details
* Removed real time icon from trip timestamps
<details>
</details>

feat: move map content, remove realtime from trip timestamps

---

src/travel-details-screens/DepartureDetailsScreenComponent.tsx

Fix margins for live button and top of departure
https://github.com/AtB-AS/kundevendt/issues/3679#issuecomment-1539648005

fix: Fix margins on departures and live button

---

src/translations/screens/subscreens/TravelToken.ts

Closing https://github.com/AtB-AS/kundevendt/issues/4009

replace AtB webshop url for Reis

---

src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx
src/travel-details-screens/DepartureDetailsScreenComponent.tsx
src/travel-details-screens/components/Trip.tsx
src/travel-details-screens/utils.ts

closes https://github.com/AtB-AS/kundevendt/issues/3686

feat: add live position icon styling

---

src/travel-details-screens/DepartureDetailsScreenComponent.tsx

Adjust minWidth for live button, and don't show live button if screenreader is enabled
https://github.com/AtB-AS/kundevendt/issues/3679#issuecomment-1543516612

fix: Don't show map button when screenreader is enabled

---

src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_DurationScreen/durationPicker/DurationPicker.tsx

Format date correctly for android by using date function. 
Addresses: https://github.com/AtB-AS/kundevendt/issues/3917#issuecomment-1549190946

fix: date format android ticket assistant

---

src/storage/StorageModel.tsx
src/travel-search-filters/FiltersContext.tsx
src/travel-search-filters/storage.ts

There was a case where filter were not fully migrated, after review from @tormoseng 
Fixes: https://github.com/AtB-AS/kundevendt/issues/3857#issuecomment-1547365503

fix: Fix an issue while migrating filters from old versions to new versions

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/CityZoneMessage.tsx
src/translations/components/CityBoxMessage.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/3857

Fix: Add proper accessibility to the link button

---

src/travel-details-screens/TripDetailsScreenComponent.tsx

Fixes issue commented here:
https://github.com/AtB-AS/mittatb-app/pull/3534#issuecomment-1549397230

fix: Correct focus when opening trip

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/CityZoneMessage.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/hooks.ts

Closes https://github.com/AtB-AS/kundevendt/issues/4061
Quick resume: The city box is only shown when the origin and destination are in the same city zone.

feature: Show message box only within zones

---

src/api/types/generated/TripsQuery.ts
src/api/types/generated/fragments/estimated-calls.ts
src/api/types/generated/fragments/service-journeys.ts
src/api/types/trips.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-trips-query.ts
src/travel-details-screens/DepartureDetailsScreenComponent.tsx
src/travel-details-screens/components/TripSection.tsx
src/travel-details-screens/use-realtime-text.ts

Closes: https://github.com/AtB-AS/kundevendt/issues/3680
Linked to changes in BFF: https://github.com/AtB-AS/atb-bff/pull/257

feat: show info regarding departure from first stop in trip details

---

src/place-screen/components/QuaySection.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PlaceScreen.tsx

The Profile_PlaceScreen was missing the onPressQuay method, and therefore not navigating.

Fix: Loading of additional departures in favourite departure flow

---

src/travel-details-screens/components/TripRow.tsx

max zoom before:
max zoom now:

fix: 200% zoom in trip details

---

src/components/map/hooks/use-decide-camera-focus-mode.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
src/travel-details-screens/components/Trip.tsx
src/travel-details-screens/components/TripSection.tsx
src/travel-details-screens/utils.ts

Closes https://github.com/AtB-AS/kundevendt/issues/4103

fix: Do not read flex mode from booking data

---

src/components/screen-header/ScreenHeader.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/Dashboard_RootScreen.tsx

closes https://github.com/AtB-AS/kundevendt/issues/3990

fix: Ensures spacing consistency in title header

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx

By testing with the text-panel enabled at the bottom, I belive this fixes the issue. However I am not able to test since I dont have a "leselist". 
Before this fix, the text disappeared when it was done reading. By adding the role the text stays there. 
I also found the text to be built in a way that made it hard to read. It was read correctly but shown with large gaps. By joining the strings this way it is more readable and also easier to edit the texts later:
old: 
new:
Adding to this, I want to make a suggestion that the `screenReaderPause` should be a ". " instead of "\n" as this will make it easier to read if the text panel is adopted, but will not make a difference in how it is read by the screen reader. 
Lastly I moved a margin to so that the screen reader box marking what being …

fix: Leselist problem stopping user from selecting a travel suggestion

---

package.json
src/api/serviceJourney.ts
src/components/icon-box/CounterIconBox.tsx
src/components/icon-box/TransportationIconBox.tsx
src/components/map/components/mobility/BikeStations.tsx
src/components/map/components/mobility/CarStations.tsx
src/components/map/components/mobility/Vehicles.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
src/theme/colors.ts
src/travel-details-map-screen/components/MapRoute.tsx
src/utils/use-transportation-color.ts
yarn.lock

Update map leg colors, update design system version
<details>
</details>
Close https://github.com/AtB-AS/kundevendt/issues/3689

feat: Update design system for new transport colors

---

src/travel-details-screens/components/TripSummary.tsx

fix: 200% zoom in travel time and distance

---

src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx

Set correct zoom level on opening the travel details map

fix: Set correct zoom level on map

---

src/translations/components/CancelledDeparture.ts

https://github.com/AtB-AS/kundevendt/issues/3591#issuecomment-1569769267
> Legg på punktum på slutten av setningen.

fix: add "." to end of cancelled departure text

---

src/components/map/Map.tsx
src/components/map/MapConfig.ts
src/components/map/components/mobility/BikeStations.tsx
src/components/map/components/mobility/CarStations.tsx
src/components/map/components/mobility/Vehicles.tsx
src/components/map/hooks/use-trigger-camera-move-effect.tsx
src/components/map/types.ts
src/components/map/utils.ts
src/tariff-zones-selector/TariffZonesSelectorMap.tsx
src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx

It fixes an issue regarding rotation after discussion with @marius-at-atb 
Closes https://github.com/AtB-AS/kundevendt/issues/3688

fix: Upgrading mapbox version

---

src/components/screen-view/FullScreenView.tsx
src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_NearbyStopPlacesScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_NearbyStopPlacesScreen.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_NearbyStopPlacesScreen.tsx
src/travel-details-screens/DepartureDetailsScreenComponent.tsx
src/travel-details-screens/TripDetailsScreenComponent.tsx

Instead of using the old 'SimpleDisappearingHeader' the stop places
screen(s) now uses the new 'FullScreenView' which has a parallax
scroll effect.
- Departures
- Dashboard -> Add favorite
- Profile -> Add favorite
- TripSearch
- TripDetails
- DepartureDetails

feat: StopPlacesScreen use parallax scroll

---

ios/Podfile.lock
package.json
src/components/map/Map.tsx
src/components/map/MapConfig.ts
src/components/map/hooks/use-trigger-camera-move-effect.tsx
src/components/map/types.ts
src/components/map/utils.ts
src/tariff-zones-selector/TariffZonesSelectorMap.tsx
src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx
yarn.lock

This branch reverse changes that were merged accidentally into master for reasons that I do not know.
Related to: https://github.com/AtB-AS/mittatb-app/pull/3633

fix: Revert unwanted changes merged into master

---

src/components/parallax-scroll/ParallaxScroll.tsx
src/components/screen-header/ScreenHeader.tsx

Fix problem where scrolling is blocked by the header when it is collapsed
https://github.com/AtB-AS/kundevendt/issues/3675#issuecomment-1588642929

fix: Fix collapsed header blocking scrolling

---

src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx

closes https://github.com/AtB-AS/kundevendt/issues/3688
Solves iOS stage build error by using onRegionIsChanging instead of onCameraChanged.
However still using onCameraChanged for Android, where onRegionIsChanging produces laggy behaviour.
Also fixes a minor issue where the live bus icon would be hidden until the first location change.

fix: Live bus map error

---

.github/workflows/build-staging-android.yml

This reverts commit eff3393b0e29214c167c2d5f46c26d66bd54ac08.

Revert "build: Fixed build id when registering Android app version (#3656)"

---

src/mobility/components/filter/BikeFilter.tsx
src/mobility/components/filter/CarFilter.tsx
src/mobility/components/filter/ScooterFilter.tsx

Fixes https://github.com/AtB-AS/kundevendt/issues/4029

fix: Map filter: Show 'All' toggle when there are zero or more than one operator

---

src/components/map/components/mobility/BikeStations.tsx

Fixes https://github.com/AtB-AS/kundevendt/issues/4190

fix: Make city bike stations disappear at same zoom level as stop places

---

src/components/map/components/filter/MapFilter.tsx
src/components/map/components/mobility/Vehicles.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/4252

fix: PostHog logging for map clicks

---

src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx

closes https://github.com/AtB-AS/kundevendt/issues/4213
No longer showing red icon when the websocket reconnects

fix: flickering bus icon

---

src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx

Fixes: https://github.com/AtB-AS/kundevendt/issues/4052#issuecomment-1607202221

bug: Fix disabled `Confirm selection` button 

---

src/reference-data/types.ts
src/reference-data/utils.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByAlias.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByProducts.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-defaults.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Assistant/TicketAssistantTile.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProducts.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContracts.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistantContext.tsx
src/stacks-hierarchy/Root_TicketAssistantStack/handle-recommended-ticket-response.ts

I've added two new distribution channels: `debug-app` and `debug-web` which can be used to test products in production for users with debug enabled. 
The proposed solution has been discussed in this thread from [Slack](https://mittatb.slack.com/archives/C025NUF4WA0/p1682064525997789). From what I can see, there are no checks on the distribution channel that would create Bugsnag errors for previous app versions. 
Closes https://github.com/AtB-AS/kundevendt/issues/3897

feat: product testing for debug users in production

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContracts.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/4584

Make recent fare contracts spinner appear immediately

---

src/api/index.ts
src/api/use-subscription.ts
src/api/vehicles.ts
src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx

adds suggested changes from https://github.com/AtB-AS/mittatb-app/pull/3686#pullrequestreview-1500638714
Shouldn't be any functional changes

refactor: simplify websocket implementation

---

ios/Podfile.lock
ios/atb.xcodeproj/project.pbxproj

A part of: https://github.com/AtB-AS/kundevendt/issues/4243
NOTE: This is not including the Debug, Release and Debug config files to be embedded again, it is a result of a pod install after these files were removed.

fix: Do a `pod install` to keep update Xcode project with the fixes made on security fix at https://github.com/AtB-AS/mittatb-app/pull/3695

---

src/chat/ContactSheet.tsx

Closing https://github.com/AtB-AS/kundevendt/issues/4592
Icon colour for "Forbedre appen" now matching text next to the icon.
[Figma](https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/01.-Components?type=design&node-id=4632%3A15731&mode=design&t=0koY3bIOg1C4DZ3R-1)
<details>
<summary>Screenshots after fix</summary>
</details>

fix: explicit icon colour for "Improve app" button

---

src/components/transportation-modes/TransportModes.tsx
src/components/transportation-modes/index.ts
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Summary.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductIllustration.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductTile.tsx
src/translations/screens/FareContract.ts

closes https://github.com/AtB-AS/kundevendt/issues/3363
Before:
<br /><br />
After:

feat: new FareProductTile design with new illustrations

---

src/mobile-token/MobileTokenContext.tsx
src/mobile-token/tokenService.ts
src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx
src/stacks-hierarchy/Root_ActiveTokenOnPhoneRequiredForFareProductScreen.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/4135
Depends on: https://github.com/AtB-AS/abt-token-server/pull/49 & https://github.com/AtB-AS/abt-token-server/pull/51

feat: bypass toggle restrictions on `MobileTokenRequired`

---

src/translations/screens/Onboarding.ts
src/translations/screens/subscreens/AnonymousPurchases.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/5273

fix: correct onboarding texts for FRAM

---

src/reference-data/types.ts
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts
src/ticketing/types.ts
src/translations/screens/subscreens/PurchaseConfirmation.ts

closes https://github.com/AtB-AS/kundevendt/issues/3830
Add text line that informs about ticket time duration in Purchase Confirmation Screen.
<br />
<br />

feat: ticketing valid duration info

---

package.json
yarn.lock

closes https://github.com/AtB-AS/kundevendt/issues/5709
Dark mode color updated in Design System for more contrast.
Before:
After:

chore: Update Design System versions

---

src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Summary.tsx
src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts
src/ticketing/api.ts
src/translations/screens/subscreens/PurchaseOverview.ts

Update offer endpoint to use stop-places
Close https://github.com/AtB-AS/kundevendt/issues/4044

feat: Update to use stop place endpoint

---

src/configuration/defaults.ts
src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx
src/translations/screens/subscreens/PurchaseConfirmation.ts

Update texts on confirmation screen for boat tickets, and add boat tickets to default modes we sell tickets for
Close https://github.com/AtB-AS/kundevendt/issues/4044

feat: Update ticket confirmation screen

---

docs/Release.md

Updates docs to be more specific on the process of merging release branches to master. Not sure if this is exactly the "correct" way, so please suggest changes, but this is how I've done it 😄

docs: update merging of release branch docs

---

src/auth/AuthContext.tsx
src/translations/screens/subscreens/Login.ts

Handle sms code has expired. Show message to users telling them to re-request one-time code
Update title and other texts, and fix nynorsk
<details>
</details>
Close https://github.com/AtB-AS/kundevendt/issues/3730
[Figma sketches](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=16507%3A67037&mode=design&t=rKdqIMbogMmA9kjH-1)

feat: Show message if sms code has expired and fix nynorsk

---

src/reference-data/defaults/fare-product-type-config.json
src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductTile.tsx
src/translations/screens/subscreens/TravelToken.ts

Closes [Text change in token toggle](https://github.com/AtB-AS/kundevendt/issues/5712)
Depends on: https://github.com/AtB-AS/firestore-configuration/pull/227

feat: Text changes in token toggle

---

src/api/trips.ts
src/api/types/generated/fragments/trips.ts
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/NonTransitResults.tsx
src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-non-transit-trips-query.tsx
src/translations/screens/TripSearch.ts

Closes [#7198](https://github.com/AtB-AS/kundevendt/issues/7198)

feat: Add bike rental to non transit search results

---

src/api/types/generated/TripsQuery.ts
src/components/map/index.ts
src/mobility/use-stations.tsx
src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx
src/travel-details-screens/components/Trip.tsx

Part of https://github.com/AtB-AS/kundevendt/issues/7198

feat: Show city bike stations in map for bike rental trip search

---

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/NonTransitResults.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/7291

fix: Use bike icon for city bike suggestion

---

src/translations/screens/TripSearch.ts

Closes https://github.com/AtB-AS/kundevendt/issues/6990

fix: Adjust text for no trip search results

---

src/translations/screens/subscreens/TripDetails.ts
src/travel-details-screens/components/SummaryDetail.tsx
src/travel-details-screens/components/TripSummary.tsx

Closes https://github.com/AtB-AS/kundevendt/issues/7280

fix: Show total bike distance in trip details
