AtB-AS/mittatb-app

src/components/disappearing-header/index.tsx, src/screens/Assistant/FadeBetween.tsx, src/screens/Assistant/index.tsx, src/utils/use-conditional-memo.ts
Think this is a bit better than the fix from last evening, since it forces DisappearingHeader to wait with content height recalculation till after animation is done.
Also fixes glitch in FadeBetween so it doesn't enable animation till after component mount
=> fix: Delay DisappearingHeader recalculation till after animation

src/screens/Ticketing/Purchase/Travellers/index.tsx, src/screens/Ticketing/Splash/index.tsx
Since Google is adamant that these are ads (they are not but whatever), best to just remove them.
=> fix: Remove links to AtB Mobillett

src/components/sections/index.tsx, src/components/sections/radio-section.tsx, src/components/sections/section.tsx, src/index.tsx, src/navigation/TabNavigator.tsx, src/preferences/PreferencesContext.tsx, src/preferences/index.tsx, src/preferences/storage.ts, src/preferences/types.ts, src/screens/Profile/Appearance/index.tsx, src/screens/Profile/Home/index.tsx, src/screens/Profile/SelectStartScreen/index.tsx, src/screens/Profile/index.tsx, src/storage/index.ts, src/theme/ThemeContext.tsx
Adds user preferences context to app. Also adds two settings:
- Setting preferred startup screen
- Overriding dark mode locally (not listening to phone settings)
Note: From the design I've added an option "override phone". Logically I have a hard time managing if it should show dark mode or not when not explicitly saying override. Imagine scenario: We toggle to dark mode in-app, but switch back to non-dark mode. And then we go back to phone settings and activate darkmode, but the app is still light. Now there is no option to ever let the phone decide darkmode or not. Another option is to only ever override darkmode, so setting darkmode option to true sets option but deactivating it removes the option. But this would cause you not to be able to override to have light mode if the phone it …
=> feat: adds user preference to select start screen

src/favorite-chips/index.tsx, src/screens/TripDetailsModal/Map/CompactMap.tsx, src/utils/use-disable-map-check.ts
- Disable map for now when Voice Over is active on iOS. This is to prevent brutal app crash which is out of our control. Should be reverted as soon as possible.
=> fix: disables map when on iOS with voice over to prevent brutal crash

src/screens/Ticketing/Tickets/Ticket.tsx
Added a11ylabels for ticket support icon (upper left corner), so that screen reader users also can use this to determine if a ticket is valid or not.
=> fix: A11ylabels for ticket support icons

src/components/disappearing-header/index.tsx, src/navigation/TabNavigator.tsx, src/utils/navigation.tsx
My Android Emulator crashed hard now, need to do a full reset. Could you check, @rikkekantega ?
Max size for iOS:
=> fix: tab height issue on iOS and max scale

src/components/disappearing-header/index.tsx, src/screens/Assistant/FadeBetween.tsx, src/screens/Assistant/index.tsx, src/screens/Nearby/index.tsx
This is ridiculous, I know. Some of this doesn't make any sense and is brittle as a wood glued vase. However, it seems to workaround with our current issues with animated header for now. I think we should rethink this component and look into shared elements to do this instead, but that would require more work now and postpone the wanted release. But we should do proper QA-ing of this.
The issues seem to be caused by `scrollY` animated value being triggered by RefreshControl and when animating back to the initial state after refreshing, it's no longer the correct value. Not an issue on Android as the animation is positioned absolute and elevated. This doesn't seem to be possible on iOS with the current implementation.
Should properly check on Android also as the implementation has changed …
=> fix: hack/workaround for offset issues in header animation. NOT proper fix

src/components/sections/section.tsx
There were some issues with handling falsey values in section wrapper. This checks for actual first and last index of valid child to set proper radius.
Point is now to get a list indicating what is valid children and not. With that list we find both first and last index that is valid. These should get radiuses set. Technically valid children can be strings, but I think that is kind of outside the scope to patch that kind of usage.
=> fix: support for arbitrary falsey items in section

src/location-search/LocationSearch.tsx
=> fix: margin for no-result box on location search

src/screens/Ticketing/Purchase/Payment/CreditCard/index.tsx, src/screens/Ticketing/Purchase/Payment/CreditCard/use-terminal-state.ts
Move payment redirect check to `loadEnd` so race condition where callback is cancelled if we navigate away from the WebView too fast.
=> fix: Terminal payment redirect load needs time to finish

src/favorite-chips/index.tsx, src/geocoder/use-reverse-geocoder.ts, src/location-search/map-selection/index.tsx, src/screens/Assistant/index.tsx, src/screens/Nearby/index.tsx
Fixed a bug (three places) where the second closest location from the
hook useReverseGeocoder was used as the current location.
As every usage of useReverseGeocoder was mainly interested in only the
closest location, this was added as an own field in the returned state.
=> fix: Use closest location from reverse geo lookup

src/components/transportation-icon/index.tsx, src/utils/transportation-color.ts, src/utils/transportation-names.ts
Noticed when running through favorite branch locally that we weren't handling transport mode "coach". Seems like coach mode is a type of bus. Entur also display it as a bus. I've added this to existing icon/color functions.
=> fix: Add mode "coach" to transport color/icon

src/api/tariffZones.ts
This will also make A the default tariff zone as it is the first tariff
zone in the array.
=> chore: Sort tariff zones for easier selection

src/error-boundary/ErrorView.tsx
Crashes because `useChatIcon` uses remote-config, which is not available in the `ErrorBoundary`
=> fix: Remove chat icon since this will crash the ErrorView

src/ScreenHeader/animated-header.tsx, src/api/departures/types.ts, src/components/disappearing-header/simple.tsx, src/components/sections/action-item.tsx, src/components/transportation-icon/index.tsx, src/favorites/FavoritesContext.tsx, src/favorites/index.tsx, src/favorites/storage.ts, src/favorites/types.ts, src/location-search/types.ts, src/screens/Nearby/NearbyResults.tsx, src/screens/Nearby/index.tsx, src/screens/Nearby/section-items/line.tsx, src/screens/Nearby/section-items/quay-section.tsx, src/screens/Nearby/state.ts, src/screens/Profile/AddEditFavorite/index.tsx, src/screens/Profile/FavoriteList/SortFavorites.tsx, src/screens/Profile/FavoriteList/index.tsx, src/storage/index.ts, src/translations/screens/Nearby.ts, src/utils/transportation-color.ts, src/utils/transportation-names.ts
**This is dependent on production deployment of the BFF. It is also dependent on #775 which should be merged first**
This adds favorite departures from the departure screen. Only scoped to #680 where we can add favorites directly from results. Currently, this is the only way to add favorite departures.
For Code Review, see Acceptance Criteria on #680.
=> feat: Adds favorite departures (closes #680)

assets/svgs/mono-icons/actions/Delete.svg, src/assets/svg/icons/actions/Delete.tsx, src/components/sections/favorite-departure-item.tsx, src/components/sections/favorite-item.tsx, src/components/sections/index.tsx, src/screens/Profile/FavoriteDepartures/index.tsx, src/screens/Profile/Home/index.tsx, src/screens/Profile/index.tsx, src/translations/components/Section.ts, src/translations/index.ts, src/translations/screens/Profile.ts, src/translations/screens/subscreens/FavoriteDepartures.ts
**This is dependent on production deployment of the BFF. It is also dependent on #783 which should be merged first**
This could be merged into #783 as it is a small change
I think this should be a separate change from adding favorite through profile screen. Adding through wizard is a larger change which technically is nice to have (though very nice, don't get me wrong). But I think we can try to QA this and the other dependant changes and deploy that before implementing new add favorite flow.
=> feat: Adds ability to remove favorite departure

src/components/sections/counter-input.tsx
Even though the count was 1, the accessibility elements for the decrease
button was hidden.
=> fix: Counter-input accessibility bug

src/preferences/types.ts, src/screens/Profile/Home/index.tsx, src/screens/Profile/Language/index.tsx, src/screens/Profile/index.tsx, src/translations/LanguageContext.tsx, src/translations/commons.ts, src/translations/index.ts, src/translations/screens/Profile.ts, src/translations/screens/subscreens/LanguageSettingsTexts.ts
Defaults to "default language", currently set to "Norsk bokmål".
Using phone settings is optional - App then gets system locale, and decides on what will be considered the best app language.
User can choose app language explicitly from "Mitt AtB".
closes #780
=> feat: Language preferences in profile settings (behind feature flag)

src/screens/Ticketing/Purchase/TariffZones/index.tsx, src/screens/Ticketing/Purchase/Travellers/index.tsx, src/translations/screens/subscreens/TariffZones.ts
A commit showing how the logic would be distributed with text logic in the React components as opposed in the texts-files. The texts-files ends up much cleaner, but with the cost of increasing the size of the React component with text logic.
=> refactor: Internalization text in component

src/screens/Profile/FavoriteDepartures/index.tsx, src/screens/Profile/FavoriteList/SortFavorites.tsx, src/screens/Profile/FavoriteList/index.tsx
There's a bug when showing many favorites where the bottom padding on safe area sets bottom margin when we have bottom tabs. This deactivates bottom edge from safe area to avoid double padding (both in tab bar and content view).
=> fix: bottom padding in favorite lists

src/components/button/index.tsx, src/screens/TripDetails/components/TripSummary.tsx, src/translations/screens/subscreens/TripDetails.ts
- Rephrased "Nth step" to "Step n", in hope of more understandable iOS Voiceover reading
- Added "Total" to a11yLabel for total walk distance.
- Make screen readers ignore disabled buttons (discussable, perhaps an "inactive/disabled" a11y description is better?)
=> fix: QA adjustments on improved voiceover

src/api/fareContracts.ts
The old search offers endpoint was not working properly when the travel
was through more than one zone.
=> fix: Use new offers endpoint which allow two zones

src/translations/LanguageContext.tsx
Fixed broken langugage logic on initial app install, choosing locale based language instead of default preference selected language.
closes #843
=> fix: Broken logic on choosing language initial app install

src/screens/Profile/Language/index.tsx, src/translations/LanguageContext.tsx, src/translations/commons.ts
In cases where the user is onboarded to the app for the first time, it makes more sense to choose language based on system preference than having Norwegian set as default.
This is still not a perfect solution:
- System preferred language isn't always the preferred app language. 
- We only support Norwegian and English. All other system languages will be ignored, and default app language chosen. One might think that a foreigner could be more familiar with Norwegian than English
User is still able to able override language in app settings.
=> fix: Default use system language

src/TicketContext.tsx
When fetching fare contracts failed:
- It did not automatically retry
- Manual retry did not work, since the refresh control was already in
the refreshing state
=> feat: More robust fetching of fare contracts

src/api/utils.ts, src/reference-data/utils.ts, src/screens/Ticketing/Purchase/Confirmation/index.tsx, src/screens/Ticketing/Purchase/Overview/index.tsx, src/screens/Ticketing/Purchase/TariffZones/index.tsx, src/screens/Ticketing/Purchase/Travellers/index.tsx, src/screens/Ticketing/Ticket/TicketInfo.tsx, src/screens/Ticketing/Tickets/TicketOptions.tsx, src/tariff-zone-search/TariffZoneMapSelection.tsx, src/tariff-zone-search/TariffZoneResults.tsx, src/tariff-zone-search/VenueResults.tsx, src/translations/screens/subscreens/PurchaseConfirmation.ts, src/translations/screens/subscreens/PurchaseOverview.ts, src/translations/screens/subscreens/Travellers.ts
The reference data (UserProfiles, TariffZones, PreassignedFareProducts)
format support multiple languages by providing names and other texts in
a type which has a field 'lang' specifying language and a field 'value'
containing the text in that language. In our code this is typed as a
'LanguageAndText'.
This commit add utility functions for selecting the correct text based
on the current language.
=> feat: Show ref data names in correct langauge

src/translations/LanguageContext.tsx, src/translations/commons.ts
There is an issue with the language selection when feature toggle is disabled where it defaults to English. That kind of defeat the purpose of the feature toggle as a safety mechanism to enforce "old" way to show things. This PR fixes that.
This PR also fixes what seems to be a small error in handling default system languages where it now looks to just select the _most_ preferred language or English.
=> fix: Fix language prioritizing and default to no if enable_i18n is false

src/components/disappearing-header/content.tsx, src/components/pagination/index.tsx, src/screens/Nearby/section-items/line.tsx, src/screens/TripDetails/DepartureDetails/index.tsx, src/screens/TripDetails/DepartureDetails/types.ts, src/screens/TripDetails/DepartureDetails/use-departure-data.ts, src/screens/TripDetails/Details/index.tsx, src/screens/TripDetails/components/Trip.tsx, src/screens/TripDetails/components/TripSection.tsx, src/screens/TripDetails/components/TripSummary.tsx, src/translations/components/Pagination.ts, src/translations/screens/subscreens/DepartureDetails.ts, src/utils/date.ts, src/utils/use-is-loading.ts, src/utils/use-pollable-resource.ts
This adds pagination and date metadata to departure details view.
- Unifies behavior/design for trip pattern details and service journey/departure details.
- Adds disappearing map on scroll.
- Adds pagination for service journey/departure details
- Delays loading indicator 400 ms to avoid it showing too often.
https://user-images.githubusercontent.com/606374/106045112-deb0c680-60e0-11eb-915d-af69434e2257.mov
Closing #879
=> feat: Adds pagination and date to service journey/departure details

ios/Podfile.lock, package.json, src/api/client.ts, src/diagnostics/bugsnagConfig.ts, src/remote-config.ts, yarn.lock
* Upgrade to latest Bugsnag (several improvements apparently)
* Add `axios-better-stacktrace` (https://github.com/svsool/axios-better-stacktrace) since we have thousands of entries for `Error node_modules/axios/lib/core/createError.js:16`. Problem is `axios` creates a new Error at that line, which is the one Bugsnag reports. We're losing a lot of context around the error.
* Enable logging of `network-error`s and `timeout`s. But gate it behind a feature flag if we're finding it spams us.
=> feat: Add network logging for Bugsnag

.github/workflows/publish_remote_config.yml, .github/workflows/update_reference_data.yml
Syncs src/reference-data/*.json every hour and opens a PR if there are any diffs.
On push: uses an external tool: github.com/atb-as/remoteconfig/cmd/rc that lets you publish key=value pairs as default values in remote config. Need to revisit later when we need to differentiate on environments.
=> feat: workflow: update reference data & remote config

src/screens/Ticketing/Purchase/Overview/index.tsx, src/screens/Ticketing/Purchase/Product/index.tsx, src/screens/Ticketing/Purchase/index.tsx, src/translations/index.ts, src/translations/screens/subscreens/Product.ts
If more than one preassigned fare product is defined in RemoteConfig,
the user will be able to go to the product selection screen for
selecting product. In the overview screen the first product will still
be selected as default product.
The old app code also selected the first product in RemoteConfig as
default, and never allowed the user to change the product. To keep the
old app functioning as is, the 'Enkeltbillett buss/trikk' product must
be kept as the first product defined in the list from RemoteConfig.
=> feat: Add product selection screen

src/screens/Ticketing/Purchase/Confirmation/index.tsx
Users were unable to pay if they used enlarged text and selected
multiple traveller types, as the payment button came below the screen
view, and they were not able to scroll.
I won't be surprised if this also is the case on other screens. Maybe we
could create a View-component which enforced this layout somehow:
-- Header (with safe area top)
-- ScrollView
-- Footer (optional, with safe area bottom)
=> fix: Make confirmation screen scrollable

package.json, src/api/client.ts, yarn.lock
Upgrade to latest `axios-better-stacktrace` and concat error inside interceptor to get a better stack
=> fix: Update logging to include topmost error

src/components/screen-header/animated-header.tsx, src/components/screen-header/index.tsx, src/components/sections/text-input.tsx, src/components/text/index.tsx, src/utils/navigation.tsx
The combination of a long header title and large accessibility font
size made the title text overlap with the left button text. With this
change, the left button and right button will be rendered below the
header title if they are to wide to be on the same line.
Tried adding the same logic for the animated header, but decided not to
invest the necessary time for making it work. The animated header, and
its usage in the disappearing header, is quite complex, and changes
there can be error-prone. Instead used a simpler solution with
fontscale, but the buttons will as of now not render below the title on
the animated header.
=> fix: Fix header text overlap bug

src/components/sections/link-item.tsx
=> fix: Long text in LinkItem should not move icon

package.json, src/screens/Ticketing/Purchase/Overview/index.tsx, yarn.lock
If the user is sharing his location, and the location in within a
tariff zone, use this tariff zone as the default tariff zone when
purchasing ticket. Else the default tariff zone will be the first tariff
zone in RemoteConfig.
There was talks about letting the user select tariff zone based on his
nearest stops, to reduce the risk of selecting a initial tariff zone
that does not include the actual stop the user will travel from. This
may be implemented later if necessary.
=> feat: Default tariff zone from location

src/screens/Ticketing/Purchase/Overview/index.tsx, src/screens/Ticketing/Purchase/Travellers/index.tsx, src/translations/screens/subscreens/PurchaseOverview.ts
A summary of the selected travellers was added to the top of the travellers screen. The text follows the same logic as the overview screen, where three or more selected traveller groups gives the text "X travellers" instead of listing every group.
=> feat: Add summary on travellers screen

src/components/screen-header/index.tsx
On Android the header buttons sometimes flickered below the header title
for a single render. This was because for the first onLayout event the
button width was full screen width, event though the height of 0 made it
not visible yet.
=> fix: Flickering header button text

src/components/map/MapControls.tsx, src/screens/Assistant/ResultItem.tsx, src/theme/colors.ts
This PR fixes issue with only "Details" being pressable, after several feedbacks and discussions. The latest feedback can be seen at https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/4207849/conversations/159245400004398.
Also, the primary border in dark mode was way too contrasty. Although this is another issue I fixed this in the same go. I can separate this into two different PR-s if necessary, but I was lazy. Sorry!
(Attached image of the Map-screen as it also uses border primary style.)
=> fix: makes entire result item in Assistant pressable

.eslintrc.js, eslint-rules/avoid-imports.js, eslint-rules/import-warning.js, eslint-rules/index.js, eslint-rules/translations-warning.js, package.json, src/screens/Assistant/ResultItem.tsx, src/screens/Assistant/journey-date-picker/index.tsx, src/screens/Nearby/Nearby.tsx, src/screens/Nearby/section-items/line.tsx, src/screens/Onboarding/components/StepContainer.tsx, src/screens/Profile/SelectStartScreen/index.tsx, src/screens/Ticketing/Purchase/Overview/index.tsx, src/screens/Ticketing/Purchase/Payment/CreditCard/index.tsx, src/screens/Ticketing/Purchase/Payment/Vipps/index.tsx, src/screens/Ticketing/Purchase/TariffZones/index.tsx, src/screens/TripDetails/components/TripMessages.tsx, src/screens/TripDetails/components/TripSection.tsx, src/screens/TripDetails/components/TripSummary.tsx, src/screens/TripDetails/components/WaitSection.tsx, yarn.lock
This adds 3 custom linting rules to make some implicit project knowledge explicit. Namely:
1. We should always use `@react-navigation/native` instead of `@react-navigation/core`. Both work but native is more performant and is best practice. VSCode often suggests `/core`. This lint rule gives a warning when not using `/native` and provides autofix.
1. We should always use `SafeAreaView` from `react-native-safe-area-context` instead of `react-native`. SafeAreaView from react-native calculates padding wrong currently (at least for our use case). 
1. Texts from `/translate` modules should always be wrapped in `t` function provided from `@leile/lobo-t`. This is a naive implementation that doesn't actually check if given identifier `t` is from the correct function. Also the AST traversing is …
=> fix: adds custom lint rules to avoid simple mistakes

src/components/button/index.tsx
The Button component had two minor bugs when used with icon:
- The text was not completely centered on the button
- Long texts overlapped the icon
With this fix a horizontal margin is added to both sides when an icon is
present, making the text remain centered. Also this margin is now set to
xLarge (24), which makes it greater than the icon size (20), thus
hindering overlap.
=> fix: Button text centered with icon

src/components/sections/generic-item.tsx, src/components/sections/internals/internal-labeled-item.tsx, src/components/sections/link-item.tsx, src/components/sections/section-utils/use-section-item.ts, src/components/sections/text-input.tsx, src/screens/Nearby/section-items/line.tsx, src/screens/Profile/DesignSystem.tsx, src/translations/components/Section.ts
Fixes #983
This sets general flex on section base items. Can introduce some regressions but it should also fix text overflowing for every section item.
@gorandalum Could you check Ticketing?
=> fix: issue with wrapping section items

src/components/button/index.tsx, src/screens/Profile/Login/ConfirmCode.tsx
Added the underline by using TouchableOpacity and ThemeText instead of
using button. Modifying button by specifying text type, or adding a mode
"link" would have given more reusability, but this would be adding modes
that is outside the design system.
Also removed the possibility to specify text types for buttons. The text
types should be whatever was intended for that button mode in the design
system.
=> feat: Add underline for resend code button

src/screens/Onboarding/components/Illustration.tsx, src/screens/Onboarding/components/NavigationControls.tsx, src/screens/Onboarding/components/StepContainer.tsx, src/screens/Onboarding/index.tsx
The onboarding screens do not behave well on shorter screens, spesifically androids, eg. nexus 4.
The screens implement a scroll view for text info and step navigation, resulting in step navigation being pushed out of the screen with no visible cue (e.g. scroll bar) to guide the user forward.
re-implent views with working flex-layout, shrinking the illustration to make space for text and navigation when vertical space is limited.
=> fix: flex layout supporting shorter screens

src/screens/Ticketing/Tickets/Tabs.tsx, src/screens/Ticketing/Tickets/index.tsx, src/tickets/TicketContext.tsx, src/tickets/utils.ts
Earlier active tickets that expired was "hanging around" on the active
tab until the view was remounted. With this change the tickets are
rendered on their correct tab, and changing tab just as it expires.
=> feat: Tickets are shown on the correct tab

src/navigation/index.tsx, src/screens/Profile/index.tsx
Modal transitions default to scale animation on android and are not consistent with design intentions.
By explicitly using slidefromBottom transitions from IOS on the Assistant screen and slidefromRight transitions on Profile screen we get consistent transitions that are in line with the design.
The disappearing header has its own problems and are handled elsewhere.
Some modals still use scale on Android when they are not out of line with the design (tickets, maps etc)
=> fix: modal transitions for android

src/screens/Profile/Login/ConfirmCode.tsx
The destructive 'x' button for clearing did not work as the input field
was not fully managed by the component state code.
=> fix: Make 'x' on confirm code input work

src/components/sections/header-item.tsx, src/location-search/JourneyHistory.tsx, src/location-search/LocationSearch.tsx, src/location-search/index.tsx, src/location-search/types.ts, src/location-search/utils.ts, src/screens/Assistant/Assistant.tsx, src/screens/Nearby/Nearby.tsx, src/screens/Profile/AddEditFavorite/AddForm.tsx, src/screens/Profile/Home/index.tsx, src/search-history/index.tsx, src/search-history/storage.ts, src/search-history/types.d.ts, src/storage/index.ts, src/translations/screens/Profile.ts, src/translations/screens/subscreens/LocationSearch.ts
Closes #673
This PR adds the ability to re-use previous journey searches.
With this, I also added the ability to clear search history as a part of privacy. I feel this is more important now with actual journey searches, even though it is still only stored locally. (I also needed it for testing).
=> feat: adds recently searched journeys to location search and ability to clear history. Closes #673 

src/components/button/index.tsx, src/screens/Profile/DesignSystem.tsx
See #1016. This also fixes padding on inline buttons.
=> fix: bug with excessive padding for inline buttons

src/screens/Profile/Home/index.tsx
=> fix: padding for profile home screen

fastlane/Fastfile
destinations -- Comma separated list of distribution group names. Default is 'Collaborators', use '*' for all distribution groups
=> fix: Distribute to all QA groups

src/screens/Ticketing/Purchase/Confirmation/index.tsx, src/screens/Ticketing/Ticket/Details/DetailsContent.tsx, src/screens/Ticketing/Ticket/TicketInfo.tsx
Setting accessibile true on parent views that contain multiple texts,
making them be read by the screen reader in one go, instead of each text
being selectable.
=> feat: Group texts for screen reader

src/auth/AuthContext.tsx
It is not necessary to force refresh id token on login anymore as no
custom claims is used for setting up the firestore fare contract
subscription. This will also give slightly better handling of missing
internet connection on startup as the app can use cached token.
=> feat: Not force refresh id token on login

src/screens/Ticketing/Purchase/Overview/index.tsx, src/screens/Ticketing/Purchase/TariffZones/index.tsx, src/screens/Ticketing/Purchase/TariffZones/search/TariffZoneResults.tsx
Disable the tariff zone map selection if screen reader is enabled, as
MapBox crashes with screen reader. Instead show a list of the available
tariff zones.
=> feat: No tariff zone map if screen reader enabled

.eslintrc.js, src/screens/Assistant/ResultItem.tsx, src/screens/Nearby/section-items/line.tsx, src/screens/Nearby/section-items/more.tsx, src/screens/TripDetails/components/TripRow.tsx
An issue with using TouchableOpacity from `react-native-gesture-handler` as it is inaccessible. Add avoid import to eslint rule and fix instances of this occurring today.
This should fix issue with screen reader
=> fix: fixes inaccessible presses

src/components/sections/button-input.tsx, src/screens/Ticketing/Purchase/TariffZones/index.tsx, src/translations/screens/subscreens/TariffZones.ts
- Use blue/green colors for selected zones in map as using red color
could have unwanted connotations.
- The zone up for selection on next click is marked with bold text.
- Some text improvements.
=> feat: Improvements to zone selection after testing

src/components/message-box/index.tsx
Now use the text color appropriate for the tiny message box theme type.
=> fix: Wrong color on tiny message box

src/screens/Ticketing/Ticket/Details/DetailsContent.tsx, src/screens/Ticketing/Ticket/TicketInfo.tsx
The texts in the ticket details screen were read a little too fast with
no breaks between the lines. This was fixed by adding accessibility
labels with screen reader pauses.
=> feat: Screen reader improvements at ticket details

src/screens/Ticketing/Purchase/Confirmation/index.tsx, src/utils/numbers.ts
Method 'toLocaleString' does not work on Android, but will be fixed in
RN 0.65. Added a temporary solution for formatting of tax amount until
we upgrade to RN 0.65.
=> fix: Better formatting of tax amount

src/api/client.ts
Previously if all three retries failed the error would be logged four
times. Once for the initial request and once for each of the three
retries. With this change only the error from the last retry will be
logged. Also if one of the retries is successful, no error will be
logged.
=> feat: Retried requests errors logged only once

src/utils/use-focus-on-load.ts
Thix fiex the app crashing in some situations as the navigation object
could not be found.
=> fix: Handle navigation not found when focusing

src/components/disappearing-header/index.tsx, src/components/disappearing-header/simple.tsx, src/components/screen-header/animated-header.tsx, src/components/screen-header/full-header.tsx, src/components/sections/favorite-departure-item.tsx, src/location-search/LocationSearch.tsx, src/location-search/map-selection/LocationBar.tsx, src/navigation/index.tsx, src/screens/Loading/index.tsx, src/screens/Ticketing/Purchase/TariffZones/index.tsx, src/screens/Ticketing/Purchase/TariffZones/search/index.tsx, src/screens/Ticketing/Splash/Info.tsx, src/screens/Ticketing/Tickets/TabBar.tsx, src/screens/Ticketing/Tickets/UpgradeSplash.tsx, src/screens/Ticketing/Tickets/index.tsx, src/screens/TripDetails/DepartureDetails/index.tsx, src/screens/TripDetails/Details/index.tsx, src/screens/TripDetails/QuayDepartures/index.tsx, src/screens/TripDetails/components/TripLegDecoration.tsx, src/theme/colors.ts
After some contemplation I figured that the extra layer with theme
colors did more harm than good, as it removed the tight link between
the app design and the Figma design.
=> feat: Remove theme overrides for background colors

.github/workflows/build-staging-ios.yml, .github/workflows/build-store-ios.yml
iOS build failing currently, I believe it is related to v1.9.3 being installed by default on Github Actions, trying to remedy this
=> fix: Correct CocoaPods-version in Github Actions

src/screens/Nearby/Nearby.tsx
=> fix: set focus on load for Nearby screen header

src/screens/Profile/AddEditFavorite/EmojiPopup.tsx
The .map function throws error since the emojis are undefined. I have
not used time on looking into why the emojis are undefined, just quick
fixed this to make the app not crash.
=> fix: Emoji popup crashing on some Android versions

src/components/screen-header/animated-header.tsx
Resolves #1153
Kjent "feil" på bakgrunn av denne endringen er at "alternativ tittel" leses opp rett etter header. Skal se på om den kan gjemmes i en separat PR. Ikke blocking slik jeg ser det.
=> fix: Don't lock focus after navigation

src/components/sections/text-input.tsx, src/location-search/LocationSearch.tsx, src/translations/components/Section.ts
Resolves #1181
Kjører `blur` på input-feltet ved escape-gesture. Dette vil også skje selv om input ikke er focused, så hvis vi skal ha flere actions på escape må vi i framtiden håndtere noe bedre i view-hiarchy her. Altså f. eks. "navigate back" hvis input ikke er focused. La også til at header ikke skulle fokuseres først i søk-modalen, som betyr at input fokuseres først.
=> feat: Blur TextInput on escape gesture (iOS)

src/navigation/TabNavigator.tsx
fikser en feil der icon legger seg oppå label på veldig store skjermer (pad).
Tabbar nav vil default legge icon og label på samme linje hvis man har stor skjerm real-estate, men det funker ikke så bra siden vi bruker vårt eget ThemeTextView for å vise label, og fører til at icon legger seg oppå label.
En enkel fiks for dette er å sette at icon altid skal vises på linjen over label slik den alltid gjør på mobil.
Setter også at line height hentes fra theme, istedet for hardkodet.
=> fix: label always below icon on tabbar

src/navigation/index.tsx
During transitions the generic white background from React naviation
some times "leaked" through, giving a noticable flash to the user,
especially in dark mode. We got report from a user in Intercom that
this was unpleasant.
The best fix would be to remove these "leaks" of the background color
all together, but I could not find a good solution for this. As such
this was fixed by setting the background color for React navigation to
be 'background_1' from the AtB theme. This makes the background light
gray in light mode and dark gray in dark mode, making the background
leek less unpleasant.
=> feat: Set background color for React navigation

src/tickets/TicketContext.tsx
There was a bug where some customers ended up with haveing both an
active reservation and active ticket with the same order id. This was
(probably) because of a race condition where the reservation was created
after the ticket was created, and thus never "cleaned up".
=> fix: Handle ticket created before reservation

src/components/bottom-sheet/BottomSheetContext.tsx, src/departure-list/section-items/line.tsx
Basert på kommentar fra Tor på #1260:
> markerer favoritt og velger alle variasjoner av en linje, så flyttes fokus til Avganger nede på menyen. Upraktisk hvis man da sveiper til siden for å kunne markere f.ex Vis kun mine favoritter.
Bør testes på Android, og også at det ikke gir noen regresjoner for det å åpne bottom sheet under billettkjøp.
=> feat: Handle focus on bottom sheet close

src/tickets/TicketContext.tsx
Ticketing Context sin useEffect mangler enable_ticketing som dependency som kan føre til at dersom enable ticketing går fra false til true ila appens levetid så vil vi ikke legge på en lytter på Firebases onSnapshot. I praksis kan det slå ut med at om remoteconfig feiler og default enable_ticketing = false, så vil vi ikke kunne legge på en ny lytter når config en gang blir hentet.
Ytterste konsekvens kan være at billetter ikke dukker opp som forventet.
=> fix: enable/disable ticketing snapshot listeners

src/auth/AuthContext.tsx, src/auth/utils.ts
Kan se ut som det er en bitteliten sjanse for feil med innlogging til anonym her i rette omstendigheter, selv om det burde fungere som regel via signout -> så signin anon.
Gjør funksjoner signing/confirm om til useCallbacks for litt optimalisering og sletter ubrukt kode.
=> refactor: Setter funksjoner som memoed og fikser potensiell anonym innlogging bug

src/api/departures/departure-group.ts, src/api/departures/index.ts, src/screens/Assistant/journey-date-picker/index.tsx, src/screens/Nearby/Nearby.tsx, src/screens/Nearby/departure-date-picker/index.tsx, src/screens/Nearby/index.tsx, src/screens/Nearby/state.ts, src/translations/index.ts, src/translations/screens/Nearby.ts, src/translations/screens/subscreens/DepartureDatePicker.ts, src/utils/date.ts
Bytter ut favorittsteder i Avganger-visningen til å kunne hente ut avganger frem i tid.
=> feat: adds ability to fetch departures from the future

src/utils/navigation.tsx
Teksstørrelsen som brukes i beregning av høyde på navbar er begrenset til å ikke være mindre enn 1. Dette forhindrer nedre del av skjerm å bli skjult.
Før/etter:
fixes #1425
=> fix: screen height is too big when fontScale is less than 1

src/departure-list/section-items/line.tsx
Avganger som nettopp har passert fører ikke lengre til at avgangen blir "grået ut", slik at tekst er mer leselig, og det er mulig å trykke på avganger som uansett er synlig.
**Før:**
**Etter:** (Avgangen vil alltid se slik ut frem til den forsvinner)
fixes #1392
=> fix: past departures no longer causes disabled buttons

src/favorites/FavoritesContext.tsx
Når brukeren legger alle versjoner av en linje til favoritter, slettes eksisterende favoritter med samme linjenummer. Her manglet en sjekk for om de eksisterende favorittene var på samme quay. 
Ved å kun filtrere bort favoritter har både samme `lineId` og `quayId`, fungerer dette som det skal. 
https://user-images.githubusercontent.com/1774972/129033511-b7bd92c7-3a21-4315-a141-e8e6b63f554e.mp4
fixes #1445
=> fix: add check for `quayId` in `addFavoriteDeparture`

src/components/sections/action-item.tsx, src/components/switch/index.tsx, src/utils/use-delay-gate.ts, src/utils/use-gate.ts
@monopoint kjempebra catch på fixen her! Jeg tenkte vi kunne flytte den fiksen til en egen component slik at den potensielt kan brukes andre plasser også hvis det behovet oppstår?
=> fix: Refactor fixed Switch into own component for reuse

src/screens/Nearby/DepartureTimeSheet.tsx, src/utils/use-keyboard-height.ts
Forsøk på å fikse at tastatur på iOS skjuler tidsvelgeren på avganger. Når tastatur lastes legges det til en padding under innhold tilsvarende størrelse på tastatur. 
https://user-images.githubusercontent.com/1774972/130027165-f6ad697f-16bc-4786-88d2-3ab9024c92a7.mp4
fixes #1492
=> fix: time selector on departures hidden by keyboard on ios

src/utils/use-keyboard-height.ts
Liten typo i use-keyboard-height.ts, som fører til at listener ikke blir fjernet etter bruk.
=> fix: typo in `use-keyboard-height`

src/departure-list/section-items/line.tsx, src/screens/TripDetails/components/Time.tsx
Nitpick: Siden translation av missingRealTimePrefix [allerede har en whitespace](https://github.com/AtB-AS/mittatb-app/blob/0fe7872e38b1c60fc3294d1db166e16eb5c09b2a/src/translations/dictionary.ts#L16) (`'ca. '`). Bør der ikke være ekstra mellomrom når det brukes i tekst, siden det fører til litt for lang avstand mellom "ca." og klokkeslett, og gir litt mindre plass til tidspunkt på avganger-skjermen.
=> fix: double space after missingRealTimePrefix

src/screens/Assistant/Assistant.tsx, src/screens/Assistant/Results.tsx, src/screens/Assistant/types.tsx, src/translations/screens/Assistant.ts
Noen oversettelser mangler på engelsk for `NoResultReason` i feilmeldingen når man ikke får resultater i reisesøk. Byttet ut en enum i `src/screens/Assistant/types.tsx` med oversettelser i `src/translations/screens/Assistant.ts`. 
Usikker på om å sende `t: TFunc<typeof Language>` som parameter til `computeNoResultReasons` er helt riktig, men det ser ut til å fungere bra.
=> fix: add missing translations for noResultReasons

src/components/disappearing-header/index.tsx, src/components/screen-header/animated-header.tsx, src/screens/Assistant/Assistant.tsx
Se issue #1502 for demo av problemet.
DisappearingHeader har nå en `showAlterntativeTitle` attributt, som deaktiverer `alternativeTitleComponent` når den er false. 
Den er nå satt til å være false
1. så lenge `from` og `to` ikke er definert
2. mens DisappearingHeader animerer, for å unngå at [alternativ tittel vises mens søk blir gjort.](https://user-images.githubusercontent.com/1774972/131834700-27e85e86-d70e-4214-bbb0-b0eb0c08d1eb.mov
)
https://user-images.githubusercontent.com/1774972/131834981-c9a2f32d-c235-4044-ab02-3a8ab89ac493.mov
fixes #1502
=> fix: wrong header when returning to home from search

.github/workflows/build-staging-android.yml, .github/workflows/build-staging-ios.yml, .github/workflows/build-store-android.yml, .github/workflows/build-store-ios.yml, README.md, package.json, scripts/android/run-android.sh, scripts/generate-native-assets.sh, scripts/override-environment.sh, setup.sh
Endrer setup commandoen til `yarn setup dev atb` for å forenkle ting, og separerer generering av native assets fra override-environment. Dette bør fikse bygget, samt potensielt gjøre det enklere å "setup" en lokal dev-env.
=> feat: First time setup commands

package.json, src/components/sections/action-item.tsx, src/components/sections/generic-clickable-item.tsx, src/components/sections/index.tsx, src/components/sections/phone-input.tsx, src/login/PhoneInput.tsx, src/translations/components/Section.ts, src/translations/screens/subscreens/Login.ts, yarn.lock
Ny mobilnummer-input-felt med landskode / prefiks velger, som gjør det mulig å bruke internasjonale mobilnummer ved innlogging. 
Noen punker om hvordan det er implementert:
- Rammeverket https://github.com/AfterShip/phone blir brukt for å validere riktig lengde av mobilnummer. Det er også mulig å sjekke at de første sifferene er mobilnummer, men dette er slått av, og håndteres heller i backend. 
- Kun engelsk oversettelse av land/regioner er lagt inn nå.
- Mange av `+1` regionene har blitt filtrert ut (f.eks. British Virgin Islands), siden disse vil fungere ved å velge "+1 United States". Der er fortsatt noen duplikater for landskoder, men (eks. Åland Islands), men tenker det er greit å ha med.
- ~PRen oppdaterer også komponenten `ActionItem`, og gir den en optional parameter `children`, …
=> feat: updated phone number with prefix input

src/login/ActiveTicketPrompt.tsx, src/login/LoginOnboarding.tsx, src/login/PhoneInput.tsx, src/login/in-app/ActiveTicketPrompt.tsx, src/login/in-app/LoginInAppStack.tsx, src/login/in-app/LoginOnboarding.tsx, src/login/in-app/PhoneInputInApp.tsx, src/screens/Ticketing/Tickets/Tabs.tsx, src/translations/screens/Tickets.ts, src/translations/screens/subscreens/Login.ts
Lagt til ny skjerm med info til brukere som prøver å logge inn med aktive billetter, `ActiveTicketPrompt`. Fjernet også `loginReason` fra PhoneInput.tsx, siden denne ikke lenger er i bruk (c992fa3727f57c03b447f336fc1c774d0ff5aae4). 
https://user-images.githubusercontent.com/1774972/134673392-afdf499e-c9da-43f1-ab1a-eec82a8c3d47.mp4
Todo:
```jsx
{
title: _(
'Du har en aktiv billett', 
'You have an active ticket'
),
body: _(
'Når du logger inn vil dine anonyme billetter **ikke** kunne overføres til din profil. Hvis du ønsker å beholde din aktive billett venter du med innloggingen til billetten har utløpt.',
'When you log in, your anonymous tickets will **not** be transferred to your profile. If you want to keep your active ticket, wait for it to expire before logging in.',
),
laterButton: …
```
=> feat: show warning when user tries to log in with active ticket

src/auth/AuthContext.tsx, src/login/PhoneInput.tsx
@tormoseng oppdaget en feil med at prefiks ikke kom med i kallet til `singInWithPhoneNumber`, og at `+47` fortsatt blir hardkodet inn i starten av alle mobilnummer når man prøver å logge inn.
=> fix: include prefix when calling `signInWithPhoneNumber`

src/login/ActiveTicketPrompt.tsx, src/screens/Ticketing/Ticket/index.tsx
Oppdaterer `SimpleTicket` til å ikke støtte billettkontroll i `ActiveTicketPrompt` skjermbildet, siden dette sikkert er uventet funksjonalitet for de fleste :)
Før/etter: (Se "Show details / inspections"-knappen)
=> fix: hide `SimpleTicket` details on `ActiveTicketPrompt` screen

ios/Podfile.lock, src/components/bottom-sheet/AnimatedBottomSheet.tsx, src/screens/Ticketing/Purchase/Confirmation/index.tsx, src/screens/Ticketing/Purchase/Payment/SelectPaymentMethod/index.tsx
> Uten innlogging
> 
>     Med VoiceOver så leser valgmodul opp "Betal med ... - aktiver for å betale med ..." uavhengig av om denne allerede er valgt.
>     Markering av en betalingsmåte gir ingen feedback på hverken VoiceOver eller TalkBack at denne er valgt.
>     Android 7.0 / Talkback: Fra billettkjøp, velger jeg "Velg betalingsmåte". Header "Velg betalingsmåte" blir ikke lest opp.
> 
> Med innlogging
> 
>     Med både VoiceOver og TalkBack så er det ikke alltid header kommer i fokus. Kan være avhengig av om jeg har vært "inne der før" og gjort en betaling.
>     Med VoiceOver så får jeg ikke markert lagre-kort-checkbox. Sveip til høyre og venstre veksler kun mellom betalingsmåtene og kommer ikke innom lagre-kort-checkbox (dette skjer ikke med TalkBack).
>     Med VoiceOver så får …
=> fix: #1497 testing results

src/departure-list/DeparturesList.tsx, src/departure-list/section-items/line.tsx, src/departure-list/section-items/quay-section.tsx, src/screens/Nearby/Nearby.tsx, src/screens/TripDetails/QuayDepartures/index.tsx, src/utils/date.ts
If a departure on the departures screen is more than 24 hours in the
future, it will be prefixed with the date.
=> feat: Date on next day departures

src/components/sections/link-item.tsx
I nye den avganger visningen er det nyttig å kunne sette `textType` for en LinkItem i lister, som i dette eksemelet med bold tekst. Gjør den som egen PR for å gjøre #1734 litt mindre.
=> feat: add textType prop to link-item

android/app/src/main/AndroidManifest.xml, src/GeolocationContext.tsx
Potential fix for https://github.com/AtB-AS/mittatb-app/issues/1792
> On Android 12 (API level 31) or higher, users can request that your app retrieve only approximate location information, even when your app requests the ACCESS_FINE_LOCATION runtime permission.
> To handle this potential user behavior, don't request the ACCESS_FINE_LOCATION permission by itself. Instead, request both the ACCESS_FINE_LOCATION permission and the ACCESS_COARSE_LOCATION permission in a single runtime request. If you try to request only ACCESS_FINE_LOCATION, the system ignores the request on some releases of Android 12.
=> fix: ACCESS_COARSE_LOCATION option for Android manifest

src/screens/Profile/DesignSystem.tsx
Etter ønske fra @hildeor får man nå hex-kode som alert når man trykker på en "farge-knapp" på design system skjermen.
https://user-images.githubusercontent.com/1774972/144057442-5f338848-7036-42a6-9adb-d19393cbe516.mp4
=> feat: add hex code alert to design system color buttons

src/screens/Ticketing/Tickets/Tabs.tsx
I tickets følger ikke `topMessage` sitt innhold fargen til info status, men er satt til primary_1. Får en liten issue med det når jeg oppdaterer design systemet.
=> fix: use status theme color for MessageBox content

yarn.lock
Oppdaterer design systemet med forandringer fra https://github.com/AtB-AS/design-system/pull/12 og https://github.com/AtB-AS/design-system/pull/15
Det er kun fargekoder som blir forandret, så ingenting direkte breaking, men man bør verifisere at farger som har forandret seg ser ok ut i appen. 
Et kjent problem er beskrevet i #1844.
=> chore: upgrade theme to version 5.0.1

package.json, src/components/sections/phone-input.tsx, src/location-search/LocationSearch.tsx, src/screens/Ticketing/Purchase/TariffZones/search/index.tsx, src/screens/Ticketing/Ticket/Details/ReceiptScreen.tsx, src/utils/use-keyboard-height.ts, yarn.lock
Med RN-oppgradering så har de deprecated gamle-måten å remove listener subscription på Keyboard (og andre EventEmitters). Vi får masse warnings på de, men flesteparten av de kommer fra bruk i andre avhengigheter. Så vi burde i grunn oppgradere de etter ny butikk-release. Men vi kan fikse en plass, og det er i vår egen kodebase.
=> fix: Listener warnings (in our code)

src/components/transportation-icon/index.tsx, src/departure-list/section-items/line.tsx, src/screens/Profile/DesignSystem.tsx, src/utils/use-transportation-color.ts
- Legger til en `colorType: 'color' | 'backgroundColor'` parameter til `useTransportationColor()` slik at man kan hente både forgrunn og bakgrunnsfarge. `TransportationIcon` komponenten tar i bruk dette til en ramme rundt ikonene. 
- La også inn oversikt over alle typer Transportation ikoner i design systemet.
closes #1844
=> feat: update transportation icons

src/screens/Departures/StopPlaceScreen.tsx
Forandringer:
- Bruker nå temafarger til innhold i lineChip
- Oppdatert LineChips til å fungere bedre for forskjellige tekststørrelser. (basert på `fontScale`)
- Håndtert situasjoner hvor avgangen ikke har en PublicCode (f.eks. fly) eller ikon (f.eks. T-bane)
#1394
=> feat: update line chips

src/screens/Assistant/Assistant.tsx, src/screens/Nearby/DepartureTimeSheet.tsx, src/screens/Nearby/Nearby.tsx, src/screens/Nearby/state.ts, src/screens/Nearby/types.ts
Ref problemstilling diskutert på Slack ang. søketidspunkt, så holder skjermbildene lengre på søketidspunktene enn vi skulle ønske. Spesielt i forbindelse med at telefoner får økt ytelse og kan holde på appene i minnet lengre. Så noen tiltak slik at skjermbildene ikke oppfører seg forvirrende hvis de åpner etter ei stund:
* Oppdaterte Avganger til å være lik Reisesøk med pull-to-refresh, at dette også oppdaterer søketidspunkt gitt at “Nå” er valgt.
* På Avganger så vil “Nå” oppdateres automatisk hvis det har gått mer enn 10 minutter siden forrige “søketidspunkt”. Dette vil bety en full-refresh hvert 10. minutter, som ikke vil være en høy kostnad i antall ekstra API-kall.
* På Reisesøk så vil “Nå” oppdateres automatisk hvis det har gått mer enn 1 time. Dette kan potensielt settes lavere, …
=> fix: Reset search times at intervals

src/screens/Profile/Language/index.tsx
Fikser issue https://github.com/AtB-AS/mittatb-app/issues/1627
Problemet som oppsto er at når en enhet har et annet systemspråk enn norsk, og brukeren huker av "useSystemLanguage" er language fortsatt undefined. Nå oppdateres language når useSystemLanguage oppdateres
=> fix: When setting "useSystemLanguage", set language to a value if undefined

src/utils/date.ts
=> fix: use "min" as shorthand for "minute" in English

src/components/transportation-icon/index.tsx, src/utils/use-transportation-color.ts
=> feat: Use correct theme color on line number text

src/screens/Departures/StopPlaceScreen.tsx, src/screens/Departures/index.tsx
Lagt til navigasjon til detaljvisning fra nye avganger. Bruker foreløbig de gamle skjermene med JP2, og viser også til "gamle" avganger når man navigerer til et stopp fra detaljer.
https://user-images.githubusercontent.com/1774972/149936850-70ee3618-f576-4421-84e3-354a861860c3.mp4
closes #2012
=> feat: add departure details navigation

src/screens/Departures/StopPlaceScreen.tsx, src/screens/Departures/components/DateNavigator.tsx
- Flyttet komponent `DateNavigator`, ut av StopPlaceScreen, for å forenkle, og gjøre den mer gjenbrukbar
- Fjernet muligheten til å velge dato tilbake i tid 891719adf61143dc4adcd4d3b1956fd048ed7e07 (fiks av #2046)
fixes #2046
=> feat: update departures date navigation 

src/components/transportation-icon/index.tsx
There was a bug where the left padding was 8px and the right
padding was 12px when line number text was not included.
=> fix: Padding small on transportation icon

src/screens/Ticketing/Splash/Info.tsx, src/translations/screens/TicketSplash.ts
Feil farge valgt på ticketing splash:
Før:
Etter:
=> fix: color for text on ticketing splash

src/auth/AuthContext.tsx, src/screens/Profile/Home/index.tsx, src/translations/screens/Profile.ts
Related https://github.com/AtB-AS/webshop/issues/469
Det store spørsmålet er, skal kundenummer vises om du ikke er logget inn med telefonnummer? Du er anonym, men du har fortsatt et kundenummer (for at du skal kunne gjennomføre et kjøp). Men gir det mening å vise det? Jeg synes på sett og vis det, siden det gjør det mulig for kundeservice å hjelpe de selv om de er anonym
=> feat: Add customer number to Profile

src/chat/metadata.ts, src/screens/Profile/Home/index.tsx
closes #1957
Logger en event `enable_beta_departures` og `enable_beta_tripsearch` hver gang noen toggler en betafunksjon av eller på, som legges som parameter "toggle: enable / disable". 
Dette betyr at samme bruker kan telles som flere aktiveringer hvis man skrur av og på flere ganger, men tenker det er ok i denne omgang.
Legger til to attributter for intercom `AtB-Beta-TripSearch` og `AtB-Beta-Departures`, som er disabled eller enabled. Disse settes ved aktiverering / deaktivering, så den vil ikke være satt for de som allerede har skrudd betafunksjonene på før denne funksjonen er lagt til.
[Eksempel i intercom](https://app.intercom.com/a/apps/xcvep5se/inbox/inbox/5163675/conversations/159542700000718)
=> feat: add beta features analytics

src/api/types/generated/QuayDeparturesQuery.ts, src/api/types/generated/StopQuayDeparturesQuery.ts, src/screens/Departures/components/QuaySection.tsx
=> fix: use `aimedDepartureTime` as part of EstimatedCallItem key

src/screens/Departures/components/QuaySection.tsx
Liten fiks av feil logikk i om liste skulle ha border i bunnen eller ikke.
=> fix: quay section border

src/api/departures/stops-nearest.ts, src/screens/Departures/state/quay-state.ts, src/screens/Departures/state/stop-place-state.ts
Legger til at avganger som listes ut for et stoppested, er begrenset til samme dag eller minimum 3 timer, slik som for quays.
Eksempel: Ladeveien har flere enn 2 avganger neste dag som ville blitt listet ut før, men nå begrenes det til 3 timer, siden søket er fra kl. 23:50.
closes #2131
=> feat: use timeRange for StopPlace departures

.github/workflows/build-staging-android.yml, .github/workflows/build-staging-ios.yml, .github/workflows/build-store-android.yml, .github/workflows/build-store-ios.yml
Fikser feil med bygging i main.
Dette oppdaterer til nåværende anbefalte node-versjon. v12 som brukes per i dag har end-of-life i april.
=> fix: updates node in build scripts to lts

src/screens/Profile/Home/index.tsx, src/translations/screens/Profile.ts
Ref. https://mittatb.slack.com/archives/CS3JNRXEV/p1644484599374919
Flytter invitasjonskode-knappen til under beta-seksjonen
=> fix: Move invitation code to beta-section

src/screens/Departures/PlaceScreen.tsx, src/screens/Departures/QuayView.tsx, src/screens/Departures/StopPlaceView.tsx, src/screens/Departures/components/DateNavigator.tsx
Som beskrevet i issue:
- Dato og klokkeslett bevares hvis man hopper mellom plattformer / "alle stopp"
- Klokkeslett bevares hvis man hopper mellom datoer ("Neste dag" / "Forrige dag")
- Dato og tid blir resatt til nåtidspunkt hvis man går ut av stoppestedet og tilbake til søkeskjermen
Klokkeslett blir også resatt til "nå" hvis man går til dagens dato, og klokkeslett er tilbake i tid. 
https://user-images.githubusercontent.com/1774972/153556225-999a253d-690a-49fa-903a-5e305b7ac5cf.mp4
closes #2146
=> feat: preserve time selection across views and dates

src/chat/use-chat-unread-count.ts
Per nå vises chat count dersom intercom ikke er aktivert også. For de fleste tilfeller vil dette vel være 0, så ikke sikkert det er et problem. Men det kan være tilfeller hvor AtB går fra å ha Intercom aktivt til å være inaktivt hvor det henger igjen count.
Ikke viktig sak, men rett skal være rett osv.
=> fix: only show chat count indicator if intercom enabled

src/index.tsx, src/mobile-token/MobileTokenContext.tsx, src/screens/Ticketing/Ticket/Details/DetailsContent.tsx, src/screens/Ticketing/Tickets/Tabs.tsx, src/tickets/types.ts
Forslag til hvordan vi kan remotely enable mobile-token for enkelte brukere via Firestore. Tanken er, de som allerede har brukt invitasjonskode og har fått `enable_period_ticket` satt skal få fortsette med det. Men vi kan også skru på et flagg på kundeprofilen i Firestore for å enable både mobile-token og periodebillett. 
Hvis ønskelig kan også denne løsningen utvides på BFF til å samtidig sette flagget i Firestore når folk inputter invitasjonskoden.
=> feat: Own Firestore-flag for enabling mobile-token

src/screens/Departures/components/QuaySection.tsx
Under refaktorering av avganger ble forandringene i #2045 med padding mellom quays overskrevet, så jeg prøver igjen!
=> fix: update quay section padding

.github/workflows/README.md, .github/workflows/build-store-ios.yml
Also add docs on how to generate the necessary API-key
Fordelen med dette er at vi slipper å gå inn kontinuerlig å re-authetnicate koblingen mot App Store inni AppCenter
=> chore: Switch AtB TestFlight-upload to Fastlane

package.json, scripts/android/upload-sourcemaps.sh, yarn.lock
Forsøk på å fikse at bygg feiler med opplasting av source maps til bugsnag ([eksempel](https://github.com/AtB-AS/mittatb-app/runs/5215170352?check_suite_focus=true)). Oppgraderer fra depricated bugsnag-sourcemaps til @bugsnag/source-maps. Denne har litt nye CLI argumenter ([docs](https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/)), så har oppdatert upload-source-maps.sh med disse.
Er ikke sikker på om dette er kilden til problemet, men er kanskje lurt å oppgradere uansett.
Lukker #2183, gitt at det fikser problemet med bygg
=> build: replace depricated `bugsnag-sourcemaps`

src/screens/Ticketing/Purchase/Overview/index.tsx, src/screens/Ticketing/Ticket/Details/DetailsScreen.tsx, src/translations/screens/subscreens/PurchaseOverview.ts
Dette er et _forslag_ på en veldig simpel implementasjonen av meldingsboks for samarbeidsbilletten. Er med på at dette kan gjøres mer generelt og vakkert, men lurer på om dette er en grei nok midlertidig™ løsning. Kan godt forandre på implementasjonen, men da trenger jeg noen forslag for hvilken retning jeg skal ta den.
Matcher på sonevalg fra og til "ATB:TariffZone:1", så den skal ikke dukke opp for NFK/Fram.
- 'Visste du at enkeltbilletter i sone A også kan brukes på tog i sone A?'
- 'Single tickets in zone A can also be used for trips by train in zone A.'
https://user-images.githubusercontent.com/1774972/155524312-7f7f808d-858e-4325-8737-96441fac285a.mp4
closes #2155
=> feat: add information on single tickets on train in zone A

docs/Release.md, ios/atb.xcodeproj/project.pbxproj, ios/atbTests/Info.plist, scripts/ios/upload-sourcemaps.sh
Vi sender allerede inn `APP_VERSION` via `.env`-filene til både iOS-prosjektet + kjørende scripts. Så vi kan heller bruke denne og kun bumpe i `.env`-filene fremfor manuelt så mange plasser. Burde forenkle release-prosessen litt.
På sikt hadde kanskje også vært fordelaktig å se på `.env`-merging på tvers av filer, og kun override de som er forskjellig per organisasjon/miljø. En annen forbedringspotensiale er å sende inn `APP_VERSION` fra release-data/tag. 
(Vi henter allerede ut release-notater i workflow i dette [steget](https://github.com/AtB-AS/mittatb-app/blob/beeae85aecfa160b6465b2d5be843acbb74c87eb/.github/workflows/build-store-android.yml#L34), og sender det inn når det [pushes mot AppCenter](https://github.com/AtB-AS/mittatb-app/blob/beeae85aecfa160b6465b2d5be843acbb74c87eb/.github …
=> chore: Use APP_VERSION for version in iOS project + scripts

src/screens/Ticketing/Ticket/TicketInfo.tsx
Fiks av feil farger på "Ikke vis i kontroll"-ikonet ([Slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646129545400579)), som dukket opp i QA #2211.
Fikk til å gjenskape problemet ved å logge inn på en bruker med ikke-inspiserbare billetter, men det ble riktig igjen etter restart av appen. 
Oppdaterer fra `backgroundColor: 'none'` til `backgroundColor: undefined`. Selv om jeg ikke fullt og helt forstår hvordan feilen oppstod, klarer jeg ikke å gjenskape det lengre, og er ganske sikker på at dette er det som forårsaker feilen.
=> fix: use undefined as non-inspectable icon background

src/travel-token-box/index.tsx
Oppdatert styling på tittel i travel-token-box. Ref. [slack-tråd](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646134161002599)
=> fix: update travel-token-box title styling

src/screens/Ticketing/Tickets/Tabs.tsx, src/screens/Ticketing/Tickets/TicketsScrollView.tsx
Legger til en `showMobileTokenInfo` parameter på `TicketsScrollView`, så vises info om token kun i fanen for aktive billetter.
=> fix: hide TravelTokenBox on expired tickets screen

src/screens/Assistant_v2/ResultItem.tsx
Fiks av aligment av klokkeslett i resultFooter, slik at det henger sammen med holdeplass-teksten, men det er holdeplass-teksten som blir forkortet hvis der ikke er nok plass.
=> fix: alignment of start time in resultItemFooter

src/screens/Profile/TravelToken/SelectTravelTokenScreen.tsx
Ref. [slack](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646662437063149)
Fiks av at padding ble lagt som `style` på et scrollview istedet for `contentContainerStyle`.
=> fix: use contentContainerStyle in SelectTravelToken ScrollView

src/components/message-box/index.tsx, src/components/text/markdown-renderer.tsx, src/screens/Profile/DesignSystem.tsx
- Space under title
- bold tekst funker ikke på android hvis man bruke fontWeight direkte. endret til å bruke type="body__primary--bold"
- Støtte for quotes: '' og "" i markup
=> fix: header spaceing + android fix

fastlane/Fastfile
Ser at bygget feiler pga. en syntaksfeil i Fastfile. Legger til en manglende parantes.
f.eks. https://github.com/AtB-AS/mittatb-app/runs/5478910974?check_suite_focus=true
=> fix: add missing `)` to Fastfile

src/screens/Ticketing/Ticket/TicketInfo.tsx
Oppdatert InspectionSymbol til å alltid ha mørkt innhold for periodebilletter der bakgrunnen er grønn, for å opprettholde kontrast mellom ikon og innhold.
=> fix: use dark content on period ticket inspection symbol

scripts/ios/upload-sourcemaps.sh
Oppdaterer upload-sourcemaps.sh til å bruke upload-source-maps pakken for iOS, på samme måte som det ble gjort for android i #2215. For at scriptene skal fungerer på samme måte, og ikke som et api-kall.
=> build: upload ios source maps with bugsnag-source-maps cli

.github/workflows/build-staging-ios.yml, scripts/ios/upload-sourcemaps.sh
Ble ikke riktig å ha med `--project-root='pwd'` i oppdatert upload-sourcemaps, så fjerner denne her. 
Denne gangen fikk jeg testet det skikkelig også, i bygg https://github.com/AtB-AS/mittatb-app/runs/5552376900?check_suite_focus=true
=> build: fix upload of source maps

src/screens/Profile/TravelToken/index.tsx, src/translations/components/TravelTokenBox.ts, src/translations/screens/Profile.ts, src/translations/screens/subscreens/Information.ts, src/translations/screens/subscreens/Login.ts, src/translations/screens/subscreens/TravelToken.ts, src/travel-token-box/index.tsx
- missing english translations
- FAQ
- token toggle texts and translations
- use "phone", not "mobile" in english translations
=> fix: update language and translations

src/components/feedback/SubmittedComponent.tsx, src/components/feedback/index.tsx, src/translations/screens/Feedback.ts
This feature makes it possible to submit additonal feedback through Intercom, and receive an answer, after giving feedback in our generic feedback component. 
The feedback given in the component is submitted as an Intercom-event to make the chat operators job easier, along with the Firebase documentID, so that additional info such as TripPatterns or QuayListData submitted from the generic component can be examined when needed.
=> feat: additional feedback through Intercom after using generic feedback component

.github/workflows/build-staging-android.yml, .github/workflows/build-staging-ios.yml
Registrert feil med feil versjon på APK som sendes til AppCenter (https://mittatb.slack.com/archives/C02EEG7D8EL/p1647422820463809). Det gjør at det blir feil versjon sendt videre og registrering av app til Entur får feil versjon. Konsekvens er at Android staging er på feil versjon og fungerer ikke.
Hypotesen er at det er cache-mekanismen som slår til her. Ser du på byggingen til [bump av 1.17](https://github.com/AtB-AS/mittatb-app/runs/5509338055?check_suite_focus=true) så slår cachen fremdeles til. På iOS fungerer dette for `ios/`-mappen endres med plists som har fått endret versjon. Men for Android er det kun en referanse til miljøvariabel via gradle, så de endrer seg ikke, og får hit på cachen.
Dette vil ikke skje på samme måte i store build, for der er det ikke apk/ipa cache. …
=> fix: include env file hash to cache key in build steps

src/screens/Assistant/Assistant.tsx, src/screens/Assistant/use-trips-query.ts, src/utils/location.ts
Implementert at reisesøk blir avbrutt hvis det er samme, eller to nære stopp (innenfor 200m). Dette er implementert litt annerledes enn for reisesøk v1, fordi OTP2 faktisk gir en del forslag selv om det er fra og til samme sted. Nå avbrytes søket hvis det er for kort avstand, istedet for å reagere på at resultatet er tomt. 
https://user-images.githubusercontent.com/1774972/158805983-85c5adc8-900e-4fc6-a875-ea0791bb84bc.mp4
closes #1993
=> fix: cancel trip search for very short distances

src/components/disappearing-header/index.tsx, src/components/disappearing-header/simple.tsx, src/screens/Assistant/Assistant.tsx
Uten at jeg skal gå for hardt ut her, men nå tror jeg de problemene med mystisk space på iOS for enkelte reisesøk er borte. Det var uforutsigbar oppførsel hvor det noen ganger ble feil og andre ganger ikke. Av en grunn så oppstod det i langt større grad på Reisesøk v2 enn v1.
Feilen ser ut til å være ganske banal og irriterende. Det skjer en automatisk endring av insets kompansert i iOS i bakkant basert på toolbar og tabbar. Som gjorde at den ble varierende høyde i enkelte tilfeller. Men vi styrer insets manuelt og det ble derfor trekt fra/lagt til alt ettersom i ulike tilfeller.
Her deaktiverer vi automatisk justering av insets og med det håper jeg å kunne sette punktum på et problem fra november 2020.
Dette gjør og i mer eller mindre grad at headerMargin ikke trengs (som trolig var et …
=> fix: gap in disappearing header for some cases on iOS. fixes #2077

src/screens/Assistant/Assistant.tsx, src/screens/Assistant/ResultItem.tsx, src/screens/Assistant/Results.tsx
Deaktivert gjennomstreking når searchTime.option er 'now'. Ref. https://github.com/AtB-AS/mittatb-app/issues/2194#issuecomment-1075187479. 
fixes #2194
=> fix: disable strike through when searching for trips 'now'

src/screens/Assistant/Assistant.tsx, src/translations/screens/Assistant.ts
Forslag på løsning for buggy spinner ved lasting av reiseforslag. Denne implementasjonen lener seg mer på native refresh implementasjon, men bruker fortsatt custom melding ved lasting av "flere" resultat. ~Litt rar oppførsel på Andorid med spinner når man laster flere, så vurderer å legge inn en sjekk på OS-type, og heller løse det forskjellig mellom plattformene.~
Tar gjerne tilbakemeldinger på hvordan det kan se ut og oppføre seg. Mer info om bakgrunn i linket issue #1997.
https://user-images.githubusercontent.com/1774972/160110400-9488cfe0-d9a8-48cc-9663-ce2ee66f75be.mov
=> feat: use native spinner when loading tripPatterns

src/components/feedback/SubmittedComponent.tsx, src/translations/screens/Feedback.ts
Berører hovedsakelig OOS-aktører som ikke har Intercom aktivert. Da håndteres muligheten for å gi ekstra feedback på samme måte som kundeservice, altså at en valgfri link åpnes i ekstern nettleser.
NFK:
AtB:
=> feat: Åpne kontaktskjema i stedet for Intercom når Intercom er deaktivert

src/components/disappearing-header/index.tsx
Oppdaterer spinner tint på iOS, siden den ikke var særlig synlig i light mode.
Tenkte det var greit å ta i samme runde som #1997, men ikke egentlig relatert.
https://user-images.githubusercontent.com/1774972/160566534-07ad46eb-d548-44d6-907f-55d70debc064.mp4
=> fix: use text color tint for disappearing header spinner

src/screens/Assistant/Assistant.tsx
Det ble oppdaget en feil med skjermleser hvor man fikk opp "Vi fant dessverre ingen reiseruter som passer til ditt søk." uten at man hadde gjort et søk. Fikser det ved å skjule hele `Results` når det ikke har blitt gjort noe søk.
=> fix: hide results from screen reader when search is empty

src/screens/Assistant/ResultItem.tsx, src/translations/screens/Assistant.ts
Legger til UU beskrivelse av reiseforslag som er tilbake i tid.
Vet ikke om "Passert reise" / "Passed trip" er beste måten å beskrive forslagene på, så åpen for forslag på språk.
closes #2194
=> fix: a11y for passed trips

src/api/departures/stops-nearest.ts, src/api/types/generated/StopsDetailsQuery.ts, src/screens/Departures/NearbyPlaces.tsx, src/screens/Departures/PlaceScreen.tsx, src/screens/Departures/state/stop-place-details-state.ts
Legger til funksjonalitet for autonavigering når man søker eller velger en favoritt som er en holdeplass, ikke adresse. Dette krever nytt endepunkt i BFF (https://github.com/AtB-AS/atb-bff/pull/132) siden når man navigerer til et stopp, har listen med nærmeste holdeplasser ikke nødvendigvis lastet allerede, slik at man må hente holdeplass-detaljer etter navigasjon. 
Noen detaljer som er verdt å påpeke:
- Når man velger en holdeplass fra søk eller favoritt som er del av et multimodal stopp, er det "barn-nodene" som blir vist, mens holdeplasser som dukker opp i listen "i nærheten" er multimodale.
- F.eks. om man har busstasjonen ved Trondheim S som favoritt, får man ikke se tog-plattformene etter autonavigering. Holdeplasser "i nærheten" er multimodale, slik at man ser både buss og tog fra …
=> feat: automatically navigate to stop places in depatures

e2e/tests/travelsearch.e2e.ts, e2e/utils/commonHelpers.ts, e2e/utils/expectHelpers.ts, e2e/utils/interactionHelpers.ts, e2e/utils/myprofile.ts, src/location-search/LocationSearch.tsx
The e2e-tests fails due to the keyboard popping up when giving a search input. This was not foreseen on the local simulation as the keyboard was toggled off. Here, a testID is added to be able to scroll among the recent locations and journeys.
=> test: fix-failed-e2e-tests

src/screens/Departures/NearbyPlaces.tsx
Fixes incorrect sorting when distance to stop place is exactly 0.
fixes #2524
=> fix: incorrect sorting of stop places when distance is 0

e2e/tests/departuresV2.e2e.ts
The tests have failed after a search for a bus stop in departures v2 automatically sends the user to the departures view without having to choose the platform. This should fix that. Also included a test for searching after
- a bus stop that automatically leads to the departure view
- a place that necessitates the user to choose a bus top nearby
=> test: fix on e2e departure v2 tests

src/components/feedback/GoodOrBadButton.tsx, src/components/feedback/RenderQuestions.tsx
Utbedrer kommentar nevnt i #2345. Blir ikke helt klok på hva som er ideell måte å gjøre ting på, for å tekkes både Android og iOS, men nå skal i hvert "bra" eller "dårlig" bli lest opp på Android også, i tillegg til alternativtekstene.
=> fix: Announce feedback alternatives on Android

src/screens/Ticketing/Ticket/TicketInfo.tsx
Fiks av issue fra QA 1.18 https://mittatb.slack.com/archives/C0116FMPX4Y/p1651142612065779?thread_ts=1651142412.623509&cid=C0116FMPX4Y
=> fix: use text color as fill of TicketInspectionSymbol

src/screens/Ticketing/Ticket/Carnet/CarnetFooter.tsx
Det ble feil farge på brukte og aktive klipp i klippekort i appen etter oppdateringen av design system, oppdatert til å bruke background_0 nå.
=> refactor: fix carnet dot colors

src/screens/Ticketing/Tickets/RecentTickets/RecentTicketComponent.tsx, src/translations/screens/subscreens/RecentTicketsTexts.ts
Her var ordet kategorier manglende, pluss at teksten er gjort til tertiary. Har ikke satt farge eksplisitt, men det skal vel ikke være nødvendig. Har også redusert litt på avstanden vertikalt, siden den virket litt stor i forhold til skissene.
Fikser også denne om antall kategorier for skjermleser: https://mittatb.slack.com/archives/C0116FMPX4Y/p1651225167558959
=> refactor: make recent ticket "other categories" text match Figma

.github/workflows/build-staging-ios.yml
Invalidates IPA cache when assets change. This will cause new images to be included in the bundle. Will invalidate the cache when assets change (changes in generated assets and other assets).
This is not an issue in store as it is not cached.
=> ci: invalidate ipa build cache when assets changes to include new images

src/screens/TripDetails/DepartureDetails/index.tsx, src/screens/TripDetails/components/TripMessages.tsx
Denne PR baserer seg på bruk av `enable-ticketing` flagget i RemoteConfig. 
Det vil si at dersom `enable-ticketing` er satt til `false` vil ikke advarsler knyttet til billettkjøp vises, og i praksis vil irrelevante AtB-varsler ikke vises i Reis-appen. 
Med andre ord må dette håndteres på nytt når NFK en dag lanserer billettering, hvis info om samarbeidsbilletten fremdeles er aktuelt.
=> feat: require enable_ticketing to show ticket warnings

src/translations/screens/TicketSplash.ts, src/translations/screens/subscreens/TripDetails.ts
Denne PR løser #2604 og gjør to ting:
- Viser "X intermediate stops" i stedet for "X intermediate stop" på engelsk, hvis flere enn ett stopp
- Endrer til organize i stedet for organise på Nordland sin ticket-splash
For øvrig er jeg litt usikker på hvorvidt denne bør merges til `release/1.18` eller `master`, men det blir i hvert fall merge conflicts om jeg velger master.
=> fix: replace stop with stops if several intermediate stops

src/screens/Ticketing/Purchase/Overview/components/Zones.tsx, src/screens/Ticketing/Purchase/Overview/index.tsx, src/translations/screens/subscreens/PurchaseOverview.ts
After implementing the Summary-component i saw some small changes that
could be done to make the implementations more aligned.
- Renamed to 'Zones'. Follow the pattern with components named with
CamelCase. Also not necessary with suffix "Item" or "Component" since
it is inside a components-folder.
- Moved specifying the top margin from inside the component to the
overview screen. Components should generally not handle margins around
the component, this should be handled where the component is used.
- Added "accessible: true" on the section. Without this the
"accessibilityRole: 'button'" was not working as intended, atleast on
iOS.
=> refactor: Some fixes to the zones component

src/screens/Ticketing/Purchase/Overview/components/DurationSelection.tsx
Fix of android talkback accessibility label in the DurationSelection component (ref https://github.com/AtB-AS/mittatb-app/issues/2457#issuecomment-1118488504)
=> refactor: fix a11y label on android

src/screens/Ticketing/Purchase/Overview/index.tsx
I forgot to add logic to hide the StartTimeSelection component from the single ticket purchase view in #2626. This PR fixes that.
=> refactor: hide StartTimeSelection for single tickets

src/assets/information-data/ticketInspectionInformation.json, src/translations/screens/subscreens/Information.ts
The Norwegian version states that minors over 15 will be fined. In English its mentioned minors under 15 are fined. The Norwegian version is correct, hence fixed the english version.
=> refactor: fix translation in english

package.json, src/navigation/TabNavigator.tsx, yarn.lock
Fixes invisible active tab in NFK-app in combination with design-system PR: https://github.com/AtB-AS/design-system/pull/41
With the changes in the design system from here: https://github.com/AtB-AS/design-system/pull/41 the app looks like this:
=> fix: replace activeTintColor in TabNavigator

src/components/radio-segments/index.tsx, src/screens/Ticketing/Purchase/Overview/components/StartTimeSelection.tsx, src/utils/date.ts
Fix of UU feedback from #2459, about misleading screen reader texts in the StartTimeSelection component. When the "Later" button is selected, the accessibilityLabel is now e.g. "Later, 14 may at 13:37" for dates that are not today, and "Later, 13:37" for dates that are today.
- Updates `formatToVerboseDateTime()` to omit date when the date is "today". The function is only used in `DateNavigator` in Departures 2.0, but just for dates that are not "today", so it should be unaffected by this change.
- Added `accessibilityLabel` param to the RadioSegment component.
=> refactor: fix StartTimeSelection a11y issues

src/screens/Ticketing/Splash/Info.tsx, src/translations/screens/Onboarding.ts, src/translations/screens/TicketSplash.ts
Updated styling and text for NFK splashes, solves #2671 
For the introduction splash, we have now updated the text to be in line with current features of the app. 
For the ticketing splash, all text is now left adjusted, and the heading is now jumbo_bold in line with the intro splash and the AtB splash for activating ticketing that may be used when ticketing is released at NFK. The paragraph text has also been updated.
<details>
<summary>Screenshots for the intro</summary>
</details>
<details>
<summary>Screenshots ticketing</summary>
<details>
=> refactor: revamp NFK splashes

e2e/tests/tickets.e2e.ts, e2e/tests/travelsearch.e2e.ts, e2e/utils/tickets.ts, src/screens/Ticketing/Purchase/Overview/components/Summary.tsx
There are som failing e2e test scenarios on GH Actions:
- travelsearch: should list recent locations
- the elements for tapping is hiding behind the keyboard. Solved by resetting the search history.
- ticketing: should get an offer for a single ticket
- add the missing test-ID offerTotalPriceText
- ticketing: should be able to change travellers
- add the missing test-ID offerTotalPriceText
- ticketing: should be able to change zone
- tapping a zone removes the keyboard, so another tap is in order to actually tap the chosen zone
=> test: e2e tests fixes

__tests__/utils-test.ts, src/screens/TripDetails/components/utils.ts
Date-fns show warnings that it will now longer support dates in string type.
updatet isShortWaitTime to parse any strings and updated tests with a "weird" case.
=> refactor: future proof date-fns and shortWaitTime

src/screens/Profile/DesignSystem.tsx
Legger til swatches i design systemet, med alle `staticColors`.
Klarte ikke helt å unngå å duplisere kode her, fordi jeg ikke klarer å generalisere linjen 
```
theme.static.transport[color as StaticColorByType<'transport'>];
```
uten å hardkode `transport`.
=> feat: add staticColor swatches to design system

src/components/sections/counter-input.tsx
Seems like accessible={false} is not enough for our case to work in android, so I have added an android specific flag which marks the element not important for accessibility and hence it would be ignored.
https://github.com/AtB-AS/kundevendt/issues/130
=> add android specific-property-to-make-irrelevant-info-inaccessible

src/screens/Departures/components/EstimatedCallItem.tsx, src/screens/Departures/components/QuaySection.tsx
As of now we have two accessible elements which give two different kind of information, while only one of them is important. Getting rid of redundant one and moving the informative message to outer accessible element.
=> fix: remove redundant accessible element for better usability

src/translations/components/ServiceDisruptions.ts
Avoids showing atb.no references in NFK app.
=> refactor: replace NFK traffic situation url

e2e/tests/myprofile.e2e.ts, src/assets/information-data/paymentInformation.json, src/translations/screens/Onboarding.ts, src/translations/screens/Profile.ts, src/translations/screens/subscreens/Information.ts, src/translations/screens/subscreens/Login.ts
Ref. [discussion on slack](https://mittatb.slack.com/archives/C036F9Q15R8/p1654066778806459) on updating translations for "sign in" to "log in".
=> refactor: update language to use "log in" over "sign in"

src/reference-data/defaults/preassigned-fare-products.json, src/reference-data/types.ts, src/screens/Ticketing/Purchase/Overview/components/TravellerSelection.tsx, src/screens/Ticketing/Purchase/Overview/components/Zones.tsx, src/screens/Ticketing/Purchase/Overview/index.tsx, src/screens/Ticketing/Purchase/TariffZones/index.tsx, src/screens/Ticketing/Purchase/utils.ts, src/screens/Ticketing/Tickets/AvailableTickets/AvailableTickets.tsx, src/screens/Ticketing/Tickets/Tabs.tsx, src/translations/screens/Tickets.ts, src/translations/screens/subscreens/PurchaseConfirmation.ts, src/translations/screens/subscreens/PurchaseOverview.ts, src/translations/screens/subscreens/TariffZones.ts
1. It has been decided that user should be able to buy 24h ticket anonymously unlike other periodic tickets. 
2. This PR also requires changes in Fire store to update preassignedFareProducts_v2.
- change ticket type of 24 hour ticker to 'hour24' from 'period'
- add isApplicableOnSingleZoneOnly as true for 24h ticket
- remove Student as a valid user for the same
The changes have been done in  firestore config in staging but should be done in PROD file while moving this change to production. 
Github issue: https://github.com/AtB-AS/kundevendt/issues/56
=> feat: extract 24 h ticket out of periodic ticket 2

src/screens/Ticketing/Tickets/RecentTickets/RecentTickets.tsx
Now when we have added 24 hour ticket as a new ticket type, it got missed from recent purchases. So have added it here.
=> fix: add 24 hour ticket in recent purchase

tools/release/changelog.config.js
Skips nfk-only releases when finding latest releasetag, so that all changes are included in the changelog of next common release.
=> build: Avoid changelog error after org-specific releases

src/screens/Profile/Home/index.tsx
Adds icons as explained in https://github.com/AtB-AS/kundevendt/issues/67.
New icons for:
- Signing out
- Deleting search history
=> feat: Add explicit icons to profile links

src/screens/Profile/Home/index.tsx, src/screens/Profile/Home/utils.ts, src/translations/screens/Profile.ts
Solves https://github.com/AtB-AS/kundevendt/issues/1756 and refactors https://github.com/AtB-AS/mittatb-app/pull/2754
Destructive alerts are now split into a title and a message. The message is optional, title is currently required.
With title:
Without title (same as before):
=> refactor: split title and message in destructive alerts

package.json
We have now increased the size of label__uppercase to 10 from 8. This has been done as part of https://github.com/AtB-AS/kundevendt/issues/1666. 
Please find one such example below!
Before: 
After:
=> bump theme package to reflect bigger fonts for label uppercase

.github/workflows/build-staging-android.yml, .github/workflows/build-staging-ios.yml, .gitignore, package.json
Done in the same way that is advised locally. This is just temporary until Entur hosts the libraries, and we can't do a production release with this method as of now as the native code is not obfuscated.
=> chore: Use yalc during staing build

.github/workflows/lint.yml, .github/workflows/tsc.yml
Not optimal, as it makes the tsc/lint actions slower. However, just for
a short time.
=> chore: Yalc mobiletoken-sdk during tsc/lint

ios/atb.xcodeproj/project.pbxproj
It will fix an issue with devices that don't support this feature. Despite the code handling, this seems like including the framework and making it optional will not break the app.
=> Update project.pbxproj to include CoreNFC.framework as optional

src/screens/Ticketing/Ticket/TicketInfo.tsx, src/translations/screens/Ticket.ts
Solves: https://github.com/AtB-AS/kundevendt/issues/220
Scenarios covered:
Case 1: Info on the ticket itself about errors (internet lack ex.)
Case 2: Info on the ticket itself if not token
Case 3: Info on the ticket itself when tokens are missing
Case 4: Info that the t: card is used as a travel document inside the ticket itself
Case 5: Info about mobile token is used as a travel document inside the ticket itself
Eg Case 5:
=> feat: show specific warning messages if the relevant token is not the one in hand

src/screens/Ticketing/Ticket/TicketInfo.tsx, src/translations/screens/Ticket.ts
Found minor bug while verifying https://github.com/AtB-AS/kundevendt/issues/220.
=> fallback to unnamed device when device name could not be fetched

src/screens/Ticketing/Purchase/Confirmation/index.tsx, src/screens/Ticketing/Purchase/Payment/CreditCard/index.tsx, src/screens/Ticketing/Purchase/Payment/CreditCard/use-terminal-state.ts, src/screens/Ticketing/Purchase/Payment/SelectPaymentMethod/index.tsx, src/screens/Ticketing/Purchase/saved-payment-utils.ts, src/screens/Ticketing/Purchase/types.ts
Should fix https://github.com/AtB-AS/kundevendt/issues/108
Could be worth looking at the error handling, a bit unsure about that part. Maybe you remember what we were planning there, @mikaelbr?
A bit unsure about how this actually worked before, but we are now migrating from listening to the `onLoadEnd` event in the WebView, and instead listening to the `onNavigationStateChange` events. This is because the `onLoadEnd` event never fired, because the WebView itself seemed to be navigated away from and interrupted before the event.
Additionally, we previously saved all recurring payment data at Entur just after purchase, and fetched it back immediately, which probably hasn't been working for some time. We are now only saving the payment data at Entur during the purchase, and fetching it back …
=> fix: recover saving of Nets-based payment methods

src/mobile-token/MobileTokenContext.tsx
Retrieving token has possible side effects like renewing,
activation, etc. This should not be done on the old token if there has
been any user change.
=> refactor: Check mobile token user change before retrieving token

src/screens/MobileTokenOnboarding/InspectableTokenScreen.tsx
**Needs to be included in v1.22**
As of now we have same label for both the cases which is not relevant to both of them. 
Please ignore the error in place of relevant token details, its the buttons that have been fiexed.
<div><img width="200" alt="image" src="https://user-images.githubusercontent.com/29625161/178930859-f6fce5d0-3b72-40c4-bd68-0338909cfa0a.jpg">
</div>
=> fix: add correct label on buttons

src/screens/Ticketing/Tickets/index.tsx
Solves: https://github.com/AtB-AS/kundevendt/issues/2017
**Needs to be included in v1.22**
For now I have simply commented it with a relevant comment to enable again
=> feat: disable ticket onboarding component temporarily

src/components/location-icon/index.tsx, src/location-search/LocationResults.tsx, src/location-search/utils.ts, src/translations/screens/subscreens/LocationSearch.ts
Solves https://github.com/AtB-AS/kundevendt/issues/111
Please find some examples of how the accessibility labels would sound like :
- Tram stop Skansen, Trondheim. Activate to use this location.
- Bus stop Skansen, Trondheim. Activate to use this location.
- Airport Trondheim lufthavan, Størdal. Activate to use this location.
- Location Skansen, Trondheim. Activate to use this location. (This would be used when the resulted location is not a specific stop but just a location)
=> feat: use different accessibility labels for different stop icons

src/screens/Assistant/Assistant.tsx
Solves https://github.com/AtB-AS/kundevendt/issues/1944
The messages are already in place but were not being rendered. So just had to modify a condition to get them back. 
<div>
</div>
=> feat: render results and hence error messages even when the to and from locations combo is not valid

src/screens/Departures/components/QuaySection.tsx, src/screens/Departures/state/stop-place-state.ts
Solves https://github.com/AtB-AS/kundevendt/issues/2065 
We load more departures than displayed and show from backup in case one or more departures have passed.
=> feat: fetch more departures that shown in screen to show when one or more trips have passed

src/components/disappearing-header/simple.tsx, src/screens/Departures/AllStopsOverview.tsx, src/screens/Departures/FavouriteStopsOverview.tsx, src/screens/Departures/NearbyPlacesScreen.tsx, src/screens/Departures/PlaceScreen.tsx, src/screens/Departures/QuayView.tsx, src/screens/Departures/StopPlaceView.tsx, src/screens/Departures/components/DateNavigator.tsx, src/screens/Departures/components/StopPlaces.tsx, src/screens/Departures/index.tsx, src/screens/Departures/utils.ts, src/translations/screens/Departures.ts
Closes https://github.com/AtB-AS/kundevendt/issues/151
Every stop that has one or more lines marked as Favourite, should appear in the favorites tab. 
<div>
</div>
=> feat: add separate tab for favourite tabs

src/screens/Departures/QuayView.tsx, src/screens/Departures/StopPlaceView.tsx, src/screens/Departures/components/QuaySection.tsx, src/translations/screens/Departures.ts
https://github.com/AtB-AS/kundevendt/issues/150
- Adds a message to departures that suggest toggling favorites off when there are no results.
- Minimizes quays instead of hiding them when favorites are toggled.
https://user-images.githubusercontent.com/1774972/184355562-0fd0508c-7ea4-4510-a321-75d148c85da4.mp4
=> fix: update behaviour on no favorite departures

src/api/departures/stops-nearest.ts, src/screens/Departures/state/quay-state.ts, src/screens/Departures/state/stop-place-state.ts
After https://github.com/AtB-AS/mittatb-app/pull/2838, the startTime value in departures would be undefined, which broke realtime. Updates to use default value, and always be defined.
Also updates some other potentially-undefined values in departure states, to prevent a similar issue appearing again.
=> fix: prevent queryInput from having undefined values

src/screens/Departures/FavouriteStopsOverview.tsx, src/screens/Departures/state/stop-place-details-state.ts
Even when requested location ids were empty we were sending a request to BFF, which in return gives a 400, but doesn't do anything with the existing state. This results in an incorrect state in favorites tab and probably elsewhere as well.
So, here we set the output to empty when the input is empty without even calling BFF.
=> fix: stop details should be updated to empty array when input is empty

src/global-messages/GlobalMessagesContext.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/2220
Filters globalMessages in app Firestore query (which means irrelevant globalMessages, such as for webshop, won't be fetched).
This also removes the possibility to enter a single context as a string, now context must be given as an array with strings.
=> refactor: Filter globalMessages to app before fetching

src/screens/Ticketing/Purchase/Payment/CreditCard/index.tsx, src/screens/Ticketing/Purchase/Payment/CreditCard/use-terminal-state.ts, src/translations/screens/subscreens/PaymentCreditCard.ts
Sca exemption flow was not working as the bankid authentication was "hidden" from
the user. The code was simplified some to fix this, and will now only have a
screen saying "loading", and not inspect redirect urls to find out the appropriate
loading screen text.
Fixes AtB-AS/kundevendt#2114
=> fix: Fix sca exemption flow

src/screens/Departures/FavouriteStopsOverview.tsx, src/screens/Departures/PlaceScreen.tsx
Follow up improvement to https://github.com/AtB-AS/kundevendt/issues/151
When navigating from the favorites tab, filtering on favorites are turned on by default.
https://user-images.githubusercontent.com/1774972/185370381-4de0309b-a3ea-45d3-8262-ebca2f954271.mp4
=> feat: favorites tab shows only favorites by default

Gemfile
Fixes issue from 777717e028efdcd66d1c0b7a88d180b74ef1164b. Connected to https://github.com/AtB-AS/kundevendt/issues/1776
Update Cocoapods to the latest version. Min. required is 1.10.2 but I don't know if there's a reason _not_ to use the latest as long as Fastlane and AppCenter support it.
=> ci: updates cocoapods to latest version (1.11.3)

.github/workflows/build-staging-ios.yml, .github/workflows/build-store-ios.yml
It handles "large" time-out times when building, something built can be slow due to a large number of dependencies or limited resources in the host machine, so is good to have these.
=> Workaround for higher time-out

src/screens/Ticketing/Ticket/Component/ZoneSymbol.tsx
Solves https://github.com/AtB-AS/kundevendt/issues/1755
Fixing this as part of upgrading the tickets view.
<div>
</div>
=> refactor: show zone symbol for 24 h as periodic tickets

src/global-messages/converters.ts
Noticed a weakness in the data validation of global messages, where if `type` or `active` is set to some value not in the Status-type, the invalid value would slip trough, eventually leading to the app crashing.
This would be an issue if a typo is made in firestore, or if we add more status types in the future. Since the bug is part of v1.23, it will stay an issue for users on that version of the app.
Also related to https://github.com/AtB-AS/kundevendt/issues/2190
=> fix: update validation of GlobalMessage data

src/screens/Ticketing/Purchase/Overview/components/Zones.tsx, src/screens/Ticketing/Purchase/TariffZones/index.tsx, src/translations/screens/subscreens/TariffZones.ts
Solves zone text as part of https://github.com/AtB-AS/kundevendt/issues/330
Before: 
<div>
</div>
After: 
<div>
</div>
=> fix: improve multiple zone text in valid and buy tickets

src/screens/Ticketing/Ticket/Details/DetailsContent.tsx, src/screens/Ticketing/Ticket/Details/DetailsScreen.tsx, src/translations/screens/subscreens/PurchaseOverview.ts
Fixes https://github.com/AtB-AS/kundevendt/issues/2247 
Updated information regarding trains and night buses for 24 hour pass. It was previously the same as for period tickets.  
Single tickets were not available in staging during the time of testing and I was therefore not able to verify that the information is still correct for other ticket types. 
<details>
Details screen for 24h pass before: 
Details screen for 24h pass after:
</details>
=> fix: display correct info regarding trains/night buses on 24 hour pass

src/components/sections/action-item.tsx, src/components/sections/counter-input.tsx
Refactor https://github.com/AtB-AS/kundevendt/issues/2217 
I have updated the spacing for the passenger categories component in buy tickets according to https://github.com/AtB-AS/kundevendt/issues/2217. 
<details>
**Before:**
**After:**
</details>
=> refactor: spacing on passenger category component

src/screens/Dashboard/DeparturesWidget.tsx, src/translations/screens/Departures.ts
Closing https://github.com/AtB-AS/kundevendt/issues/2350 (at least the button)
Info about no favourites in separate PR.
=> feat: add button to select frontpage favourites

src/screens/Ticketing/Purchase/Overview/index.tsx, src/screens/Ticketing/Ticket/Details/DetailsScreen.tsx, src/screens/Ticketing/utils.ts
Fixes https://github.com/AtB-AS/kundevendt/issues/2247. 
Added missing information regarding train/night buses to the purchase view for 24 hour pass. 
I also extracted the function getTrainTicketNoticeText in a seperate utils file as the same check is done for multiple views (ticket details and purchase view).
=> fix: add correct information regarding train/night buses for 24 hour pass

src/api/departures/types.ts, src/departure-list/section-items/line.tsx, src/departure-list/section-items/quay-section.tsx, src/favorites/FavoritesContext.tsx, src/remote-config.ts, src/screens/Assistant/SelectFavouritesBottomSheet.tsx, src/screens/Dashboard/DeparturesWidget.tsx, src/translations/screens/Departures.ts
Closing https://github.com/AtB-AS/kundevendt/issues/2350 
Fixes:
- Widget departure list is now populated based on the [list of frontpage favourites, not the list of the usual favourites](https://mittatb.slack.com/archives/C0116FMPX4Y/p1662029593492219?thread_ts=1662018942.356549&cid=C0116FMPX4Y).
- [Wrong color textbox for no favourites in bottomsheet](https://mittatb.slack.com/archives/C0116FMPX4Y/p1662018985293819)
- [Only Norwegian text for "Close" button in bottomsheet](https://mittatb.slack.com/archives/C0116FMPX4Y/p1662020632484449?thread_ts=1662018985.293819&cid=C0116FMPX4Y)
- [Hide stars from QuaySections in frontpage](https://mittatb.slack.com/archives/C0116FMPX4Y/p1662032715985089?thread_ts=1662018942.356549&cid=C0116FMPX4Y)
- Added widget box explaining that the widget only …
=> fix: merge selecting and displaying frontpage favourites

src/screens/Assistant/SelectFavouritesBottomSheet.tsx
Is now "Lukk" or "Close" instead of "Avbryt" or "Cancel":
=> fix: close instead of cancel in frontpage favs bottomsheet

src/components/message-box/index.tsx, src/global-messages/GlobalMessage.tsx, src/global-messages/GlobalMessagesContext.tsx, src/global-messages/converters.ts, src/global-messages/storage.ts, src/screens/Profile/DebugInfo/index.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/1997
<div> 
</div>
<div> 
</div>
=> feat: make global messages dissmisable

src/screens/Dashboard/Dashboard.tsx
Fixing issue with missing GlobalMessages in the new dashboard as stated here: https://github.com/AtB-AS/kundevendt/issues/1876#issuecomment-1229844347
<details>
<summary>Screenshot with multiple messages</summary>
</details>
=> fix: add globalMessagesBox to dashboard

src/screens/Departures/state/stop-place-state.ts
Closes: https://github.com/AtB-AS/kundevendt/issues/2366
A short explanation of the changes:
Due to many `hooks` being called for filtering favourites, time pickers, and more.. was producing multiple calls to the server end-point at the same time with the `useEffect`, to avoid this the `state` value from  `ReducerWithSideEffects` is compared while `isLoading` (Requesting data) otherwise then proceed to load the data.
=> refactor: Duplicate requests for departure v2

.github/workflows/test-e2e-ios.yml
The GH Action still picks up the SDK from the temp location. Try with *false* as value for the *use-build-cache* field
=> test: not use cache on first run

ios/atb/AtB.entitlements, ios/atb/Info.plist
Closes: https://github.com/AtB-AS/kundevendt/issues/1983
We have noticed that for the newest version of iOS `15.6.1` there is an issue where asking for the status of the NFC is failing due to an exception: `NFCHardwareManager areFeaturesSupported:outError`. The issue comes random on some devices, but what I have noticed is that the call from swift calls an Objective-C implementation that returns nil when the issue happens and interprets on swift as a false in the condition, causing the exception but not broking the app, in such cases, the condition returns false as no NFC supported.
The proposed solution adds an extra feature use of (NFC) hardware status, preventing the issue arise.
=> fix: Issue when NFC is not available

src/departure-list/section-items/quay-section.tsx, src/screens/Assistant/SelectFavouritesBottomSheet.tsx, src/translations/screens/Departures.ts, src/translations/screens/subscreens/SelectFavouriteDeparturesTexts.ts
Additions:
- Displaying public code in frontpage favourite bottomsheet
- Hiding "Load more departures" button from `LineSection` in frontpage
- Displaying correct texts from marketing in no favourites box
- Improved accessabilityLabel and actions for selecting favourites from bottomsheet
Still missing (and will be handled in a later PR):
- Removal of mysterious shadow below LineSection
- Facilitate both English and Norwegian urls, a general issue that will be resolved with Firestore-config
=> fix: frontpage favourites minor improvements

src/favorites/FavoritesContext.tsx, src/screens/Assistant/SelectFavouritesBottomSheet.tsx, src/screens/Dashboard/DeparturesWidget.tsx, src/screens/Dashboard/state.ts
- Removes unused `location` param for dashboard favorites state
- Save favorites to storage only on "Save selection", not on close/cancel
- Adds ActivityIndicator when favorites are loading
- Handles the case where there are no selected dashboard favorites
=> refactor: fix various dashboard favorites bugs

Gemfile, Gemfile.lock
Sets correct versions of gem, ruby and bundler. Fixes borked builds (example of fix: https://github.com/AtB-AS/mittatb-app/actions/runs/3080712866/jobs/4978387060)
=> chore: set proper ruby/bundler versions

fastlane/Fastfile, scripts/android/upload-sourcemaps.sh
The path for source maps in Hermes has changed for Android builds.
Related to: https://github.com/AtB-AS/mittatb-app/pull/2880
Verified fix here: https://github.com/AtB-AS/mittatb-app/actions/runs/3081458452/jobs/4980030720
=> ci: fix sourcemap path for hermes

src/departure-list/section-items/line.tsx, src/screens/Departures/PlaceScreen.tsx, src/screens/TripDetails/DepartureDetails/index.tsx, src/screens/TripDetails/Details/index.tsx, src/screens/TripDetails/components/TripSection.tsx, src/translations/screens/subscreens/DepartureDetails.ts
Fixes comment https://github.com/AtB-AS/kundevendt/issues/2448#issuecomment-1250718276
This PR fixes a crash that happens when navigating to DepartureDetails with activeItemIndex being undefined. (_The actual issue was that even though the default was specified as `0` in the code, it became `1` in practice. I still don't understand why this is 🙃_)
- `activeItemIndex` is now set as a required parameter to fix the bug.
- Uses of DepartureDetails are now also implemented with stack navigation, with `push` instead of `navigate`. This will be visible to the user as navigating further and further down the stack, instead of being thrown "back" to the previous screen when opening DepartureDetails. This also makes error handling easier.
- Added an error message "Oops! We had some issues loading …
=> fix: update DepartureDetails navigation

src/screens/Ticketing/Purchase/Confirmation/index.tsx
ref https://mittatb.slack.com/archives/C02EEG7D8EL/p1663767182403119?thread_ts=1663759032.715949&cid=C02EEG7D8EL
Still building the app locally to test this, but looking at the other code this should fix our decimal issue.
=> fix: format totalPrice in purchase confirmation

src/screens/Ticketing/Purchase/Confirmation/index.tsx
Follow up to https://github.com/AtB-AS/mittatb-app/pull/2964
- Noticed the offer prices when purchasing for more than one traveler type also had the decimal issue from QA, [ref. slack](https://mittatb.slack.com/archives/C02EEG7D8EL/p1663767182403119?thread_ts=1663759032.715949&cid=C02EEG7D8EL)
- Price would sometimes be rounded the wrong way, without the `2` as set param to `formatDecimalNumber`
=> fix: format offer prices in purchase confirmation

android/app/src/main/AndroidManifest.xml
This should fix linking to app not working on Android phones after dependency upgrades.
Fixes https://github.com/AtB-AS/kundevendt/issues/2228
=> refactor: Add app scheme to AndroidManifest

tools/release/changelog.config.js
This reverts commit 21ebd2c1bce703abe640ed2e69814a0070ec5154.
Running `yarn release-draft` has been failing since this change, so changing it back here. The change would generate change logs based on the previous org-specific release, instead of the previous release in general. Since we're changing it back, we need to do some manual work if we're not synchronizing our releases, but since that's the plan, this is a less important feature.
=> revert: "build: Avoid changelog error after org-... (#2742)"

src/screens/Dashboard/state.ts
Updates dashboard favorites to use JP3 endopoint `bff/v2/departures/realtime` instead of `bff/v1/departures-realtime`.
~Unsure whether to merge to master or release branch for this one. @tormoseng Do we have time to re-test?~
=> refactor: use jp3 for realtime data on dashboard favorites

.github/workflows/build-staging-android.yml, .github/workflows/build-store-android.yml
Ubuntu deprecated brew from PATH (as seen in top link here: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md).
This re-adds it to the path for the two android builds (also fixes a build missing wrong env)
Running example: https://github.com/AtB-AS/mittatb-app/actions/runs/3130611534/jobs/5081043717
=> ci: fix missing brew on latest ubuntu agent

src/screens/Ticketing/Tickets/TicketReservation.tsx
Closes comments on https://github.com/AtB-AS/kundevendt/issues/2090
1. Made the view accessible so that screen reader takes all the three details together
2. Updated view to be in sync with the one in ticket details screen
Now:
Before:
=> refactor: improve screen reader and rejected ticket details UI

src/departure-list/utils.ts
Fixes a bug with incorrect sorting of realtime departures. This was done with the function 
```js
return a.expectedDepartureTime < b.expectedDepartureTime ? 0 : 1
```
which returns 0 if `a` is less than `b`, and 1 otherwise.
From the docs:
>`param sortFn()`: Function used to determine the order of the elements. It is expected to return a negative value if the first argument is less than the second argument, _zero if they're equal_, and a positive value otherwise. If omitted, the elements are sorted in ascending, ASCII character order.
Note **"zero if they're equal"**. 
The function would essentially return "equal" instead of "less than", when sorting departures, which surprisingly worked ok-ish for most phones. On some Android devices however, this resulted in "not at all sorted sorting", …
=> fix: sorting of realtime departures

src/components/map/Map.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/2374#issuecomment-1265410056
We were relying on **useEffect** hook inside **useSelectedFeatureChangeEffect** to fly to current location, however we realized that hook would not be called in all situations causing a bug where the user is not taken to the current position always.
Hence added flyToLocation always on button click, to avoid any bugs for this.
=> refactor: fly to current position always

src/components/rail-replacement-bus-message/index.tsx, src/screens/Assistant/ResultItem.tsx, src/screens/Dashboard/ResultItem.tsx, src/screens/TripDetails/components/TripMessages.tsx, src/screens/TripDetails/components/TripSection.tsx, src/translations/components/RailReplacementBusMessage.ts, src/translations/screens/Assistant.ts, src/translations/screens/subscreens/TripDetails.ts
Solves https://github.com/AtB-AS/kundevendt/issues/2566
This has not been designed by Christian (but he has agreed on trying it in production), so have a short look at the visual stuff as well :) 
**Features**
Show yellow warning icon indicating a situation in result list:
In trip overview, say that trip includes rail replacement bus. And also inform which leg is rail replacement bus:
=> feat: handle rail replacement bus services

src/screens/Departures/NearbyPlacesScreen.tsx
Closing https://github.com/AtB-AS/kundevendt/issues/2617
It seems that the label text colours were given by `interactive_1.default.text`, while the background colour were set using 
`background_accent_0.background`. Updated it now to using the same interactive colour, in line with my understanding of the AtB figma sketches. 
<details>
<summary>Screenshots - AtB</summary>
</details>
<details>
<summary>Screenshots - NFK</summary>
</details>
=> fix: correct tabselector background colour

src/components/page-indicator/index.tsx
Closing https://github.com/AtB-AS/kundevendt/issues/2620
Changes colours of onboarding progress dots to be in line with Figma sketches, solving strange colours for NFK. The inactive dots were hardcoded as #FFFFFF for AtB, they will now turn dark in dark mode.
<details>
<summary>Screenshots - AtB</summary>
</details>
<details>
<summary>Screenshots - NFK</summary>
</details>
=> fix: replace color values for onboarding dots

src/api/geocoder.ts, src/api/types/generated/TripsQuery.ts, src/screens/TripDetails/components/TripSection.tsx
When departures v2 is enabled, if we have access to the relevant stop place id, we do not need to make a bff call before we navigate. The ID is made accessible with an bff update: https://github.com/AtB-AS/atb-bff/pull/167/files
This fixes https://github.com/AtB-AS/kundevendt/issues/73 and https://github.com/AtB-AS/kundevendt/issues/481 when departures v2 is enabled, as shown in this screen recording:
https://user-images.githubusercontent.com/1774972/194310360-09b06012-6415-45d5-b912-ae57a396b377.mp4
I tried to summarize whats needed to solve the issue for depatures v1 [here](https://github.com/AtB-AS/kundevendt/issues/481#issuecomment-1269907024)
=> fix: use place id for navigating from TripDetails to PlaceScreen

src/remote-config.ts
Closing https://github.com/AtB-AS/kundevendt/issues/2655
by setting the default remote config value `new_favourites_info_url` to be an empty string. This is a falsy value which hides the link from the widget.
=> refactor: empty default new_favourites_info_url

src/screens/Dashboard/Dashboard.tsx, src/screens/Dashboard/TripSearch.tsx
fixes https://github.com/AtB-AS/kundevendt/issues/2576
This resets the travel search in dashboard at the same time as navigating to the trip search screen. This means we don't have to bother with reseting the search field when navigating back to the dashboard  (in cases like swiping back / android back button / double tapping the navbar).
=> fix: reset dashboard travel search when navigating

src/screens/Dashboard/Dashboard.tsx, src/screens/Dashboard/DeparturesWidget.tsx
The "departue favorites widget" has two names, `FavoritesWidget` for the component when exported, and `DeparturesWidget` for the file name. I suggest we use `DeparturesWidget` both places.
=> refactor: rename FavouritesWidget to DeparturesWidget

src/screens/Assistant/Assistant.tsx, src/screens/Dashboard/TripSearch.tsx
fixes https://github.com/AtB-AS/kundevendt/issues/2181
When search time "now" is selected, refreshing the Assistant (or TripSearch when front page is enabled) will also update the searchTime date.
=> fix: update searchTime on refresh of trip search

e2e/tests/tickets.e2e.ts
The e2e tests is lacking decimals on the ticket price in summary. This is added here.
=> test: add decimals on summary price

src/utils/use-app-state-status.ts, src/utils/use-is-screen-reader-enabled.ts
Found two hooks with deprecated `removeEventListener()` calls:
```
@deprecated
Use the remove() method on the event subscription returned by addEventListener().
```
The `useIsScreenReaderEnabled` hook would sometimes cause a crash while I was working on https://github.com/AtB-AS/mittatb-app/pull/2983, which was fixed by this update. I'm not sure if `useAppStateStatus` has a similar issue.
=> refactor: replace deprecated removeEventListener calls

src/mobile-token/MobileTokenContext.tsx, src/mobile-token/tokenService.ts, src/mobile-token/types.ts, src/screens/Profile/TravelToken/ChangeTokenAction.tsx, src/screens/Profile/TravelToken/FaqSection.tsx, src/screens/Profile/TravelToken/index.tsx, src/screens/Profile/TravelToken/use-token-toggle-details.ts, src/translations/screens/subscreens/TravelToken.ts, src/utils/date.ts
Closes https://github.com/AtB-AS/kundevendt/issues/2511
1. Calls abt-token-server API (PR: https://github.com/AtB-AS/abt-token-server/pull/32) to get toggle limit for the user.
2. Max limit is configured in firestore ;  configuration => other => tokenToggleMaxLimit
3. If tokenToggleMaxLimit is not set in firestore no limitation would be applied on toggle
4. Added new point in the FAQ regarding token toggle.
<div>
</div>
=> feat: show toggle limit when user tries to toggle token

src/screens/Ticketing/Purchase/Overview/index.tsx
Fixes an issue where the student category was missing when purchasing periodic tickets in the app, because the list wasn't updated with the correct set of travellers when selecting a different fare product.
In order to keep the list of selectable travellers updated, this PR uses navigation params instead of a local state. This updates the offer defaults, and the list of travellers.
https://user-images.githubusercontent.com/1774972/196380100-c55efe1f-d08a-4a38-8b43-e636b4218587.mp4
=> fix: update offer defaults when updating preassignedFareProduct

scripts/android/register-app-version.sh, scripts/ios/register-app-version.sh
The field 'application_version_id' is changed to 'version_name'. In
addition we start using the field 'version_code' for Android, which is
necessary for Play Integrity.
Resolves https://github.com/AtB-AS/kundevendt/issues/2687
=> build: Update register scripts

fastlane/Fastfile
Short explanation: The keychain that stores the certificates for signing is expired before the compilation ends, causing an endless loop in the linking process. Ensuring more time `timeout` in the creation guarantee to be available.
=> build: Adds a fix to the keychain for Github Actions

src/screens/Ticketing/Tickets/AvailableTickets/AvailableTickets.tsx, src/screens/Ticketing/Tickets/RecentTickets/RecentTickets.tsx, src/screens/Ticketing/Tickets/Tabs.tsx
fixes https://github.com/AtB-AS/kundevendt/issues/2333
On the ticketing screen, the background color is now set as default to the same color as the tab, which solves the "scroll area" from being the wrong color as described in https://github.com/AtB-AS/kundevendt/issues/2333.
Also handles the case where the user has no previous purchases, which makes the "All products" section the same color as the tab.
[Tickets / Buy](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?node-id=11562%3A50133)
[Tickets / Buy (with Recent tickets)](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?node-id=6648%3A45714)
[Tickets / Buy  (loading)](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?node-id=11562%3A50788)
https://user-images.githubusercontent.com/1774972/196419080-fb082bf0-1762-488a-aaf …
=> fix: change implementation of background colors for ticketing

src/screens/Dashboard/DeparturesWidget.tsx
closes https://github.com/AtB-AS/kundevendt/issues/2595
Sorts dashboard favorite departures by distance to the user geolocation. If location permission is not given, the app keeps the default order.
=> feat: sort dashboard departures by distance

src/screens/Profile/TravelToken/use-token-toggle-details.ts
Closes https://github.com/AtB-AS/kundevendt/issues/2511#issuecomment-1285071939
We can end up in a situation when toggle max limit becomes less than the number of times toggled by the user. This can happen when we reduce the max limit in firestore and the user has already toggled more than the new max limit. Hence setting toggle attempts left to zero for the user in such case.
=> refactor: set toggle limit to zero if somhow max limit ends up being less than times toggled by user

package.json, yarn.lock
Partly solving https://github.com/AtB-AS/kundevendt/issues/2628
This PR bumps the version number of generate-assets to include a new NFK noFavouriteDepartures widget illustration. 
Shouldn't affect AtB in any way, but I understand you might want to wait after making a release candidate. Design system PR for reference: https://github.com/AtB-AS/design-system/pull/76
Screenshot for NFK:
=> fix: replace NFK NoFavouriteDepartures illustration

package.json, yarn.lock
Upgrading theme and asset in app to contain the following fixes:
- [Removal of classes in NFK svgs causing tsc errors during setup](https://mittatb.slack.com/archives/C025NUF4WA0/p1666360096355189)
- [Support for some organizations using separate assets while other use common assets (travelcard / t:kort)](https://github.com/AtB-AS/kundevendt/issues/2701)
Testing: 
Nothing changed for AtB. Can probably check that t:kort illustration in token toggle onboarding is correct.
=> fix: upgrade theme and assets to remove nfk build error

android/build.gradle
Following the [release of AndroidXBrowser v 1.5.0-alpha01](https://developer.android.com/jetpack/androidx/releases/browser#1.5.0-alpha01) last evening, building the app on Android required compiling to Android SDK version 33, which requires some testing. Because we had a lower SDK version, building the Android app failed with a Gradle Error.
Mikael discovered that our dependency package `react-native-inappbrowser-reborn` picked whatever newest AndroidX packages [it could find](https://github.com/proyecto26/react-native-inappbrowser/blob/a51ecc774e8e0fe494879d1dc60ed23148fea886/README.md#mostly-automatic-installation) if we didn't [specify a version](https://github.com/proyecto26/react-native-inappbrowser/blob/a51ecc774e8e0fe494879d1dc60ed23148fea886/README.md#mostly-automatic-installation) …
=> build: require specific androidXBrowser

src/screens/Ticketing/FareProducts/AvailableFareProducts/AvailableFareProducts.tsx, src/screens/Ticketing/FareProducts/PurchaseTab.tsx, src/screens/Ticketing/Purchase/AnonymousPurchaseWarning.tsx
ref. https://github.com/AtB-AS/kundevendt/issues/2333#issuecomment-1285218487 (and also previous PR https://github.com/AtB-AS/mittatb-app/pull/3018)
Fixes an inconsistency with [sketches](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?node-id=10194%3A48114) where the warning message for anonymous users was shown in the same section as recent tickets.
Now the ticketing screen looks like this:
=> fix: move AnonymousPurchaseWarning from repeat purchase section

src/api/trips_v2.ts
fixes https://github.com/AtB-AS/kundevendt/issues/2451
Following https://github.com/AtB-AS/atb-bff/pull/169, skip error logging to bugsnag for 410 responses from the singleTrip BFF endpoint.
I have tested that in the simulator on iOS, there is no "bugsnag-popup" when we get a 410 response.
=> fix: skip error logging on singleTrip 410 responses

src/components/message-box/index.tsx, src/components/sections/index.tsx, src/components/sections/message-item.tsx, src/screens/Profile/DesignSystem.tsx, src/translations/dictionary.ts, src/utils/message-type-to-icon.ts
Support title and message, and the screen reader will read the status message type before reading the text content.
This is to be used when adding situation messages on departures v2.
=> refactor: Add new section message tem

package.json, yarn.lock
Updating theme package, to include new NFK destructive interactive colours in the 1.28 version of app.
Should include the following changes in the theme package (only NFK colours as far as I can see):
- https://github.com/AtB-AS/design-system/commit/395f3eaa76b380ae6111892afd68310047acc3de
- https://github.com/AtB-AS/design-system/commit/734ffae25faa33fd6b66fa3d3c0638d3bce58996
- https://github.com/AtB-AS/design-system/commit/9ddd692faa9d76987823f766ea779eb52cf6b673
=> feat: upgrade theme package to get new NFK colours

package.json, yarn.lock
Fixing failing Android build by upgrading from 0.70.1 to 0.70.5, not sure about the consequences, but app is now building successfully on my machine again following this change.
[Fix](https://github.com/facebook/react-native/issues/35210) applied by @jorelosorio as well, as [mentioned in Slack](https://mittatb.slack.com/archives/C02EEG7D8EL/p1668076346917619?thread_ts=1668073468.778059&cid=C02EEG7D8EL), but cannot see that is has been merged to master?
Example of failed build: https://github.com/AtB-AS/mittatb-app/actions/runs/3437647338/jobs/5734721377
=> build: upgrade react-native to 0.70.5 to fix Android build issues

src/screens/Departures/components/QuaySection.tsx
There was an error where not only the last item of a QuaySection had bottom border-radius.
Before/After
<div>
</div>
=> refactor: Fix QuaySection border bottom error

src/departure-list/section-items/quay-header.tsx
https://www.sprakradet.no/sprakhjelp/Skriveregler/Mellomrom/
"Det skal vere mellomrom mellom tal og (forkorta) nemningar anten nemninga står framfor talet eller etter det.
10 kr, 5,68 kg, 25 l, 5 m, 10 min"
=> fix: add space before unit of measurement in distance

src/screens/Departures/QuayView.tsx, src/screens/Departures/StopPlaceView.tsx, src/screens/Departures/state/quay-state.ts, src/screens/Departures/state/stop-place-state.ts
Restructured the logic in quay-state and stop-place-state so (hopefully) only one effect for reloading state is fired when anything changes.
Resolves https://github.com/AtB-AS/kundevendt/issues/2875
=> refactor: Date change didn't refresh departure search

src/screens/Ticketing/FareContracts/ValidityLine.tsx
Remove dashes to avoid gaps in progress bar on Android
<details>
<summary>Screenshot before fix</summary>
</details>
<details>
<summary>Screenshot after fix</summary>
</details>
Close https://github.com/AtB-AS/kundevendt/issues/2293
=> fix: remove dashes to avoid broken progress bar

e2e/tests/departuresV2.e2e.ts, e2e/tests/tickets.e2e.ts, e2e/utils/departures.ts, src/screens/Departures/DeparturesOnboardingScreen.tsx
The new departure onboarding has to be clicked in order to run the departure v2 tests. In addition, the ticket tab is renamed "Active" from previous "Valid".
=> test: handle departure onboarding and ticket change

src/screens/Departures/components/QuaySection.tsx
Screenshots from Departures/Map/Assistant:
<div>
</div>
=> feat: Add situation message to quay

src/screens/Departures/state/quay-state.ts, src/screens/Departures/state/stop-place-state.ts
When a new departures search was fired, the old search was cancelled by the abort controller. This cancellation led to the action "SET_ERROR" was sent slightly after the new search was actually started. So the error message was shown to the user even though no error had happened.
Resolves https://github.com/AtB-AS/kundevendt/issues/2890
=> refactor: Not show err msg when doing new search

src/screens/TripDetails/utils.ts, src/utils/date.ts
When the expected time was before aimed time, the aimed time was
shown. I am not sure if this was intentional or not. But when searching
for trips all legs of the trip is based on the realtime data, so we need
to show the expected time for all legs.
Resolves https://github.com/AtB-AS/kundevendt/issues/2928
=> fix: Show realtime even though before aimed time

src/components/message-box/index.tsx, src/screens/TripDetails/DepartureDetails/index.tsx, src/screens/TripDetails/components/TripSection.tsx, src/screens/TripDetails/components/WaitSection.tsx
Removed as it was just a normal MessageBox without the status icon and
no possibility for setting title.
Resolves https://github.com/AtB-AS/kundevendt/issues/2908
=> refactor: Remove TinyMessageBox

tools/release/changelog.config.js
Closing https://github.com/AtB-AS/kundevendt/issues/2508
Negative lookahead is not supported in [POSIX Extented Regular Expressions](https://en.wikibooks.org/wiki/Regular_Expressions/POSIX-Extended_Regular_Expressions), which is what's used with `grep -E`. A possible solution to this is to chain two `grep` expressions, where one of them inverts the match. As it is now it matches the organization ID wherever it is in the tag, but I don't see that as an issue.
I also went ahead and added `fram` to the expression, since that will potentialle be needed in the near future.
=> build(changelog): Fix grep for latest release tag

src/screens/TripDetails/components/DetailsMessages.tsx
Show correct information message when trip has train in zone a and starts on foot
https://github.com/AtB-AS/kundevendt/issues/2728
=> fix: show correct information message when starting on foot

e2e/tests/tickets.e2e.ts
There is currently an error when choosing a combination of adult and other categories when buying tickets. This is due to the offer response from Entur. Until this is fixed, some assertions are disabled to make the e2e test run again.
=> test: disable test due to entur error

src/configuration/FirestoreConfigurationContext.tsx, src/configuration/converters.ts, src/reference-data/defaults.ts, src/reference-data/defaults/fare-product-type-config.json, src/screens/Ticketing/FareContracts/utils.ts
Just a draft PR for now. Having problems with my development environment so haven't tested the implementation of this, but maybe enough to show how it'll be used.
closes https://github.com/AtB-AS/kundevendt/issues/2895
=> feat: add fare product type configurations from firestore

.github/actions/ios-build-setup/action.yml, scripts/ios/override-config-files.sh
I have no idea why this is now necessary, but wasn't before 🤔 Or to be more precise, I don't fully understand why it was working before without copying .netrc before installing pods.
I see the macos-12 runner changed version from 20221121.1 to 20221127.5 when this started happening, but don't see anything relevant in the changelogs that could have caused this.
It seems like the build started failing exactly on the day two years after the mapbox token was created was just a coincidence.
=> build: Copy .netrc in ios setup

ios/atb.xcodeproj/project.pbxproj
Fixes a crash that seems to appear when building iOS with Xcode 14.1 on Intel macs. Adds hermes to this section to the Xcode project:
=> chore: add hermes to "Link Binary With Libraries"

__tests__/utils-test.ts, src/api/serviceJourney.ts, src/api/types/generated/ServiceJourneyWithEstimatedCallsQuery.ts, src/api/types/generated/fragments/estimated-calls.ts, src/api/types/generated/fragments/notices.ts, src/api/types/generated/fragments/quays.ts, src/api/types/generated/fragments/service-journeys.ts, src/api/types/generated/fragments/stop-places.ts, src/api/types/generated/serviceJourney.ts, src/screens/TripDetails/DepartureDetails/index.tsx, src/screens/TripDetails/DepartureDetails/use-departure-data.ts, src/screens/TripDetails/components/DetailsMessages.tsx, src/translations/screens/subscreens/DepartureDetails.ts, src/utils/only-uniques.ts, src/utils/transportation-names.ts
To enable this we use the new serviceJourney/{id}/calls endpoint in the bff. This also gets the relevant notices on service journey, journey pattern and line level. In addition show the situations on each estimated call, but filter out those who are shown at the top. This is for removing line- and serviceJourney-level situations which are duplicated for each estimated call.
=> feat: Show notices on Departure Details

src/api/departures/types.ts, src/api/types/generated/QuayDeparturesQuery.ts, src/api/types/generated/StopQuayDeparturesQuery.ts, src/departure-list/section-items/line.tsx, src/screens/Assistant/ResultItem.tsx, src/screens/Dashboard/ResultItem.tsx, src/screens/Departures/components/EstimatedCallItem.tsx, src/screens/Departures/components/StopPlaceItem.tsx, src/screens/TripDetails/DepartureDetails/index.tsx, src/screens/TripDetails/DepartureDetails/use-departure-data.ts, src/screens/TripDetails/components/TripSection.tsx, src/screens/TripDetails/utils.ts, src/situations/SituationOrNoticeIcon.tsx, src/situations/index.tsx, src/situations/utils.ts
On trip and estimated call we show a blue or yellow info icon if it has any situations. Now if the trip or estimated call has any notices the blue icon will show.
This is fixed for Assistant on the new frontpage (but not the old one), on departures v2, and on departures v1 on the frontpage.
=> feat: Show info icon if trip or call has notices

src/components/accessible-text/AccessibleText.tsx, src/screens/TripDetails/DepartureDetails/index.tsx
Instead of using message boxes, just have the boarding info as secondary text under the quay name. Also skip redundant boarding info on first and last stop of service journey.
Also fixed som padding on the TripRow for situation message, so it is a little closer to the quay name above.
Resolves https://github.com/AtB-AS/kundevendt/issues/2992
Before/After:
<div>
</div>
=> feat: Make boarding info less intrusive

package.json, src/departure-list/section-items/line.tsx, src/screens/Departures/components/EstimatedCallItem.tsx, yarn.lock
Add dark mode version of realtime icon
<details>
<summary>Screenshots dark mode</summary>
</details>
<details>
<summary>Screenshots light mode</summary>
</details>
https://github.com/AtB-AS/design-system/pull/92
https://github.com/AtB-AS/kundevendt/issues/2947
https://github.com/AtB-AS/kundevendt/issues/2950
=> feat: add dark realtime icon

src/screens/Profile/DebugInfo/index.tsx
Adds a "Preferences" section to the debug menu, to make issues like https://github.com/AtB-AS/mittatb-app/pull/3122, easier to test and debug. Pressing a line will set the preference to `undefined`, which will fall back to defaults.
=> feat: add preferences to debug menu with reset

src/api/types/generated/TripsQuery.ts, src/api/types/generated/journey_planner_v3_types.ts, src/screens/TripDetails/components/TripSection.tsx, src/translations/screens/subscreens/TripDetails.ts
Add realtime with previously passed bus stop on trip details.
<details>
</details>
https://github.com/AtB-AS/atb-bff/pull/197
Close https://github.com/AtB-AS/kundevendt/issues/2949
=> feat: add realtime to trip details

src/components/feedback/index.tsx
Fixes an error when submitting feedback, caused by `isReprompt` / `answeredAtDisplayCount` was undefined, which isn't supported in firestore, unless `ignoreUndefinedProperties` is set to true.
~Fixed by initializing the value to `1`, and providing a fallback. I could have set `answeredAtDisplayCount` to be required [here](https://github.com/AtB-AS/mittatb-app/blob/rosvik/1996-error-in-feedback-components-for-ios/src/components/feedback/index.tsx#L81) in `VersionStats` as well, but since there is data saved to user's devices where it is undefined, I think we should still support it, and rather use a fallback.~
fixes https://github.com/AtB-AS/kundevendt/issues/1996
=> fix: handle undefined firestore feedback values

src/screens/Ticketing/FareContracts/Component/InspectionSymbol.tsx, src/screens/Ticketing/FareContracts/Details/DetailsScreen.tsx, src/screens/Ticketing/FareContracts/FareContractInfo.tsx, src/screens/Ticketing/FareContracts/index.tsx, src/ticketing/types.ts, src/ticketing/utils.ts
Closes: https://github.com/AtB-AS/kundevendt/issues/2731
In order to test please buy a normal single ticket and in the firestore configuration please add the type as `NightTicket`. Please also remove the `tariffZoneRefs` field. Together with all that please also in the `fareProductRef` add either:
- ATB:PreassignedFareProduct:8f351521
- ATB:PreassignedFareProduct:877baeff
- ATB:PreassignedFareProduct:e317a807
Example of one night ticket:
```json
{
"created": {
"nanoseconds": 17154000,
"seconds": 1671009490
},
"customerAccountId": "ATB:CustomerAccount:aONCHMcM0TOSJaVvts3BZmtfn9I3",
"eventTimestamp": {
"nanoseconds": 860808000,
"seconds": 1671009490
},
"id": "ATB:FareContract:4KB3B8B4-aONCHMcM0TOSJaVvts3BZmtfn9I3",
"minimumSecurityLevel": -200,
"orderId": "4KB3B8B4",
"paymentType": [
"VISA" …
```
=> feat: Show night ticket and handle different states

src/components/screen-header/index.tsx
Using 'accessible: false' on the Text child component so it isn't accessible in the instances where the parent view has
'accessible: false'.
=> refactor: Not accessible empty header title

e2e/tests/departuresV1.e2e.ts, e2e/tests/departuresV2.e2e.ts, e2e/tests/myprofile.e2e.ts, e2e/tests/tickets.e2e.ts, e2e/tests/travelsearch.e2e.ts
There have been some test failures lately - due to a change on trip details and departures v2 as default. These are fixed here. In addition, I've moved skipped tests into a separate `describe` block that is skipped entirely. This way, skipped tests do not need to run `beforeEach` operations and the tests run a bit quicker.
=> test: e2e fix and optimization

src/screens/Departures/components/QuaySection.tsx, src/translations/screens/Departures.ts
Replace quay name with "see more departures"
<details>
</details>
Close https://github.com/AtB-AS/kundevendt/issues/2953
=> feat: replace quay name with "see more departures"

src/screens/Ticketing/FareProducts/PurchaseTab.tsx, src/screens/Ticketing/FareProducts/RecentFareProducts/RecentFareContractComponent.tsx, src/screens/Ticketing/FareProducts/RecentFareProducts/RecentFareContracts.tsx, src/screens/Ticketing/Purchase/Confirmation/index.tsx, src/screens/Ticketing/Purchase/Overview/components/Summary.tsx, src/screens/Ticketing/Purchase/Overview/components/ZonesSelection.tsx, src/screens/Ticketing/Purchase/Overview/index.tsx, src/screens/Ticketing/Purchase/TariffZones/index.tsx, src/screens/Ticketing/Purchase/types.ts, src/translations/screens/subscreens/PurchaseConfirmation.ts, src/translations/screens/subscreens/PurchaseOverview.ts
Get the fare product type name during the purchase prosess from the new FareProductTypeConfigs in FireStore.
=> refactor: Purchase screen texts from FireStore

src/configuration/converters.ts, src/configuration/types.ts, src/reference-data/defaults/fare-product-type-config.json, src/screens/Ticketing/FareContracts/Carnet/UsedAccessValidityHeader.tsx, src/screens/Ticketing/FareContracts/Component/TransportMode.tsx, src/screens/Ticketing/FareContracts/ValidityHeader.tsx, src/screens/Ticketing/FareContracts/utils.ts, src/screens/Ticketing/FareProducts/AvailableFareProducts/FareProductTile.tsx, src/screens/Ticketing/FareProducts/RecentFareProducts/RecentFareContractComponent.tsx, src/screens/Ticketing/FareProducts/RecentFareProducts/RecentFareContracts.tsx, src/screens/Ticketing/Purchase/Overview/components/Summary.tsx, src/translations/screens/FareContract.ts
Show transportation mode icons based on the new
FareProductTypeConfigs in FireStore.
=> refactor: Transportation modes from Firestore

src/configuration/converters.ts, src/login/LoginOnboarding.tsx, src/login/in-app/LoginOnboarding.tsx, src/reference-data/defaults/fare-product-type-config.json, src/screens/Ticketing/FareProducts/PurchaseTab.tsx, src/translations/screens/subscreens/Login.ts
Whether a product requires login or not is now based on the field 'requiresLogin' in the new FareProductTypeConfigs in FireStore.
Also made the login-onboarding screen with "you need to login" warning to be more generic.
=> refactor: Whether product requires login from Firestore

src/api/trips_v2.ts, src/screens/TripDetails/Details/index.tsx, src/screens/TripDetails/Details/use-current-trip-pattern-with-updates.ts
- It was not working at all because of wrong expected data type from single trip query endpoint.
- Keeps updated state for each trip pattern, so changing index by navigating left or right doesn't reset to the orignal trip pattern
- Hide loading indicator to make it feel more "snappy". The user don't need to know that it is updating behind the scenes.
- Not update a trip pattern with wrong data. This is done by utilizing the AbortController signal so when the index change the old request is aborted.
- Moved complexity into its own hook, to make the main Details component a little cleaner.
- Changed according to coding guidelines.
=> refactor: Fix updating trip patterns

src/screens/TripDetails/DepartureDetails/index.tsx, src/screens/TripDetails/components/Time.tsx, src/screens/TripDetails/components/TripSection.tsx, src/translations/dictionary.ts, src/translations/screens/subscreens/TripDetails.ts
Add realtime icon to trip leg times to remove "ca." and differenciate between no realtime and trip that has not passed any stops.
<details>
</details>
https://github.com/AtB-AS/kundevendt/issues/2949
=> feat: Add realtime icon to trip leg times

src/departure-list/section-items/quay-header.tsx
Make quay header text on departures front page bold.
<details>
</details>
https://github.com/AtB-AS/kundevendt/issues/2740
=> refactor: Change to bold quay name

src/components/button/index.tsx, src/components/map/components/BackArrow.tsx, src/components/map/components/MapControls.tsx, src/components/map/components/PositionArrow.tsx, src/departure-list/section-items/line.tsx, src/favorite-chips/index.tsx, src/screens/Departures/components/DateSelection.tsx, src/screens/Profile/DesignSystem.tsx, src/screens/TripDetails/components/PaginatedDetailsHeader.tsx
Type 'compact' mainly decided the internal padding of the button, but it also made the button behave as it had type 'inline'. The compact mode was extracted from the type field into its own field, so it is possible to specify compact mode both when the button type is 'inline' or 'block'.
=> refactor: 'compact' as own field on button

src/components/button/index.tsx
Previously icon sizes could not be specified, and as such the hardcoded value of xLarge (24) was correct. When we now can specify the icon size, we need to calculate the necessary margin dynamically.
=> reaftor: Calculate button margin based on icon size

package.json, src/screens/Profile/DesignSystem.tsx, yarn.lock
Upgrades theme package to include new secondary text color in dark mode. Also adds text colors to the design system page, and displays color codes on swatches.
closes https://github.com/AtB-AS/kundevendt/issues/3040
=> chore: upgrade theme package

src/components/switch/FixedSwitch.tsx, src/screens/Dashboard/SelectFavouritesBottomSheet.tsx, src/screens/Ticketing/Purchase/Overview/components/InfoToggle.tsx
Everywhere the FixedSwitch was used there was need for scaling it
with font scale etc. This is now moved into the FixedSwitch so the
scaling is done in just one place.
Also add the possibility for setting an interactive color for the
switch.
Affects mainly three places:
- The switch in select favourites
- The switch on InfoToggle (like on show travellers info text)
- The switches under "My profile"
=> refactor: FixedSwitch improvements 

src/components/sections/items/ActionSectionItem.tsx, src/components/sections/items/ExpandableSectionItem.tsx, src/departure-list/DeparturesList.tsx, src/translations/components/Section.ts
Two main reasons:
- The ActionSectionItem was quite large and complex, with options for expandable, checkable and toggleable. It is better if these are seperate components.
- We already have the ExpandableSectionItem which should instead be used for this.
This affects two places, the FAQ in SelectTokenScreen, and the expandable stop place name in v1 departures.
=> refactor: Remove expand option in ActionSectionItem

src/components/sections/index.ts, src/components/sections/items/ActionSectionItem.tsx, src/components/sections/items/ToggleSectionItem.tsx, src/components/switch/index.ts, src/components/toggle/Toggle.tsx, src/components/toggle/index.ts, src/screens/Dashboard/SelectFavouritesBottomSheet.tsx, src/screens/Dashboard/TravelSearchFiltersBottomSheet.tsx, src/screens/Departures/components/FavoriteToggle.tsx, src/screens/Nearby/Nearby.tsx, src/screens/Profile/Appearance/index.tsx, src/screens/Profile/DebugInfo/index.tsx, src/screens/Profile/DesignSystem.tsx, src/screens/Profile/Home/index.tsx, src/screens/Profile/Language/index.tsx, src/screens/Ticketing/Purchase/Overview/components/InfoToggle.tsx
The old 'toggle' mode on ActionSectionItem had some screen reader challenges. This is fixed in this commit, alongside some restructuring.
- Created a new ToggleSectionItem instead of using ActionSectionItem.
- Renamed FixedSwitch to Toggle. This is because toggle is used as the word for the component in design-sketches/Figma, and it is slightly more intuitive.
- Parameter names are now 'value' and 'onValueChange' so it is the same parameters as using the Toggle (previously FixedSwitch) directly.
- When using screen reader the whole section item is now selected, and some extra measures has been added to ensure the accessibility state is read correctly.
=> refactor: Add ToggleSectionItem

.github/workflows/build-store-android.yml, .github/workflows/build-store-ios.yml
Registering NFK iOS and Android app versions with Entur, while also uploading source maps for NFK Android.
=> build: register nfk app versions

src/components/sections/items/InternalLabeledSectionItem.tsx, src/screens/Dashboard/SelectFavouritesBottomSheet.tsx, src/screens/Dashboard/TravelSearchFiltersBottomSheet.tsx
- Add section seperator under heading for select favourites bottom sheet so it looks the same as the filters bottom sheet.
- Some changes to the internal section label so text doesn't overflow.
- Fixed a bug where removing a filter option from Firestore made the "all" button work incorrectly.
=> refactor: Fix some filters design flaws

src/components/button/Button.tsx, src/components/theme-icon/NotificationIndicator.tsx, src/components/theme-icon/ThemeIcon.tsx, src/components/theme-icon/index.ts, src/components/theme-icon/types.ts, src/screens/Profile/DesignSystem.tsx, src/theme/colors.ts
Add the possibility to add a small notification indicator at the top
right of icons through specifying a notification color to the
ThemeIcon. Also possible to add on button icons.
Screenshots from in-app DesignSystem:
(Button number 2 and 4 has notification indicator)
=> refactor: Add support for notification on icons

src/components/button/Button.tsx, src/components/theme-icon/NotificationIndicator.tsx, src/components/theme-icon/ThemeIcon.tsx, src/screens/Profile/DesignSystem.tsx
After discussion with @ckbilstad regarding that the icons should "pop" a little more.
The code is getting more complex for the notification indicators, but I think it is worth it as it is quite a hassle to add these icons with indicators to the design-system repo as well. Adding them to the design-system requires there to be a version for light/dark (since they are not mono), and also NFK/Fram must add their own if they want another notification indicator color.
=> refactor: Add notification indicator spacing

ios/atb/Info.plist
Changed value together with Jorge. Most likely just a field that was dynamic at some point, but become hardcoded for testing at some point.
Hopefully solves https://github.com/AtB-AS/kundevendt/issues/3257
=> fix: change AppTeamIdentifier into dynamic value

src/components/theme-icon/NotificationIndicator.tsx
Makes notification icons, and the border around them adjust to font size.
<div>
</div>
closes https://github.com/AtB-AS/kundevendt/issues/3229
=> feat: notification indicator based on font size

src/api/departures/index.ts, src/screens/Dashboard/state.ts, src/screens/Departures/state/quay-state.ts, src/screens/Departures/state/stop-place-state.ts, src/screens/Nearby/state.ts
After the upgrade of old endpoints to OTP2 (Issue https://github.com/AtB-AS/kundevendt/issues/3171 among others), the endpoints `bff/v1/departures-realtime` and `bff/v2/departures/realtime` are identical in functionality. Therefore it makes sense to stop using `bff/v1/departures-realtime`, and deprecate it.
I think it makes sense to test this later, as I'm also working on a larger BFF refactoring.
=> refactor: stop using bff/v1/departures-realtime for realtime

src/translations/components/TravelTokenBox.ts, src/translations/screens/FareContract.ts, src/translations/screens/Onboarding.ts, src/translations/screens/Profile.ts, src/translations/screens/Ticketing.ts, src/translations/screens/subscreens/MobileTokenOnboarding.ts, src/translations/screens/subscreens/PurchaseOverview.ts, src/translations/screens/subscreens/TravelToken.ts
https://github.com/AtB-AS/mittatb-app/pull/3220 2.0
Fixes t:kort references and AtB references in ticketing related screens for Reis.
Mostly work of Adrian.
=> fix: Add missing t:card translations for NFK

src/translations/screens/subscreens/DeleteProfile.ts, src/translations/screens/subscreens/TravelToken.ts
Closing https://github.com/AtB-AS/kundevendt/issues/3022
Changes to Reis instead of AtB references in these views:
<details>
</details>
=> fix: toggle FAQ translations for Reis

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_PlaceScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DeparturesStack/Departures_PlaceScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_PlaceScreen.tsx
In the Dashboard-stack the PlaceScreen mode can be both 'Departures' and 'Favorites'. This mode should be forwarded when pushing new PlaceScreen on the stack.
=> refactor: Correct mode on PlaceScreen in Dashboard stack

android/app/build.gradle
Two kotlin dependencies were picked up as two different transitive dependencies, but with mis-matching version numbers. Adding them as specific dependencies in our build.gradle should fix this.
=> build: Fix Android dependency error

ios/departureWidget/DepartureWidget.swift, ios/departureWidget/Structs.swift, ios/departureWidget/Views/ChipView.swift, ios/departureWidget/Views/DepartureTimesView.swift, ios/departureWidget/Views/WidgetInfoView.swift, ios/departureWidget/WidgetViewModel.swift, src/stacks-hierarchy/RootStack.tsx
Deeplinks in medium widget:
1. Can now click individual departures on the medium widget. 
2. This redirects you to the details screen of the clicked departure.
Closes https://github.com/AtB-AS/kundevendt/issues/3289
=> feat: deeplink from each departure on medium widget

src/departure-list/section-items/line.tsx, src/place-screen/components/EstimatedCallItem.tsx, src/travel-details-screens/TripDetailsScreenComponent.tsx
related to https://github.com/AtB-AS/kundevendt/issues/3219
Use aimed departure time (rutetid) in the paginated header instead of expected time, to prevent header going out of sync after realtime updates. This affects both trip details and departure details.
<div>
</div>
=> fix: use aimedDepartureTime for pagination header

package.json, yarn.lock
Related to https://github.com/AtB-AS/kundevendt/issues/3063
Uses changed SVG from https://github.com/AtB-AS/design-system/pull/101
=> fix: bump generate-assets to include new nfk travelplanning svg

src/login/PhoneInput.tsx, src/translations/screens/subscreens/Login.ts
There was no color defined for the spinner, so it defaulted to a gray color. I set the color to the primary text color since that has been used for the spinner in other places as well.
I also fixed the casing of the phone input heading, in english.
Android:
iOS:
Fixes https://github.com/AtB-AS/kundevendt/issues/3059
=> fix: use theme color for login spinner

src/components/sections/items/ExpandableSectionItem.tsx, src/configuration/FirestoreConfigurationContext.tsx, src/configuration/converters.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Purchase/Overview/components/FlexTicketDiscountInfo.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Purchase/Overview/index.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Purchase/Overview/use-offer-state.ts, src/ticketing/types.ts, src/translations/screens/subscreens/PurchaseOverview.ts
When the field `flexDiscountLadder` is returned in the offer response, the flex discount info is shown. Although we only have flex discount for adult now, the app supports discounts on multiple user profile types.
The expandable with the info is as of now always expanded at start of the purchase process. Might do something about this later, like storing the state of the expandable on the device storage.
The description text has a reference to a specific zone and number of days. Because of this it is made overrideable by specifying a 'discountInfo' under 'appTexts' in Firestore Configuration.
Also a minor change to the ExpandableSectionItem which makes the full height/width of the expandable heading be focusable for the screen reader.
=> feat: Add flex discount info

src/components/info-chip/InfoChip.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Purchase/Overview/components/FlexTicketDiscountInfo.tsx
This is changed so they are the same as on recent fare products and fare contracts.
This only affects dark mode. 
Before:
After:
=> fix: Update chip info colors on discount info

src/mobile-token/mobileTokenClient.ts, src/mobile-token/tokenService.ts
Some GRPC errors are not errors per se, but a part of a normal expected flow, for example the error signifying that the token needs renewal. Other errors that really are errors should be handled and logged in the mobile token specific code.
=> fix: Not log GRPC errors in axios client

src/utils/date.ts
follow up to https://github.com/AtB-AS/kundevendt/issues/3219
Fixes issue found by @HanneLH, where minutes were rounded when seconds are shown:
https://user-images.githubusercontent.com/1774972/217524138-8db08d45-b175-4758-a1eb-81648e75815c.MP4
=> fix: don't round minutes when showing seconds

src/translations/screens/subscreens/MobileTokenOnboarding.ts
Replaces this AtB reference when token does not work:
=> fix: replace AtB kundesenter text for NFK

src/translations/screens/subscreens/PurchaseOverview.ts
Removes tram for summary text in NFK app. Should be unchanged for AtB, and ideally it should use the dynamic message based on actually included transport methods in the product, so hopefully won't be used for too long.
=> fix: remove tram on nfk summary page

package.json, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareProducts/AvailableFareProducts/AvailableFareProducts.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Purchase/TariffZones/index.tsx, yarn.lock
Use the new colors added for zone selection. These colors were added to fix the low contrast colors for NFK. The AtB colors are still the same as before.
New NFK colors:
Fixes https://github.com/AtB-AS/kundevendt/issues/3060
=> fix: use new colors for zone selection

Gemfile.lock
The version 0.4.0 has been yanked (removed) from the RubyGems.
https://rubygems.org/gems/fastlane-plugin-firebase_app_distribution/versions
=> fix: Update firebase_app_distribution plugin

ios/Configs/Debug.xcconfig
When adding GCC_PREPROCESSOR_DEFINITIONS to Xcode config seems like it rewrites internal Xcode settings for debugging even dough it uses the $(inherit), this PR brings back DEBUG macro.
=> fix: Update Debug.xcconfig to allow build from Dev machines

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareProducts/index.tsx
There is a bug with the react-navigation material top tab library
on Android, where after navigating to it from other places in the
app (and also through deep linking to it) the animation is not
triggered when changing tab, meaning the selected tab is correct,
but the content shown is actually from the previously selected tab.
I did not find any other easy enough way to fix this except
disabling animation on the purchase tabs.
This fixes the issue described in this comment:
https://github.com/AtB-AS/mittatb-app/pull/3278#issuecomment-1427749363
=> fix: Stale animation caused wrong content on purchase tab

src/reference-data/defaults/user-profiles.json, src/reference-data/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Purchase/Travellers/MultipleTravellersSelection.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Purchase/Travellers/SingleTravellerSelection.tsx, src/translations/screens/subscreens/TicketTraveller.ts
Closing https://github.com/AtB-AS/kundevendt/issues/3480 
Using the changes from https://github.com/AtB-AS/webshop2/pull/270, modified to work in the app. 
Ensures that passenger category descriptions for ticketing are used from Firestore referenceData if it exists.
=> feat: Firestore traveler category description

.gitignore, src/configuration/FirestoreConfigurationContext.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_GenericWebsiteInformationScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/TabNav_ProfileStack.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/navigation-types.ts, src/translations/screens/subscreens/GenericWebsiteInformationScreen.ts
Closing https://github.com/AtB-AS/kundevendt/issues/3046
Makes it possible to provide urls in Firestore for the information that AtB are providing by embedding text into the code of the app. Should be unchanged for AtB if urls are not provided.
In the unlikely event that the app should function while being offline, a fallback generic page (found in Screenshots) have been implemented for other orgs than AtB.
<details>
NFK (notice external link icon):
AtB:
Norwegian fallback page:
English fallback page:
</details>
=> feat: support external links for ticketing info in my profile

src/components/transportation-icon/TransportationIcon.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
The new travel search was missing some test-ids that is beneficial for the E2E-tests once they're up and running again.
From https://github.com/AtB-AS/kundevendt/issues/3288
=> test: add testid for e2e

src/api/departures/departure-group.ts, src/api/departures/index.ts, src/place-screen/hooks/use-quay-data.ts, src/place-screen/hooks/use-stop-place-state.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/use-favorite-departure-data.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_NearbyStack/use-departure-data.ts, src/utils/array.ts
Together with https://github.com/AtB-AS/atb-bff/pull/224, this PR adds filtering on lines when fetching realtime departures on the dashboard, and when favorites are toggled in departures. (Also a bit of related refactoring)
resolves https://github.com/AtB-AS/kundevendt/issues/3252
=> fix: filter realtime departures by line

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx, src/utils/date.ts
Fix minutes in walk icon to match trip details and avoid 0 minutes in icon
https://github.com/AtB-AS/kundevendt/issues/3288#issuecomment-1434420975
=> fix: Show walking minutes with correct rounding

src/components/button/Button.tsx
Fix issue where there is a margin on right side of buttons on map
=> fix: Only put margin on icon in button if there is another element

src/remote-config.ts, src/vehicles/components/OperatorLogo.tsx
Since we don't know yet how operators will provide logos through Entur we add a remote config to disable logos if they don't behave as expected.
=> feat: Remote config to disable vehicle operator logos

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ZonesSelection.tsx, src/stacks-hierarchy/Root_PurchaseTariffZonesSearchByMapScreen.tsx, src/translations/screens/subscreens/PurchaseOverview.ts, src/translations/screens/subscreens/TariffZones.ts
closes https://github.com/AtB-AS/kundevendt/issues/3536
Updates the zone selection component to show selected stop places. If from and to zone and stop place are the same, show only one line, if not split into two lines with "From" and "To" labels. If there's only one zone selectable, only one line is shown.
https://user-images.githubusercontent.com/1774972/223431288-19b49cbd-bc4c-478f-ac7a-f27bd85328d2.mp4
=> feat: update zone selection component

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ZonesSelection.tsx, src/stacks-hierarchy/Root_PurchaseTariffZonesSearchByMapScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/CompactFareContractInfo.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/FareContractInfo.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/utils.ts, src/translations/screens/subscreens/PurchaseOverview.ts
Updates a11y label to reflect what the zone selection component displays after https://github.com/AtB-AS/mittatb-app/pull/3346, e.g. "Selected zones: From Prinsens gate, zone A, to Zone B1.
Also moves `tariffZonesSummary` to closer to where it's being used now.
closes https://github.com/AtB-AS/kundevendt/issues/3536
=> feat: update zone selection a11y label

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/Component/InspectionSymbol.tsx
closes https://github.com/AtB-AS/kundevendt/issues/3636
- Updates InspectionSymbol to show the "Moon" icon when `fareProductTypeConfig.illustration` is set to "night".
- Updates `shouldFill` to use the `illustration` field as well. (No visual changes, but could prevent things from breaking in the future)
<div>
</div>
=> feat: update night ticket inspection symbol

src/components/toggle/Toggle.tsx
Make Android toggles visible when dark mode is set in app but not on phone.
<details>
</details>
Close https://github.com/AtB-AS/kundevendt/issues/2359
=> fix: Fix Android dark mode toggle

src/RemoteConfigContext.tsx, src/remote-config.ts
- Will retry fetching remote config values every 15 seconds until a
successful fetch.
- Will only notify error to Bugsnag if 'enable_network_logging' is
true. If it is not true, a breadcrumb will be sent instead.
- The default value for 'enable_network_logging' was changed to
false as this is the value that we have in production today.
=> feat: Retry Remote Config fetch when the request failed

src/diagnostics/bugsnagConfig.ts, src/setup.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-state.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/CompactFareContracts.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/CompactFareContractInfo.tsx, src/storage/index.ts, src/translations/components/CancelledDeparture.ts, src/translations/components/DetailsMessages.ts, src/translations/components/ScreenHeader.ts, src/translations/components/ServiceDisruptions.ts, src/translations/components/TravelTokenBox.ts, src/translations/index.ts, src/translations/screens/FareContract.ts, src/translations/screens/Onboarding.ts, src/translations/screens/Profile.ts, src/translations/screens/Ticketing.ts, src/translations/screens/TicketingSplash.ts, src/translations/screens/subscreens/ContactSheet.ts, src/translations/screens/subscreens/DeleteProfile.ts, src/translations/screens/subscreens/GenericWebsiteInformationScreen.ts, src/translations/screens/subscreens/Information.ts, src/translations/screens/subscreens/MobileTokenOnboarding.ts, src/translations/screens/subscreens/PurchaseOverview.ts, src/translations/screens/subscreens/TravelToken.ts, src/travel-details-screens/DepartureDetailsScreenComponent.tsx
Some errors which shows up in the Metro when running up the simulator locally are fixed. These are mainly:
- React unique keys errors
- Removed usage of "setAppGroupName" in AsyncStorage since it gave "undefined is not a function". This method was no longer supported by the AsyncStorage lib, and also the error was spamming Bugsnag for every user.
- Removed some cyclical dependencies in the translations module.
- Turned off logging breadcrumbs to console when developing locally. This can easily be overrided in the `bugsnagConfig.ts`.
The app should work as before. Mainly two things in the app can be affected by this change, which is:
=> fix: Fix several warnings

src/setup.ts, src/storage/index.ts
Readding usage of the `setAppGroupName`. It was recently removed as it gave an error on Android, but is now added again as it is necessary to do on iOS.
=> fix: Set appGroupName in storage as it is necessary on iOS

src/components/transportation-modes/TransportModes.tsx, src/components/transportation-modes/index.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/Carnet/CarnetDetails.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/Carnet/UsedAccessValidityHeader.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/Component/TransportMode.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/Details/DetailsContent.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/PreActivatedFareContractInfo.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareContracts/ValidityHeader.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareProducts/AvailableFareProducts/FareProductTile.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/FareProducts/RecentFareProducts/RecentFareContractComponent.tsx, src/translations/screens/FareContract.ts, src/translations/screens/subscreens/RecentFareContractsTexts.ts
Closes: https://github.com/AtB-AS/kundevendt/issues/3154
* Adjusted icon size in ticket page / tabs to 'small'
* Added box with +xx for when there are more than 2 transport modes and text reflecting several travel modes
* Made use og common component TransportMode.tsx in RecentFareContractComponent.tsx
* Created a common function for formatting transport mode texts liks BUS/TRAM
=> feat: Adjusted icon size in ticket inspection and showing a maximum of two icons

src/components/disappearing-header/ContentWithDisappearingHeader.tsx, src/travel-details-map-screen/components/CompactTravelDetailsMap.tsx
Setting `useNativeDriver` to `true` seems to work when testing on iPhone 12 mini emulator. I am not exactly sure why, and probably not worth investing more time into understanding it since the map is going to be removed from this animated header really soon.
This change should be tested to see if it works, and if the scroll animation is good enough without it. More info about the setting can be found here:
https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated
A specific note about what happens with the value set to false:
> without the native driver it will always run a frame behind of the gesture because of the async nature of React Native.
Since this is a delayed/parallax type of animation, it hopefully isn't noticeable for the user. Should probably compare side by …
=> fix: Stretched compact map fix

ios/departureWidget/Views/DepartureTimesView.swift
Replaced the ellipsis icon(down right) with a right chevron after a talk with Sebastian, Christian and Øyvind.
New:
Old:
=> fix: new icon on widget

src/api/departures/departure-group.ts, src/place-screen/components/QuayView.tsx, src/place-screen/components/StopPlaceView.tsx, src/place-screen/hooks/use-departures-data.ts, src/place-screen/utils.ts
- Adds `timeRange` query variable to realtime query (added to BFF here https://github.com/AtB-AS/atb-bff/pull/241)
- Adds `limitPerQuay` param to `useDeparturesData` to limit amount of departures per screen. This fixes https://github.com/AtB-AS/kundevendt/issues/3654#issuecomment-1476060960
- Refactors how `queryInput` is sent BFF endpoints, to make it easier to track where each variable is set, and synchronize between the realtime and initial departures, which is important for cache.
=> fix: update handling of departures query variables

src/nearby-stop-places/components/StopPlaces.tsx, src/place-screen/components/QuaySection.tsx, src/place-screen/components/QuayView.tsx, src/place-screen/components/StopPlaceView.tsx, src/place-screen/hooks/use-departures-data.ts
Fixes some issues related to departures
- a useEffect dependency list could vary in length.
- a BFF request was sent without required quayIds, that caused an error message to pop up for a split second.
- updated logic for showing loading indicator, by adding an `isLoading` param to to QuaySection
fixes https://github.com/AtB-AS/kundevendt/issues/3654#issuecomment-1482609501
=> fix: various departures fixes

src/place-screen/hooks/use-departures-data.ts, src/place-screen/utils.ts
Updates use-departures-data to fix realtime queries when search params change.
- Updates `loadRealTimeData` dependency list
- More resilient handling of `startTime` param, to prevent it from being out of sync between initial and realtime request.
fixes https://github.com/AtB-AS/kundevendt/issues/3654#issuecomment-1484886323
=> fix: update departures realtime query when params change

ios/atb/Info.plist
Adds missing allowed URL for recaptcha and local login.
Fixes https://github.com/AtB-AS/kundevendt/issues/3774 and allows for logging in for FRAM locally
=> chore: adds FRAM firebase id to info.plist allowed urls

src/auth/AuthContext.tsx, src/login/PhoneInput.tsx
We only sent errors to Bugsnag when confirm code failed, but we
also want to do it when sending in phone number fails.
This change was requested by @Sebstorvik when he asked to find a login-error in Bugsnag. We found out that the logging was recently added, but just to the confirm code step, while the login-error he found was in the phone input step. Since finding this error took as long time as fixing it, I just created a PR.
=> feat: Notify errors when sign in fails

.github/workflows/build-staging-ios.yml
We want to play whack-a-mole with the errors that will eventually hit us with the creation of the new FRAM app. 
I guess this is the best way to do that?
All staging builds jobs will send out an email that the job failed for some days, but if we've understood how matrixes works it will only affect the FRAM build job.
=> build: add FRAM to ios-staging GH action

ios/Configs/Debug.xcconfig
Flipper debugger was disabled for iOS on debug mode.
=> fix: Enable flipper on iOS

package.json, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_ScooterOnboardingScreen.tsx, src/translations/screens/subscreens/MobilityTexts.ts, yarn.lock
This should have been split into two (three?) different onboarding screens - one for vehicles and one for city bikes (and possibly a third for both). Given the time constraints before release, it's considered sufficient to just update the text.
=> fix: Update scooter onbarding text and image

package.json, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx, src/theme/ThemedAssets.tsx, src/theme/colors.ts, yarn.lock
Add changes to theme creation such that a theme for FRAM is created. Updated the package `@atb-as/generate-assets` to get the updated images with the correct colors.
Fixes https://github.com/AtB-AS/kundevendt/issues/3773
=> fix: Create theme and fix image colors for FRAM

ios/atb/Info.plist
Replaces FRAM Google ID after recreating app with new identifier.
=> fix: replace FRAM ios reversed id

src/components/button/Button.tsx, src/components/map/components/filter/MapFilter.tsx, src/components/theme-icon/ThemeIcon.tsx
The error happenend because the provided svg to ThemeIcon is called
as a function, which doesn't work with the LoadingSpinnger
component.
This was fixed by making the loading a flag on ThemeIcon, which now
internally handles correct showing of LoadingSpinner.
The warning that was shown:
```
Warning: React has detected a change in the order of Hooks called by ThemeIcon. This will lead to bugs
and errors if not fixed. For more information, read the Rules of Hooks: 
https://reactjs.org/link/rules-of-hooks
Previous render            Next render
------------------------------------------------------
1. useContext                 useContext
2. useState                   useState
3. useEffect                  useEffect
4. undefined                  useContext …
```
=> fix: Fix hooks order error in ThemeIcon

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContracts.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/use-recent-fare-contracts.ts
The react component key for recent fare contracts only used fare
product and travellers, and not zones. Which ment that we got a
duplicate key error if a user had two recent fare contracts
with same product and travellers, but different zones.
When doing this the logic for the key ended up being almost a
duplicate of checking for unique fare contracts. So now we use the
underlying fields for the recent fare contract to create an id
which can be used both as react key and for filtering out
duplicates.
Example of error we got before this fix:
```
ERROR Warning: Encountered two children with the same key, `ATB:PreassignedFareProduct:8808c3601ADULT`. 
Keys should be unique so that components maintain their identity across updates. 
Non-unique keys may cause children to be duplicated and/or …
```
=> fix: Duplicate key on recent fare contracts

src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx
Set color of tabBar to primary
new:
old:
=> fix: top border color on tab navigator

src/index.tsx, src/translations/components/Section.ts, src/translations/dictionary.ts, src/translations/screens/Nearby.ts, src/translations/screens/TripSearch.ts
Moved the geoLocationContext inside the appLanguangeProvider
=> fix: Norwegian text when English language selected in travel search details

src/chat/ContactSheet.tsx, src/chat/use-chat-icon.tsx, src/translations/components/ScreenHeader.ts, src/translations/screens/subscreens/ContactSheet.ts
Found that the contact sheet had no design in figma when looking into status disruption. Designed with øyvind in figma and applied the changes. Also fixed so that the chatIcon uses the correct notification. 
[Figma](https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/01.-Components?node-id=4632-15731&t=csb2PQqfPviugacR-4)
=> fix: ui changes to contact sheet and correct notification icon on chat

src/travel-details-screens/DepartureDetailsScreenComponent.tsx
Wrap header content on departure details
https://github.com/AtB-AS/kundevendt/issues/3679#issuecomment-1539913245
=> fix: Fix departure details header wrap

src/components/parallax-scroll/ParallaxScroll.tsx
The VoiceOver on the parallex scroll content was messed up because
of absolute positioning not making it clear the navigation order of
the components. By wrapping the parallax scroll children in a View
and placing the top padding there, VoiceOver behaves correctly.
Fixes:
https://github.com/AtB-AS/mittatb-app/pull/3509#issuecomment-1541390219
=> fix: Screen reader with parallax scroll

src/configuration/FirestoreConfigurationContext.tsx, src/reference-data/types.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/use-offer-defaults.ts
This change allows us to configure the default tariff zone using the Firestore configuration. This has already been implemented in the webshop as NFK and FRAM do not want the default tariff zone to be the first from the list of tariff zones. 
The order for selecting a tariff zone is 
geolocation > default tariff zone from Firestore configuration > first tariff zone in the list of tariff zones.
Closes https://github.com/AtB-AS/kundevendt/issues/3659
=> feat: configurable default tariff zone

src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketSummary/TicketSummary.tsx, src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketSummary/utils.ts
Some code cleanup and now calculates savings like this:
1. If the recommended ticket's duration is longer than the user's specified duration, we should compare it with the specified period.
2. If the recommended ticket lasts shorter than the specified period, we should compare it with the ticket's duration.
=> Fix: wrong calculations in ticket summary of ticket assistant

src/stacks-hierarchy/utils.ts
When a cards shown expire date on the card is shown as 01.2024, it is valid thru the entire month of January and the expire date is technically 02.2024(this is how we store it).  I would say this is the correct way to store the expire date, and a simple fix is to do as I have done, subtract one month when getting the string to show.
=> fix: wrong expiry date shown on payment card

src/reference-data/types.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ZonesSelection.tsx, src/stacks-hierarchy/Root_PurchaseTariffZonesSearchByMapScreen.tsx, src/stacks-hierarchy/navigation-types.ts
Closing https://github.com/AtB-AS/kundevendt/issues/3946
Makes three day ticket at NFK only selectable in a single zone using a `isApplicableOnSingleZoneOnly` flag that exists in the code from before (but not on the referenceData).
=> feat: add single zone flag on referenceData

src/stacks-hierarchy/Root_TicketAssistantStack/navigation-types.ts
Fixes tsc error from https://github.com/AtB-AS/mittatb-app/pull/3520
Error in question: https://github.com/AtB-AS/mittatb-app/actions/runs/4977991584/jobs/8907818405#step:8:5
=> fix: add missing preAssigned-type in route param

src/place-screen/hooks/use-departures-data.ts
Fix issue with departures only showing up to 3 hours in advance. Also fix unexpected behaviour where we get more or less departures by switching between days.
Close https://github.com/AtB-AS/kundevendt/issues/3983
=> fix: Show departures more than 3 hours in the future

android/gradle.properties, src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_CategoryPickerScreen.tsx
Now opens the default traveller in category selection in the ticket assistant.
With student as default: 
Adresses: https://github.com/AtB-AS/kundevendt/issues/3917#issuecomment-1549178307
=> fix: use default traveller in ticket assistant

src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketSummary/TicketSummary.tsx
When the input duration is shorter than one week, we need to calculate the amount of travels differently.
Addresses: https://github.com/AtB-AS/kundevendt/issues/3917#issuecomment-1549521933
=> fix: Savings calculation for duration under 1 week

src/anonymous-purchase-consequences-screen/components/Actions.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
There were inconsistencies in the use of interactive colors on the filter menu, whereas one used interactive_0 and the other _1. This makes it consistent. It doesn't look like it affects AtB in any way.
Fixes https://github.com/AtB-AS/kundevendt/issues/3930
=> fix: Correct filter outline color for NFK app

src/translations/screens/subscreens/TicketTraveller.ts
I've removed the bike and night bus references in the traveler descriptions for FRAM. 
Fixes https://github.com/AtB-AS/kundevendt/issues/4053
=> fix: remove incorrect traveler description texts for FRAM

src/translations/screens/subscreens/PurchaseOverview.ts
24hr tickets are to be used on trains in the same way as period tickets. It was also decided together with @oyvindmikkelsenatb and @Sebstorvik that the single tickets should get the same text
=> fix: Correct info text about trains on 24hr ticket

src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistantContext.tsx, src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketAssistant_SummaryScreen.tsx
Added the close button to the error screen swell after suggestion from @tormoseng.
Also made it so that loading is true by default, incase a user swipes thru very fast. If not it will show the summary screen before starting the load.
=> fix: add close button to error screen in assistant

src/stacks-hierarchy/Root_FareContractDetailsScreen.tsx
Currently the notice "Periodebilletter i sone A kan også brukes på tog i sone A" is shown for FRAM's "fylkesbilletter". This is because these travel rights don't have any zones and the `shouldShowValidOnTrainNotice`-check returns true. I've updated it to handle travel rights where the `tariffZoneRefs` is an empty array. 
Fixes https://github.com/AtB-AS/kundevendt/issues/4077
=> fix: remove train notices for FRAM

src/utils/date.ts
Force " " as conjunction char instead of default ","
No comma between "3 t" and "31 min":
=> Fix: Remove comma from trip details time

src/translations/components/CityBoxMessage.ts
Closes: https://github.com/AtB-AS/kundevendt/issues/4062
=> fix: City box message translations were inverted NO in ENG

src/api/index.ts, src/remote-config.ts, src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx
closes https://github.com/AtB-AS/kundevendt/issues/3687
- Shows a gray icon when the data is more than 10 seconds old (not sure if this is the correct threshold, it does appear quite often when the update frequency also is 10s)
- Shows a red icon when the websocket is disconnected.
- Shows a spinner when the websocket is connecting. (This doesn't actually appear in practice for me, since the websocket seems to connect very quickly, but I guess it could happen on slower phones)
<div>
</div>
https://github.com/AtB-AS/mittatb-app/assets/1774972/8859697f-38df-41a6-8624-34bf531a35eb
=> feat: handle live position error states

src/configuration/FirestoreConfigurationContext.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/translations/screens/Profile.ts
Closes https://github.com/AtB-AS/kundevendt/issues/4004
FRAM would like to have a link to their refund form so I've extended the configurable links with `refundInfo`.
=> feat: refund information link

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/ResultItem.tsx
Fixing bug that was created in [this PR](https://github.com/AtB-AS/mittatb-app/pull/3588):
> The app is crashing on Android when doing a trip search Steinkjer skole (bus stop place) > Steinkjer stasjon (train stop place) with TypeError: Cannot read property 'realtime' of undefined
=> fix: app crash on walk result in trip search

src/place-screen/hooks/use-departures-data.ts
Seems like this bug was caused by a self triggering useEffect that had a dependency on lastRefreshTime and also updated lastRefreshTime. Since this state handling has been quite brittle in the past as well, I refactored it a bit.
closes https://github.com/AtB-AS/kundevendt/issues/4024
=> fix: update departures focus logic to not cause infinite loops

src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_WelcomeScreen.tsx
https://github.com/AtB-AS/kundevendt/issues/3917#issuecomment-1568409637
> @adriawh Legg på en info (i) for informasjonen rundt at fungerer ikke på båtbillett.
Before:
After:
=> Fix: Add info icon to message about boat tickets in assistant

src/api/getRecommendedTicket.ts, src/stacks-hierarchy/Root_TicketAssistantStack/handle-recommended-ticket-response.ts, src/stacks-hierarchy/Root_TicketAssistantStack/types.ts
To show the correct category of the offered ticket, now using user profile id to be able to match correctly. Changes also done to endpoint in Atb-ticket.
Example:
The assistant used to show military 180 day ticket, but this should be adult as 180 military does not exist.
=> fix: Use user profile id in ticket assistant

.github/workflows/build-store-android.yml, .github/workflows/build-store-ios.yml
this reverts parts of 278855eeff7eb1d733d9e03817a30952baab82ae
Since the addition of FRAM to store github actions build, I'm reverting those changes from 278855eeff7eb1d733d9e03817a30952baab82ae
=> revert: remove fram from store build

package.json, src/remote-config.ts, src/stacks-hierarchy/Root_OnboardingStack/Onboarding_AlsoGoodToKnowScreen.tsx, src/stacks-hierarchy/Root_OnboardingStack/Onboarding_GoodToKnowScreen.tsx, src/stacks-hierarchy/Root_OnboardingStack/Root_OnboardingStack.tsx, src/stacks-hierarchy/Root_OnboardingStack/navigation-types.ts, src/translations/screens/Onboarding.ts, yarn.lock
FRAM would like to have some additional information in the app's onboarding to communicate the differences between the current app and the new one. I decided to use remote config to enable this. 
Before merging we need to release a new version of @atb-as/generate-assets and upgrade the dependency because of new illustrations (https://github.com/AtB-AS/design-system/pull/135). This will fix the tsc error.
<details>
</details>
Closes https://github.com/AtB-AS/kundevendt/issues/4066
=> feat: new onboarding screens

.github/workflows/build-store-android.yml, .github/workflows/build-store-ios.yml
When taking out a release candidate for 1.37 the GitHub action exited when it should not have (https://github.com/AtB-AS/mittatb-app/actions/runs/5144679993/jobs/9261277315). Johannes reverted the change I made (https://github.com/AtB-AS/mittatb-app/pull/3618/files) so that AtB and NFK could do a release. 
We believe the problem was caused due to a formatting error as the check in itself looks good. It seems that it's not necessary to use the operator `>`, so I think we should test without it. 
Ref: https://github.com/orgs/community/discussions/25641#discussioncomment-3248574
Fixes https://github.com/AtB-AS/kundevendt/issues/4176
=> build: fix build-store bug

.eslintrc.js, src/components/location-icon/LocationIcon.tsx, src/components/location-icon/index.ts, src/components/location-icon/utils.ts, src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationResults.tsx, src/stacks-hierarchy/Root_LocationSearchByTextScreen/index.ts, src/stacks-hierarchy/Root_LocationSearchByTextScreen/utils.ts
In general I don't think any files outside of stacks-hierarchy
should import anything from stacks-hierarchy. For now just turn
this on for the components folder.
No testing necessary
=> refactor: Add eslint rule for import from stacks-hiearchy

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/Travellers/SingleTravellerSelection.tsx, src/translations/screens/subscreens/TicketTraveller.ts
Closing https://github.com/AtB-AS/kundevendt/issues/4174
Ensuring that Nordland can have separate age limits for Travel Pass Nordland that is going into sale with 1.37.
Code is checking if there's an override available for the given product type (only entered for travel-pass type), and returning descriptions as before if not.
=> feat: override passenger category texts for special products

src/api/client.ts
Doesn't look like this will actually change anything in practice, since the `config.retry` field defaults to undefined / falsy, and I don't think it is set to true anywhere at the moment. But disabling retries entirely on 429 (Too Many Requests) is nice to have for the future.
closes https://github.com/AtB-AS/kundevendt/issues/3978
=> feat: disable retries on 429 responses

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
When dragging down to refresh on the trip search screen, the search
was not refreshed if a departure or arrival time was chosen. This is
fixed by recreating the search time object on refresh so the search
useEffect triggers.
=> fix: Pull to refresh on trip search

src/service-disruptions/ServiceDisruptionSheet.tsx
Fixes issue found when testing https://github.com/AtB-AS/kundevendt/issues/4141
I believe we've been using the wrong interactive color for the status message button. I guess this hasn't been noticed as it works for AtB. This is what it currently looks like for FRAM:
This can be fixed by changing this to interactive_2 which is used for the contact button. This changes nothing for AtB and solves the issue for NFK/FRAM. See screenshots: 
<details>
AtB
NFK
FRAM
</details>
=> fix: status message button color

package.json, yarn.lock
Fixed the image sizing of TravelPlanning to reduce the overall height so that the Next button is visible again.
Fixes https://github.com/AtB-AS/kundevendt/issues/4216
=> chore: Update @atb/generate-assets to fix image size

src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx, src/travel-details-map-screen/components/DirectionArrow.tsx
resolves https://github.com/AtB-AS/kundevendt/issues/3688
Turn ShapeSource circle into a MarkerView instead. This syncs the movement of the bus icon, arrow and the circle, following this comment from @HanneLH in https://github.com/AtB-AS/kundevendt/issues/3688#issuecomment-1594148006_
=> fix: Draw live bus position circle icon as MarkerView

.github/workflows/build-staging-android.yml
When registering Android app versions the newest build overwrites
the old one. Meaning only one build, the newest, will be able to
create and renew mobile tokens.
In staging this is a problem since we have such frequent builds,
and it will be a chore to always ensure to be on the newest build
when testing something related to mobiletoken or ticketing in
general.
We asked Entur, and they said in staging it was ok to do the same
as is done in dev, that every Android build has the same value for
the build id. This means that all staging builds on the same app
version should keep working after new builds.
=> build: Fixed build id when registering Android app version

src/AppContext.tsx, src/stacks-hierarchy/Root_MobileTokenOnboarding/utils.ts
After login in there was a race condition between the navigation
done by the login screen and the navigation to the mobile token
onboarding. This is fixed by only redirecting to the mobile token
onboarding when the TabNavigator is actually focused.
=> fix: Fix after login onboarding race condition

src/translations/screens/subscreens/TripDetails.ts, src/travel-details-screens/components/DetailsMessages.tsx, src/travel-details-screens/utils.ts
Closes https://github.com/AtB-AS/kundevendt/issues/4067
This PR adds a new message to be displayed for travels with short wait times and no guaranteed correspondence. The message will be displayed in addition to the already existing message about the short wait time. This change is specific to FRAM's needs, and I've used org-specific translations for the message.
<details>
</details>
=> feat: add message for travels with short wait times and no guaranteed correspondence

.github/workflows/build-store-android.yml, .github/workflows/build-store-ios.yml
These changes were overwritten when merging the branch `release/1.37` back to the master branch (https://github.com/AtB-AS/mittatb-app/commit/b42353a3e4d941d3f95f6e7d9b33759bdec592b4).
=> build: add FRAM to github action matrix

src/fare-contracts/components/InspectionSymbol.tsx
_Edited_
I've removed the zone names from the inspection symbol if the zone names have more than 3 characters. This is to ensure that we don't experience what is seen in the image below, and still keep it the as today for AtB. The designers will look into how we can make it consistent for all organizations. 
<details>
<summary>Original description</summary>
I've removed the zone names from the inspection symbol according to the new Figma sketch (See the issue for reasoning (https://github.com/AtB-AS/kundevendt/issues/4160)): 
</details>
Fixes https://github.com/AtB-AS/kundevendt/issues/4160
=> fix: inspection symbol for zone names with length greater than 3 characters

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByProducts.tsx, src/translations/screens/Onboarding.ts, src/translations/screens/subscreens/MobileTokenOnboarding.ts
*App onboarding:*
- Slide 1: «Flere funksjoner og billetter blir lagt til jevnlig!»
Fjernet «og billetter» 
- Slide 2: «…reise, og en korrespondanse …»
Endret til «…reise. En korrespondanse …»
- Slide 3: «…Du kan altså kjøpe…»
Fjernet «altså» 
*Mobile token onboarding*
Slide 3: «Billetten din er trygt lagret på Min bruker.».
Endret til «Billetten din er trygt lagret på din konto i skyen.»
Closes https://github.com/AtB-AS/kundevendt/issues/4273
=> fix: Update texts on onboarding screens

src/stacks-hierarchy/Root_LoginConfirmCodeScreen.tsx, src/stacks-hierarchy/Root_LoginPhoneInputScreen.tsx
Noticed that the loading indicator spinner was black on the dark background color on the login screens. Updated to use the text color based on the pages `themeColor` setting.
Clarified with @oyvindmikkelsenatb
=> fix: improve contrast on login activity indicator

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/RecentFareContracts/RecentFareContractComponent.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/use-recent-fare-contracts.ts
The traveller order should be based on user profile order, but it
was overwritten by some redundant sorting code.
Before/After:
<div>
</div>
=> fix: Traveller order in recent tickets

src/stacks-hierarchy/Root_PurchasePaymentWithCreditCardScreen/use-terminal-state.ts, src/stacks-hierarchy/Root_PurchasePaymentWithVippsScreen/use-vipps-state.ts, src/ticketing/api.ts, src/ticketing/types.ts
In march, when implementing sub accounts, it was added a field
´customer_account_id´ in the reserve offer endpoint, which also
was added to the reservations in Firestore.
It was added code in the app to check that a reservation has the
correct customer account id, however it was not added code to
set the customer account id when reserving a offer. As such no
reservations created from the app showed up in the app.
Sending in customer account id when reserving offer.
=> fix: Set customerAccountId on reserveOffer

src/api/use-subscription.ts, src/api/vehicles.ts, src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx
Updates websocket logic to rely on onClose events instead of onError, since they provide status codes, and doesn't of arbitrarily failing on reconnects on android. `useSubscription`s onclose now returns an `isError` field based on expected status codes from https://www.rfc-editor.org/rfc/rfc6455.html#section-7.4
Resolves comment https://github.com/AtB-AS/kundevendt/issues/4213#issuecomment-1607173946
closes https://github.com/AtB-AS/kundevendt/issues/4236
=> fix: update websocket error handling to use onClose events

src/departure-list/section-items/line.tsx
The issue where the next day's departure shows as "now" in favorite departures is most likely because the service journey ID is the same for these two and therefore the key for the component is the same. To solve this, I've added the aimed time to the key, as is done for the other components. 
An example of this issue can be seen in the following screenshot, where two of the departures marked as "now" is planned to leave the following two days. 
Fixes https://github.com/AtB-AS/kundevendt/issues/4277
=> fix: departure time in favorite departures

src/reference-data/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DefaultUserProfileScreen.tsx
Part of https://github.com/AtB-AS/kundevendt/issues/4225
Hiding userProfiles with flag `hideFromDefaultTravellerSelection` from default traveller category selection. 
Used at FRAM for hiding userProfiles only associated with certain products on the authority endpoint.
<details>
Before:
Now:
</details>
=> feat: hide certain default traveller profiles

ios/atb.xcodeproj/project.pbxproj
Closes: https://github.com/AtB-AS/kundevendt/issues/4243
A build was made on: https://github.com/AtB-AS/mittatb-app/actions/runs/5357274058/jobs/9717917636
```
Version 1.39 (1687529871)
Jun 23, 2023 at 17:44
18.19 MB
```
No files were exposes any more after `unzip` the `.ipa`, App seems to work as before, but must be fully tested to confirm this.
=> fix: Remove the build file from being embedded in the Apple IPA

src/departure-list/utils.ts, src/sdk.ts
To prevent us from updating the wrong departure in favorite departures with real-time data for another departure, I've added a check on `aimedDepartureTime`. This change was necessary because departures have the same `serviceJourneyId`, which caused the app to update the wrong departure in the user's favorite departures list. 
See https://github.com/AtB-AS/atb-bff/pull/279 for necessary changes to the bff. 
Closes https://github.com/AtB-AS/kundevendt/issues/4277
=> fix: updating the wrong departure in favorite departures with realtime data

src/chat/use-chat-icon.tsx, src/components/bottom-sheet/BottomSheetContext.tsx, src/components/map/hooks/use-update-bottom-sheet-when-selected-entity-changes.tsx, src/components/sections/items/GenericClickableSectionItem.tsx, src/favorites/use-on-mark-favourite-departures.tsx, src/place-screen/components/DateSelection.tsx, src/service-disruptions/use-service-disruption-icon.tsx, src/situations/use-situation-bottom-sheet.tsx, src/stacks-hierarchy/Root_AddEditFavoritePlaceScreen/Root_AddEditFavoritePlaceScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/StartTimeSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravellerSelection.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/DeparturesWidget.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/use-travel-search-filters-state.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_NearbyStack/Nearby_Root.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
Resolves https://github.com/AtB-AS/kundevendt/issues/4714
Return onOpenFocusRef and onCloseFocusRef in BottomSheetState, remove close from contentFunction.
Bonus: no longer using setTimeout for giveFocus.
Also provides onCloseFocusRef to GenericClickableSectionItem which fixes the specific case of returning from traveller selection.
=> chore: bottom sheet focus improvements

src/components/bottom-sheet/BottomSheetContext.tsx, src/utils/use-focus-on-load.ts
resolves https://github.com/AtB-AS/kundevendt/issues/4714
Timeouts were replaced in https://github.com/AtB-AS/mittatb-app/pull/3702 with InteractionManager.runAfterInteractions, however causing https://github.com/AtB-AS/kundevendt/issues/4714#issuecomment-1619874411.
Fixed by adding a small timeout in giveFocus for the screen reader when the bottomSheet closes.
=> fix: add optional timeout in giveFocus

src/components/beta-tag/BetaTag.tsx, src/components/beta-tag/index.ts, src/components/info-tag/InfoTag.tsx, src/components/info-tag/index.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Assistant/TicketAssistantTile.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTile.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTileIllustration.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductIllustration.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductTile.tsx
closes https://github.com/AtB-AS/kundevendt/issues/3363
This updates the design of the TicketAssistantTile.
Also TicketingTile.tsx was created, shared by both FareProductTile and TicketAssistantTile, as [suggested](https://github.com/AtB-AS/mittatb-app/pull/3710#issuecomment-1623166177).
Turned FareProductIllustration into TicketingTileIllustration.
Also updates the BetaTag design.
Before:
<br /><br />
After:
<br />
=> feat: update ticket assistant tile design

src/fare-contracts/components/FareContractDestinations.tsx, src/translations/screens/subscreens/PurchaseOverview.ts
closes https://github.com/AtB-AS/kundevendt/issues/4138#issuecomment-1630723842
Reads out "From 'A', to 'B'" with the screen reader when selecting the destinations.
=> feat: add a11y label to destinations container

src/reference-data/defaults/preassigned-fare-products.json
Update reference data to match firestore data that fixes bug where you cannot pick duration on period boat tickets
https://github.com/AtB-AS/firestore-configuration/pull/224
https://github.com/AtB-AS/kundevendt/issues/4044
=> chore: Update preassigned fare products for boat tickets

src/fare-contracts/components/InspectionSymbol.tsx, src/reference-data/defaults/fare-product-type-config.json, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/CompactFareContracts.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTile.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTileIllustration.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductTile.tsx
Update front page ticket view to show correct transport icon and color
https://www.figma.com/file/XdptDDbXUrO2Phz4NWfgdi/Boat-tickets?type=design&node-id=607%3A24834&mode=design&t=xpsDPVj4UaiKJdTo-1
Updating illustration to "boat-period" for boat period ticket:
https://github.com/AtB-AS/firestore-configuration/pull/226
=> fix: Use correct illustration on front page ticket

src/components/text/ThemeText.tsx, src/stacks-hierarchy/Root_ActiveTokenOnPhoneRequiredForFareProductScreen.tsx
Closes: https://github.com/AtB-AS/kundevendt/issues/4051
This PR fixes:
1. Move the information about all active tickets to mobile before the "Switch to phone" button
2. With screen reader, after choosing a device as bearer, the focus now jumps to the header. The focus should here remain on the chosen bearer - to allow the user to focus down and read the "warning" before making the switch.
=> fix: Accessibility for set active token to phone

src/translations/types.ts, src/translations/utils.ts, src/utils/map-to-language-and-texts.ts
In order to support nynorsk in features like global messages, this adds checks for "nn" and "nno" in `getTextForLanguage`, and adds "nno" as an allowed language in `mapToLanguageAndText` (global messages).
This also applies to things like disruption messages from journey planner, but I don't know if there are any messages in nynorsk, so I don't think we're able to test it.
fixes https://github.com/AtB-AS/kundevendt/issues/5935
=> feat: support Nynorsk `LanguageAndTextType`

src/translations/screens/subscreens/TripDetails.ts, src/travel-details-screens/components/TripSection.tsx
Adds duration, e.g. "Sykle i 3 minutter" to a bicycle leg, similar to what's done for walking legs.
From findings during testing of https://github.com/AtB-AS/kundevendt/issues/7198
=> fix: Add duration to bicycle leg

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/HarborSelection.tsx
Set to-harbor to disabled for screenreader when no from-harbor is selected
https://github.com/AtB-AS/kundevendt/issues/4137
=> fix: Set disabled state for screenreader

src/configuration/FirestoreConfigurationContext.tsx, src/fare-contracts/FareContractInfo.tsx, src/fare-contracts/components/FareContractHarborStopPlaces.tsx, src/reference-data/types.ts, src/translations/screens/FareContract.ts
Reuse the harbors query to fetch harbor names from Entur, instead
of using Firestore.
=> refactor: Harbor names from Entur in ticket purchase flow

src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
It seems that there is a native iOS bug when the spinner refreshing
state is always set to false. 
The issue was (hopefully) fixed this by "resetting" the refresh control by removing it when screen is out of focus.
=> fix: Spinner stuck on iOS

src/utils/date.ts
Closing https://github.com/AtB-AS/kundevendt/issues/5989.
Restructuring use of [humanize-duration](https://www.npmjs.com/package/humanize-duration) to support Nynorsk. 
Features:
- Initializing humanizer object with nynorsk languages provided
- Removing duplicate wrongly defined Bokmål and English (if these had been used, single units would have been plural e.g. 1 days / 1 minutter)
- Using initialized humanizer instead of calling "humanizeDuration" directly
Also considering adding a PR to the library so we can remove all the nynorsk specific stuff, but guess that will take some time to have approved.
=> feat: nynorsk duration humanizer

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/HarborSelection.tsx
closes https://github.com/AtB-AS/kundevendt/issues/7367
The ref used to focus the screen reader when returning from a boat harbor selection, is now set according to which selection you just set (from or to).
=> fix: boat ticket screen reader focus fix

src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/translations/screens/subscreens/PurchaseOverview.ts, src/translations/screens/subscreens/TravelToken.ts
- Fix a couple of words in some translations
- Don't render summary if the text is empty. This is to not show the text regarding a ticket being valid for bus/tram.
Closes https://github.com/AtB-AS/kundevendt/issues/7804
=> fix: Fix translations for FRAM

ios/Podfile, ios/Podfile.lock, package.json, react-native.config.js, yarn.lock
Solution based on:
https://reactnative.dev/docs/next/speeding-ci-builds#:~:text=Flipper%20is%20a%20debugging%20tool,built%20in%20the%20CI%20environment.
https://dev.to/retyui/disable-flipper-on-ci-builds-for-react-native-complete-guide-bnd
=> chore: Fix flipper in CI

src/preferences/types.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductDescriptionToggle.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/ProductSelectionByProducts.tsx, src/translations/screens/subscreens/PurchaseOverview.ts
Added a toggle button, same (similar) as the one used for traveller selection previously (removed in https://github.com/AtB-AS/mittatb-app/pull/3657). The button is added only for products with `productSelectionMode: product`, which is only a few of the products. This is mainly affecting FRAM which has a couple of products of this kind, AtB/NFK mostly has the night ticket.
Fixes https://github.com/AtB-AS/kundevendt/issues/4223
=> feat: Add toggle button for product description

android/app/src/staging/java/no/mittatb/ReactNativeFlipper.java
ReactNativeFlipper requires a stub for every environment. We have special case where we have added staging build target, which is compiled to QA. This adds stub to that build target also
=> fix: adds staging flipper in addition to release

android/app/build.gradle
Seems like some of the settings that was removed while upgrading React Native is needed to run properly. This readds them
=> chore: readds removed react settings

src/index.tsx
In debug, we get the warnings "`new NativeEventEmitter()` was
called with a non-null argument without the required
`removeListeners` method.
Doing this will make those errors not pop up as warning boxes in
the app. They will still appear in the console.
=> chore: LogBox ignore new NativeEventEmitter warnings

android/app/src/store/java/no/mittatb/ReactNativeFlipper.java
This adds ReactNativeFlipper empty stub for the last build variant (store). Required for building store bundles
=> fix: adds store flipper stub

src/AppContext.tsx, src/RemoteConfigContext.tsx
The force refresh of RemoteConfig should no longer be necessary, as
it was mainly for development before we got the button for
refreshing it in the debug menu.
In addition the remote config force refresh created a full remount
on every app startup, creating significant wait time with just
a blank screen.
=> feat: Remove Remote Config force refresh

src/suppress-pass-presentation/index.ts
Fixes fare contract details screen from crashing on Android because of calling iOS native functionality.
=> fix: android error because of apple pass suppression

src/api/use-subscription.ts, src/api/vehicles.ts, src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx
There is some newly introduced issue in later React Native that forces Android Websocket connection to close after 30 sec (1006 error). Currently can't find the cause of this issue, but we are able to immediately reconnect. This issue becomes very apparent to the client by the fact that there are stale functions used in `useSubscription` causing the disconnected indicator in the live map _not_ to be updated.
There are apparently cases from before where the client times out by design. I don't think this is that, but as it is already by the design the negative effect of Java WebSocket bug isn't as critical and the workaround with reconnecting is fine I think. Not ideal, but fine.
This PR:
- Fixes error indicator not updating after reconnect for `useSubscription`
- Introduces a delay on the …
=> fix: resetting disconnect icon for live vehicles

src/auth/AuthContext.tsx, src/auth/auth-utils.ts, src/auth/types.ts, src/auth/use-check-if-account-creation-finished.ts
I found it was better to change the auth status to retry the
account creation check. By doing it this way the clients doesn't
need to handle clearing timeouts and such.
=> refactor: Small auth changes

Gemfile
The changed comment was outdated. https://rbenv.org is no longer live, and installing with rvm caused issues.
=> fix: update gemfile comment

package.json, src/utils/__tests__/use-interval.test.ts, src/utils/use-interval.ts, yarn.lock
This removes useInterval to remove cases
where useInterval is called infinitely. Rewriting
to setTimeout will only call recursively and not
fill the message queue with as many awaiting
invocations in some cases.
Still not a perfect solution, but will be an improvement.
---
I have tested some locally and started writing some tests for this, but having some issues with fake timers and invocations. We should experiment with the implementations. But feeling the lack of good unit tests in cases like this. I haven't checked out if Detox tests are fixed.
This might also just be reference implementation to show a more elaborate example from what we discussed on Slack @gorandalum and @marius-at-atb .
Trying to debug some I added some logging. There are A LOT of time loops running in the app 😅. …
=> fix: rewrites use-interval to use setTimout

src/stacks-hierarchy/Root_PurchaseHarborSearchScreen/Root_PurchaseHarborSearchScreen.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/7367
When going back from PurchaseHarborSearchScreen, the isFocused + setTimeout focus logic interrupted giveFocus in Root_PurchaseOverviewScreen. See https://github.com/AtB-AS/kundevendt/issues/7367#issuecomment-1700464339
Fixed with giveFocus util instead of setTimeout solution
=> fix: use giveFocus util for setting focus

src/components/transportation-modes/TransportModes.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProductGroup.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/Components/FareProducts/FareProducts.tsx, src/translations/screens/FareContract.ts
Closing https://github.com/AtB-AS/kundevendt/issues/8114
Also fixing that "Other tickets" title had different font size than the transportmode texts, due to being regular ThemeText. 
Please let me know if this is intentional, they seem to have been designed with same size according to [Figma sketches](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=17165-67089&mode=design&t=Z25Fo7tOiaaAc7DH-0).
<details>
<summary>Screenshots - current title difference</summary>
Notice larger font size of "Andre billetter" title in first image
</details>
<details>
<summary>Screenshots - new behaviour</summary>
</details>
=> feat: add support for custom fareproductgroup heading

src/stacks-hierarchy/Root_OnboardingStack/use-finish-onboarding.ts
Tor Kjetil found a bug where the onboarding was triggered at app startup even though the user had finished the onboarding.
The reason was that the storage of the "has_onboarded" flag did not always happen, as
the `useFinishOnboarding` hook had unmounted. This was now changed
to a more simple logic:
- Set onboarded to true
- Then fire the request for geolocation
=> fix: Onboarding triggered multiple times

src/stacks-hierarchy/RootStack.tsx
We see some strange effects of rendering the NavigationContainer
when there is no navigators to render. This was changed by moving
the LoadingScreenBoundary outside of the NavigationContainer.
=> refactor: Move LoadingBoundery

src/analytics/types.ts, src/loading-screen/LoadingErrorScreen.tsx
[This comment](https://github.com/AtB-AS/kundevendt/issues/4157#issuecomment-1708190735) from Tor:
> @gorandalum Would it be possible to add an event to BugSnag or PostHog when a user enters the Try again screen? And possibly also on the Try again button itself? @Sebstorvik would really like to know how many users are affected by the missing claims.
=> feat: Add analytics for loading boundary error

src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
Adding/removing RefreshControl based on focus gives odd behaviour
on Android where the scroll offset is lost after navigating.
The adding/removing of RefreshControl was added to fix a stuck
spinner on iOS issue, but this doesn't seem to still happen after
updating react-native versions. So the fix for now is to remove
the stuck spinner fix.
The original fix was implemented here:
https://github.com/AtB-AS/mittatb-app/pull/3762
Based on the behaviour in this comment:
https://mittatb.slack.com/archives/C0116FMPX4Y/p1691563608147469
=> fix: Remove spinner stuck fix

src/components/sections/items/date-input/DateInputSectionItem.ios.tsx, src/components/sections/items/date-input/utils.ts, src/reference-data/types.ts, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/StartTimeSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravelDate/TravelDateSheet.tsx, src/translations/screens/subscreens/TravelDate.ts
Closing https://github.com/AtB-AS/kundevendt/issues/8388
Adding option to provide limitation to a product in the referenceData, where `latestActivationDate` is provided as a string given by epoch time. Tested with FRAM Buss Vaksen, having latest day of activation 31st of October 23:59:59. 
Will be part of FRAM 1.41 on a separate release branch and AtB 1.42. (No plans to use for AtB AFAIK)
=> feat: add latest activation date option to datepicker

src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx
[Removing it](https://github.com/AtB-AS/mittatb-app/pull/3855) did actually reintroduce the stuck spinner on iOS bug.
Now just reenabling the previously removed hack, but now just for
iOS.
=> fix: Readd stuck spinner on iOS fix

src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx
> If the bus is in focus, and you press the 'My Location' button on the map, the focus shifts slightly to your position before returning to the bus again. This is related to the 'Touch event.'
>If you have shifted the focus away from the bus on the map and then choose to click on 'My Location,' this issue does not occur.
Fixed by removing tracking when pressing position arrow
=> fix: Stop tracking bus when selecting user position 

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Assistant/TicketAssistantTile.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx
Adds some missing padding below ticket tiles
=> fix: add margin to bottom of PurchaseTabScreen

yarn.lock
In [this merge](https://github.com/AtB-AS/mittatb-app/pull/3842) the yarn lock was missing this change. The old slider was removed in the package.json, but not in the yarn.lock
=> chore: remove old slider in yarn.lock

src/mobility/utils.ts
Ryde has changed form factor from SCOOTER to SCOOTER_STANDING. We need to treat both these form factors as scooters.
Closes https://github.com/AtB-AS/kundevendt/issues/8649
=> fix: Support scooter standing

src/translations/screens/Onboarding.ts
Update to the onboarding text for FRAM: 
I've removed the text about purchasing a ticket more than 48 hours in advance. 
Closes https://github.com/AtB-AS/kundevendt/issues/8825
=> feat: new onboarding text for FRAM

.github/workflows/build-staging-android.yml, .github/workflows/build-staging-ios.yml, .github/workflows/build-store-android.yml, .github/workflows/build-store-ios.yml, .github/workflows/lint.yml, .github/workflows/test-e2e-ios.yml, .github/workflows/tsc.yml
Entur registry token expires after a year. To give less work when they
expire we have moved the ENTUR_REGISTRY_USER and
ENTUR_REGISTRY_TOKEN to the organizational level in GitHub. Also
the ENTUR_REGISTRY_USER is now a variable instead of secret, so it
can be read.
=> chore: ENTUR_REGISTRY_USER from org vars

src/fare-contracts/details/DetailsContent.tsx, src/global-messages/types.ts, src/stacks-hierarchy/Root_FareContractDetailsScreen.tsx, src/translations/screens/FareContract.ts
closes https://github.com/AtB-AS/kundevendt/issues/7512
Adds a `app-fare-contract-details` global message context, replacing the last hard coded collab ticket messages in the app 🎉  (But some "from travel search to ticketing" logic still remains)
=> feat: add app-fare-contract-details global message context

src/components/screen-header/ScreenHeader.tsx, src/place-screen/PlaceScreenComponent.tsx, src/place-screen/components/StopPlaceAndQuaySelection.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_MapStack/Map_RootScreen.tsx
I've noticed there are several places where the header takes up more space than it should according to the sketches. Tried to clean up that here:
- Reduces header margin to 12px/medium instead of large, as that's what's used in [the sketches](https://www.figma.com/file/2QTjAdekdIPuLFovQhVrY3/Components?node-id=4383%3A8566&mode=dev) 
- This also adds a bit of bottom sheet specific code to give it more padding, that will probably be replaced by https://github.com/AtB-AS/kundevendt/issues/4211
- Makes the status bar on android transparent, fixing some contrast issues, and utilizing more of the screen.
- Removes a bit of padding above the StopPlace/Quay selector on departures
=> fix: various header fixes

.github/workflows/build-store-android.yml
We are having trouble with the AppCenter integration:
https://mittatb.slack.com/archives/C02EEG7D8EL/p1695204736271979?thread_ts=1695200240.568439&cid=C02EEG7D8EL
But for the store build AppCenter is an unnecessary middle step, so we'll
try sending it directly to Google Play like NFK and Fram does instead.
=> chore: Distribute APK directly to Google Play

src/fare-contracts/details/DetailsContent.tsx
Since the collab ticket only applies to tickets that are just in zone A, and not e.g. from A to B1, we need to check that numberOfZones == 1 when showing the message.
fixes https://github.com/AtB-AS/kundevendt/issues/7512#issuecomment-1729336551
=> fix: add numberOfZones as fare contract details ruleVariable

src/components/sections/items/TextInputSectionItem.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx
As part of https://github.com/AtB-AS/kundevendt/issues/4275, we need to support error state for TextInputSectionItems.
Implemented to look like this:
=> feat: added support for errorText

src/components/sections/items/date-input/DateInputSectionItem.ios.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/Root_PurchaseOverviewScreen.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/StartTimeSelection.tsx, src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/TravelDate/TravelDateSheet.tsx, src/translations/screens/subscreens/TravelDate.ts
Closing https://github.com/AtB-AS/kundevendt/issues/8886
Based on suggestion from https://github.com/AtB-AS/mittatb-app/pull/3886#issuecomment-1731197343
Enforces `latestActivationDate` also on Android where the `maximumDate` prop is not respected in our datepicker.
If a date later than the latest activation date is entered, a yellow warning `MessageBox` will appear and the submit button will be disabled. These measures are reverted when a valid date before the latest activation date is set, or when a different category / product is selected.
https://github.com/AtB-AS/mittatb-app/assets/21310942/ad92f541-c38d-4419-892b-6bc7c3b97ba0
=> fix: enforce latestActivationDate also on Android

src/stacks-hierarchy/Root_PurchaseOverviewScreen/components/HarborSelection.tsx, src/translations/screens/subscreens/PurchaseOverview.ts
Removes some unnecessary padding from the bottom harbor selection, and updates "harbors" to "harbor" in english.
closes https://github.com/AtB-AS/kundevendt/issues/8878
=> fix: remove unnecessary padding on harbor selection

src/stacks-hierarchy/Root_PurchasePaymentWithCreditCardScreen/Root_PurchasePaymentWithCreditCardScreen.tsx
Fixed by adding keyboardAvoidingView that adapts to the header height on android. If the header height is not adjusted for, the view will not always adapt when keyboard is over input field. 
Before:
https://github.com/AtB-AS/mittatb-app/assets/70323886/bac61b89-e749-4a0b-bcac-0a3c246dd401
After:
https://github.com/AtB-AS/mittatb-app/assets/70323886/1303f2e1-f64b-464e-bf10-cdecaf5401ba
Still works as intended on iOS:
https://github.com/AtB-AS/mittatb-app/assets/70323886/de737740-bf5d-4efe-9954-a0656bdcc428
=> fix: payment webView not scrollable on android

src/fare-contracts/details/Barcode.tsx, src/mobile-token/MobileTokenContext.tsx, src/remote-config.ts
I've added a new RemoteConfig prop defaulting to 0 so we can opt-in on the timeout behavior: `token_timeout_in_seconds`. If this is 0 timeout will always be false.
This feature adds a timeout flag to the token context. It does not stop the execution of the code, as I think that is hard to stop the execution flow like this and I don't think it is favorable either. So the logic here is to have a timeout mechanism that marks the loading as timed out and if it proceeds afterwards it will unmark it as timed out making it proper again.
I've also added a BugSnag notification when the timeout handler is invoked. This will allow us to see how often this happens and all the breadcrumbs that the token SDK cases will get posted to BugSnag. Hopefully, we'll get more context and information on what is …
=> feat: adds timeout notification for token and fallback to static aztec

.github/workflows/build-staging-android.yml, android/app/build.gradle, android/build.gradle, android/gradle.properties, ios/Podfile.lock
Enable a force build option for Android in staging.
Also, when building the Android app, the warning "Detected multiple Kotlin daemon sessions at build/kotlin/sessions" is fixed by specifying a kotlin version. See https://github.com/facebook/react-native/issues/33488
=> fix: specify kotlin version, enable force build option

src/loading-screen/LoadingScreenBoundary.tsx
=> fix: Retry auth no longer done on outdated state

src/components/sections/SectionSeparator.tsx
One for the pixel-peepers 🧐:
Since most places where sections are used are on a background_2 color, I'm updating the SectionSeparator to look more correct in the places we use it today, and with slightly more contrast.
=> fix: update section separator color

src/components/empty-state/EmptyState.tsx, src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx, src/nearby-stop-places/components/StopPlaces.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/Results.tsx, src/theme/ThemedAssets.tsx, src/translations/screens/Nearby.ts, src/translations/screens/TripSearch.ts
Closes https://github.com/AtB-AS/kundevendt/issues/7302
When no nearby stop places are found:
When no trip search results are found:
Note: Following discussion with @ckbilstad, renaming the OnBehalfOf illustration will be addressed together with other renaming issues later. Also even though both OnBehalfOf svgs are identical at the moment, it is expected to have an updated dark mode version.
=> feat: handle empty state for searches

CONTRIBUTING.md
Based on observations of "chore: " being used as a type in changelogs, I suggest including it in our file for contributions. It is even part of the example below in the file 🙈 
This is based on the description of conventional commits: https://github.com/commitizen/conventional-commit-types/blob/master/index.json
=> docs: add chore as a changelog type

ios/Podfile.lock, package.json, src/fare-contracts/details/Barcode.tsx, src/stacks-hierarchy/Root_FareContractDetailsScreen.tsx, yarn.lock
Fixes https://github.com/AtB-AS/kundevendt/issues/9404
This _SHOULD_ adjust brightness when opening the screen for control to read the QR code better. In many cases the screen is too dark to read properly, and instead of having users adjust it manually we temporary try to adjust brightness when opening screen for inspection.
- This is impossible to test on simulator and emulator. We need to find a way to test this on the device and see if it works and if it is feasible. 
- The dependency used here seems old and not very well maintained. However, there is no other alternative and for now the implementation seems so simple and straightforward that our own implementation would be the same. So reducing administrative overhead and resisting the urge of "not invented here"-isms. I decided to …
=> feat: adds device brightness adjustment on ticket details sreen

ios/atb.xcodeproj/project.pbxproj
Closes: https://github.com/AtB-AS/kundevendt/issues/11303
> NOTE: This PR also upgrades Debug min iOS Version from 12.2 to 12.4 as it was on Release. I didn't find a reason to have it out of synch, if you know one please let me know.
Before:
Now:
=> fix: Remove support for MacOs

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DesignSystemScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx
As we had the "New" label for token toggle has been around for more than a year, let's remove it 👷🏼‍♀️ 
Also added preview of labels in design system 🌟 
Closes: https://github.com/AtB-AS/kundevendt/issues/3928
=> feat: remove label new from token toggle in my pofile

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Assistant/TicketAssistantTile.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/TicketingTile.tsx, src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_FrequencyScreen.tsx, src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_SummaryScreen/TicketSummary/TicketSummary.tsx
[Comment #1](https://github.com/AtB-AS/kundevendt/issues/4240#issuecomment-1756871312)
[Comment #2](https://github.com/AtB-AS/kundevendt/issues/4240#issuecomment-1756876653)
Changes:
- InfoTag on TicketingTile can now be new or beta
- Removed Beta from accessibilityLabel on TicketAssistantTile
- Added line to accessibilityLabel on recommended ticket summary
- Now using track marks for numbers on slider to ensure correct position
Numbers now overflow, but is visible on larger text. Can't move numbers, as they must align with the slider. Was decided that this is better than cutoff with @HanneLH:
=> fix: screen reader and slider on ticket assistant

src/translations/screens/Departures.ts, src/translations/screens/subscreens/FavoriteDepartures.ts, src/translations/screens/subscreens/SelectFavouriteDeparturesTexts.ts
This will not change domain language/code language to be consistent with UK English in regards to favorite vs favourite. And we should discuss if translation language convention is the same as code language. It isn't automatically the same.
This just fixes 3 specific places in translations where it still said favorite.
Fixes https://github.com/AtB-AS/kundevendt/issues/9424
=> fix: fix consistent use of favourite

src/translations/screens/subscreens/PurchaseConfirmation.ts
Tickets not valid on bus. 
Fixes https://github.com/AtB-AS/kundevendt/issues/8894
Only affects NFK
=> fix(nfk): Remove tram/tog for message in harbor zones

src/fare-contracts/details/Barcode.tsx
See the description and problem at https://github.com/AtB-AS/kundevendt/issues/12080
This only changes the size of Static QR (which FRAM also uses for all QRs as of now)
Don't know if there is a specific reason as to why it is small (other than taking a lot of visual space ofc).
Fixes https://github.com/AtB-AS/kundevendt/issues/12080
=> fix: increase qr code size

src/stacks-hierarchy/Root_PurchaseAsAnonymousConsequencesScreen.tsx
When logging in with active tickets we don't show a warning if we navigate using the warning box on the ticket view. This is causing some issues for FRAM where people don't know they'll lose their tickets.
This solves it in the same way as it is solved for login button on Profile page. It doesn't solve the same direct navigation as before if vipps is not activated. Don't know if this is needed?
Also, not an ideal solution as such, you create some nested stacks here that might not seem like an optimal flow. Might also add the warning on the step before showing why you should log in, but this is also kind of odd 🤔
This is just a quick proposal for me and we can discuss if this is the best way to solve it or not.
<details>
<summary>Screen recordings</summary> …
=> fix: shows warning when logging in with active tickets

src/fare-contracts/details/Barcode.tsx, src/translations/screens/FareContract.ts
After more insights into troubles with reading barcodes using the FLV+, I think the problem isn't the size itself, but also that the device isn't able to separate the QR code from the rest on the page. We have reports even that in some cases the barcode is too big.
Also there is problem with the FLV+ on dark mode. So for the bottom sheet here, in addition to increasing screen brightness I set the entire background to white no matter what theme you use.
Users of the existing app for FRAM are used to being able to press the QR code to see it bigger, even though this is kind of a hidden feature here. But there is existing work on improving visual inspection and restructuring this page where the QR code is smaller, so I think this is OK until that feature gets worked on.
I only added the …
=> feat: adds bottom sheet with isolated barcode on barcode press

src/storage/StorageModel.tsx
When debugging errors it is some times helpful to see the values
which were retrieved from local storage.
Also delete some unused storage keys.
=> feat: Log storage value in Bugsnag breadcrumbs

src/auth/index.ts, src/loading-screen/LoadingErrorScreen.tsx, src/loading-screen/LoadingScreenBoundary.tsx, src/loading-screen/__tests__/use-loading-state.test.ts, src/loading-screen/__tests__/use-log-event-on-timeout.test.ts, src/loading-screen/types.ts, src/loading-screen/use-loading-state.ts, src/loading-screen/use-log-event-on-timeout-status.ts, src/loading-screen/use-log-event-on-timeout.ts
The previous code had a subtle bug, where the `isLoadingAppState` and `authStatus` were not in the dependency list of the `useCallback` setting up the timeout. This caused the event logged to PostHog to include the values as they were when the timeout was set up, and not the actual values when the timeout function was executed.
```ts
const setupLoadingTimeout = useCallback(() => {
setDidTimeout(false);
timeoutRef.current = setTimeout(() => {
analytics.logEvent('Loading boundary', 'Loading boundary timeout', {
isLoadingAppState,
authStatus,
});
setDidTimeout(true);
}, 10000);
}, []); // <- Missing deps
```
It couldn't be resolved by just naively adding the values in the callback function dependency array, since that had other unwanted side effects. To solve this I did a refactoring of the …
=> refactor: Improve loading state code and add tests

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_ActiveFareProductsTabScreen.tsx
When pulling to refresh in active tickets screen, we log the event and provide properties on the count of reservations and active fare contracts. 
Closes: https://github.com/AtB-AS/kundevendt/issues/13745
Extension to: https://github.com/AtB-AS/kundevendt/issues/10085
=> refactor: add analytics on pull to refresh

src/travel-details-screens/utils.ts
https://mittatb.slack.com/archives/C0116FMPX4Y/p1698127130815159
The quay public code (like P2) should not be used as leg public
code, as it represents the quay number in a stop place with
numbered quays.
When finding public code for the leg only use the line public code, and not the quay public code.
=> fix: Not use quay public code as leg public code

src/components/radio/RadioBox.tsx, src/components/radio/RadioIcon.tsx, src/select-travel-token-screen/SelectTravelTokenScreenComponent.tsx, src/stacks-hierarchy/Root_ParkingViolationsReporting/components/SelectGroup.tsx, src/theme/colors.ts
Changed from using static colors to interactive colors for default and active in RadioBoxes, providing a prop to set the interactiveColor. 
Looks like this after current changes:
Closes: https://github.com/AtB-AS/kundevendt/issues/8652
=> feat: use interactive color on token toggle screen

src/analytics/AnalyticsContext.tsx, src/auth/AuthContext.tsx, src/auth/types.ts, src/auth/use-check-if-account-creation-finished.ts, src/auth/use-fetch-customer-data-after-user-changed.ts, src/auth/use-subscribe-to-auth-user-change.ts, src/auth/utils.ts, src/fare-contracts/PurchaseReservation.tsx, src/mobile-token/MobileTokenContext.tsx, src/stacks-hierarchy/Root_ParkingViolationsReporting/Root_ParkingViolationsQr.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/Root_PurchaseConfirmationScreen.tsx, src/stacks-hierarchy/Root_PurchaseConfirmationScreen/components/SelectPaymentMethodSheet.tsx, src/stacks-hierarchy/Root_PurchasePaymentWithCreditCardScreen/use-terminal-state.ts, src/stacks-hierarchy/Root_PurchasePaymentWithVippsScreen/use-vipps-state.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_PaymentOptionsScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_RootScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_TicketingStack/Ticketing_TicketTabNavStack/TicketTabNav_PurchaseTabScreen/TicketTabNav_PurchaseTabScreen.tsx, src/stacks-hierarchy/saved-payment-utils.ts, src/ticketing/TicketingContext.tsx
Some reports coming in lately regarding missing customer id.
Some refactoring of the auth process. No large changes, but several
smaller ones:
- More logging of Bugsnag breadcrumbs during the authentication
process.
- No longer exposing the internal Firebase User type out through
the AuthContext. Now instead exposing the specific fields that
may be used.
- Fixed all exhaustive deps errors in the auth module. One of the
changes to fix this was accessing the current user through
'auth().currentUser' instead of passing around the user object.
This was necessary as we could get the same user object multiple
times from the user change subscription, which caused dependency
change in hooks when it was not intended.
- The userId and the abtCustomerId were the same value, so the
abtCustomerId was …
=> refactor: Better encapsulation and logging in auth

src/fare-contracts/details/Barcode.tsx, src/translations/screens/FareContract.ts
Fixing https://github.com/AtB-AS/mittatb-app/pull/3952#issuecomment-1779257983
Fixed by splitting the common label into two different labels, with and without the activation hint. 
Only barcodes with `PressableOpacity` having `onPress={onOpenBarcodePress}` should have the activation hint. This means that `MobileTokenAztec` should have label without activation hint.
=> fix: no activation hint for non-activatable barcodes

src/components/map/Map.tsx, src/components/map/components/mobility/Scooters.tsx, src/components/map/components/mobility/Stations.tsx, src/components/map/components/mobility/Vehicles.tsx
- Updates the scooter cluster zoom logic to zoom at least "2 steps", or to the point where the cluster expands, whichever is furthest.
- Changes [clusterRadius](https://github.com/rnmapbox/maps/blob/main/docs/ShapeSource.md#clusterradius) from 50 (the default), to 40. This means there are slightly less clusters than before, and more individual scooters. 
- Changes zoom animation for scooter clusters from 400ms to around 200ms (scaled to how far we zoom)
- Changes zoom animation for station clusters from 400ms to 200ms
https://github.com/AtB-AS/mittatb-app/assets/1774972/052d979a-2bac-4865-8ca6-4526bc738893
=> feat: improve scooter cluster zoom level on click

src/components/map/components/mobility/BikeStations.tsx, src/components/map/components/mobility/CarStations.tsx, src/components/map/components/mobility/Stations.tsx
Same as https://github.com/AtB-AS/mittatb-app/pull/3980, but for bike stations. Adds clustering to bike stations, where the count is the sum of all leaf nodes.
=> feat: add bike station clusters

src/announcements/AnnouncementsContext.tsx, src/announcements/storage.ts, src/announcements/types.ts, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcement.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DebugInfoScreen.tsx, src/translations/screens/Dashboard.ts
Closes https://github.com/AtB-AS/kundevendt/issues/10321
Adds an X to the top right corner of each announcement that dismisses the announcement when pressed. Which announcements the user has dismissed is saved in the store.
=> feat: Dismissible announcements

src/utils/use-pollable-resource.ts, src/utils/use-previous.ts
- Adding prevState to dependency array of reload funcion is safe as
it is a reference.
- Adding setisLoading to dependency array of reload function is
safe as it is referentially stable.
- Adding reload to dependency array of the reload-on-focus
useEffect is safe because the original
load-on-reload-function-change useEffect now sets firstLoadIsDone
to false.
- AbortController changed to ref as we don't want to add it in the
dependency list for the useInterval hook.
And as a final note we should probably look into using useReactQuery
for this logic, as it supports most of what usePollableResource is
trying to achieve.
=> refactor: Make use-pollable-resource exhaustive deps fix

src/utils/destination-displays-are-equal.ts
Resolves https://github.com/AtB-AS/kundevendt/issues/2732
Allows undefined via to match with empty via.
This caused a bug where getExistingFavorite would not match a favorite, and a star would not be filled in correctly.
Also see https://github.com/AtB-AS/atb-bff/pull/309 keeping destinationDisplaysAreEqual in sync
=> fix: allow undefined via to match with empty via

src/utils/__tests__/use-do-once-when.test.ts, src/utils/use-do-once-when.ts
The input function (fn) was not in the dependency list of the
useEffect running the function. JUst naively adding it could not
be done, as that would make the effect rerun on every render as
input functions are not stable references.
The solution would be either:
- Add the function to the dependency list, and users of the hook
would need to ensure that they only send in stable references,
for example by wrapping function with useCallback.
- Use the input function as a ref, which would not rerun the effect
even though the function changes.
The latter option was selected as that is easier on the client, and
is the same as it is working before.
=> refactor: Deps fix in useDoOnceWhen

src/fare-contracts/ValidityHeader.tsx, src/fare-contracts/ValidityLine.tsx, src/fare-contracts/components/FareContractStatusSymbol.tsx, src/fare-contracts/utils.ts, src/translations/screens/FareContract.ts, src/translations/screens/Ticketing.ts
Adds status for showing cancelled tickets.
Fixes https://github.com/AtB-AS/kundevendt/issues/14931
Example:
=> feat: adds support for showing cancelled tickets

e2e/index_noLogs/index.js, e2e/test/pageobjects/departure.overview.page.ts, e2e/test/pageobjects/frontpage.page.ts, e2e/test/specs/frontpage.e2e.ts, e2e/test/specs/travelsearch.e2e.ts, src/components/message-box/MessageBox.tsx, src/components/touchable-opacity-or-view/PressableOpacityOrView.tsx, src/global-messages/GlobalMessage.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcement.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_RootScreen/components/Announcements.tsx
The E2E-tests started to fail when there was added several announcements (the add favorites button "disappeared" on frontpage). Here, the frontpage tests first closes all dissmissible global messages and announcements before doing the tests.
In this PR:
- test-ids on global messages and announcements
- remove messages test case on frontpage
Note! Also added an index.js in its own folder that removes all log messages for local testing with metro. Can be copied to root during tests.
=> test: e2e-test improvements

e2e/test/pageobjects/travelsearch.overview.page.ts, e2e/test/specs/travelsearch.e2e.ts
Fix the error `e2e/test/specs/travelsearch.e2e.ts(86,45): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.` from https://github.com/AtB-AS/mittatb-app/actions/runs/6808388945/job/18512750417
=> fix: tsc error in e2e

e2e/test/pageobjects/onboarding.page.ts, e2e/test/specs/onboarding.e2e.ts, src/stacks-hierarchy/Root_NotificationPermissionScreen.tsx
Will be a temporary fix to make the tests run until the new onboarding flow is in place.
=> test: add notification screen in e2e-tests

src/mobile-token/MobileTokenContext.tsx, src/remote-config.ts
Some functions were not necessary to create on render and wrap with
useCallback. Instead move them out of the render body, which
makes them non-reactive functions and as such don't need to be in
the dependency list of the hooks where they are used.
Also change the token timeout default value to 10 as it is really
beneficial to log error to bugsnag after 10 seconds, and it should
instead be opt-out.
=> refactor: Move function creation out of React render

src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/NonTransitResults.tsx
| ------ | ----- |
| <img width=200 src="https://github.com/AtB-AS/mittatb-app/assets/70323886/5eb7b9cc-7fc2-4d03-9ec1-38fded830338"/> | <img width=200 src="https://github.com/AtB-AS/mittatb-app/assets/70323886/2a4f0d12-5e72-44e0-8265-ce3a68e3bed3"/> |
<details>
<summary>📹 Video</summary>
<p>
https://github.com/AtB-AS/mittatb-app/assets/70323886/a11a1908-41a9-4f87-98f3-e163cec716c9
</p>
</details>
=> fix: Remove scroll visual and remove "cutoff" from nonTransitResults

src/beacons/use-beacons.ts, src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx, src/stacks-hierarchy/Root_LocationSearchByTextScreen/components/LocationSearchContent.tsx, src/stacks-hierarchy/Root_ParkingViolationsReporting/Root_ParkingViolationsQr.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/Dashboard_TripSearchScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/Results.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_ProfileStack/Profile_DeleteProfileScreen.tsx, src/translations/commons.ts, src/travel-details-screens/use-departure-data.ts
The translate function (t) from lobot was not a stable reference,
and recreated on every render. This ment it could not be added to
dependency lists without causing the hooks to be run too often.
In this PR we wrap the translate function with 'useCallback', and
add the 't' function to the dependency lists.
I also created an [issue at the lobo-t repo](https://github.com/leile/lobo-t/issues/7), and offered creating a
PR there, but no response yet.
=> refactor: Make translate func a stable reference

e2e/test/specs/frontpage.e2e.ts, src/components/empty-state/EmptyState.tsx, src/fare-contracts/FareContractAndReservationsList.tsx, src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx, src/nearby-stop-places/components/StopPlaces.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/Results.tsx
The e2e tests are not using location, so with the empty state change, a test-id was not found.
Added test-ids to the empty state, and updated the e2e-frontpage test.
=> test: handle empty state in e2e

src/travel-token-box/TravelTokenBox.tsx
React components shouldn't be created like normal javascript functions,
as that bypasses the rules and optimisations of React. The
ErrorMessages component here did not work as intended, as it made
the app crash with 'Rendered fewer hooks than expected' since the
hooks inside the component was rendered conditionally.
The solution now was inlining the error  message boxes into the
TravelTokenBox component.
Fixes:
https://github.com/AtB-AS/kundevendt/issues/10087#issuecomment-1808164753
https://app.bugsnag.com/atb-as/mittatb/errors/655221f4bdc7f80008277524?filters%5Buser.id%5D=d21ab310-04c3-4ba4-afc5-dcc88679951f&event_id=6552221900cc77ff8eac0000
=> fix: Render crash on TravelTokenBox

ios/Podfile.lock
Looks like I missed the update to ios podfile, causing crash on latest iOS staging, this PR updates the version in podfile.lock
=> chore: update react-native-webview on podfile.lock

fastlane/Fastfile
Closing: https://github.com/AtB-AS/kundevendt/issues/15533
Second attempt at possible fix for https://github.com/AtB-AS/mittatb-app/pull/3972/files#r1394271463
=> build: remove duplicate app- from aab copy path in fastfile

fastlane/Fastfile
Closing https://github.com/AtB-AS/kundevendt/issues/15533
This time changing the path instead of filename.
=> build: fix .aab path instead of filename

src/components/map/Map.tsx, src/tariff-zones-selector/TariffZonesSelectorMap.tsx, src/travel-details-map-screen/TravelDetailsMapScreenComponent.tsx
The non-native user location pin has an onPress handler which is
hard to circumvent, and the hitbox is quite wide. This means when
the user location pin was close to an entity that should be
clickable (like bus stop, bike station, etc.) the click was not
registered by the map.
To fix this we change to the native location pin. The native
location pin is not interactable, which is kinda exactly what we
want here, as we don't want to register clicks on the location pin.
Another minor drawback is that it is not as pretty as the
non-native pin, but this was ok by designers.
Relevant issue about UserLocation pin blocking presses on
underlying components:
https://github.com/rnmapbox/maps/issues/241
Gif before/after:
<div>
<image width=350 …
=> feat: Use native user location pin

ios/departureWidget/APIService.swift, ios/departureWidget/Info.plist
Noticed that the widget had been using the staging build of the api. 
Acceptance criteria:
=> fix: widget set url with env

src/components/map/utils.ts
The logic was originally the other way around, that el-scooters
and free-floating-bikes were not clickable, but this ment some
other entities (like quays) was unintentionally clickable. Now
instead change the logic around so we whitelist which entities
that should be clickable.
Before/After:
<div>
<image width=300 src='https://github.com/AtB-AS/mittatb-app/assets/675421/a6f418e4-f96c-4038-b2e3-ffca9b23d019'/>
<image width=300 src='https://github.com/AtB-AS/mittatb-app/assets/675421/72559e5b-d5f0-4646-957d-a5e96af8c541'/>
</div>
=> fix: Only stations and stop places clickable in map

src/components/map/Map.tsx, src/components/map/components/filter/MapFilter.tsx, src/components/map/hooks/use-decide-camera-focus-mode.tsx, src/components/map/hooks/use-update-bottom-sheet-when-selected-entity-changes.tsx, src/components/map/types.ts, src/components/map/utils.ts
The reason for the bug was that the Map tried to show a walking
path, but since the filters sheet uses so much of the screen it
wasn't enough space to show to walk path, even if it zoomed all
the way out (showing Antarctica).
The fix is that when the filter sheet is opened, we needed to
reset the map state that said that the departures sheet and the
walk path should be visible.
One drawback of this solution is that there is no animation when
switching from the departures sheet to the filters sheet, but I
couldn't get that to work without causing havoc.
=> fix: Not move to antarctica when opening filters sheet

src/stacks-hierarchy/Root_NotificationPermissionScreen.tsx, src/stacks-hierarchy/Root_TabNavigatorStack/Root_TabNavigatorStack.tsx
The notification onboarding will now show:
- After buying a ticket
- When logging in and having an active ticket
- Opening the app after updating and having an active ticket
Screen now also uses the `register` from `usePushNotifications()`
[Figma](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?type=design&node-id=18256-2778&mode=dev)
=> fix: notification onboarding flow and register for notifications

ios/departureWidget/APIService.swift, ios/departureWidget/Storage.swift
By adding install_id to the sent requests, we can see how many individual users have the widget active. Was solved this way to avoid adding potshot to the native widget code, and to reduce the amount of logging in posthog.
To find the amount users, check how many individual install_id's have used the `bff/v2/departure-favorites` with a limitPerLine of 50.
=> fix: add install_id to api calls from iOS widget

src/stacks-hierarchy/Root_ReceiptScreen.tsx
Closes https://github.com/AtB-AS/kundevendt/issues/14884
After user succeeded in sending receipt to their e-mail, entering a new e-mail address updates the text shown by the success message. 
Reset the state whenever the e-mail field is updated, unless the state is `loading`.
<details>
<Summary>video</Summary>
https://github.com/AtB-AS/mittatb-app/assets/1777333/13d802c0-91b9-4955-b8cd-913b896aa6e8
</details>
=> fix: reset state when email input field is updated

src/time/TimeContext.tsx, src/time/index.ts
ref. https://github.com/AtB-AS/mittatb-app/pull/4029#issuecomment-1810328096
Adds getServerNow() to TimeContext, providing our best estimate for the current server time based on the diff from device time, last time it was updated.
When logging serverNow every time it is updated in TimeContext, and logging the state in an useInterval:
```js
useInterval(
() => {
console.log('Date.now()', Date.now(), 'getServerNow()', getServerNow(), 'serverNow', serverNow);
},
500,
[getServerNow],
);
```
Gives this in the console
```
LOG  Date.now() 1700211225129 getServerNow() 1700211225144 serverNow 1700211224576
LOG  Date.now() 1700211225646 getServerNow() 1700211225661 serverNow 1700211224576
LOG  Date.now() 1700211226181 getServerNow() 1700211226196 serverNow 1700211224576
LOG  Date.now() 1700211226696 …
```
=> feat: add getServerNow to TimeContext
